'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {atTime,properties,propertyValue,type Keyframe,type Layer,type Property} from '@/lib/studio-model';
import {shiftKeys} from '@/lib/creative-tools';
import {Choice,Num} from './controls';
const easing=['linear','smooth','step','bezier'];
export default function KeyEditor({item,patch,time,setTime,duration}:{item:Layer;patch:(v:Partial<Layer>)=>void;time:number;setTime:(v:number)=>void;duration:number}){
 const [property,setProperty]=useState<Property>('x'),[ease,setEase]=useState<Keyframe['ease']>('linear'),[page,setPage]=useState(0),[value,setValue]=useState(0),[selected,setSelected]=useState<number[]>([]),[clipboard,setClipboard]=useState<Keyframe[]>([]),[offset,setOffset]=useState(.1),[error,setError]=useState('');
 const drag=useRef<{x:number;width:number;indices:number[];copy:boolean}|null>(null),[dragDelta,setDragDelta]=useState(0);
 const keys=item.keys[property]||[],pages=Math.max(1,Math.ceil(keys.length/20)),current=Math.min(page,pages-1),chosen=selected.filter(i=>i<keys.length),curve=keys[chosen[0]]?.curve||[.25,.1,.25,1];
 useEffect(()=>setValue(propertyValue(atTime(item,time),property)),[item,time,property]);
 useEffect(()=>{setPage(0);setSelected([]);},[item.id,property]);
 function change(next:Keyframe[]){if(next.length>1000){setError('A property supports up to 1000 keys.');return;}setError('');patch({keys:{...item.keys,[property]:next.sort((a,b)=>a.time-b.time)}});}
 function edit(index:number,partial:Partial<Keyframe>){change(keys.filter((k,i)=>i===index||partial.time===undefined||Math.abs(k.time-partial.time)>.000001).map(k=>k===keys[index]?{...k,...partial}:k));}
 function shift(delta:number,copy=false){try{change(shiftKeys(keys,chosen,delta,duration,copy));setSelected([]);}catch(e){setError((e as Error).message);}}
 return <div className="key-editor"><label>Property<Choice label="Animated property" value={property} options={properties} onChange={v=>setProperty(v as Property)}/></label><label>Value at playhead<Num label="Key value at playhead" value={value} onChange={setValue}/></label><label>New key interpolation<Choice label="New key interpolation" value={ease} options={easing} onChange={v=>setEase(v as Keyframe['ease'])}/></label><Button size="sm" disabled={keys.length>=1000&&!keys.some(k=>Math.abs(k.time-time)<.000001)} onClick={()=>{const next=keys.filter(k=>Math.abs(k.time-time)>.000001);next.push({time,value,ease,...(ease==='bezier'?{curve:[.25,.1,.25,1] as [number,number,number,number]}:{})});change(next);setPage(Math.floor(next.filter(k=>k.time<time).length/20));}}>◆ Set key at {time.toFixed(3)}s</Button>
 <div className="key-selection-track" aria-label="Draggable keyframe track" onPointerMove={e=>{if(drag.current)setDragDelta((e.clientX-drag.current.x)/drag.current.width*duration);}} onPointerUp={e=>{const d=drag.current;if(!d)return;drag.current=null;setDragDelta(0);try{if(Math.abs(e.clientX-d.x)>2){change(shiftKeys(keys,d.indices,(e.clientX-d.x)/d.width*duration,duration,d.copy));setSelected([]);}}catch(e){setError((e as Error).message);}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{drag.current=null;setDragDelta(0);}}>{keys.map((k,i)=><button key={i} aria-label={'Drag keyframe '+(i+1)} aria-pressed={chosen.includes(i)} style={{left:`${Math.max(0,Math.min(duration,k.time+(drag.current?.indices.includes(i)?dragDelta:0)))/duration*100}%`}} onPointerDown={e=>{const indices=e.shiftKey?chosen.includes(i)?chosen.filter(n=>n!==i):[...chosen,i]:chosen.includes(i)?chosen:[i];setSelected(indices);setTime(k.time);const parent=e.currentTarget.parentElement!;parent.setPointerCapture(e.pointerId);drag.current={x:e.clientX,width:parent.getBoundingClientRect().width,indices,copy:e.altKey};e.preventDefault();}}/>)}</div>
 <p className="helper">Shift-click selects multiple keys. Drag to move together; Alt-drag copies.</p><div className="key-bulk-tools"><Button size="sm" variant="outline" onClick={()=>setSelected(keys.map((_,i)=>i))}>Select all keys</Button><Button size="sm" variant="outline" disabled={!chosen.length} onClick={()=>setClipboard(keys.filter((_,i)=>chosen.includes(i)).map(k=>({...k})))}>Copy keys</Button><Button size="sm" variant="outline" disabled={!clipboard.length} onClick={()=>{const origin=Math.min(...clipboard.map(k=>k.time)),next=clipboard.map(k=>({...k,time:k.time-origin+time}));if(next.some(k=>k.time>duration)){setError('Copied keys would exceed scene duration. Move the playhead earlier.');return;}change([...keys.filter(k=>!next.some(n=>Math.abs(n.time-k.time)<.000001)),...next]);}}>Paste at playhead</Button><Button size="sm" variant="ghost" disabled={!chosen.length} onClick={()=>{change(keys.filter((_,i)=>!chosen.includes(i)));setSelected([]);}}>Delete selected</Button></div><label>Move selected by seconds<Num label="Keyframe offset" value={offset} min={-duration} max={duration} step={.01} onChange={setOffset}/></label><Button size="sm" variant="outline" disabled={!chosen.length} onClick={()=>shift(offset)}>Move {chosen.length} keys</Button>
 {chosen.length>0&&<><label>Selected interpolation<Choice label="Selected key interpolation" value={keys[chosen[0]].ease} options={easing} onChange={v=>change(keys.map((k,i)=>chosen.includes(i)?{...k,ease:v as Keyframe['ease']}:k))}/></label><EasingCurve curve={curve} change={curve=>change(keys.map((k,i)=>chosen.includes(i)?{...k,ease:'bezier',curve}:k))}/></>}
 <div className="ae-key-tools"><Button variant="ghost" size="sm" disabled={!current} onClick={()=>setPage(current-1)}>Previous</Button><span>{keys.length} keys · {current+1}/{pages}</span><Button variant="ghost" size="sm" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</Button></div>
 {keys.slice(current*20,current*20+20).map((f,n)=>{const i=current*20+n;return <div className="key-row" key={i}><input type="checkbox" aria-label={'Select keyframe '+(i+1)} checked={chosen.includes(i)} onChange={e=>setSelected(e.target.checked?[...chosen,i]:chosen.filter(n=>n!==i))}/><Button variant="ghost" size="sm" aria-label={'Go to keyframe '+(i+1)} onClick={()=>{setSelected([i]);setTime(f.time);}}>◆</Button><Num label={'Keyframe time '+(i+1)} value={f.time} min={0} max={duration} step={.001} onChange={time=>edit(i,{time})}/><Num label={'Keyframe value '+(i+1)} value={f.value} onChange={value=>edit(i,{value})}/><Choice label={'Keyframe interpolation '+(i+1)} value={f.ease} options={easing} onChange={ease=>edit(i,{ease:ease as Keyframe['ease']})}/><Button variant="ghost" size="icon" aria-label="Remove keyframe" onClick={()=>change(keys.filter((_,j)=>i!==j))}>×</Button></div>;})}{error&&<p role="alert" className="error">{error}</p>}
 </div>;
}
export function EasingCurve({curve,change}:{curve:[number,number,number,number];change:(v:[number,number,number,number])=>void}){
 const active=useRef<number|null>(null),x=(n:number)=>20+n*200,y=(n:number)=>130-n*100;
 return <><svg viewBox="0 0 240 150" className="easing-editor" aria-label="Bezier easing curve" onPointerMove={e=>{if(active.current===null)return;const r=e.currentTarget.getBoundingClientRect(),next=[...curve] as typeof curve;next[active.current]=Math.max(0,Math.min(1,((e.clientX-r.left)*240/r.width-20)/200));next[active.current+1]=Math.max(-2,Math.min(3,(130-(e.clientY-r.top)*150/r.height)/100));change(next);}} onPointerUp={e=>{active.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{active.current=null;}}><path d={`M20 130 L${x(curve[0])} ${y(curve[1])} M220 30 L${x(curve[2])} ${y(curve[3])}`} stroke="#667b91" fill="none"/><path d={`M20 130 C${x(curve[0])} ${y(curve[1])} ${x(curve[2])} ${y(curve[3])} 220 30`} fill="none" stroke="#ff994d" strokeWidth="3"/>{[0,2].map(i=><circle key={i} cx={x(curve[i])} cy={y(curve[i+1])} r="7" fill="#e7f0f9" onPointerDown={e=>{active.current=i;e.currentTarget.ownerSVGElement!.setPointerCapture(e.pointerId);}}/>)}</svg><div className="property-grid">{curve.map((v,i)=><label key={i}>{['X1','Y1','X2','Y2'][i]}<Num label={'Bezier '+['X1','Y1','X2','Y2'][i]} value={v} min={i%2?-2:0} max={i%2?3:1} step={.01} onChange={n=>change(curve.map((v,j)=>j===i?n:v) as typeof curve)}/></label>)}</div></>;
}
