'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {desktopBridge} from '@/lib/desktop';
import {aeScene,type AeDraft,type AeOptions} from '@/lib/ae-model';
import type {Project} from '@/lib/studio-model';
import {Graphic} from './canvas';

type FontInfo={family:string;fullName:string;postscriptName:string};
type Props={disabled:boolean;projectId:string;beforeCommit:()=>Promise<{projectId:string;revision:number}>;afterCommit:()=>void;onImported:(v:{project:Project;revision:number;sceneId:string})=>void;onError:(e:unknown)=>void};
export default function AeImport({disabled,projectId,beforeCommit,afterCommit,onImported,onError}:Props){
 const bridge=desktopBridge()!,dialog=useRef<HTMLDialogElement>(null),generation=useRef(0),originalProject=useRef(projectId);
 const [opened,setOpened]=useState(false),[busy,setBusy]=useState(false),[committing,setCommitting]=useState(false),[draft,setDraft]=useState<AeDraft|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[fonts,setFonts]=useState<FontInfo[]>([]),[fontStatus,setFontStatus]=useState<AeOptions['fontStatus']>('unavailable'),[missing,setMissing]=useState<string[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[accepted,setAccepted]=useState(false);
 useEffect(()=>{if(opened&&!dialog.current?.open)dialog.current?.showModal();if(!opened&&dialog.current?.open)dialog.current?.close();},[opened]);
 useEffect(()=>()=>{generation.current++;bridge.cancelAe().catch(()=>{});},[]);
 useEffect(()=>{if(!playing||!draft)return;const start=performance.now()-time*1000;let frame:number;function tick(){const next=(performance.now()-start)/1000;if(next>=draft!.scene.duration){setTime(draft!.scene.duration);setPlaying(false);return;}setTime(next);frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,draft]);
 function close(){generation.current++;bridge.cancelAe().catch(onError);setOpened(false);setDraft(null);setPlaying(false);setBusy(false);}
 async function choose(){
  const sequence=++generation.current;originalProject.current=projectId;setBusy(true);setDraft(null);setError('');setNotice('');setTime(0);setPlaying(false);setAccepted(false);
  try{
   let available:FontInfo[]=[],checked:AeOptions['fontStatus']='unavailable';
   try{const query=(window as unknown as {queryLocalFonts?:()=>Promise<FontInfo[]>}).queryLocalFonts;if(query){available=await query();checked='checked';}}catch{/* Report unavailable enumeration, with explicit font mapping. */}
   if(sequence!==generation.current)return;
   const next=await bridge.prepareAe();if(sequence!==generation.current)return;if(!next)return;
   const map:Record<string,string>={},absent:string[]=[];
   for(const name of new Set(next.scene.layers.flatMap(l=>l.sourceFont?[l.sourceFont]:[]))){const match=available.find(f=>[f.postscriptName,f.fullName,f.family].some(v=>v.toLowerCase()===name.toLowerCase()));map[name]=match?.family||'Arial';if(!match&&checked==='checked')absent.push(name);}
   setFonts(available);setFontStatus(checked);setMissing(absent);setMapping(map);setDraft(next);
  }catch(e){if(sequence===generation.current)setError(e instanceof Error?e.message:'AE package inspection failed.');}finally{if(sequence===generation.current)setBusy(false);}
 }
 async function exporter(){const sequence=generation.current;setBusy(true);setError('');try{if(await bridge.saveAeExporter()&&sequence===generation.current)setNotice('Exporter saved. Run it in After Effects using File → Scripts → Run Script File.');}catch(e){if(sequence===generation.current)setError(e instanceof Error?e.message:'Could not save exporter.');}finally{if(sequence===generation.current)setBusy(false);}}
 async function reference(){if(!draft)return;const sequence=generation.current;setBusy(true);setPlaying(false);setError('');try{const next=await bridge.aeReference({id:draft.id,time});if(next&&sequence===generation.current)setDraft(next);}catch(e){if(sequence===generation.current)setError(e instanceof Error?e.message:'Could not attach reference.');}finally{if(sequence===generation.current)setBusy(false);}}
 async function commit(){if(!draft)return;setCommitting(true);setBusy(true);setPlaying(false);setError('');try{const target=await beforeCommit();if(target.projectId!==originalProject.current)throw Error('The open project changed. Cancel and import again.');const result=await bridge.commitAe({id:draft.id,...target,fonts:mapping,fontStatus,missingFonts:missing,acceptWarnings:true});onImported(result);setOpened(false);setDraft(null);}catch(e){setError(e instanceof Error?e.message:'AE import failed.');}finally{afterCommit();setCommitting(false);setBusy(false);}}
 const preview=draft?aeScene(draft,{fonts:mapping,fontStatus,missingFonts:missing}):null,report=preview?.importReport?.format==='ae'?preview.importReport:null,references=report?.references||[],matched=references.find(r=>Math.abs(r.time-time)<.0001);
 const invalidFonts=Object.values(mapping).some(name=>!name.trim()||fontStatus==='checked'&&!fonts.some(f=>f.family.toLowerCase()===name.trim().toLowerCase()));
 return <><Button size="sm" variant="ghost" disabled={disabled} onClick={()=>{setOpened(true);setError('');setNotice('');}}>Import AE</Button>{opened&&<dialog ref={dialog} aria-label="Import After Effects animation" className="psd-dialog ae-dialog" onCancel={e=>{e.preventDefault();if(!committing)close();}}>
 <header><div><h2>Import After Effects animation</h2><p>{draft?draft.fileName:'Local conversion · no uploads'}</p></div><Button variant="ghost" disabled={committing} onClick={close}>Cancel</Button></header>
 {error&&<p role="alert" className="psd-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!draft?<section className="ae-start"><h3>Bring an AE composition into your studio</h3><ol><li>Save the exporter below.</li><li>In After Effects, open your composition, set its work area, then run the exporter through <strong>File → Scripts → Run Script File</strong>.</li><li>Save the <strong>.bcae</strong> package and choose it here.</li></ol><p>Converts supported 2D point text, solids and PNG layers with sampled position, anchor, scale, rotation, opacity and layer timing. AE must be installed on the computer that exports the composition.</p><p>Direct .aep/.aepx opening, shape paths, precomps, 3D, masks, effects and plugin rendering are not supported. Review skipped layers and compare reference frames.</p><div className="row"><Button variant="outline" disabled={busy} onClick={exporter}>Save AE exporter</Button><Button disabled={busy} onClick={choose}>{busy?'Reading local package…':'Choose AE package'}</Button></div></section>:<>
 <div className="ae-playback"><Button variant="outline" disabled={busy} onClick={()=>{if(!playing&&time>=draft.scene.duration)setTime(0);setPlaying(!playing);}}>{playing?'Pause preview':'Play preview'}</Button><input aria-label="AE preview time" type="range" min={0} max={draft.scene.duration} step={1/(draft.scene.frameRate||30)} value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/><label>Time (s)<input aria-label="AE time seconds" type="number" min={0} max={draft.scene.duration} step={1/(draft.scene.frameRate||30)} value={Number(time.toFixed(4))} onChange={e=>{setPlaying(false);setTime(Math.max(0,Math.min(draft.scene.duration,Number(e.target.value)||0)));}}/></label><span>{draft.scene.width} × {draft.scene.height} · {draft.scene.layers.length} layers · {draft.scene.frameRate} fps</span></div>
 <div className="psd-comparison ae-comparison"><section><h3>AE reference render</h3><div className="psd-preview ae-reference">{matched?<img alt={'AE reference at '+matched.time.toFixed(3)+' seconds'} src={draft.images[matched.src]}/>:<p>{references.length?'Choose a saved reference time below to compare matching frames.':'Attach PNG frames rendered in After Effects to check the conversion.'}</p>}</div><div className="row ae-reference-tools"><select aria-label="AE reference time" value={matched?.src||''} onChange={e=>{const r=references.find(r=>r.src===e.target.value);if(r){setPlaying(false);setTime(r.time);}}}><option value="">Reference times</option>{references.map((r,i)=><option key={r.src} value={r.src}>{i+1}: {r.time.toFixed(3)} s</option>)}</select><Button variant="outline" disabled={busy||references.length>=20} onClick={reference}>Attach PNG at {time.toFixed(3)} s</Button></div><p className="helper">Time is relative to the exported work area. AE composition time: {((report?.workAreaStart||0)+time).toFixed(3)} s. PNG must match the composition dimensions.</p></section><section><h3>BroadcastCG result</h3><div className="psd-preview ae-result">{preview&&<Graphic scene={preview} time={time} images={draft.images} id="ae-review"/>}</div><p className="helper">Sampled keys remain editable in Animate. Text and images can use your existing variables and data bindings.</p></section></div>
 {!!Object.keys(mapping).length&&<section className="psd-fonts ae-fonts"><h3>Fonts</h3><p>{fontStatus==='checked'?'Checked against fonts installed on this computer.':'Font availability could not be checked.'} Fonts are not embedded.</p><datalist id="ae-font-families">{[...new Set(fonts.map(f=>f.family))].sort().map(f=><option key={f} value={f}/>)}</datalist>{Object.entries(mapping).map(([name,family])=><label key={name}>{name} {missing.includes(name)&&<strong className="psd-error">Missing</strong>}<input list="ae-font-families" aria-label={'AE font mapping for '+name} value={family} maxLength={100} disabled={busy} onChange={e=>setMapping(v=>({...v,[name]:e.target.value}))}/></label>)}</section>}
 {invalidFonts&&<p role="alert" className="psd-error">Choose an installed family for each font mapping.</p>}<details className="psd-report" open><summary>Conversion report · {report?.warnings.length} notes</summary><ul>{report?.warnings.map((w,i)=><li key={i}><strong>{w.layer}</strong> — {w.message}</li>)}</ul></details><label className="ae-accept"><input type="checkbox" checked={accepted} disabled={busy} onChange={e=>setAccepted(e.target.checked)}/>I reviewed the conversion notes and any skipped layers.</label>
 </>}
 <footer><span>{draft?'Adds an editable scene. Import does not change Program.':'After export, BroadcastCG runs the animation without After Effects.'}</span>{draft&&<Button disabled={busy||!accepted||invalidFonts} onClick={commit}>{busy?'Saving import…':'Add AE scene to project'}</Button>}</footer>
 </dialog>}</>;
}
