'use client';
import {useEffect,useRef,useState,type CSSProperties,type PointerEvent} from 'react';
import {ChevronRight,ChevronDown,ChevronLeft,Timer,Diamond,Play,Pause,SkipBack,Eye,EyeOff,Lock,Unlock,Copy,ClipboardPaste,Trash2,ZoomIn,ZoomOut} from 'lucide-react';
import {atTime,properties,propertyValue,timelineKeyframes,type Layer,type Property,type Scene,type Keyframe} from '@/lib/studio-model';
import {clampTimelineDelta,deleteTimelineKeys,disableTimelineTrack,easeTimelineKeys,keyIdentity,moveTimelineKeys,pasteTimelineKeys,percentProperty,propertyBounds,propertyLabels,resolveTimelineKeys,sameKeyTime,setTimelineValue,timelineSourceValue,type CopiedTimelineKey,type TimelineKey} from '@/lib/timeline-tools';
import {editValues} from '@/lib/editing-tools';
import {EasingCurve} from './advanced-key-editor';
import './animation-timeline.css';
import TimelineNumber from './timeline-number';
import {LayerTimeBar,TimingTools} from './timeline-clips';
import PropertyTracks from './property-tracks';
import {sceneDuration} from '@/lib/timeline-clips';
import './motion-tools.css';

type Props={scene:Scene;selected:string;select:(id:string)=>void;update:(fn:(s:Scene)=>Scene)=>void;time:number;seek:(time:number)=>void;playing:boolean;play:()=>void;preview:(scene:Scene|null)=>void};
type Drag={x:number;width:number;keys:TimelineKey[];copy:boolean;base:Scene;anchor:number};
const trackOrder:Property[]=['x','y','scaleX','scaleY','rotation','opacity','anchorX','anchorY','width','height','pathProgress'];

export default function AnimationTimeline({scene,selected,select,update,time,seek,playing,play,preview}:Props){
 const [expanded,setExpanded]=useState<Set<string>>(()=>new Set([selected])),[animatedOnly,setAnimatedOnly]=useState(false),[search,setSearch]=useState(''),[zoom,setZoom]=useState(1),[snap,setSnap]=useState(true),[height,setHeight]=useState(310),[width,setWidth]=useState(1000),[selection,setSelection]=useState<TimelineKey[]>([]),[clipboard,setClipboard]=useState<CopiedTimelineKey[]>([]),[message,setMessage]=useState(''),[delta,setDelta]=useState(0);
 const scroll=useRef<HTMLDivElement>(null),drag=useRef<Drag|null>(null),resize=useRef<{y:number;height:number}|null>(null),latest=useRef(scene);latest.current=scene;
 const fps=scene.frameRate||60,chosen=resolveTimelineKeys(scene,selection),chosenIds=new Set(chosen.map(keyIdentity)),one=chosen.length===1?chosen[0]:null,selectionLocked=chosen.some(k=>scene.layers.find(l=>l.id===k.layerId)?.locked);
 const contentWidth=354+Math.max(360,width-354)*zoom,visible=scene.layers.filter(l=>l.name.toLowerCase().includes(search.toLowerCase()));
 useEffect(()=>{const node=scroll.current;if(!node)return;const observer=new ResizeObserver(([e])=>setWidth(e.contentRect.width));observer.observe(node);return()=>observer.disconnect();},[]);
 function safely(fn:()=>void){try{fn();setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Animation edit failed.');}}
 function change(fn:(s:Scene)=>Scene){safely(()=>{const next=fn(scene);update(()=>next);});}
 function editLayer(id:string,fn:(l:Layer)=>Layer){change(s=>({...s,layers:s.layers.map(l=>l.id===id?fn(l):l)}));}
 function go(t:number){seek(Math.max(0,Math.min(scene.duration,t)));}
 function addKey(l:Layer,p:Property){editLayer(l.id,layer=>setTimelineValue(layer,p,time,timelineSourceValue(layer,p,time),true));setSelection([{layerId:l.id,property:p,time}]);select(l.id);}
 function remove(){change(s=>deleteTimelineKeys(s,chosen));setSelection([]);}
 function copy(){setClipboard(structuredClone(chosen));setMessage(`${chosen.length} keyframes copied. Single-layer keys paste onto the selected layer.`);}
 function paste(){safely(()=>{const target=new Set(clipboard.map(k=>k.layerId)).size===1?selected:undefined;const result=pasteTimelineKeys(scene,clipboard,time,target);update(()=>result.scene);setSelection(result.selection);setExpanded(ids=>new Set([...ids,...result.selection.map(k=>k.layerId)]));});}
 function moved(amount:number,duplicate=false){safely(()=>{const result=moveTimelineKeys(scene,chosen,amount,duplicate);update(()=>result.scene);setSelection(result.selection);});}
 function dragAmount(e:PointerEvent){const d=drag.current;if(!d)return 0;let amount=(e.clientX-d.x)/d.width*scene.duration;if(snap)amount=Math.round((d.anchor+amount)*fps)/fps-d.anchor;return clampTimelineDelta(d.base,d.keys,amount);}
 function endDrag(e:PointerEvent<HTMLDivElement>){const d=drag.current;if(!d)return;const amount=dragAmount(e);drag.current=null;setDelta(0);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(Math.abs(e.clientX-d.x)<3)return;safely(()=>{if(latest.current!==d.base)throw Error('The scene changed during the drag. Try moving the keys again.');const result=moveTimelineKeys(d.base,d.keys,amount,d.copy);update(()=>result.scene);setSelection(result.selection);});}
 function keyDown(e:React.KeyboardEvent){if((e.target as HTMLElement).closest('input,select,textarea,[contenteditable=true]'))return;const command=e.ctrlKey||e.metaKey;if(command&&e.key.toLowerCase()==='c'&&chosen.length){e.preventDefault();e.stopPropagation();copy();}else if(command&&e.key.toLowerCase()==='v'&&clipboard.length){e.preventDefault();e.stopPropagation();paste();}else if(['Delete','Backspace'].includes(e.key)&&chosen.length&&!selectionLocked){e.preventDefault();e.stopPropagation();remove();}else if(command&&e.key.toLowerCase()==='a'){e.preventDefault();e.stopPropagation();setSelection(visible.flatMap(l=>l.locked?[]:properties.flatMap(p=>(l.keys[p]||[]).map(k=>({layerId:l.id,property:p,time:k.time})))));}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();go(time+(e.key==='ArrowRight'?1:-1)/fps);}else if(e.key.toLowerCase()==='u'){e.preventDefault();setAnimatedOnly(v=>!v);}else if(e.key==='Escape'){drag.current=null;setDelta(0);setSelection([]);}}
 function lane(l:Layer,p?:Property){
  const keys=p?l.keys[p]||[]:timelineKeyframes(l),selectedDrag=new Set(drag.current?.keys.map(keyIdentity));
  return <div className="tl-lane" data-track-layer={l.id} data-track-property={p||'summary'} onPointerMove={e=>{if(drag.current)setDelta(dragAmount(e));}} onPointerUp={endDrag} onPointerCancel={()=>{drag.current=null;setDelta(0);}} onDoubleClick={e=>{if(!p||l.locked||(e.target as HTMLElement).closest('button'))return;const r=e.currentTarget.getBoundingClientRect();let t=(e.clientX-r.left)/r.width*scene.duration;if(snap)t=Math.round(t*fps)/fps;t=Math.max(0,Math.min(scene.duration,t));editLayer(l.id,layer=>setTimelineValue(layer,p!,t,timelineSourceValue(layer,p!,t),true));go(t);setSelection([{layerId:l.id,property:p,time:t}]);}} onPointerDown={e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();let t=(e.clientX-r.left)/r.width*scene.duration;if(snap)t=Math.round(t*fps)/fps;go(t);setSelection([]);select(l.id);}}>
   {!p&&<LayerTimeBar layer={l} scene={scene} selected={selected} select={id=>{seek(time);select(id);}} snap={snap} preview={preview} commit={next=>change(()=>next)} error={e=>setMessage((e as Error).message)}/>}
   {keys.filter(k=>k.time<=scene.duration).map((k,i)=>{const ref={layerId:l.id,property:p||'x',time:k.time},id=keyIdentity(ref),moving=p&&selectedDrag.has(id);return <button key={i} className={`tl-key ${p?'':'tl-summary-key'} ${k.ease}`} title={`${p?propertyLabels[p]+': '+k.value+' · ':''}${k.time.toFixed(3)}s · ${k.ease}`} aria-label={`${l.name} ${p?propertyLabels[p]+' ':''}key at ${k.time} seconds`} aria-pressed={!!p&&chosenIds.has(id)} data-key-time={k.time} style={{left:`${(k.time+(moving?delta:0))/scene.duration*100}%`}} onClick={e=>{if(e.detail===0){select(l.id);go(k.time);if(p)setSelection([ref]);}}} onPointerDown={e=>{if(e.button!==0)return;e.stopPropagation();e.preventDefault();select(l.id);go(k.time);if(!p){setExpanded(ids=>new Set([...ids,l.id]));return;}const next=e.shiftKey||e.ctrlKey?(chosenIds.has(id)?chosen.filter(n=>keyIdentity(n)!==id):[...chosen,ref]):chosenIds.has(id)?chosen:[ref];setSelection(next);if(l.locked||!next.some(n=>keyIdentity(n)===id))return;const parent=e.currentTarget.parentElement!;parent.setPointerCapture(e.pointerId);drag.current={x:e.clientX,width:parent.getBoundingClientRect().width,keys:next,copy:e.altKey,base:scene,anchor:k.time};}}/>;})}
   <div className="tl-playhead" style={{left:`${time/scene.duration*100}%`}}/>
  </div>;
 }
 return <section className="timeline advanced-timeline" aria-label="Animation timeline" tabIndex={0} onKeyDown={keyDown} style={{'--timeline-height':height+'px'} as CSSProperties}>
  <div className="tl-resize" role="separator" aria-label="Resize timeline" aria-orientation="horizontal" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();e.stopPropagation();setHeight(h=>Math.max(220,Math.min(innerHeight*.6,h+(e.key==='ArrowUp'?25:-25))));}}} onPointerDown={e=>{resize.current={y:e.clientY,height};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(resize.current)setHeight(Math.max(220,Math.min(innerHeight*.6,resize.current.height+resize.current.y-e.clientY)));}} onPointerUp={e=>{resize.current=null;e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{resize.current=null;}}/>
  <div className="tl-toolbar"><strong>Timeline</strong><span className="tl-scene-name" title={scene.name}>{scene.name}</span><button aria-label="Go to timeline start" onClick={()=>go(0)}><SkipBack size={14}/></button><button onClick={play} aria-label={playing?'Pause timeline':'Play timeline'}>{playing?<Pause size={14}/>:<Play size={14}/>} {playing?'Pause':'Play'}</button><TimelineNumber label="Timeline time" value={time} min={0} max={scene.duration} step={1/fps} onCommit={go}/><span className="tl-unit">s</span><label>Duration <TimelineNumber label="Scene duration" value={scene.duration} min={.1} max={600} onCommit={duration=>change(s=>{go(Math.min(time,duration));return sceneDuration(s,duration);})}/></label><span className="tl-spacer"/><input className="tl-search" aria-label="Search timeline layers" placeholder="Find layer…" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>setExpanded(new Set(visible.map(l=>l.id)))}>Expand all</button><button onClick={()=>setExpanded(new Set())}>Collapse</button><label><input type="checkbox" checked={animatedOnly} onChange={e=>setAnimatedOnly(e.target.checked)}/>Animated only</label><label><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/>Snap {fps} fps</label><button aria-label="Zoom timeline out" disabled={zoom===1} onClick={()=>setZoom(z=>Math.max(1,z/2))}><ZoomOut size={15}/></button><span>{zoom}×</span><button aria-label="Zoom timeline in" disabled={zoom===8} onClick={()=>setZoom(z=>Math.min(8,z*2))}><ZoomIn size={15}/></button></div>
  <div className="tl-editbar" data-keys={chosen.length>0}><span>{chosen.length?`${chosen.length} keys selected`:'Expand a layer to animate its properties'}</span><button disabled={!chosen.length} onClick={copy}><Copy size={13}/>Copy</button><button disabled={!clipboard.length} onClick={paste}><ClipboardPaste size={13}/>Paste</button><button disabled={!chosen.length||selectionLocked} onClick={remove}><Trash2 size={13}/>Delete keys</button>{chosen.length>0&&<><label>Easing <select aria-label="Timeline selected easing" disabled={selectionLocked} value={chosen.every(k=>k.key.ease===chosen[0].key.ease)?chosen[0].key.ease:''} onChange={e=>change(s=>easeTimelineKeys(s,chosen,e.target.value as Keyframe['ease']))}><option value="" disabled>Mixed</option><option value="linear">Linear</option><option value="smooth">Easy ease</option><option value="step">Hold</option><option value="bezier">Bezier</option></select></label>{one&&<><label>Time <TimelineNumber label="Selected timeline key time" value={one.time} min={0} max={scene.duration} step={1/fps} disabled={selectionLocked} onCommit={value=>moved(value-one.time)}/></label><label>Value <TimelineNumber label="Selected timeline key value" value={one.key.value} disabled={selectionLocked} {...propertyBounds(one.property)} onCommit={value=>editLayer(one.layerId,l=>setTimelineValue(l,one.property,one.time,value,true))}/></label></>}{chosen.every(k=>k.key.ease==='bezier')&&!selectionLocked&&<details className="tl-curve"><summary>Curve editor</summary><div><EasingCurve curve={chosen[0].key.curve||[.25,.1,.25,1]} change={curve=>change(s=>easeTimelineKeys(s,chosen,'bezier',curve))}/></div></details>}</>}<span className="tl-spacer"/><small>Shift: select · Alt-drag: copy · Double-click track: add key</small></div>
  <TimingTools scene={scene} selected={selected} time={time} seek={go} keys={chosen} commit={next=>change(()=>next)} preview={preview} error={e=>setMessage((e as Error).message)}/>
  {message&&<div className="tl-message" role="status">{message}<button aria-label="Dismiss timeline message" onClick={()=>setMessage('')}>×</button></div>}
  <div className="tl-scroll" ref={scroll}><div className="tl-content" style={{width:contentWidth}}><div className="tl-row tl-ruler"><div className="tl-label">LAYER / PROPERTY <span>VALUE · KEY</span></div><div className="tl-ruler-lane" role="slider" tabIndex={0} aria-label="Timeline playhead" aria-valuemin={0} aria-valuemax={scene.duration} aria-valuenow={time} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();go(snap?Math.round((e.clientX-r.left)/r.width*scene.duration*fps)/fps:(e.clientX-r.left)/r.width*scene.duration);}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=e.currentTarget.getBoundingClientRect();go(snap?Math.round((e.clientX-r.left)/r.width*scene.duration*fps)/fps:(e.clientX-r.left)/r.width*scene.duration);}} onPointerUp={e=>e.currentTarget.releasePointerCapture(e.pointerId)}>{Array.from({length:11},(_,i)=><span key={i} style={{left:`${i*10}%`}}>{(scene.duration*i/10).toFixed(scene.duration<10?2:1)}s</span>)}{scene.workArea&&<div className="tl-work-area" style={{left:`${scene.workArea.start/scene.duration*100}%`,width:`${(scene.workArea.end-scene.workArea.start)/scene.duration*100}%`}}/>}{scene.markers?.filter(m=>m.time<=scene.duration).map(m=><button key={m.id} className="tl-marker" title={m.name} aria-label={"Go to marker "+m.name} style={{left:`${m.time/scene.duration*100}%`}} onPointerDown={e=>e.stopPropagation()} onClick={()=>go(m.time)}>◆</button>)}<i style={{left:`${time/scene.duration*100}%`}}/></div></div>
   {visible.map(l=><div key={l.id} className="tl-layer" data-timeline-layer={l.id}><div className="tl-row tl-layer-row" data-selected={l.id===selected}><div className="tl-label"><button aria-label={`${expanded.has(l.id)?'Collapse':'Expand'} ${l.name} animation`} aria-expanded={expanded.has(l.id)} onClick={()=>{setExpanded(ids=>{const next=new Set(ids);if(next.has(l.id))next.delete(l.id);else next.add(l.id);return next;});select(l.id);}}>{expanded.has(l.id)?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</button><button className="tl-layer-name" title={l.name} onClick={()=>select(l.id)}>{l.name}</button><button aria-label={`${l.visible?'Hide':'Show'} ${l.name} in timeline`} onClick={()=>editLayer(l.id,layer=>({...layer,visible:!layer.visible}))}>{l.visible?<Eye size={13}/>:<EyeOff size={13}/>}</button><button aria-label={`${l.locked?'Unlock':'Lock'} ${l.name} in timeline`} onClick={()=>editLayer(l.id,layer=>({...layer,locked:!layer.locked}))}>{l.locked?<Lock size={13}/>:<Unlock size={13}/>}</button></div>{lane(l)}</div>
   {expanded.has(l.id)&&<>{trackOrder.filter(p=>(p!=='pathProgress'||l.motionPath||l.keys.pathProgress?.length)&&(!animatedOnly||l.keys[p]?.length)).map(p=>{const keys=l.keys[p]||[],at=keys.find(k=>sameKeyTime(k.time,time)),before=[...keys].sort((a,b)=>b.time-a.time).find(k=>k.time<time-.000001),after=[...keys].sort((a,b)=>a.time-b.time).find(k=>k.time>time+.000001),factor=percentProperty(p)?100:1,value=propertyValue(atTime(l,time),p),bounds=propertyBounds(p);return <div className="tl-row tl-property-row" data-timeline-property={p} key={p}><div className="tl-label"><button className="tl-stopwatch" aria-label={`${keys.length?'Disable':'Enable'} ${l.name} ${propertyLabels[p]} animation`} aria-pressed={!!keys.length} disabled={l.locked} title={keys.length?'Remove animation and keep the current value':'Enable animation at the playhead'} onClick={()=>{if(keys.length){if(window.confirm(`Remove all ${propertyLabels[p]} keyframes from ${l.name}? The value at the playhead will be kept. You can undo this change.`))editLayer(l.id,layer=>disableTimelineTrack(layer,p,time));}else addKey(l,p);}}><Timer size={14}/></button><span className="tl-property-name">{propertyLabels[p]}{percentProperty(p)?' %':p==='rotation'?' °':''}</span><TimelineNumber key={time} context={scene} scrubStep={1} onScrubStart={()=>{seek(time);select(l.id);}} onPreview={v=>{if(v===null){preview(null);return;}safely(()=>preview({...scene,layers:scene.layers.map(layer=>layer.id===l.id?editValues(layer,{[p]:v/factor},time,true):layer)}));}} label={`${l.name} ${propertyLabels[p]} value`} value={value*factor} disabled={l.locked} min={bounds.min===undefined?undefined:bounds.min*factor} max={bounds.max===undefined?undefined:bounds.max*factor} step={percentProperty(p)?1:.1} onCommit={v=>editLayer(l.id,layer=>editValues(layer,{[p]:v/factor},time,true))}/><button aria-label={`Previous ${l.name} ${propertyLabels[p]} key`} disabled={!before} onClick={()=>{go(before!.time);setSelection([{layerId:l.id,property:p,time:before!.time}]);}}><ChevronLeft size={12}/></button><button aria-label={`${at?'Remove':'Add'} ${l.name} ${propertyLabels[p]} key at playhead`} aria-pressed={!!at} disabled={l.locked} onClick={()=>{if(at){change(s=>deleteTimelineKeys(s,[{layerId:l.id,property:p,time:at.time}]));setSelection([]);}else addKey(l,p);}}><Diamond size={12}/></button><button aria-label={`Next ${l.name} ${propertyLabels[p]} key`} disabled={!after} onClick={()=>{go(after!.time);setSelection([{layerId:l.id,property:p,time:after!.time}]);}}><ChevronRight size={12}/></button></div>{lane(l,p)}</div>;})}<PropertyTracks layer={l} scene={scene} time={time} seek={go} preview={preview} commit={next=>change(()=>next)} error={e=>setMessage((e as Error).message)}/>{animatedOnly&&!properties.some(p=>l.keys[p]?.length)&&<div className="tl-empty-track">No animated properties. Turn off “Animated only” to add a track.</div>}</>}
   </div>)}{!visible.length&&<p className="tl-empty-track">No matching layers.</p>}
  </div></div>
 </section>;
}
