'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {alignArtwork} from '@/lib/art-transitions';
import {artStates} from '@/lib/button-art-schema';
import {artId,artPart,artPreset,buttonArtwork,patchArtPart,resolvedArtPart,type ArtPart,type ArtState,type ArtStyle,type ButtonArt} from '@/lib/button-art';
import {validateProject,type Control,type Project} from '@/lib/studio-model';
import {playerVariables} from '@/lib/panel-parts';
import {ButtonArtwork} from './button-artwork';
import {Num} from './controls';
import {api} from '@/lib/client-api';
import './button-art.css';
export default function ButtonArtEditor({item,project,patch}:{item:Control;project:Project;patch:(v:Partial<Control>)=>void}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState<ButtonArt>(()=>item.artwork||buttonArtwork(item.label,item.color)),[selected,setSelected]=useState(''),[state,setState]=useState<ArtState>('normal'),[error,setError]=useState(''),[snap,setSnap]=useState(4),[preset,setPreset]=useState('rounded');
 const [partsSelected,setPartsSelected]=useState<string[]>([]);const history=useRef<ButtonArt[]>([]),future=useRef<ButtonArt[]>([]),stage=useRef<HTMLDivElement>(null),gesture=useRef<{base:ButtonArt;x:number;y:number;matrix:DOMMatrix;resize:boolean;id:string;next:ButtonArt}|null>(null);
 const source=draft.parts.find(p=>p.id===selected),part=source?resolvedArtPart(source,state):undefined;
 function commit(next:ButtonArt){history.current=[...history.current.slice(-39),draft];future.current=[];setDraft(next);setError('');}
 function change(v:Partial<ArtStyle>){if(source)try{commit(patchArtPart(draft,source.id,state,v));}catch(e){setError((e as Error).message);}}
 function undo(){const last=history.current.pop();if(last){future.current.push(draft);setDraft(last);}}
 function redo(){const last=future.current.pop();if(last){history.current.push(draft);setDraft(last);}}
 function add(kind:ArtPart['kind']){if(draft.parts.length>=50){setError('A design supports up to 50 visual layers.');return;}const p=artPart(kind,{x:draft.width*.1,y:draft.height*.15,width:draft.width*.8,height:draft.height*.7,...(kind==='rect'?{fill:'#245388',radius:12}:{})});commit({...draft,parts:[...draft.parts,p]});setSelected(p.id);setState('normal');}
 function duplicate(){if(!source||source.locked||draft.parts.length>=50)return;const p={...structuredClone(source),id:artId(),name:source.name.slice(0,90)+' copy',x:source.x+8,y:source.y+8};commit({...draft,parts:[...draft.parts,p]});setSelected(p.id);}
 function remove(){if(source&&!source.locked){commit({...draft,parts:draft.parts.filter(p=>p.id!==source.id)});setSelected('');}}
 function order(delta:number){if(!source)return;const parts=[...draft.parts],i=parts.findIndex(p=>p.id===source.id),j=Math.max(0,Math.min(parts.length-1,i+delta));[parts[i],parts[j]]=[parts[j],parts[i]];commit({...draft,parts});}
 function begin(e:React.PointerEvent){if(e.button!==0)return;const id=(e.target as Element).closest('[data-art-part]')?.getAttribute('data-art-part')||((e.target as Element).closest('[data-art-resize]')?selected:'');const p=draft.parts.find(p=>p.id===id);if(!p)return;setSelected(p.id);if(p.locked)return;e.preventDefault();e.stopPropagation();const resize=!!(e.target as Element).closest('[data-art-resize]'),svg=stage.current!.querySelector('svg')!,element=resize?[...svg.querySelectorAll<SVGGraphicsElement>('[data-art-part]')].find(el=>el.dataset.artPart===id)!:svg;const matrix=element.getScreenCTM()!.inverse(),point=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix);gesture.current={base:draft,x:point.x,y:point.y,matrix,resize,id:p.id,next:draft};e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e:React.PointerEvent){const g=gesture.current;if(!g)return;const base=resolvedArtPart(g.base.parts.find(p=>p.id===g.id)!,state),point=new DOMPoint(e.clientX,e.clientY).matrixTransform(g.matrix),round=(n:number)=>Math.round(n/(e.altKey?1:snap||1))*(e.altKey?1:snap||1),dx=point.x-g.x,dy=point.y-g.y;let width=Math.max(1,Math.min(4000,round(base.width+dx))),height=Math.max(1,Math.min(4000,round(base.height+dy)));if(e.shiftKey&&g.resize)height=Math.max(1,Math.min(4000,width*base.height/base.width));g.next=patchArtPart(g.base,g.id,state,g.resize?{width,height}:{x:Math.max(-2000,Math.min(4000,round(base.x+dx))),y:Math.max(-2000,Math.min(4000,round(base.y+dy)))});setDraft(g.next);}
 function end(cancel=false){const g=gesture.current;if(!g)return;gesture.current=null;if(cancel)setDraft(g.base);else{history.current=[...history.current.slice(-39),g.base];future.current=[];setDraft(g.next);}}
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape'&&gesture.current){e.preventDefault();e.stopPropagation();end(true);}};window.addEventListener('keydown',fn,true);return()=>window.removeEventListener('keydown',fn,true);},[]);
 function save(){try{const next={...project,panels:project.panels.map(p=>({...p,controls:p.controls.map(c=>c.id===item.id?{...c,artwork:draft}:c)}))};validateProject(next);patch({artwork:structuredClone(draft)});setOpen(false);}catch(e){setError((e as Error).message);}}
 return <><Button className="full button-art-launch" variant="secondary" onClick={()=>{const art=structuredClone(item.artwork||buttonArtwork(item.label,item.color));setDraft(art);setPartsSelected([]);setSelected(art.parts.at(-1)?.id||'');history.current=[];future.current=[];setState('normal');setError('');setOpen(true);}}>Design {item.kind==='artwork'?'artwork':'button'} visually</Button><p className="creative-help">Arrange your own shapes, text, symbols and images. Actions stay separate from the artwork.</p>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="button-art-dialog" onKeyDown={e=>{if((e.target as HTMLElement).closest('input,textarea,select'))return;if(e.ctrlKey||e.metaKey){if(e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();e.shiftKey?redo():undo();}if(e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}return;}if(e.key==='Delete'){e.preventDefault();remove();}if(part&&!source?.locked&&e.key.startsWith('Arrow')){e.preventDefault();const step=e.shiftKey?10:1;change({x:part.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0),y:part.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)});}}}><DialogHeader><DialogTitle>Visual button designer · {item.label}</DialogTitle><DialogDescription>Each visual layer is editable. Preview states without running actions, then apply the design.</DialogDescription></DialogHeader>
 <div className="art-topbar">{artStates.map(s=><button key={s} aria-pressed={s===state} onClick={()=>setState(s)}>{s}</button>)}<label>Transition (s)<Num label="Button transition seconds" value={draft.transition?.duration||0} min={0} max={3} step={.05} onChange={duration=>commit({...draft,transition:{duration,ease:draft.transition?.ease||'smooth'}})}/></label><label>Easing<select aria-label="Button transition easing" value={draft.transition?.ease||'smooth'} onChange={e=>commit({...draft,transition:{duration:draft.transition?.duration||.2,ease:e.target.value as 'linear'}})}><option>smooth</option><option>linear</option></select></label><span className="spacer"/><button disabled={!history.current.length} onClick={undo}>Undo design edit</button><button disabled={!future.current.length} onClick={redo}>Redo</button><label>Snap<select aria-label="Artwork snap" value={snap} onChange={e=>setSnap(Number(e.target.value))}>{[0,1,4,8,16].map(n=><option key={n} value={n}>{n||'Off'}</option>)}</select></label></div>
 <div className="art-editor-layout"><aside className="art-layer-panel"><h3>ADD A PART</h3><div className="art-add-tools">{(['rect','ellipse','text','image','line','polygon'] as const).map(kind=><button key={kind} aria-label={'Add artwork '+kind} onClick={()=>add(kind)}>+ {kind==='rect'?'Rectangle':kind==='text'?'Text / icon':kind}</button>)}</div><h3>VISUAL LAYERS · {draft.parts.length}/50</h3>{[...draft.parts].reverse().map(p=><div className={'art-layer-row '+(selected===p.id?'selected':'')} key={p.id}><input type="checkbox" aria-label={"Select artwork layer "+p.name} checked={partsSelected.includes(p.id)} onChange={e=>setPartsSelected(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/><button className="art-layer-name" onClick={()=>setSelected(p.id)}>{p.name}</button><button title={p.visible?'Hide':'Show'} onClick={()=>commit({...draft,parts:draft.parts.map(x=>x.id===p.id?{...x,visible:!x.visible}:x)})}>{p.visible?'◉':'○'}</button><button title={p.locked?'Unlock':'Lock'} onClick={()=>commit({...draft,parts:draft.parts.map(x=>x.id===p.id?{...x,locked:!x.locked}:x)})}>{p.locked?'🔒':'◇'}</button></div>)}<label>Align / resize<select aria-label="Align artwork layers" value="" onChange={e=>commit(alignArtwork(draft,partsSelected.length?partsSelected:[selected],state,e.target.value))}><option value="">Choose operation…</option>{['left','center','right','top','middle','bottom','space-x','space-y','same-width','same-height'].map(v=><option key={v}>{v}</option>)}</select></label><small>Tick layers to align them together. A single layer aligns to the button canvas.</small><div className="art-order-tools"><button disabled={!part} onClick={()=>order(1)}>Forward</button><button disabled={!part} onClick={()=>order(-1)}>Backward</button><button disabled={!part||source?.locked} onClick={duplicate}>Duplicate part</button><button disabled={!part||source?.locked} onClick={remove}>Delete part</button></div></aside>
 <main className="art-preview-panel"><div className="art-canvas-options"><label>Width<Num label="Artwork canvas width" min={24} max={2000} value={draft.width} onChange={width=>commit({...draft,width})}/></label><label>Height<Num label="Artwork canvas height" min={24} max={2000} value={draft.height} onChange={height=>commit({...draft,height})}/></label><label>Fit<select aria-label="Artwork fit" value={draft.fit} onChange={e=>commit({...draft,fit:e.target.value as ButtonArt['fit']})}><option value="stretch">Stretch with button</option><option value="contain">Keep proportions</option></select></label></div><div className="art-stage-wrap"><div ref={stage} tabIndex={0} className="art-edit-stage" style={{aspectRatio:`${draft.width}/${draft.height}`,width:`min(100%, ${320*draft.width/draft.height}px)`}} onPointerDownCapture={begin} onPointerMove={move} onPointerUp={()=>end()} onPointerCancel={()=>end(true)} onLostPointerCapture={()=>{if(gesture.current)end(true);}}>
  <ButtonArtwork art={{...draft,fit:'stretch'}} variables={item.kind==='player'?playerVariables(item,project):project.variables} state={state} select={setSelected} selected={selected} selectedIds={partsSelected.length?partsSelected:[selected]}/>{part&&!source?.locked&&<svg className="art-handle-overlay" viewBox={`0 0 ${draft.width} ${draft.height}`} preserveAspectRatio="none"><g transform={`translate(${part.x} ${part.y}) rotate(${part.rotation} ${part.width/2} ${part.height/2})`}><rect data-art-resize x={part.width-5} y={part.height-5} width="10" height="10" fill="#65d5ff"/></g></svg>}
 </div></div><p className="art-hint">Drag to move · corner to resize · arrows to nudge · Shift preserves proportions · Alt ignores snap</p><div className="art-presets"><label>Starting shape<select aria-label="Artwork preset" value={preset} onChange={e=>setPreset(e.target.value)}>{['blank','rounded','circle','hexagon','shirt','image'].map(s=><option key={s}>{s}</option>)}</select></label><button onClick={()=>{const art=artPreset(preset as Parameters<typeof artPreset>[0],item.label,item.color);commit(art);setSelected(art.parts.at(-1)?.id||'');setState('normal');}}>Use starting shape</button></div><small>Normal changes are inherited unless a layer has an override for the previewed state.</small></main>
 <aside className="art-inspector">{part&&source?<fieldset disabled={source.locked}><h3>{state.toUpperCase()} · PART PROPERTIES</h3><label>Layer name<Input aria-label="Artwork layer name" value={source.name} maxLength={100} onChange={e=>commit({...draft,parts:draft.parts.map(p=>p.id===source.id?{...p,name:e.target.value}:p)})}/></label><div className="art-property-grid">{(['x','y','width','height','rotation','opacity','radius','strokeWidth'] as const).map(k=><label key={k}>{k}<Num label={'Artwork '+k} value={part[k]} min={k==='width'||k==='height'?1:k==='opacity'||k==='radius'||k==='strokeWidth'?0:-2000} max={k==='rotation'?3600:k==='opacity'?1:k==='radius'?1000:k==='strokeWidth'?100:4000} step={k==='opacity'?.05:1} onChange={v=>change({[k]:v})}/></label>)}</div><label><input type="checkbox" aria-label="Artwork part visible" checked={part.visible} onChange={e=>change({visible:e.target.checked})}/>Visible in {state}</label>
  {(['fill','gradient','stroke'] as const).map(k=><label key={k}>{k==='gradient'?'Gradient end (optional)':k}<div className="art-color"><input type="color" aria-label={'Artwork '+k+' color'} value={/^#[a-f0-9]{6}$/i.test(part[k])?part[k]:'#ffffff'} onChange={e=>change({[k]:e.target.value})}/><Input aria-label={'Artwork '+k} value={part[k]} placeholder="Color, none or {{variable}}" onChange={e=>change({[k]:e.target.value})}/></div><select aria-label={'Bind artwork '+k} value="" onChange={e=>{if(e.target.value)change({[k]:'{{'+e.target.value+'}}'});}}><option value="">Bind to a variable…</option>{Object.keys(project.variables).map(key=><option key={key}>{key}</option>)}{item.kind==='player'&&<option>player.color</option>}</select></label>)}{part.gradient&&<label>Gradient angle<Num label="Artwork gradient angle" value={part.angle} min={-360} max={360} onChange={angle=>change({angle})}/></label>}
  {part.kind==='text'&&<><label>Text / icon<textarea aria-label="Artwork text" value={part.text} onChange={e=>change({text:e.target.value})}/></label><label>Insert data<select aria-label="Artwork text variable" value="" onChange={e=>{if(e.target.value)change({text:part.text+'{{'+e.target.value+'}}'});}}><option value="">Choose a variable…</option>{[...Object.keys(project.variables),...(item.kind==='player'?['player.number','player.name','player.position','player.team']:[])].map(key=><option key={key}>{key}</option>)}</select></label><label>Font<Input aria-label="Artwork font" value={part.fontFamily} onChange={e=>change({fontFamily:e.target.value})}/></label><div className="art-property-grid"><label>Font size<Num label="Artwork font size" value={part.fontSize} min={1} max={500} onChange={fontSize=>change({fontSize})}/></label><label>Weight<Num value={part.fontWeight} min={100} max={900} step={100} onChange={fontWeight=>change({fontWeight})}/></label></div><label>Alignment<select value={part.align} onChange={e=>change({align:e.target.value as ArtPart['align']})}>{['left','center','right'].map(s=><option key={s}>{s}</option>)}</select></label></>}
  {part.kind==='image'&&<><label>Image URL / data variable<Input aria-label="Artwork image" value={part.image} onChange={e=>change({image:e.target.value})}/></label><label>Bind image<select aria-label="Artwork image variable" value="" onChange={e=>{if(e.target.value)change({image:"{{"+e.target.value+"}}"});}}><option value="">Choose a variable…</option>{[...Object.keys(project.variables),...(item.kind==="player"?["player.photo"]:[])].map(key=><option key={key}>{key}</option>)}</select></label><label>Upload image<input aria-label="Upload artwork image" type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>10000000)throw Error('Use an image under 10 MB.');const result=await api<{url:string}>('/api/assets',{method:'POST',headers:{'Content-Type':f.type,'X-File-Name':encodeURIComponent(f.name)},body:f});change({image:result.url});}catch(e){setError((e as Error).message);}}}/></label><select aria-label="Artwork image fit" value={part.imageFit} onChange={e=>change({imageFit:e.target.value as ArtPart['imageFit']})}>{['contain','cover','stretch'].map(v=><option key={v}>{v}</option>)}</select></>}
  {part.kind==='polygon'&&<details><summary>Custom shape points</summary><p>Coordinates are fractions of the shape width and height (0–1).</p>{(source.points||[{x:.5,y:0},{x:1,y:1},{x:0,y:1}]).map((point,index)=><div className="art-point-row" key={index}><span>{index+1}</span>{(['x','y'] as const).map(axis=><Num key={axis} label={'Point '+(index+1)+' '+axis} value={point[axis]} min={0} max={1} step={.01} onChange={value=>commit({...draft,parts:draft.parts.map(p=>p.id===source.id?{...p,points:(p.points||[{x:.5,y:0},{x:1,y:1},{x:0,y:1}]).map((v,i)=>i===index?{...v,[axis]:value}:v)}:p)})}/>)}<button disabled={(source.points?.length||3)<=3} onClick={()=>commit({...draft,parts:draft.parts.map(p=>p.id===source.id?{...p,points:p.points!.filter((_,i)=>i!==index)}:p)})}>×</button></div>)}<button disabled={(source.points?.length||3)>=100} onClick={()=>commit({...draft,parts:draft.parts.map(p=>p.id===source.id?{...p,points:[...(p.points||[{x:.5,y:0},{x:1,y:1},{x:0,y:1}]),{x:.5,y:.5}]}:p)})}>Add point</button></details>}
  {state!=='normal' &&<button onClick={()=>commit({...draft,parts:draft.parts.map(p=>p.id===source.id?{...p,states:{...p.states,[state]:undefined}}:p)})}>Reset this state override</button>}
 </fieldset>:<p>Select or add a visual layer.</p>}</aside></div>{error&&<p role="alert" className="error">{error}</p>}<div className="art-dialog-footer"><small>Preview only · no actions run here</small><span className="spacer"/><Button variant="outline" onClick={()=>setOpen(false)}>Cancel design</Button><Button onClick={save}>Apply button design</Button></div>
 </DialogContent></Dialog></>;
}
