'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Choice,Num} from './controls';
import {action,type Control,type Project} from '@/lib/studio-model';
import {ActionSequenceEditor,ConditionEditor} from './action-sequence-editor';
import {VariableSelect} from './variable-select';
import {api} from '@/lib/client-api';

export function ButtonDesigner({item,project,patch}:{item:Control;project:Project;patch:(v:Partial<Control>)=>void}){
 const [uploadMessage,setUploadMessage]=useState('');
 const [state,setState]=useState<'normal'|'pressed'|'disabled'|'live'>('normal'),style=state==='normal'?item.appearance||{}:item.stateStyles?.[state]||{},set=(v:Partial<NonNullable<Control['appearance']>>)=>patch(state==='normal'?{appearance:{...style,...v}}:{stateStyles:{...item.stateStyles,[state]:{...style,...v}}});
 return <details className="button-design-editor" open><summary>Control appearance & states</summary><div className="state-tabs">{(['normal','pressed','disabled','live'] as const).map(s=><button type="button" key={s} aria-pressed={state===s} onClick={()=>setState(s)}>{s}</button>)}</div><small className="creative-help">State overrides inherit normal styling. Colors and labels accept {'{{variable}}'}.</small>{(['background','foreground','borderColor','label','icon','image','fontFamily'] as const).map(key=><label key={key}>{({background:'Background',foreground:'Text color',borderColor:'Border color',label:'Label override',icon:'Icon / symbol',image:'Image URL',fontFamily:'Font family'})[key]}<Input aria-label={state+' '+key} value={style[key]||''} placeholder={key==='image'?'https://… or {{playerPhoto}}':key==='label'?'e.g. HOME: {{homeScore}}':'Inherit'} onChange={e=>set({[key]:e.target.value||undefined})}/></label>)}<label>Upload button image<input type="file" aria-label="Upload button image" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>10000000)throw Error('Use an image smaller than 10 MB.');setUploadMessage('Uploading…');const asset=await api<{url:string}>('/api/assets',{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)},body:file});set({image:asset.url});setUploadMessage('Image added.');}catch(e){setUploadMessage((e as Error).message);}}}/></label>{uploadMessage&&<p role="status" className="creative-help">{uploadMessage}</p>}<div className="property-grid">{(['borderWidth','radius','fontSize','fontWeight'] as const).map(key=><label key={key}>{({borderWidth:'Border width',radius:'Corner radius',fontSize:'Font size',fontWeight:'Font weight'})[key]}<Num label={state+' '+key} value={style[key]??item.appearance?.[key]??({borderWidth:0,radius:8,fontSize:18,fontWeight:600})[key]} min={key==='fontSize'?10:key==='fontWeight'?100:0} max={key==='fontSize'?200:key==='fontWeight'?900:key==='radius'?150:20} step={key==='fontWeight'?100:1} onChange={n=>set({[key]:n})}/></label>)}</div><Button size="sm" variant="ghost" onClick={()=>patch(state==='normal'?{appearance:undefined}:{stateStyles:{...item.stateStyles,[state]:undefined}})}>Reset {state} style</Button></details>;
}
export function ControlRules({item,project,patch}:{item:Control;project:Project;patch:(v:Partial<Control>)=>void}){
 return <details><summary>Live state, visibility & availability</summary>{(['liveWhen','visibleWhen','enabledWhen'] as const).map(key=><section key={key}><strong>{key==='liveWhen'?'Show LIVE appearance':key==='visibleWhen'?'Show control':'Enable control'}</strong><ConditionEditor project={project} a={{...action('set'),when:item[key]}} patch={v=>patch({[key]:v.when})}/></section>)}</details>;
}
export function EventDesigner({item,project,patch}:{item:Control;project:Project;patch:(v:Partial<Control>)=>void}){
 return <details><summary>Press / release / hold actions</summary><p className="creative-help">Click uses the main action sequence. Hold runs after the delay, then repeats after each run finishes. Release runs on pointer/key up. A completed hold suppresses click.</p><div className="property-grid"><label>Hold delay · ms<Num label="Hold delay" value={item.holdDelay||500} min={250} max={5000} onChange={holdDelay=>patch({holdDelay})}/></label><label>Repeat gap · ms<Num label="Hold repeat" value={item.holdRepeat||200} min={100} max={5000} onChange={holdRepeat=>patch({holdRepeat})}/></label></div>{(['press','release','hold'] as const).map(event=><details key={event}><summary>{event.toUpperCase()} · {item.events?.[event]?.length||0} actions</summary><ActionSequenceEditor project={project} actions={item.events?.[event]||[]} onChange={actions=>patch({events:{...item.events,[event]:actions}})}/></details>)}</details>;
}
export function SelectorSettings({item,project,patch}:{item:Control;project:Project;patch:(v:Partial<Control>)=>void}){
 const config=item.optionSource,fields=item.kind==='roster'?['name','number','photo','position','team']:['value','label','photo',...Object.keys(config?.fields||{})],set=(v:Partial<NonNullable<Control['optionSource']>>)=>patch({optionSource:{sourceId:'',rowsPath:'',valuePath:'id',labelPath:'name',photoPath:'',...config,...v}}),[fieldName,setFieldName]=useState('');
 return <><div className="panel-heading section-gap">CHOICE DATA</div>{item.kind==='roster'?<label>Roster team<Choice label="Roster team" value={item.rosterTeam||'all'} options={['all','home','away']} onChange={v=>patch({rosterTeam:v as 'all'|'home'|'away'})}/></label>:<><label>Choices from<Choice label="Choices data source" value={config?.sourceId||''} options={[{value:'',label:'Manual choices'},...project.sources.map(s=>({value:s.id,label:s.name}))]} onChange={sourceId=>sourceId?set({sourceId}):patch({optionSource:undefined})}/></label>{config&&<>{(['rowsPath','valuePath','labelPath','photoPath'] as const).map(key=><label key={key}>{({rowsPath:'Array path',valuePath:'Value field',labelPath:'Label field',photoPath:'Photo field (optional)'})[key]}<Input value={config[key]} aria-label={key} onChange={e=>set({[key]:e.target.value})}/></label>)}<p className="creative-help">Fetch this source in Data or with a Fetch API action. Lists support up to 500 unique choices.</p>{Object.entries(config.fields||{}).map(([key,path])=><label key={key}>Extra field: {key}<Input value={path} placeholder="Path within each row" onChange={e=>set({fields:{...config.fields,[key]:e.target.value}})}/></label>)}<div className="row"><Input aria-label="New selector field" value={fieldName} placeholder="e.g. kills" onChange={e=>setFieldName(e.target.value)}/><Button size="sm" variant="outline" disabled={!/^[A-Za-z][\w.-]{0,49}$/.test(fieldName)} onClick={()=>{set({fields:{...config.fields,[fieldName]:fieldName}});setFieldName('');}}>Add field</Button></div></>}</>}
 {(item.kind==='roster'||config)&&<details open><summary>Fill variables when selected</summary>{fields.map(field=><label key={field}>{field}<VariableSelect label={'Selection '+field+' variable'} value={item.selectionBindings?.[field]||''} variables={project.variables} onChange={target=>{const next={...item.selectionBindings};if(target)next[field]=target;else delete next[field];patch({selectionBindings:next});}}/>{item.selectionBindings?.[field]&&<Button variant="ghost" size="sm" onClick={()=>{const next={...item.selectionBindings};delete next[field];patch({selectionBindings:next});}}>Disconnect</Button>}</label>)}<p className="creative-help">The selected ID and mapped fields update together before the main action sequence.</p></details>}</>;
}
