'use client';
import {useContext,useEffect,useLayoutEffect,useRef,useState} from 'react';
import {CanvasScale} from './canvas-view-context';
import {atTime,propertyValue,type Scene,type Layer} from '@/lib/studio-model';
import {editValues} from '@/lib/editing-tools';
import {curvePath,type CurvePoint} from '@/lib/editing-schema';
type Point={x:number;y:number};
type Frame={matrix:DOMMatrix;screen:DOMMatrix;x:number;y:number;width:number;height:number;layers:Layer[]};
type Gesture={base:Scene;frame:Frame;start:Point;kind:string;next:Scene;changed:boolean;point?:number;handle?:'in'|'out';points?:CurvePoint[]};
export default function CanvasGizmo({scene,display,ids,time,animate,mode,preview,commit,onError}:{scene:Scene;display:Scene;ids:string[];time:number;animate:boolean;mode:'select'|'nodes'|'motion';preview:(scene:Scene|null)=>void;commit:(scene:Scene)=>void;onError:(e:unknown)=>void}){
 const zoom=useContext(CanvasScale);const svg=useRef<SVGSVGElement>(null),gesture=useRef<Gesture|null>(null),[frame,setFrame]=useState<Frame|null>(null),[activePoint,setActivePoint]=useState(0),[snapLines,setSnapLines]=useState<{axis:'x'|'y';value:number;distance:number}[]>([]),latest=useRef(scene);latest.current=scene;
 function cancel(){gesture.current=null;preview(null);setSnapLines([]);}
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel();};window.addEventListener('keydown',fn);window.addEventListener('blur',cancel);return()=>{window.removeEventListener('keydown',fn);window.removeEventListener('blur',cancel);};},[]);
 useEffect(()=>{if(gesture.current&&gesture.current.base!==scene)cancel();},[scene,ids.join(','),time,mode]);
 useEffect(()=>{cancel();},[ids.join(','),time,mode]);
 useLayoutEffect(()=>{const root=svg.current?.parentElement?.querySelector('svg.graphic') as SVGSVGElement|null,rootMatrix=root?.getScreenCTM();if(!rootMatrix){setFrame(null);return;}const layers=display.layers.filter(l=>ids.includes(l.id)&&!l.locked),elements=layers.map(l=>[...root!.querySelectorAll<SVGGraphicsElement>('[data-layer-id]')].find(el=>el.dataset.layerId===l.id));if(!layers.length||elements.some(e=>!e?.getScreenCTM())||new Set(layers.map(l=>l.groupId)).size>1){setFrame(null);return;}
  const single=layers.length===1,first=elements[0]!,screen=single&&mode!=='motion'?first.getScreenCTM()!:((first.parentElement!.parentElement as unknown as SVGGraphicsElement).getScreenCTM()!);
  if(Math.abs(screen.a*screen.d-screen.b*screen.c)<.000001){setFrame(null);return;}
  const corners=layers.flatMap((l,i)=>{const matrix=screen.inverse().multiply(elements[i]!.getScreenCTM()!),size=atTime(l,time);return [[0,0],[size.width,0],[0,size.height],[size.width,size.height]].map(([x,y])=>new DOMPoint(x,y).matrixTransform(matrix));}),x=Math.min(...corners.map(p=>p.x)),y=Math.min(...corners.map(p=>p.y));
  setFrame({matrix:rootMatrix.inverse().multiply(screen),screen,x,y,width:Math.max(1,Math.max(...corners.map(p=>p.x))-x),height:Math.max(1,Math.max(...corners.map(p=>p.y))-y),layers:layers.map(l=>atTime(l,time))});
 },[display,ids.join(','),time,mode,zoom]);
 const point=(e:{clientX:number;clientY:number},f:Frame)=>new DOMPoint(e.clientX,e.clientY).matrixTransform(f.screen.inverse());
 function begin(e:React.PointerEvent,kind:string,index?:number,handle?:'in'|'out'){if(e.button!==0||!frame)return;e.preventDefault();e.stopPropagation();const original=scene.layers.find(l=>l.id===frame.layers[0].id)!;let points:CurvePoint[]|undefined;if(kind==='node'){setActivePoint(index||0);points=mode==='motion'?structuredClone(original.motionPath!.points):original.visual!.points!.map(p=>({x:p.x*original.width,y:p.y*original.height,inX:p.inX===undefined?undefined:p.inX*original.width,inY:p.inY===undefined?undefined:p.inY*original.height,outX:p.outX===undefined?undefined:p.outX*original.width,outY:p.outY===undefined?undefined:p.outY*original.height}));}
  gesture.current={base:scene,frame,start:point(e,frame),kind,next:scene,changed:false,point:index,handle,points};svg.current!.setPointerCapture(e.pointerId);
 }
 function move(e:React.PointerEvent){const g=gesture.current;if(!g)return;e.preventDefault();const f=g.frame,p=point(e,f),dx=p.x-g.start.x,dy=p.y-g.start.y;g.changed||=Math.hypot(dx,dy)>0.5;if(!g.changed)return;try{
  let changes=new Map<string,Layer>();const single=f.layers.length===1,first=f.layers[0],original=g.base.layers.find(l=>l.id===first.id)!;
  if(g.kind==='node'&&g.points){const points=structuredClone(g.points),i=g.point!,old=points[i];if(g.handle){old[g.handle+'X' as 'inX']=g.points[i][g.handle+'X' as 'inX']!+dx;old[g.handle+'Y' as 'inY']=g.points[i][g.handle+'Y' as 'inY']!+dy;if(!e.altKey){const opposite=g.handle==='in'?'out':'in';old[opposite+'X' as 'inX']=old.x*2-old[g.handle+'X' as 'inX']!;old[opposite+'Y' as 'inY']=old.y*2-old[g.handle+'Y' as 'inY']!;}}else{old.x+=dx;old.y+=dy;for(const k of ['in','out'] as const){if(old[k+'X' as 'inX']!==undefined)old[k+'X' as 'inX']!+=dx;if(old[k+'Y' as 'inY']!==undefined)old[k+'Y' as 'inY']!+=dy;}}
   if(mode==='motion')changes.set(original.id,{...original,motionPath:{...original.motionPath!,points}});else changes.set(original.id,{...original,visual:{...original.visual,points:points.map(p=>({x:Math.max(0,Math.min(1,p.x/original.width)),y:Math.max(0,Math.min(1,p.y/original.height)),inX:p.inX===undefined?undefined:Math.max(-2,Math.min(3,p.inX/original.width)),inY:p.inY===undefined?undefined:Math.max(-2,Math.min(3,p.inY/original.height)),outX:p.outX===undefined?undefined:Math.max(-2,Math.min(3,p.outX/original.width)),outY:p.outY===undefined?undefined:Math.max(-2,Math.min(3,p.outY/original.height))}))}});
  }else if(g.kind==='anchor'&&single){const ax=propertyValue(first,'anchorX')+dx,ay=propertyValue(first,'anchorY')+dy,r=first.rotation*Math.PI/180,a=Math.cos(r)*(first.scaleX??1),b=Math.sin(r)*(first.scaleX??1),c=-Math.sin(r)*(first.scaleY??1),d=Math.cos(r)*(first.scaleY??1);changes.set(first.id,editValues(original,{anchorX:ax,anchorY:ay,x:first.x+(a-1)*dx+c*dy,y:first.y+b*dx+(d-1)*dy},time,animate));
  }else if(g.kind==='move'){
   // Screen vectors are converted using the actual parent CTM, including imported groups.
   const el=[...svg.current!.parentElement!.querySelectorAll<SVGGraphicsElement>('[data-layer-id]')].find(el=>el.dataset.layerId===first.id)!,pm=(el.parentElement!.parentElement as unknown as SVGGraphicsElement).getScreenCTM()!.inverse();const screenStart=new DOMPoint(g.start.x,g.start.y).matrixTransform(f.screen),a=new DOMPoint(e.clientX,e.clientY).matrixTransform(pm),b=new DOMPoint(screenStart.x,screenStart.y).matrixTransform(pm);let mx=a.x-b.x,my=a.y-b.y;
   const lines:{axis:'x'|'y';value:number;distance:number}[]=[];if(!e.altKey&&!first.groupId){for(const axis of ['x','y'] as const){const dimension=axis==='x'?'width':'height',delta=axis==='x'?mx:my,positions=[first[axis]+delta,first[axis]+first[dimension]/2+delta,first[axis]+first[dimension]+delta];const candidates=[0,(axis==='x'?scene.width:scene.height)/2,axis==='x'?scene.width:scene.height,...(scene.guides||[]).filter(v=>v.axis===axis).map(v=>v.position),...scene.layers.filter(l=>!ids.includes(l.id)&&!l.groupId&&l.visible).flatMap(l=>{const v=atTime(l,time);return [v[axis],v[axis]+v[dimension]/2,v[axis]+v[dimension]];})];let best=6*Math.max(.1,Math.hypot(pm.a,pm.b)) ,correction=0,target=0;for(const value of candidates)for(const position of positions)if(Math.abs(value-position)<best){best=Math.abs(value-position);correction=value-position;target=value;}if(correction){if(axis==='x')mx+=correction;else my+=correction;lines.push({axis,value:target,distance:Math.round(axis==='x'?mx:my)});}}}setSnapLines(lines);
   for(const l of f.layers)changes.set(l.id,editValues(g.base.layers.find(o=>o.id===l.id)!,{x:l.x+mx,y:l.y+my},time,animate));
  }else if(g.kind==='rotate'){
   const cx=single?propertyValue(first,'anchorX'):f.x+f.width/2,cy=single?propertyValue(first,'anchorY'):f.y+f.height/2,angle=(Math.atan2(p.y-cy,p.x-cx)-Math.atan2(g.start.y-cy,g.start.x-cx))*180/Math.PI,degrees=e.shiftKey?Math.round(angle/15)*15:angle,r=degrees*Math.PI/180;
   for(const l of f.layers){const ax=propertyValue(l,'anchorX'),ay=propertyValue(l,'anchorY'),vx=l.x+ax-cx,vy=l.y+ay-cy;changes.set(l.id,editValues(g.base.layers.find(o=>o.id===l.id)!,{rotation:l.rotation+degrees,...(!single?{x:cx+vx*Math.cos(r)-vy*Math.sin(r)-ax,y:cy+vx*Math.sin(r)+vy*Math.cos(r)-ay}:{})},time,animate));}
  }else{
   const left=g.kind.includes('w'),top=g.kind.includes('n'),horizontal=g.kind.includes('w')||g.kind.includes('e'),vertical=g.kind.includes('n')||g.kind.includes('s'),fx=left?f.x+f.width:f.x,fy=top?f.y+f.height:f.y;let sx=horizontal?Math.max(.01,1+(left?-dx:dx)/f.width):1,sy=vertical?Math.max(.01,1+(top?-dy:dy)/f.height):1;
   if(e.shiftKey||!single){const ratio=horizontal?sx:sy;sx=sy=ratio;}
   for(const l of f.layers){const ax=propertyValue(l,'anchorX'),ay=propertyValue(l,'anchorY');let x:number,y:number;if(single){const r=l.rotation*Math.PI/180,tx=(1-sx)*(fx-ax)*(l.scaleX??1),ty=(1-sy)*(fy-ay)*(l.scaleY??1);x=l.x+tx*Math.cos(r)-ty*Math.sin(r);y=l.y+tx*Math.sin(r)+ty*Math.cos(r);}else{x=fx+(l.x+ax-fx)*sx-ax;y=fy+(l.y+ay-fy)*sy-ay;}changes.set(l.id,editValues(g.base.layers.find(o=>o.id===l.id)!,{x,y,scaleX:(l.scaleX??1)*sx,scaleY:(l.scaleY??1)*sy},time,animate));}
  }
  g.next={...g.base,layers:g.base.layers.map(l=>changes.get(l.id)||l)};preview(g.next);
 }catch(error){cancel();onError(error);}}
 function finish(e:React.PointerEvent){const g=gesture.current;gesture.current=null;setSnapLines([]);preview(null);if(g?.changed&&latest.current===g.base)try{commit(g.next);}catch(error){onError(error);}if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);}
 const l=frame?.layers[0],base=l?display.layers.find(v=>v.id===l.id):undefined,points=base?(mode==='motion'?base.motionPath?.points:base.visual?.points?.map(p=>({x:p.x*base.width,y:p.y*base.height,inX:p.inX===undefined?undefined:p.inX*base.width,inY:p.inY===undefined?undefined:p.inY*base.height,outX:p.outX===undefined?undefined:p.outX*base.width,outY:p.outY===undefined?undefined:p.outY*base.height}))):undefined;
 const unit=frame?1/Math.max(.03,Math.hypot(frame.screen.a,frame.screen.b)):1;
 function updatePoints(action:'smooth'|'corner'|'insert'|'remove'){if(!base||!points)return;const next=structuredClone(points),p=next[activePoint]||next[0],i=Math.min(activePoint,next.length-1);if(action==='smooth'){p.inX=p.x-40;p.inY=p.y;p.outX=p.x+40;p.outY=p.y;}if(action==='corner'){delete p.inX;delete p.inY;delete p.outX;delete p.outY;}if(action==='remove'&&next.length>2)next.splice(i,1);if(action==='insert'&&next.length<100){const b=next[Math.min(next.length-1,i+1)];next.splice(i+1,0,{x:(p.x+b.x)/2,y:(p.y+b.y)/2});}commit({...scene,layers:scene.layers.map(l=>l.id!==base.id?l:mode==='motion'?{...l,motionPath:{...l.motionPath!,points:next}}:{...l,visual:{...l.visual,points:next.map(p=>({x:p.x/l.width,y:p.y/l.height,inX:p.inX===undefined?undefined:p.inX/l.width,inY:p.inY===undefined?undefined:p.inY/l.height,outX:p.outX===undefined?undefined:p.outX/l.width,outY:p.outY===undefined?undefined:p.outY/l.height}))}})});}
 return <><svg ref={svg} className="canvas-gizmo" viewBox={`0 0 ${scene.width} ${scene.height}`} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel} onLostPointerCapture={()=>{if(gesture.current)cancel();}}>{snapLines.map(line=><g key={line.axis} stroke="#55e0c1" fill="#55e0c1"><line x1={line.axis==='x'?line.value:0} x2={line.axis==='x'?line.value:scene.width} y1={line.axis==='y'?line.value:0} y2={line.axis==='y'?line.value:scene.height} vectorEffect="non-scaling-stroke"/><text x={line.axis==='x'?line.value+8:12} y={line.axis==='y'?line.value-8:30} fontSize="22">{line.distance}px</text></g>)}{frame&&<g transform={`matrix(${frame.matrix.a} ${frame.matrix.b} ${frame.matrix.c} ${frame.matrix.d} ${frame.matrix.e} ${frame.matrix.f})`}>
 {mode==='select'?<><rect x={frame.x} y={frame.y} width={frame.width} height={frame.height} fill="transparent" stroke="#6bddff" vectorEffect="non-scaling-stroke" style={{pointerEvents:'all',cursor:'move'}} onPointerDown={e=>begin(e,'move')}/>{[['nw',0,0],['n',.5,0],['ne',1,0],['e',1,.5],['se',1,1],['s',.5,1],['sw',0,1],['w',0,.5]].map(([kind,x,y])=><rect key={kind} aria-label={'Transform '+kind} x={frame.x+Number(x)*frame.width-4*unit} y={frame.y+Number(y)*frame.height-4*unit} width={8*unit} height={8*unit} fill="#c3efff" stroke="#17354d" strokeWidth={unit} style={{pointerEvents:'all',cursor:String(kind)+'-resize'}} onPointerDown={e=>begin(e,String(kind))}/>)}<line x1={frame.x+frame.width/2} x2={frame.x+frame.width/2} y1={frame.y} y2={frame.y-24*unit} stroke="#6bddff" strokeWidth={unit}/><circle aria-label="Rotate selection" cx={frame.x+frame.width/2} cy={frame.y-28*unit} r={5*unit} fill="#6bddff" style={{pointerEvents:'all',cursor:'grab'}} onPointerDown={e=>begin(e,'rotate')}/>{frame.layers.length===1&&<circle aria-label="Layer anchor point" cx={propertyValue(l!,'anchorX')} cy={propertyValue(l!,'anchorY')} r={6*unit} fill="#192633" stroke="#ffa658" strokeWidth={2*unit} style={{pointerEvents:'all',cursor:'crosshair'}} onPointerDown={e=>begin(e,'anchor')}/>}</>:points&&base&&<g transform={mode==='motion'?`translate(${base.x} ${base.y})`:undefined}><path d={curvePath(points,mode==='nodes'&&base.visual?.closed)} fill="none" stroke="#6bddff" strokeWidth={2*unit}/>{points.map((p,i)=><g key={i}>{(['in','out'] as const).map(k=>p[k+'X' as 'inX']!==undefined&&<g key={k}><line x1={p.x} y1={p.y} x2={p[k+'X' as 'inX']} y2={p[k+'Y' as 'inY']} stroke="#b9deed" strokeWidth={unit}/><circle cx={p[k+'X' as 'inX']} cy={p[k+'Y' as 'inY']} r={4*unit} fill="#fff" style={{pointerEvents:'all',cursor:'crosshair'}} onPointerDown={e=>begin(e,'node',i,k)}/></g>)}<circle aria-label={'Path point '+(i+1)} cx={p.x} cy={p.y} r={5*unit} fill={i===activePoint?'#ff8b38':'#6bddff'} style={{pointerEvents:'all',cursor:'move'}} onPointerDown={e=>begin(e,'node',i)}/></g>)}</g>}
 </g>}</svg>{mode!=='select'&&points&&<div className="path-edit-toolbar" style={{transform:`scale(${unit})`,transformOrigin:"bottom left"}}>{(['smooth','corner','insert','remove'] as const).map(action=><button key={action} onClick={()=>updatePoints(action)}>{action}</button>)}<span>Drag points / handles · Alt breaks symmetry · Esc cancels</span></div>}</>;
}
