'use client';
import {useContext,useEffect,useRef,useState} from 'react';
import {CanvasScale} from './canvas-view-context';
import {uid,type Scene} from '@/lib/studio-model';
type Guide=NonNullable<Scene['guides']>[number];
export default function CanvasRulers({scene,commit}:{scene:Scene;commit:(scene:Scene)=>void}){
 const zoom=useContext(CanvasScale),unit=1/zoom,step=100*Math.max(1,2**Math.ceil(Math.log2(.5/zoom)));const svg=useRef<SVGSVGElement>(null),drag=useRef<Guide|null>(null),[active,setActive]=useState<Guide|null>(null);function cancel(){drag.current=null;setActive(null);}
 useEffect(()=>{cancel();},[scene]);useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel();};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[]);
 function begin(e:React.PointerEvent,axis:'x'|'y',guide?:Guide){if(guide?.locked)return;e.preventDefault();e.stopPropagation();drag.current=guide||{id:uid(),axis,position:0,locked:false};setActive(drag.current);svg.current!.setPointerCapture(e.pointerId);}
 return <svg ref={svg} className="canvas-rulers" viewBox={`0 0 ${scene.width} ${scene.height}`} onPointerMove={e=>{const guide=drag.current;if(!guide)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(e.currentTarget.getScreenCTM()!.inverse());setActive({...guide,position:Math.round(p[guide.axis])});}} onPointerUp={e=>{if(active){const guides=(scene.guides||[]).filter(g=>g.id!==active.id);if(active.position>=0&&active.position<=(active.axis==='x'?scene.width:scene.height)&&guides.length<100)guides.push(active);commit({...scene,guides});}cancel();e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={cancel} onLostPointerCapture={()=>{if(drag.current)cancel();}}><rect x="0" y={-24*unit} width={scene.width} height={24*unit} fill="#172737" style={{pointerEvents:'all',cursor:'ns-resize'}} onPointerDown={e=>begin(e,'y')}/><rect x={-24*unit} y="0" width={24*unit} height={scene.height} fill="#172737" style={{pointerEvents:'all',cursor:'ew-resize'}} onPointerDown={e=>begin(e,'x')}/>{Array.from({length:Math.ceil(scene.width/step)},(_,i)=><text key={i} x={i*step+3} y={-7*unit} fontSize={12*unit} fill="#94b0c7">{i*step}</text>)}{Array.from({length:Math.ceil(scene.height/step)},(_,i)=><text key={i} transform={`translate(${-7*unit} ${i*step+3}) rotate(90)`} fontSize={12*unit} fill="#94b0c7">{i*step}</text>)}{[...(scene.guides||[]).filter(g=>g.id!==active?.id),...(active?[active]:[])].map(g=><g key={g.id}><line x1={g.axis==='x'?g.position:0} x2={g.axis==='x'?g.position:scene.width} y1={g.axis==='y'?g.position:0} y2={g.axis==='y'?g.position:scene.height} stroke="#45d2c7" strokeWidth="1" vectorEffect="non-scaling-stroke"/><line aria-label={'Guide '+g.axis+' '+g.position} x1={g.axis==='x'?g.position:0} x2={g.axis==='x'?g.position:scene.width} y1={g.axis==='y'?g.position:0} y2={g.axis==='y'?g.position:scene.height} stroke="transparent" strokeWidth="10" vectorEffect="non-scaling-stroke" style={{pointerEvents:'stroke',cursor:g.locked?'default':g.axis==='x'?'ew-resize':'ns-resize'}} onPointerDown={e=>begin(e,g.axis,g)} onDoubleClick={()=>!g.locked&&commit({...scene,guides:scene.guides?.filter(v=>v.id!==g.id)})}/></g>)}</svg>;
}
