'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type CommandState} from '@/lib/command-types';
import './command-tools.css';
export function CommandMonitor({state,busy,canCancel,onCancel,onRefresh}:{state:CommandState;busy:boolean;canCancel:boolean;onCancel:(id?:string)=>void;onRefresh:()=>void}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState('');const active=state.active,job=state.history.find(j=>j.id===selected)||active||state.history[0];
 return <><div className="command-monitor" role="status"><span className={'command-dot '+(busy?'active':'')}/><div>{active?<><strong>{active.label}</strong> · {active.status} · {active.completedSteps}/{active.steps.length} steps <small>{active.username} · {active.workstation}</small></>:busy?'Checking command outcome…':state.history.length?<>Last run: {state.history[0].label} · <strong>{state.history[0].status}</strong></>:'Local action service ready'}</div><span className="spacer"/>{busy&&canCancel&&<Button variant="outline" size="sm" onClick={()=>onCancel(active?.id)}>Cancel sequence</Button>}<Button size="sm" variant="ghost" onClick={()=>{onRefresh();setOpen(true);}}>Execution history</Button></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="command-history-dialog"><DialogHeader><DialogTitle>Execution history</DialogTitle><DialogDescription>Accepted commands are recorded locally. Reconnect reads their outcome; it never replays a command. Cancel stops pending steps and does not undo completed actions.</DialogDescription></DialogHeader><div className="command-history-layout"><aside>{state.history.map(j=><button className={job?.id===j.id?'selected':''} key={j.id} onClick={()=>setSelected(j.id)}><strong>{j.label}</strong><small>{j.status} · {new Date(j.createdAt).toLocaleTimeString()}</small></button>)}</aside><section>{job?<><h3>{job.label} · {job.status}</h3><p>{job.username} · {job.workstation}</p><code>{job.id}</code>{job.error&&<p className="macro-error" role="alert">{job.error}</p>}<ol>{job.steps.map(s=><li key={s.index}><span className={'step-status '+s.status}>{s.status}</span><div><strong>{s.index+1}. {s.type}{s.target?' · '+s.target:''}</strong>{s.path&&<small>{s.path}</small>}{s.message&&<p>{s.message}</p>}</div></li>)}</ol></>:<p>No commands have run in this workspace.</p>}</section></div></DialogContent></Dialog></>;
}
