'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Control,Project} from '@/lib/studio-model';
import {controlKinds} from '@/lib/broadcast-tools';
import {Choice,Num} from './controls';
import {VariableSelect} from './variable-select';
export function ControlSettings({item,project,patch,change,onFormations}:{item:Control;project:Project;patch:(v:Partial<Control>)=>void;change:(fn:(p:Project)=>Project)=>void;onFormations:()=>void}){
 const [newKey,setNewKey]=useState(''),[error,setError]=useState(''),[quickDraft,setQuickDraft]=useState(item.quickSteps?.join(',')||'');
 const numeric=['counter','number','slider'].includes(item.kind),bound=!['button','pitch','bench','scoreboard','label','image'].includes(item.kind);
 return <><label>Control type<Choice label="Control type" value={item.kind} options={controlKinds} onChange={v=>{
  const kind=v as Control['kind'],primary=item.actions.find(a=>a.type==='increment'),variable=item.variable||(primary?.target&&typeof project.variables[primary.target]==='number'?primary.target:'');
  patch({kind,variable,...(kind==='counter'?{step:Math.abs(Number(primary?.value))||item.step||1,actions:item.actions.filter(a=>a!==primary),...(item.placement?{placement:{...item.placement,height:Math.max(150,item.placement.height)}}:{})}:{})});
 }}/></label>{bound&&<><label>Shared variable<VariableSelect label="Shared variable" variables={project.variables} value={item.variable} numericOnly={numeric} onChange={variable=>patch({variable})}/></label><details className="create-variable"><summary>Create a new variable</summary><Input aria-label="New control variable" value={newKey} placeholder="e.g. homeKills" onChange={e=>setNewKey(e.target.value)}/><Button size="sm" variant="secondary" onClick={()=>{const key=newKey.trim();if(!/^[A-Za-z][A-Za-z0-9_.-]{0,99}$/.test(key)){setError('Use a name beginning with a letter, without spaces.');return;}const initial=numeric?0:item.kind==='toggle'?false:item.kind==='color'?'#ffffff':item.kind==='formation'?'4-3-3':item.kind==='timer'?'00:00':'';change(p=>({...p,variables:{...p.variables,[key]:Object.hasOwn(p.variables,key)?p.variables[key]:initial},panels:p.panels.map(panel=>({...panel,controls:panel.controls.map(c=>c.id===item.id?{...c,variable:key}:c)}))}));setNewKey('');setError('');}}>Create & connect</Button>{error&&<small className="error">{error}</small>}</details></>}
 {['counter','slider'].includes(item.kind)&&<><div className="property-grid"><label>Minimum<Num label="Control minimum" value={item.minimum??0} onChange={minimum=>patch({minimum,maximum:Math.max(minimum,item.maximum??(item.kind==='slider'?100:999999))})}/></label><label>Maximum<Num label="Control maximum" value={item.maximum??(item.kind==='slider'?100:999999)} onChange={maximum=>patch({maximum,minimum:Math.min(maximum,item.minimum??0)})}/></label><label>Step<Num label="Control step" value={item.step??1} min={.001} max={100000} step={.1} onChange={step=>patch({step})}/></label>{item.kind==='counter'&&<label>Reset value<Num value={item.resetValue??0} onChange={resetValue=>patch({resetValue})}/></label>}</div>{item.kind==='counter'&&<label>Quick increments<Input placeholder="1,2,3" value={quickDraft} onChange={e=>setQuickDraft(e.target.value)} onBlur={()=>{const quickSteps=quickDraft.split(',').map(Number).filter(n=>n>0&&n<=100000).slice(0,6);patch({quickSteps:[...new Set(quickSteps)]});}}/><small>Extra scoring buttons, such as +2 and +3.</small></label>}<p className="helper muted">Changes this variable first, then runs the action sequence below.</p></>}
 {['select','segmented'].includes(item.kind)&&<label>Choices<Textarea value={item.options} onChange={e=>patch({options:e.target.value})} placeholder="One option per line, or separated by commas"/><small>Use any map names, periods, team sides or other choices.</small></label>}
 {item.kind==='formation'&&<Button variant="secondary" className="full" onClick={onFormations}>Create / edit formations</Button>}
 {item.kind==='timer'&&<><label>Clock direction<Choice value={item.timerDirection||'up'} options={[{value:'up',label:'Count up'},{value:'down',label:'Countdown'}]} onChange={v=>patch({timerDirection:v as 'up'|'down'})}/></label><label>Reset duration · seconds<Num value={item.timerSeconds??0} min={0} max={86400} onChange={timerSeconds=>patch({timerSeconds})}/></label><p className="helper muted">Reset loads this duration. Clocks keep running across studio tabs while this page stays open.</p></>}
 {item.kind==='scoreboard'&&<><label>Formation selectors<Choice value={String(item.showFormations!==false)} options={[{value:'true',label:'Show'},{value:'false',label:'Hide for other sports / esports'}]} onChange={v=>patch({showFormations:v==='true'})}/></label><label>Score + / − buttons<Choice value={String(item.showScoreButtons!==false)} options={[{value:'true',label:'Show'},{value:'false',label:'Hide'}]} onChange={v=>patch({showScoreButtons:v==='true'})}/></label></>}
 </>;
}
