'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Choice,Num} from './controls';
import {defaultCues,motionPreset} from '@/lib/creative-tools';
import {uid,type Layer,type Scene} from '@/lib/studio-model';

export function VisualInspector({item,patch}:{item:Layer;patch:(v:Partial<Layer>)=>void}){
 const v=item.visual||{},set=(next:Partial<NonNullable<Layer['visual']>>)=>patch({visual:{...v,...next}});
 const color=(key:'gradientColor'|'stroke'|'shadowColor'|'glowColor',label:string,fallback:string)=><label>{label}<Input aria-label={label} value={v[key]||fallback} onChange={e=>set({[key]:e.target.value})} placeholder="#ffffff or {{teamColor}}"/></label>;
 const number=(key:keyof typeof v,label:string,fallback:number,min:number,max:number,step=1)=><label>{label}<Num label={label} value={Number(v[key]??fallback)} min={min} max={max} step={step} onChange={n=>set({[key]:n})}/></label>;
 return <section className="creative-inspector"><div className="panel-heading section-gap">APPEARANCE & EFFECTS</div>
  {item.type!=='image'&&<><label>Fill<Choice label="Layer fill" value={v.fill||'solid'} options={['solid','linear','radial','none']} onChange={fill=>set({fill:fill as typeof v.fill})}/></label>{['linear','radial'].includes(v.fill||'')&&<>{color('gradientColor','Gradient end','#233b55')}{v.fill==='linear'&&number('gradientAngle','Gradient angle',0,-360,360)}</>}{color('stroke','Outline color','#ffffff')}{number('strokeWidth','Outline width',0,0,100)}</>}
  <details><summary>Shadow, glow & blur</summary><label className="inline-label"><input type="checkbox" checked={item.shadow} onChange={e=>patch({shadow:e.target.checked})}/>Drop shadow</label>{item.shadow&&<>{color('shadowColor','Shadow color','#000000')}<div className="property-grid">{number('shadowX','Shadow X',0,-200,200)}{number('shadowY','Shadow Y',10,-200,200)}{number('shadowBlur','Shadow softness',15,0,100)}</div></>}{color('glowColor','Glow color','#ff6a00')}<div className="property-grid">{number('glow','Glow softness',0,0,100)}{number('blur','Layer blur',0,0,50)}</div></details>
  {item.type==='image'&&<><label>Image fit<Choice label="Layer image fit" value={v.imageFit||'cover'} options={['cover','contain','stretch']} onChange={imageFit=>set({imageFit:imageFit as typeof v.imageFit})}/></label><label>Mask<Choice label="Image mask" value={v.mask||'none'} options={['none','rounded','ellipse']} onChange={mask=>set({mask:mask as typeof v.mask})}/></label>{v.mask==='rounded'&&<label>Mask radius<Num value={item.radius||24} min={0} max={1000} onChange={radius=>patch({radius})}/></label>}<div className="property-grid">{number('cropZoom','Crop zoom',1,1,10,.05)}{number('cropX','Crop horizontal %',50,0,100)}{number('cropY','Crop vertical %',50,0,100)}</div></>}
  {item.type==='text'&&<><label className="inline-label"><input type="checkbox" checked={!!v.autoFit} onChange={e=>set({autoFit:e.target.checked})}/>Auto-fit text inside its box</label><div className="property-grid">{number('letterSpacing','Letter spacing',0,-20,100,.5)}{number('lineHeight','Line height',1.18,.5,3,.01)}</div></>}
  {item.type==='path'&&<PathEditor item={item} patch={patch}/>}
 </section>;
}
function PathEditor({item,patch}:{item:Layer;patch:(v:Partial<Layer>)=>void}){
 const [active,setActive]=useState(0),points=item.visual?.points||[{x:0,y:1},{x:.5,y:0},{x:1,y:1}],set=(next:typeof points)=>patch({visual:{...item.visual,points:next}});
 function position(e:React.MouseEvent<SVGSVGElement>){const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
 return <details open><summary>Vector points</summary><svg className="path-editor" viewBox="0 0 240 150" aria-label="Vector point editor" onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))set(points.map((p,i)=>i===active?position(e):p));}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onDoubleClick={e=>{if(points.length<100)set([...points,position(e)]);}}><path d={points.map((p,i)=>(i?'L':'M')+p.x*240+' '+p.y*150).join(' ')+(item.visual?.closed!==false?'Z':'')} fill={item.visual?.closed!==false?'#ff6a0033':'none'} stroke="#ff994d"/>{points.map((p,i)=><circle key={i} cx={p.x*240} cy={p.y*150} r="6" fill={i===active?'#ffffff':'#ff6a00'} onPointerDown={e=>{setActive(i);e.currentTarget.ownerSVGElement?.setPointerCapture(e.pointerId);}}/>)}</svg><p className="helper">Drag points; double-click to add. Coordinates scale with the layer.</p><label className="inline-label"><input type="checkbox" checked={item.visual?.closed!==false} onChange={e=>patch({visual:{...item.visual,closed:e.target.checked}})}/>Closed shape</label><Button size="sm" variant="outline" disabled={points.length<=2} onClick={()=>{set(points.filter((_,i)=>i!==active));setActive(0);}}>Delete selected point</Button></details>;
}
export function CueInspector({scene,update,preview}:{scene:Scene;update:(fn:(s:Scene)=>Scene)=>void;preview:(id:string)=>void}){
 const cues=scene.cues||[];
 return <details className="cue-editor"><summary>Animation cues · {cues.length}</summary><p className="helper">Buttons can play these named sections on output. Loops continue until another cue or Hide.</p><Button size="sm" variant="outline" disabled={!!cues.length} onClick={()=>update(s=>({...s,cues:defaultCues(s.duration)}))}>Create Intro / Hold / Outro</Button>{cues.map(c=>{const patch=(v:Partial<typeof c>)=>update(s=>({...s,cues:s.cues?.map(x=>x.id===c.id?{...x,...v}:x)}));return <div className="cue-card" key={c.id}><Input aria-label="Cue name" value={c.name} maxLength={100} onChange={e=>patch({name:e.target.value||'Cue'})}/><div className="property-grid"><label>Start<Num label={'Cue start '+c.name} value={c.start} min={0} max={c.end-.001} step={.01} onChange={start=>patch({start})}/></label><label>End<Num label={'Cue end '+c.name} value={c.end} min={c.start+.001} max={scene.duration} step={.01} onChange={end=>patch({end})}/></label></div><label className="inline-label"><input type="checkbox" checked={c.loop} onChange={e=>patch({loop:e.target.checked})}/>Loop section</label><Choice label={'Cue finish '+c.name} value={c.finish} options={[{value:'hold',label:'Hold final frame'},{value:'hide',label:'Hide when finished'}]} onChange={finish=>patch({finish:finish as 'hold'|'hide'})}/><div className="row"><Button variant="outline" size="sm" onClick={()=>preview(c.id)}>Preview {c.name}</Button><Button variant="ghost" size="sm" onClick={()=>update(s=>({...s,cues:s.cues?.filter(x=>x.id!==c.id)}))}>Remove</Button></div></div>;})}<Button size="sm" variant="outline" disabled={cues.length>=50} onClick={()=>update(s=>({...s,cues:[...(s.cues||[]),{id:uid(),name:'New cue',start:0,end:s.duration,loop:false,finish:'hold'}]}))}>Add cue</Button></details>;
}
export function MotionPresets({item,duration,patch}:{item:Layer;duration:number;patch:(v:Partial<Layer>)=>void}){return <label>Motion preset<Choice label="Motion preset" value="" options={[{value:'',label:'Apply to selected layer…'},{value:'fade',label:'Fade in'},{value:'slide',label:'Slide in'},{value:'pop',label:'Pop in'},{value:'out',label:'Fade out'}]} onChange={v=>patch({keys:motionPreset(item,v,duration).keys})}/></label>;}

