'use client';
import {useState} from 'react';
import {selectorOptions} from '@/lib/creative-tools';
import {safeImage,textValue,type Control,type Project} from '@/lib/studio-model';
import {Choice,Num} from './controls';
import {Input} from '@/components/ui/input';
export function CustomWidget({control:c,project,disabled,run,onError}:{control:Control;project:Project;disabled:boolean;run:(c:Control,event?:'click',value?:string)=>Promise<void>;onError:(e:unknown)=>void}){
 const [query,setQuery]=useState(''),[choosing,setChoosing]=useState(false),options=selectorOptions(c,project),value=String(project.variables[c.variable]??''),w=c.widget||{mode:'cards',columns:2,title:'{{row.label}}',subtitle:'{{row.position}}',photo:'{{row.photo}}'};
 const select=(value:string)=>{if(disabled)return;void run(c,'click',value).then(()=>setChoosing(false)).catch(onError);};
 const render=(row:typeof options[number])=>{const data={...project.variables,...Object.fromEntries(Object.entries({...row.fields,value:row.value,label:row.label,photo:row.photo||''}).map(([k,v])=>['row.'+k,v]))};const src=textValue(w.photo,data);return <>{safeImage(src)&&<img src={src} alt=""/>}<strong>{textValue(w.title,data)}</strong>{w.mode!=='tabs'&&<small>{textValue(w.subtitle,data)}</small>}</>;};
 return <div className={'custom-widget '+w.mode} style={{background:c.appearance?.background||c.color,color:c.appearance?.foreground||'#fff',borderRadius:c.appearance?.radius||8}}><label>{textValue(c.label,project.variables)}</label>{w.mode==='dropzone'&&<button aria-label={'Drop or choose '+c.label} className="widget-dropzone" disabled={disabled} onClick={()=>setChoosing(v=>!v)} onDragOver={e=>{if(!disabled&&e.dataTransfer.types.includes('application/x-broadcastcg-row'))e.preventDefault();}} onDrop={e=>{e.preventDefault();if(disabled)return;try{const item=JSON.parse(e.dataTransfer.getData('application/x-broadcastcg-row'));if(item.projectId!==project.id||!options.some(o=>o.value===item.value))throw Error('Drop a matching row from this workspace.');select(item.value);}catch(e){onError(e);}}}>{options.find(o=>o.value===value)?render(options.find(o=>o.value===value)!):'Drop a card here, or click to choose'}</button>}{(w.mode!=='dropzone'||choosing)&&<>{w.mode!=='tabs'&&<Input aria-label={'Search '+c.label} placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/>}<div className="widget-card-grid" style={{gridTemplateColumns:`repeat(${w.columns},minmax(0,1fr))`}}>{options.filter(r=>r.label.toLowerCase().includes(query.toLowerCase())).map(row=><button key={row.value} draggable={!disabled&&w.mode!=='tabs'} disabled={disabled} aria-pressed={row.value===value} onDragStart={e=>e.dataTransfer.setData('application/x-broadcastcg-row',JSON.stringify({projectId:project.id,value:row.value}))} onClick={()=>select(row.value)}>{render(row)}</button>)}</div></>}</div>;
}
export function WidgetSettings({item,patch}:{item:Control;patch:(v:Partial<Control>)=>void}){
 const w=item.widget||{mode:'cards' as const,columns:2,title:'{{row.label}}',subtitle:'{{row.position}}',photo:'{{row.photo}}'},set=(v:Partial<typeof w>)=>patch({widget:{...w,...v}});
 return <details open><summary>Custom widget design</summary><Choice label="Widget mode" value={w.mode} options={['cards','dropzone','tabs']} onChange={mode=>set({mode:mode as typeof w.mode})}/><label>Columns<Num value={w.columns} min={1} max={8} onChange={columns=>set({columns:Math.round(columns)})}/></label>{(['title','subtitle','photo'] as const).map(k=><label key={k}>{k}<Input aria-label={'Widget '+k} value={w[k]} onChange={e=>set({[k]:e.target.value})}/></label>)}<label>Roster choices<Choice value={item.rosterTeam||''} options={[{value:'',label:'Manual / API choices'},'all','home','away']} onChange={rosterTeam=>patch({rosterTeam:(rosterTeam||undefined) as Control['rosterTeam']})}/></label><p className="helper">Use row fields in the card design. Selection and drop both fill mapped variables and run the action sequence. For tabs, connect a shared text variable and use visibility conditions on the controls belonging to each tab.</p></details>;
}
