'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ZoomIn,ZoomOut,Maximize} from 'lucide-react';
import {drawnLayer,drawingBounds,polygonLayer,zoomCanvasAt,type Point,type CanvasView} from '@/lib/design-tools';
import DesignToolbox,{toolboxItems,toolHint,type DesignTool} from './design-toolbox';
import {brushLayer,fillLayer,marqueePolygon,mergeSelection,polygonsOverlap,shapeFromDrag,type SelectionMode} from '@/lib/toolbox-tools';
import {sampleCanvasColor} from './canvas-color-sampler';
import {defaultLayerMask,type LayerMask} from '@/lib/design-schema';
import {CanvasScale} from './canvas-view-context';
import {curveLayer} from '@/lib/editing-tools';
import {curvePath,type CurvePoint} from '@/lib/editing-schema';
import type {Layer,Scene} from '@/lib/studio-model';
export type {DesignTool} from './design-toolbox';
const tools=toolboxItems;
const selections=['marquee','ellipse-select','lasso'];
const typing=(target:EventTarget|null)=>target instanceof HTMLElement&&!!target.closest('input,textarea,select,[contenteditable=true],[role=dialog]');
type Gesture={kind:'pan'|'draw';start:Point;last:Point;pan:Point;points:Point[];display:Point[];matrix?:DOMMatrix;width:number;height:number;shift:boolean;mode:SelectionMode;pointer:number;next?:Layer};
export default function DesignCanvas({scene,item,selection,select,editTime,previewLayer,commitLayer,pause,tool,setTool,color,setColor,brush,setBrush,children,create,mask,onError,onDrop}:{scene:Scene;item?:Layer;selection:string[];select:(ids:string[])=>void;editTime:number;previewLayer:(l:Layer|null)=>void;commitLayer:(l:Layer)=>void;pause:()=>void;tool:DesignTool;setTool:(v:DesignTool)=>void;color:string;setColor:(v:string)=>void;brush:number;setBrush:(v:number)=>void;children:ReactNode;create:(l:Layer)=>void;mask:(v:LayerMask)=>void;onError:(e:unknown)=>void;onDrop:(e:React.DragEvent)=>void}){
 const area=useRef<HTMLDivElement>(null),[view,setView]=useState<CanvasView|null>(null),[size,setSize]=useState({width:800,height:450}),[space,setSpace]=useState(false),[preview,setPreview]=useState<Point[]>([]),[polygon,setPolygon]=useState<Point[]>([]),[square,setSquare]=useState(false);
 const [pen,setPen]=useState<CurvePoint[]>([]),[closed,setClosed]=useState(false),penDrag=useRef<{point:Point;index:number}|null>(null);const gesture=useRef<Gesture|null>(null),current=useRef<CanvasView>({scale:1,pan:{x:0,y:0}}),spaceRef=useRef(false);
 const [background,setBackground]=useState('#ffffff'),[expanded,setExpanded]=useState(false),[paintSize,setPaintSize]=useState(12),[paintOpacity,setPaintOpacity]=useState(100),[smoothing,setSmoothing]=useState(2),[sides,setSides]=useState(5),[inner,setInner]=useState(45),[selectionMode,setSelectionMode]=useState<SelectionMode>('replace'),[contained,setContained]=useState(false),[gradientKind,setGradientKind]=useState<'linear'|'radial'>('linear'),[sampling,setSampling]=useState(false);
 const callbacks=useRef({previewLayer});callbacks.current={previewLayer};
 function cancel(){const g=gesture.current;gesture.current=null;penDrag.current=null;setPreview([]);callbacks.current.previewLayer(null);if(g&&area.current?.hasPointerCapture(g.pointer))area.current.releasePointerCapture(g.pointer);}
 useEffect(()=>{cancel();},[scene,item?.id,selection.join(','),editTime,tool]);
 // An active canvas gesture owns Escape even if another panel handles keyboard events.
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&(gesture.current||penDrag.current)){e.preventDefault();e.stopPropagation();cancel();setPolygon([]);setPen([]);setTool('select');}};window.addEventListener('keydown',escape,true);return()=>window.removeEventListener('keydown',escape,true);},[]);
 const fit=Math.max(.02,Math.min((size.width-48)/scene.width,(size.height-48)/scene.height,1));current.current=view||{scale:fit,pan:{x:0,y:0}};
 useEffect(()=>{setView(null);setPolygon([]);setPen([]);penDrag.current=null;setPreview([]);gesture.current=null;},[scene.id]);
 useEffect(()=>{setPolygon([]);setPen([]);penDrag.current=null;setPreview([]);gesture.current=null;},[tool]);
 useEffect(()=>{if(!area.current)return;const observer=new ResizeObserver(([e])=>setSize({width:e.contentRect.width,height:e.contentRect.height}));observer.observe(area.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{const el=area.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const r=el.getBoundingClientRect();setView(zoomCanvasAt(current.current,{x:e.clientX-r.left-r.width/2,y:e.clientY-r.top-r.height/2},current.current.scale*Math.exp(-Math.max(-100,Math.min(100,e.deltaY))*.0025)));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
 function finishPen(){try{if(pen.length<2)return;create(curveLayer(pen,closed,color));setPen([]);setTool('select');}catch(e){onError(e);}}
 function finishPolygon(){try{if(polygon.length<3)return;create(polygonLayer(polygon,color));setPolygon([]);setTool('select');}catch(e){onError(e);}}
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.defaultPrevented||typing(e.target)||e.altKey||document.querySelector('[role=dialog],.desktop-modal-backdrop')||(e.target instanceof HTMLElement&&e.target.closest('.advanced-timeline')))return;if(e.ctrlKey||e.metaKey){if(['0','1','+','=','-'].includes(e.key)){e.preventDefault();if(e.key==='0')setView(null);else if(e.key==='1')setView({scale:1,pan:{x:0,y:0}});else setView(zoomCanvasAt(current.current,{x:0,y:0},current.current.scale*(e.key==='-'?1/1.2:1.2)));}return;}if(e.key==='['||e.key===']'){e.preventDefault();if(tool==='brush')setPaintSize(n=>Math.max(1,Math.min(100,n+(e.key===']'?5:-5))));else setBrush(Math.max(1,Math.min(100,brush+(e.key===']'?5:-5))));return;}if(e.shiftKey&&e.key.toLowerCase()==='e'){e.preventDefault();setTool(tool==='mask-hide'?'mask-reveal':'mask-hide');return;}if(e.shiftKey&&e.key.toLowerCase()==='u'){e.preventDefault();const shapes:DesignTool[]=['rect','rounded-rect','ellipse','triangle','star','regular-polygon','line','arrow','polygon'];setTool(shapes[(shapes.indexOf(tool)+1)%shapes.length]);return;}if(e.shiftKey&&e.key.toLowerCase()==='m'){e.preventDefault();setTool(tool==='marquee'?'ellipse-select':'marquee');return;}if(e.key.toLowerCase()==='x'){e.preventDefault();setColor(background);setBackground(color);}if(e.key.toLowerCase()==='d'){e.preventDefault();setColor('#000000');setBackground('#ffffff');}if(e.code==='Space'){e.preventDefault();spaceRef.current=true;setSpace(true);}if(e.key==='Escape'){cancel();setPreview([]);setPolygon([]);setTool('select');setPen([]);penDrag.current=null;}if(e.key==='Enter'&&tool==='pen'){e.preventDefault();finishPen();}if(e.key==='Enter'&&tool==='polygon'){e.preventDefault();finishPolygon();}const key:Record<string,DesignTool>={v:'select',h:'hand',t:'text',u:'rect',o:'ellipse',l:'lasso',m:'marquee',p:'pen',a:'nodes',b:'brush',e:'mask-hide',c:'mask-rectangle',g:'gradient',i:'eyedropper',k:'fill',z:'zoom'};if(key[e.key.toLowerCase()])setTool(key[e.key.toLowerCase()]);if(e.key==='0')setView(null);if(e.key==='1')setView({scale:1,pan:{x:0,y:0}});};const up=(e:KeyboardEvent)=>{if(e.code==='Space'){spaceRef.current=false;setSpace(false);}};const blur=()=>{spaceRef.current=false;setSpace(false);cancel();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[polygon,pen,closed,tool,color,background,create,brush]);
 function point(e:{clientX:number;clientY:number},matrix?:DOMMatrix){const svg=area.current?.querySelector('svg.graphic') as SVGSVGElement|null;const m=matrix||svg?.getScreenCTM()?.inverse();if(!m)throw Error('Switch from the reference image to Show design before drawing.');const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m);if(!Number.isFinite(p.x)||!Number.isFinite(p.y))throw Error('This layer has zero scale. Give it a nonzero scale before editing its mask.');return {x:p.x,y:p.y};}
 function root(){return area.current?.querySelector('svg.graphic') as SVGSVGElement|null;}
 function layerElement(id:string){return [...(root()?.querySelectorAll<SVGGraphicsElement>('[data-layer-id]')||[])].find(el=>el.dataset.layerId===id);}
 function layerAt(e:React.PointerEvent){return document.elementsFromPoint(e.clientX,e.clientY).map(el=>el.closest('[data-layer-id]')?.getAttribute('data-layer-id')).map(id=>scene.layers.find(l=>l.id===id)).find(Boolean);}
 async function sample(p:Point){if(sampling)return;const svg=root();if(!svg)return;setSampling(true);try{setColor(await sampleCanvasColor(svg,p.x,p.y,scene.width,scene.height));}catch(error){onError(error);}finally{setSampling(false);}}
 function down(e:React.PointerEvent){
  if(e.button!==0&&e.button!==1)return;const pan=spaceRef.current||tool==='hand'||e.button===1;if(!pan&&['select','nodes','motion'].includes(tool)){if(!typing(e.target))area.current?.focus({preventScroll:true});return;}e.preventDefault();e.stopPropagation();area.current?.focus({preventScroll:true});if(gesture.current)cancel();
  try{
   if(tool==='zoom'&&!pan){const r=area.current!.getBoundingClientRect();setView(zoomCanvasAt(current.current,{x:e.clientX-r.left-r.width/2,y:e.clientY-r.top-r.height/2},current.current.scale*(e.altKey?1/1.5:1.5)));return;}
   const p=pan?{x:0,y:0}:point(e);
   if(tool==='eyedropper'&&!pan){void sample(p);return;}
   if(tool==='fill'&&!pan){const target=layerAt(e);if(!target)throw Error('Click a visible shape or text layer.');pause();commitLayer(fillLayer(target,color));select([target.id]);return;}
   area.current!.setPointerCapture(e.pointerId);
   if(pan){gesture.current={kind:'pan',start:{x:e.clientX,y:e.clientY},last:p,pan:current.current.pan,points:[],display:[],width:1,height:1,shift:false,mode:'replace',pointer:e.pointerId};return;}
   pause();if(tool==='pen'){if(pen.length>=100)return;penDrag.current={point:p,index:pen.length};setPen(points=>[...points,p]);return;}if(tool==='polygon'){setPolygon(points=>points.length<100?[...points,p]:points);return;}
   let matrix:DOMMatrix|undefined,width=scene.width,height=scene.height,q:Point=p;
   if(tool.startsWith('mask-')||tool==='gradient'){
    if(!item||item.locked)throw Error('Select an unlocked layer first.');if(tool==='gradient')fillLayer(item,color,{end:background,angle:0,kind:gradientKind});
    const el=layerElement(item.id);if(!el)throw Error('The selected layer must be visible at the current time.');matrix=el.getScreenCTM()!.inverse();const rect=el.querySelector(':scope > rect[fill="transparent"]'),box=el.getBBox();width=Number(rect?.getAttribute('width'))||box.width||item.width;height=Number(rect?.getAttribute('height'))||box.height||item.height;q=point(e,matrix);if(q.x<0||q.y<0||q.x>width||q.y>height)throw Error('Start inside the selected layer.');
   }
   gesture.current={kind:'draw',start:q,last:q,pan:current.current.pan,points:[q],display:[p],matrix,width,height,shift:e.shiftKey,mode:e.altKey?'subtract':e.shiftKey?'add':selectionMode,pointer:e.pointerId};setPreview([p]);setSquare(e.shiftKey);
  }catch(err){cancel();onError(err);}
 }
 function maskDraft(g:Gesture){
  const m=structuredClone(item?.visual?.layerMask||defaultLayerMask()),norm=(p:Point)=>({x:Math.max(0,Math.min(1,p.x/g.width)),y:Math.max(0,Math.min(1,p.y/g.height))});m.enabled=true;
  if(tool==='mask-hide'||tool==='mask-reveal'){if((m.strokes?.length||0)>=100)throw Error('This mask has 100 strokes. Clear strokes or undo before painting more.');m.strokes=[...(m.strokes||[]),{mode:tool==='mask-hide'?'hide':'reveal',size:brush/100,points:g.points.map(norm)}];}
  else{const a=norm(g.start),b=norm(g.last);m.shape=tool==='mask-ellipse'?'ellipse':'rectangle';m.x=Math.min(a.x,b.x);m.y=Math.min(a.y,b.y);m.width=Math.max(.0001,Math.abs(a.x-b.x));m.height=Math.max(.0001,Math.abs(a.y-b.y));m.points=undefined;}
  return m;
 }
 function move(e:React.PointerEvent){try{
  if(penDrag.current){const p=point(e),d=penDrag.current;setPen(points=>points.map((v,i)=>i===d.index?{...v,inX:d.point.x*2-p.x,inY:d.point.y*2-p.y,outX:p.x,outY:p.y}:v));return;}
  const g=gesture.current;if(!g)return;e.preventDefault();e.stopPropagation();if(g.kind==='pan'){setView({scale:current.current.scale,pan:{x:g.pan.x+e.clientX-g.start.x,y:g.pan.y+e.clientY-g.start.y}});return;}
  const p=point(e),q=point(e,g.matrix);g.last=q;g.shift=e.shiftKey;setSquare(e.shiftKey);
  if(['mask-hide','mask-reveal','brush','lasso'].includes(tool)){const max=tool==='mask-hide'||tool==='mask-reveal'?300:2000;if(g.points.length<max&&Math.hypot(q.x-g.points.at(-1)!.x,q.y-g.points.at(-1)!.y)>.5){g.points.push(q);g.display.push(p);}else if(g.points.length>=max){g.points=g.points.filter((_,i)=>i%2===0);g.display=g.display.filter((_,i)=>i%2===0);g.points.push(q);g.display.push(p);}setPreview([...g.display]);}else setPreview([g.display[0],p]);
  if(item&&tool.startsWith('mask-')){g.next={...item,visual:{...item.visual,layerMask:maskDraft(g)}};previewLayer(g.next);}
  if(item&&tool==='gradient'){g.next=fillLayer(item,color,{end:background,angle:Math.atan2((q.y-g.start.y)/g.height,(q.x-g.start.x)/g.width)*180/Math.PI,kind:gradientKind});previewLayer(g.next);}
 }catch(error){cancel();onError(error);}}
 function selectRegion(g:Gesture){
  if(Math.hypot(g.last.x-g.start.x,g.last.y-g.start.y)<2&&tool!=='lasso'){select(mergeSelection(selection,[],g.mode));return;}
  const region=tool==='lasso'?g.points:marqueePolygon(g.start,g.last,tool==='ellipse-select'),svg=root(),inverse=svg?.getScreenCTM()?.inverse();if(!svg||!inverse||region.length<3)return;
  const hits=scene.layers.filter(l=>!l.locked).filter(l=>{const el=layerElement(l.id),screen=el?.getScreenCTM();if(!el||!screen)return false;const r=el.querySelector(':scope > rect[fill="transparent"]'),w=Number(r?.getAttribute('width'))||l.width,h=Number(r?.getAttribute('height'))||l.height,m=inverse.multiply(screen);return polygonsOverlap(region,[new DOMPoint(0,0),new DOMPoint(w,0),new DOMPoint(w,h),new DOMPoint(0,h)].map(p=>p.matrixTransform(m)),contained);}).map(l=>l.id);select(mergeSelection(selection,hits,g.mode));
 }
 function up(e:React.PointerEvent){
  if(penDrag.current){penDrag.current=null;if(area.current?.hasPointerCapture(e.pointerId))area.current.releasePointerCapture(e.pointerId);return;}
  const g=gesture.current;if(!g)return;e.stopPropagation();gesture.current=null;setPreview([]);previewLayer(null);if(area.current?.hasPointerCapture(e.pointerId))area.current.releasePointerCapture(e.pointerId);if(g.kind==='pan')return;
  try{
   if(selections.includes(tool)){selectRegion(g);return;}
   if(tool.startsWith('mask-')){if(['mask-rectangle','mask-ellipse'].includes(tool)&&Math.hypot(g.last.x-g.start.x,g.last.y-g.start.y)<2)return;mask(maskDraft(g));return;}
   if(tool==='gradient'){if(g.next)commitLayer(g.next);return;}
   if(tool==='brush'){create(brushLayer(g.points,color,paintSize,paintOpacity/100,smoothing));return;}
   const end=g.last.x===g.start.x&&g.last.y===g.start.y?{x:g.start.x+240,y:g.start.y+(tool==='text'?70:160)}:g.last;let l:Layer;
   if(['rounded-rect','triangle','star','regular-polygon'].includes(tool))l=shapeFromDrag(tool,g.start,end,g.shift,color,sides,inner/100);else if(tool==='arrow')l={...drawnLayer('line',g.start,end,g.shift,color),type:'arrow',name:'Arrow'};else l=drawnLayer(tool as Layer['type'],g.start,end,g.shift,color);create(l);setTool('select');
  }catch(err){onError(err);}
 }
 const actual=current.current,bounds=preview.length===2?drawingBounds(preview[0],preview[1],square&&!tool.startsWith('mask-')&&!selections.includes(tool)):null;
 return <><div className="design-tool-options photoshop-options"><strong>{tools.find(t=>t[0]===tool)?.[1]}</strong>{selections.includes(tool)&&<><label>Mode <select aria-label="Selection mode" value={selectionMode} onChange={e=>setSelectionMode(e.target.value as SelectionMode)}><option value="replace">New</option><option value="add">Add</option><option value="subtract">Subtract</option></select></label><label><input type="checkbox" checked={contained} onChange={e=>setContained(e.target.checked)}/>Fully enclosed</label><span>Layer bounds</span></>}
 {tool==='brush'&&<><label>Size <input aria-label="Paint brush size" type="number" min="1" max="100" value={paintSize} onChange={e=>setPaintSize(Math.max(1,Math.min(100,Number(e.target.value))))}/>px</label><label>Opacity <input aria-label="Paint opacity" type="number" min="1" max="100" value={paintOpacity} onChange={e=>setPaintOpacity(Math.max(1,Math.min(100,Number(e.target.value))))}/>%</label><label>Smoothing <select aria-label="Brush smoothing" value={smoothing} onChange={e=>setSmoothing(Number(e.target.value))}><option value=".5">Low</option><option value="2">Medium</option><option value="5">High</option></select></label></>}
 {(tool==='mask-hide'||tool==='mask-reveal')&&<label>Mask size <input aria-label="Mask brush size" type="range" min="1" max="100" value={brush} onChange={e=>setBrush(Number(e.target.value))}/>{brush}%</label>}
 {(tool==='star'||tool==='regular-polygon')&&<label>{tool==='star'?'Points':'Sides'} <input aria-label="Shape sides" type="number" min="3" max="12" value={sides} onChange={e=>setSides(Math.max(3,Math.min(12,Number(e.target.value))))}/></label>}
 {tool==='star'&&<label>Inner <input aria-label="Star inner radius" type="number" min="10" max="90" value={inner} onChange={e=>setInner(Math.max(10,Math.min(90,Number(e.target.value))))}/>%</label>}
 {tool==='gradient'&&<label>Fill <select aria-label="Gradient tool type" value={gradientKind} onChange={e=>setGradientKind(e.target.value as 'linear'|'radial')}><option value="linear">Linear</option><option value="radial">Radial</option></select></label>}
 {tool==='eyedropper'&&<span>{sampling?'Sampling…':'Rendered artwork · foreground swatch'}</span>}<span className="spacer"/>{tool==='pen'&&<><label><input type="checkbox" checked={closed} onChange={e=>setClosed(e.target.checked)}/>Closed</label><button disabled={pen.length<2} onClick={finishPen}>Finish path</button></>}{tool==='polygon'&&<button disabled={polygon.length<3} onClick={finishPolygon}>Finish polygon</button>}<button aria-label="Zoom canvas out" onClick={()=>setView(zoomCanvasAt(actual,{x:0,y:0},actual.scale/1.25))}><ZoomOut size={14}/></button><output aria-label="Canvas zoom">{Math.round(actual.scale*100)}%</output><button aria-label="Zoom canvas in" onClick={()=>setView(zoomCanvasAt(actual,{x:0,y:0},actual.scale*1.25))}><ZoomIn size={14}/></button><button onClick={()=>setView({scale:1,pan:{x:0,y:0}})}>100%</button><button aria-label="Fit canvas" onClick={()=>setView(null)}><Maximize size={13}/>Fit</button></div>
 <div className="design-canvas-body"><DesignToolbox tool={tool} setTool={setTool} color={color} setColor={setColor} background={background} setBackground={setBackground} expanded={expanded} setExpanded={setExpanded}/>
 <div ref={area} tabIndex={0} aria-label="Design canvas" className="canvas-area design-viewport" data-tool={tool} data-zoom={actual.scale} data-pan-x={actual.pan.x} data-pan-y={actual.pan.y} style={{cursor:space||tool==='hand'?'grab':tool==='zoom'?'zoom-in':tool!=='select'?'crosshair':undefined}} onPointerDownCapture={down} onPointerMoveCapture={move} onPointerUpCapture={up} onPointerCancel={cancel} onLostPointerCapture={()=>{if(gesture.current||penDrag.current)cancel();}} onDoubleClick={()=>{if(tool==='polygon')finishPolygon();if(tool==='hand')setView(null);}} onDragOver={e=>{if((e.dataTransfer.types.includes('Files')||e.dataTransfer.types.includes('application/x-broadcastcg-asset')))e.preventDefault();}} onDrop={onDrop}>
  <div className="design-stage-transform" style={{width:scene.width,height:scene.height,transform:`translate(-50%,-50%) translate(${actual.pan.x}px,${actual.pan.y}px) scale(${actual.scale})`}}><CanvasScale.Provider value={actual.scale}>{children}</CanvasScale.Provider><svg className="design-draw-overlay" viewBox={`0 0 ${scene.width} ${scene.height}`}>
   {tool==='pen'&&<><path d={curvePath(pen,closed)} fill="none" stroke="#63d8ff" strokeWidth={2/actual.scale}/>{pen.map((p,i)=><g key={i}><circle cx={p.x} cy={p.y} r={4/actual.scale} fill="#63d8ff"/>{p.outX!==undefined&&<line x1={p.inX} y1={p.inY} x2={p.outX} y2={p.outY} stroke="#fff" strokeWidth={1/actual.scale}/>}</g>)}</>}{(tool==='polygon'||tool==='mask-hide'||tool==='mask-reveal'||tool==='brush'||tool==='lasso'||preview.length>2)&&<polyline points={(tool==='polygon'?polygon:preview).map(p=>`${p.x},${p.y}`).join(' ')} fill={tool==='lasso'?'#63d8ff15':'none'} stroke={tool==='brush'?color:'#63d8ff'} strokeWidth={tool==='brush'?paintSize:2/actual.scale} strokeOpacity={tool==='brush'?paintOpacity/100:1} strokeLinecap="round" strokeLinejoin="round"/>}
   {polygon.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={4/actual.scale} fill="#63d8ff"/>)}
   {preview.length===1&&<circle cx={preview[0].x} cy={preview[0].y} r={4/actual.scale} fill="#63d8ff"/>}
   {bounds&&!['brush','lasso','mask-hide','mask-reveal'].includes(tool)&&(tool.includes('ellipse')?<ellipse cx={bounds.x+bounds.width/2} cy={bounds.y+bounds.height/2} rx={bounds.width/2} ry={bounds.height/2} fill="#63d8ff22" stroke="#63d8ff" strokeWidth={1/actual.scale}/>:['line','arrow','gradient'].includes(tool)?<line x1={preview[0].x} y1={preview[0].y} x2={preview[1].x} y2={preview[1].y} stroke="#63d8ff" strokeWidth={2/actual.scale}/>:<rect {...bounds} fill="#63d8ff22" stroke="#63d8ff" strokeWidth={1/actual.scale}/>)}
  </svg></div>
 </div></div><div className="design-canvas-hint">{toolHint(tool)} · Wheel zoom · Space-drag pan</div></>;
}
