'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {MousePointer2,Hand,Type,Square,Circle,Minus,PenTool,Paintbrush,Scan,ZoomIn,ZoomOut,Maximize} from 'lucide-react';
import {drawnLayer,drawingBounds,polygonLayer,zoomCanvasAt,type Point,type CanvasView} from '@/lib/design-tools';
import {defaultLayerMask,type LayerMask} from '@/lib/design-schema';
import type {Layer,Scene} from '@/lib/studio-model';
export type DesignTool='select'|'hand'|'text'|'rect'|'ellipse'|'line'|'polygon'|'mask-rectangle'|'mask-ellipse'|'mask-hide'|'mask-reveal';
const tools=[['select','Select (V)',MousePointer2],['hand','Hand (H / Space)',Hand],['text','Draw text (T)',Type],['rect','Draw rectangle (U)',Square],['ellipse','Draw ellipse (O)',Circle],['line','Draw line (L)',Minus],['polygon','Draw polygon (P)',PenTool],['mask-rectangle','Rectangle mask',Scan],['mask-ellipse','Ellipse mask',Circle],['mask-hide','Mask brush: hide (B)',Paintbrush],['mask-reveal','Mask brush: reveal',Paintbrush]] as const;
const typing=(target:EventTarget|null)=>target instanceof HTMLElement&&!!target.closest('input,textarea,select,[contenteditable=true],[role=dialog]');
type Gesture={kind:'pan'|'draw';start:Point;last:Point;pan:Point;points:Point[];display:Point[];matrix?:DOMMatrix;width:number;height:number;shift:boolean};
export default function DesignCanvas({scene,item,tool,setTool,color,setColor,brush,setBrush,children,create,mask,onError,onDrop}:{scene:Scene;item?:Layer;tool:DesignTool;setTool:(v:DesignTool)=>void;color:string;setColor:(v:string)=>void;brush:number;setBrush:(v:number)=>void;children:ReactNode;create:(l:Layer)=>void;mask:(v:LayerMask)=>void;onError:(e:unknown)=>void;onDrop:(e:React.DragEvent)=>void}){
 const area=useRef<HTMLDivElement>(null),[view,setView]=useState<CanvasView|null>(null),[size,setSize]=useState({width:800,height:450}),[space,setSpace]=useState(false),[preview,setPreview]=useState<Point[]>([]),[polygon,setPolygon]=useState<Point[]>([]),[square,setSquare]=useState(false);
 const gesture=useRef<Gesture|null>(null),current=useRef<CanvasView>({scale:1,pan:{x:0,y:0}}),spaceRef=useRef(false);
 const fit=Math.max(.02,Math.min((size.width-48)/scene.width,(size.height-48)/scene.height,1));current.current=view||{scale:fit,pan:{x:0,y:0}};
 useEffect(()=>{setView(null);setPolygon([]);setPreview([]);gesture.current=null;},[scene.id]);
 useEffect(()=>{setPolygon([]);setPreview([]);gesture.current=null;},[tool]);
 useEffect(()=>{if(!area.current)return;const observer=new ResizeObserver(([e])=>setSize({width:e.contentRect.width,height:e.contentRect.height}));observer.observe(area.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{const el=area.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const r=el.getBoundingClientRect();setView(zoomCanvasAt(current.current,{x:e.clientX-r.left-r.width/2,y:e.clientY-r.top-r.height/2},current.current.scale*Math.exp(-Math.max(-100,Math.min(100,e.deltaY))*.0025)));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
 function finishPolygon(){try{if(polygon.length<3)return;create(polygonLayer(polygon,color));setPolygon([]);setTool('select');}catch(e){onError(e);}}
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.defaultPrevented||typing(e.target)||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('[role=dialog],.desktop-modal-backdrop')||(e.target instanceof HTMLElement&&e.target.closest('.advanced-timeline')))return;if(e.code==='Space'){e.preventDefault();spaceRef.current=true;setSpace(true);}if(e.key==='Escape'){gesture.current=null;setPreview([]);setPolygon([]);setTool('select');}if(e.key==='Enter'&&tool==='polygon'){e.preventDefault();finishPolygon();}const key:Record<string,DesignTool>={v:'select',h:'hand',t:'text',u:'rect',o:'ellipse',l:'line',p:'polygon',b:'mask-hide'};if(key[e.key.toLowerCase()])setTool(key[e.key.toLowerCase()]);if(e.key==='0')setView(null);if(e.key==='1')setView({scale:1,pan:{x:0,y:0}});};const up=(e:KeyboardEvent)=>{if(e.code==='Space'){spaceRef.current=false;setSpace(false);}};const blur=()=>{spaceRef.current=false;setSpace(false);gesture.current=null;setPreview([]);};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[polygon,tool,color,create]);
 function point(e:{clientX:number;clientY:number},matrix?:DOMMatrix){const svg=area.current?.querySelector('svg.graphic') as SVGSVGElement|null;const m=matrix||svg?.getScreenCTM()?.inverse();if(!m)throw Error('Switch from the reference image to Show design before drawing.');const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m);if(!Number.isFinite(p.x)||!Number.isFinite(p.y))throw Error('This layer has zero scale. Give it a nonzero scale before editing its mask.');return p;}
 function down(e:React.PointerEvent){if(e.button!==0&&e.button!==1)return;const pan=spaceRef.current||tool==='hand'||e.button===1;if(!pan&&tool==='select')return;e.preventDefault();e.stopPropagation();area.current!.setPointerCapture(e.pointerId);try{
  if(pan){gesture.current={kind:'pan',start:{x:e.clientX,y:e.clientY},last:{x:0,y:0},pan:current.current.pan,points:[],display:[],width:1,height:1,shift:false};return;}
  const p=point(e);if(tool==='polygon'){setPolygon(points=>points.length<100?[...points,p]:points);return;}
  let matrix:DOMMatrix|undefined,width=scene.width,height=scene.height,q:Point=p;
  if(tool.startsWith('mask-')){if(!item||item.locked)throw Error('Select an unlocked layer to edit its mask.');const el=[...area.current!.querySelectorAll<SVGGraphicsElement>('[data-layer-id]')].find(el=>el.dataset.layerId===item.id);if(!el)throw Error('The selected layer must be visible at the current time.');matrix=el.getScreenCTM()!.inverse();const box=el.getBBox();width=Number(el.querySelector(':scope > rect[fill="transparent"]')?.getAttribute('width'))||box.width||item.width;height=Number(el.querySelector(':scope > rect[fill="transparent"]')?.getAttribute('height'))||box.height||item.height;q=point(e,matrix);if(q.x<0||q.y<0||q.x>width||q.y>height)throw Error('Start the mask inside the selected layer.');}
  gesture.current={kind:'draw',start:q,last:q,pan:current.current.pan,points:[q],display:[p],matrix,width,height,shift:e.shiftKey};setPreview([p]);setSquare(e.shiftKey);
 }catch(err){gesture.current=null;onError(err);}}
 function move(e:React.PointerEvent){const g=gesture.current;if(!g)return;e.preventDefault();e.stopPropagation();if(g.kind==='pan'){setView({scale:current.current.scale,pan:{x:g.pan.x+e.clientX-g.start.x,y:g.pan.y+e.clientY-g.start.y}});return;}const p=point(e),q=point(e,g.matrix);g.last=q;g.shift=e.shiftKey;setSquare(e.shiftKey);if(tool.startsWith('mask-')&&(tool==='mask-hide'||tool==='mask-reveal')){if(g.points.length<300&&Math.hypot(q.x-g.points.at(-1)!.x,q.y-g.points.at(-1)!.y)>1){g.points.push(q);g.display.push(p);}setPreview([...g.display]);}else setPreview([g.display[0],p]);}
 function up(e:React.PointerEvent){const g=gesture.current;if(!g)return;e.stopPropagation();gesture.current=null;setPreview([]);if(g.kind==='pan')return;try{
  if(tool.startsWith('mask-')){const m=structuredClone(item?.visual?.layerMask||defaultLayerMask()),norm=(p:Point)=>({x:Math.max(0,Math.min(1,p.x/g.width)),y:Math.max(0,Math.min(1,p.y/g.height))});m.enabled=true;
   if(tool==='mask-hide'||tool==='mask-reveal'){if((m.strokes?.length||0)>=100)throw Error('This mask has 100 strokes. Clear strokes or undo a stroke before painting more.');m.strokes=[...(m.strokes||[]),{mode:tool==='mask-hide'?'hide':'reveal',size:brush/100,points:g.points.map(norm)}];}
   else{const a=norm(g.start),b=norm(g.last);m.shape=tool==='mask-ellipse'?'ellipse':'rectangle';m.x=Math.min(a.x,b.x);m.y=Math.min(a.y,b.y);m.width=Math.max(.0001,Math.abs(a.x-b.x));m.height=Math.max(.0001,Math.abs(a.y-b.y));m.points=undefined;}
   mask(m);
  }else{const end=g.last.x===g.start.x&&g.last.y===g.start.y?{x:g.start.x+240,y:g.start.y+(tool==='text'?70:160)}:g.last;create(drawnLayer(tool as Layer['type'],g.start,end,g.shift,color));setTool('select');}
 }catch(err){onError(err);}}
 const actual=current.current,bounds=preview.length===2?drawingBounds(preview[0],preview[1],square&&!tool.startsWith('mask-')):null;
 return <><div className="design-tool-options"><strong>{tools.find(t=>t[0]===tool)?.[1]}</strong><label>Fill <input aria-label="Drawing color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></label>{tool.startsWith('mask-')&&<label>Brush <input aria-label="Mask brush size" type="range" min="1" max="100" value={brush} onChange={e=>setBrush(Number(e.target.value))}/>{brush}%</label>}<span className="spacer"/>{tool==='polygon'&&<button disabled={polygon.length<3} onClick={finishPolygon}>Finish polygon</button>}<button aria-label="Zoom canvas out" onClick={()=>setView(zoomCanvasAt(actual,{x:0,y:0},actual.scale/1.25))}><ZoomOut size={14}/></button><output aria-label="Canvas zoom">{Math.round(actual.scale*100)}%</output><button aria-label="Zoom canvas in" onClick={()=>setView(zoomCanvasAt(actual,{x:0,y:0},actual.scale*1.25))}><ZoomIn size={14}/></button><button onClick={()=>setView({scale:1,pan:{x:0,y:0}})}>100%</button><button aria-label="Fit canvas" onClick={()=>setView(null)}><Maximize size={13}/>Fit</button></div>
 <div className="design-canvas-body"><nav className="design-tools" aria-label="Design tools">{tools.map(([id,label,Icon])=><button key={id} title={label} aria-label={label} aria-pressed={tool===id} onClick={()=>setTool(id)}><Icon size={17}/></button>)}</nav>
 <div ref={area} className="canvas-area design-viewport" data-zoom={actual.scale} data-pan-x={actual.pan.x} data-pan-y={actual.pan.y} style={{cursor:space||tool==='hand'?'grab':tool!=='select'?'crosshair':undefined}} onPointerDownCapture={down} onPointerMoveCapture={move} onPointerUpCapture={up} onPointerCancel={()=>{gesture.current=null;setPreview([]);}} onDoubleClick={()=>tool==='polygon'&&finishPolygon()} onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={onDrop}>
  <div className="design-stage-transform" style={{width:scene.width,height:scene.height,transform:`translate(-50%,-50%) translate(${actual.pan.x}px,${actual.pan.y}px) scale(${actual.scale})`}}>{children}<svg className="design-draw-overlay" viewBox={`0 0 ${scene.width} ${scene.height}`}>
   {(tool==='polygon'||tool==='mask-hide'||tool==='mask-reveal'||preview.length>2)&&<polyline points={(tool==='polygon'?polygon:preview).map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#63d8ff" strokeWidth={2/actual.scale}/>}
   {polygon.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={4/actual.scale} fill="#63d8ff"/>)}
   {preview.length===1&&<circle cx={preview[0].x} cy={preview[0].y} r={4/actual.scale} fill="#63d8ff"/>}
   {bounds&&tool!=='mask-hide'&&tool!=='mask-reveal'&&(tool.includes('ellipse')?<ellipse cx={bounds.x+bounds.width/2} cy={bounds.y+bounds.height/2} rx={bounds.width/2} ry={bounds.height/2} fill="#63d8ff22" stroke="#63d8ff" strokeWidth={1/actual.scale}/>:tool==='line'?<line x1={preview[0].x} y1={preview[0].y} x2={preview[1].x} y2={preview[1].y} stroke="#63d8ff" strokeWidth={2/actual.scale}/>:<rect {...bounds} fill="#63d8ff22" stroke="#63d8ff" strokeWidth={1/actual.scale}/>)}
  </svg></div>
 </div></div><div className="design-canvas-hint">Wheel to zoom at cursor · Space-drag / middle mouse to pan · 0 Fit · 1 Actual size{tool==='polygon'?' · Click points, Enter to finish, Esc to cancel':tool==='rect'||tool==='ellipse'?' · Shift for equal sides':''}</div></>;
}
