'use client';
import {useState} from 'react';
import {uid,layer,validateProject,type Project,type Scene,type Layer} from '@/lib/studio-model';
import {Num} from './controls';
export function CompositionTools({project,scene,create,onError}:{project:Project;scene:Scene;create:(layer:Layer)=>void;onError:(error:unknown)=>void}){
 return <select aria-label="Insert composition" value="" onChange={e=>{try{const child=project.scenes.find(s=>s.id===e.target.value)!;const instance=layer('composition',{name:child.name+' instance',x:0,y:0,width:child.width,height:child.height,composition:{sceneId:child.id,variables:{},offset:0,speed:1,loop:false}});validateProject({...project,scenes:project.scenes.map(s=>s.id===scene.id?{...s,layers:[...s.layers,instance]}:s)});create(instance);}catch(error){onError(error);}}}><option value="">Composition…</option>{project.scenes.filter(s=>s.id!==scene.id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>;
}
export default function EditingInspector({item:l,project,duration,patch,editText,editPath,section="all"}:{section?:"all"|"text"|"effects"|"path"|"motion"|"composition";item:Layer;project:Project;duration:number;patch:(value:Partial<Layer>)=>void;editText:()=>void;editPath:(motion:boolean)=>void}){
 const [effect,setEffect]=useState('blur');const effects=l.effects||[],c=l.composition,typography=l.typography||{},animation=l.textAnimation;
 const changeEffect=(id:string,value:Partial<NonNullable<Layer['effects']>[number]>)=>patch({effects:effects.map(e=>e.id===id?{...e,...value}:e)});
 const field=(label:string,value:number,change:(n:number)=>void,min=-20000,max=20000,step=1)=><label>{label}<Num label={label} value={value} min={min} max={max} step={step} onChange={change}/></label>;
 return <fieldset className="editing-inspector" disabled={l.locked}>
 {(section==='all'||section==='text')&&l.type==='text'&&<details open><summary>Text layout & animation</summary><button onClick={editText}>Edit text on canvas</button><div className="property-grid"><label>Direction<select value={typography.direction||'auto'} onChange={e=>patch({typography:{...typography,direction:e.target.value as 'auto'}})}>{['auto','ltr','rtl'].map(v=><option key={v}>{v}</option>)}</select></label><label className="inline-label"><input type="checkbox" checked={typography.wrap||false} onChange={e=>patch({typography:{...typography,wrap:e.target.checked}})}/>Wrap to box</label>{field('Paragraph gap',typography.paragraphSpacing||0,n=>patch({typography:{...typography,paragraphSpacing:n}}),0,500)}{field('Letter spacing',l.visual?.letterSpacing||0,n=>patch({visual:{...l.visual,letterSpacing:n}}),-20,100,.1)}</div><label>Animation<select value={animation?.effect||''} onChange={e=>patch({textAnimation:e.target.value?{unit:'letter',start:0,duration:.4,stagger:.04,x:0,y:40,...animation,effect:e.target.value as 'fade'}:undefined})}><option value="">None</option>{['fade','slide','reveal','typewriter'].map(v=><option key={v}>{v}</option>)}</select></label>{animation&&<div className="property-grid"><label>Animate by<select value={animation.unit} onChange={e=>patch({textAnimation:{...animation,unit:e.target.value as 'letter'}})}>{['letter','word','line'].map(v=><option key={v}>{v}</option>)}</select></label>{field('Start',animation.start,n=>patch({textAnimation:{...animation,start:n}}),0,duration,.01)}{field('Duration',animation.duration,n=>patch({textAnimation:{...animation,duration:n}}),.01,600,.01)}{field('Stagger',animation.stagger,n=>patch({textAnimation:{...animation,stagger:n}}),0,10,.01)}{field('Slide X',animation.x,n=>patch({textAnimation:{...animation,x:n}}),-2000,2000)}{field('Slide Y',animation.y,n=>patch({textAnimation:{...animation,y:n}}),-2000,2000)}</div>}</details>}
 {(section==='all'||section==='effects')&&<details open><summary>Effects stack · {effects.length}</summary>{effects.map((e,i)=><div key={e.id} className="effect-item"><header><label><input type="checkbox" checked={e.enabled} onChange={ev=>changeEffect(e.id,{enabled:ev.target.checked})}/>{e.type}</label><button title="Move effect up" disabled={!i} onClick={()=>{const next=[...effects];[next[i-1],next[i]]=[next[i],next[i-1]];patch({effects:next});}}>↑</button><button title="Move effect down" disabled={i===effects.length-1} onClick={()=>{const next=[...effects];[next[i+1],next[i]]=[next[i],next[i+1]];patch({effects:next});}}>↓</button><button title="Remove effect" onClick={()=>patch({effects:effects.filter(v=>v.id!==e.id)})}>×</button></header>{field(e.type==='hue'?'Degrees':'Amount',e.amount,n=>changeEffect(e.id,{amount:n}),e.type==='hue'?-360:0,e.type==='hue'?360:['blur','outline','shadow'].includes(e.type)?100:500,.1)}{['shadow','outline'].includes(e.type)&&<label>Color<input type="color" value={e.color||'#000000'} onChange={ev=>changeEffect(e.id,{color:ev.target.value})}/></label>}{e.type==='shadow'&&<div className="property-grid">{field('Shadow X',e.x??8,n=>changeEffect(e.id,{x:n}),-200,200)}{field('Shadow Y',e.y??8,n=>changeEffect(e.id,{y:n}),-200,200)}</div>}</div>)}<div className="row"><select aria-label="New effect" value={effect} onChange={e=>setEffect(e.target.value)}>{['brightness','contrast','saturation','hue','blur','shadow','outline'].map(v=><option key={v}>{v}</option>)}</select><button disabled={effects.length>=16} onClick={()=>patch({effects:[...effects,{id:uid(),type:effect as 'blur',enabled:true,amount:['brightness','contrast','saturation'].includes(effect)?100:effect==='hue'?0:8,color:'#000000'}]})}>Add effect</button></div></details>}
 {(section==='all'||section==='path')&&l.type==='path'&&!l.visual?.compound&&<button onClick={()=>editPath(false)}>Edit path points & handles</button>}
 {(section==='all'||section==='motion')&&<details open={section==='motion'}><summary>Motion path</summary>{!l.motionPath?<button onClick={()=>{patch({motionPath:{points:[{x:0,y:0},{x:300,y:0}],start:0,end:duration,orient:false,ease:'smooth',loop:false}});editPath(true);}}>Add motion path</button>:<><button onClick={()=>editPath(true)}>Edit route on canvas</button><div className="property-grid">{field('Route start',l.motionPath.start,n=>patch({motionPath:{...l.motionPath!,start:n}}),0,l.motionPath.end-.01,.01)}{field('Route end',l.motionPath.end,n=>patch({motionPath:{...l.motionPath!,end:n}}),l.motionPath.start+.01,600,.01)}<label>Speed curve<select value={l.motionPath.ease} onChange={e=>patch({motionPath:{...l.motionPath!,ease:e.target.value as 'linear'}})}><option>linear</option><option>smooth</option></select></label>{(['orient','loop'] as const).map(k=><label key={k}><input type="checkbox" checked={l.motionPath![k]} onChange={e=>patch({motionPath:{...l.motionPath!,[k]:e.target.checked}})}/>{k==='orient'?'Follow direction':'Loop route'}</label>)}</div><p className="helper">Add Path progress keys in the timeline for custom speed and pauses. The route offsets the layer position.</p><button onClick={()=>{const keys={...l.keys};delete keys.pathProgress;patch({motionPath:undefined,pathProgress:undefined,keys});}}>Remove motion path</button></>}</details>}
 {(section==='all'||section==='composition')&&c&&<details open><summary>Composition instance</summary><div className="property-grid">{field('Time offset',c.offset,n=>patch({composition:{...c,offset:n}}),-600,600,.01)}{field('Playback speed',c.speed,n=>patch({composition:{...c,speed:n}}),.01,20,.01)}<label><input type="checkbox" checked={c.loop} onChange={e=>patch({composition:{...c,loop:e.target.checked}})}/>Loop</label></div><p className="helper">Edit the source scene to update every instance. Override its data here.</p>{[...new Set([...JSON.stringify(project.scenes.find(s=>s.id===c.sceneId)||{}).matchAll(/\{\{([^{}]+)\}\}/g)].map(m=>m[1]))].map(key=><label key={key}>{key}<input placeholder={String(project.variables[key]??'Inherit project value')} value={String(c.variables[key]??'')} onChange={e=>{const variables={...c.variables};if(e.target.value==='')delete variables[key];else variables[key]=e.target.value;patch({composition:{...c,variables}});}}/></label>)}</details>}
 </fieldset>;
}
