'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/client-api';
import {historyLabel} from '@/lib/editing-tools';
import {validateProject,type Project} from '@/lib/studio-model';
import {Graphic} from './canvas';
type Snapshot={id:string;name:string;revision:number;created_at:number};
export default function EditingHistory({project,history,restore,save,close,onError}:{project:Project;history:Project[];restore:(project:Project)=>void;save:()=>Promise<number>;close:()=>void;onError:(error:unknown)=>void}){
 const [snapshots,setSnapshots]=useState<Snapshot[]>([]),[name,setName]=useState(''),[busy,setBusy]=useState(false);const url='/api/editing/'+encodeURIComponent(project.id)+'/snapshots';async function load(){setSnapshots(await api<Snapshot[]>(url));}useEffect(()=>{load().catch(onError);},[project.id]);
 async function snapshot(){setBusy(true);try{const revision=await save();await api(url,{method:'POST',body:JSON.stringify({name:name.trim(),revision})});setName('');await load();}catch(e){onError(e);}finally{setBusy(false);}}
 return <aside className="editing-drawer editing-history" aria-label="Edit history"><header><strong>Edit history & snapshots</strong><button onClick={close} aria-label="Close edit history">×</button></header><p>Restore creates a new Undo step. Output changes only when you TAKE or update it.</p><form className="row" onSubmit={e=>{e.preventDefault();void snapshot();}}><input aria-label="Snapshot name" value={name} maxLength={100} placeholder="Name this version" onChange={e=>setName(e.target.value)}/><button disabled={busy||!name.trim()}>Save snapshot</button></form>{snapshots.map(s=><div className="snapshot-row" key={s.id}><button onClick={async()=>{try{const value=await api<{project:Project}>(url+'/'+s.id);restore(validateProject(value.project));}catch(e){onError(e);}}}><strong>{s.name}</strong><small>{new Date(s.created_at).toLocaleString()} · revision {s.revision}</small></button><button aria-label={'Delete snapshot '+s.name} onClick={async()=>{if(!window.confirm('Remove saved snapshot “'+s.name+'”? The current project stays unchanged.'))return;try{await api(url+'/'+s.id,{method:'DELETE'});await load();}catch(e){onError(e);}}}>×</button></div>)}<h3>Session history · {history.length} steps</h3>{history.map((p,i)=>({p,i})).reverse().map(({p,i})=><button className="history-step" key={i} onClick={()=>restore(structuredClone(p))}><div><Graphic scene={p.scenes[0]} compositions={p.scenes} variables={p.variables} time={p.scenes[0].duration} id={'history-'+i}/></div><span>Before: {historyLabel(p,history[i+1]||project)}<small>Step {i+1}</small></span></button>)}</aside>;
}
