'use client';
import {useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Project,uid} from '@/lib/studio-model';
import {formationNames,formationOptions,formationPoints,formationVariableKeys,generateFormation,type FormationPoint} from '@/lib/formations';
import {Choice,Num} from './controls';

export function FormationEditor({project,change,open,onOpenChange}:{project:Project;change:(fn:(p:Project)=>Project)=>void;open:boolean;onOpenChange:(v:boolean)=>void}){
 const [source,setSource]=useState('4-3-3'),[name,setName]=useState('My formation'),[pattern,setPattern]=useState('4-2-3-1'),[points,setPoints]=useState<FormationPoint[]>(()=>generateFormation('4-3-3')),[selected,setSelected]=useState(0),[editing,setEditing]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const board=useRef<HTMLDivElement>(null),drag=useRef<number|null>(null);
 const point=points[selected];
 function patch(v:Partial<FormationPoint>){setPoints(a=>a.map((p,i)=>i===selected?{...p,...v}:p));setNotice('');}
 function save(apply?:'homeFormation'|'awayFormation'){
  const title=name.trim(),previous=project.formations?.find(f=>f.id===editing);
  if(!title||title.length>60){setError('Give the formation a name of 1–60 characters.');return;}
  if(formationNames.includes(title)||(project.formations||[]).some(f=>f.id!==editing&&f.name.toLowerCase()===title.toLowerCase())){setError('Choose a unique name. Built-in formation names are reserved.');return;}
  if(!editing&&(project.formations?.length||0)>=100){setError('This project has reached its 100-formation limit.');return;}
  const id=editing||uid();
  change(p=>{const variables={...p.variables};if(previous)for(const key of formationVariableKeys(p))if(variables[key]===previous.name)variables[key]=title;if(apply)variables[apply]=title;return {...p,variables,formations:[...(p.formations||[]).filter(f=>f.id!==id),{id,name:title,points}]};});
  setEditing(id);setSource(title);setError('');setNotice(apply?'Saved and applied to '+(apply==='homeFormation'?'home':'away')+'.':'Saved. This formation is now available in every formation dropdown.');
 }
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="formation-dialog"><DialogHeader><DialogTitle>Formation studio</DialogTitle><DialogDescription>Create a formation, drag the 11 slots, then save it to your project. The away team mirrors these positions.</DialogDescription></DialogHeader>
  <div className="formation-editor-grid"><div><label>Start from<Choice label="Formation template" value={source} options={formationOptions(project,source)} onChange={v=>{setSource(v);setPoints(formationPoints(project,v).map(p=>({...p})));const saved=project.formations?.find(f=>f.name===v);setEditing(saved?.id||'');setName(saved?.name||v+' custom');setNotice('');setError('');}}/></label><label>Formation name<Input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><label>Generate from lines<Input aria-label="Formation lines" value={pattern} onChange={e=>setPattern(e.target.value)} placeholder="4-2-3-1"/></label><Button variant="secondary" onClick={()=>{try{setPoints(generateFormation(pattern));setEditing('');setName(pattern+' custom');setNotice('');setError('');}catch(e){setError((e as Error).message);}}}>Generate 11 positions</Button><p className="helper muted">The numbers total 10 outfield players, plus a goalkeeper. Or drag each position freely.</p><label>Selected slot<Choice label="Formation slot" value={String(selected)} options={points.map((p,i)=>({value:String(i),label:(i+1)+' · '+p.role}))} onChange={v=>setSelected(Number(v))}/></label><label>Position label<Input value={point.role} maxLength={12} onChange={e=>patch({role:e.target.value})}/></label><div className="property-grid"><label>X %<Num label="Formation slot x" value={point.x} min={2} max={48} onChange={x=>patch({x})}/></label><label>Y %<Num label="Formation slot y" value={point.y} min={4} max={96} onChange={y=>patch({y})}/></label></div></div>
  <div><div className="formation-board" ref={board}><span className="formation-goal"/>{points.map((p,i)=><button type="button" key={i} className={selected===i?'selected':''} style={{left:p.x*2+'%',top:p.y+'%'}} aria-label={'Formation slot '+(i+1)+' '+p.role} onPointerDown={e=>{if(e.button!==0)return;setSelected(i);drag.current=i;e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();e.currentTarget.focus();}} onPointerMove={e=>{if(drag.current!==i||!board.current)return;const r=board.current.getBoundingClientRect(),x=Math.max(2,Math.min(48,(e.clientX-r.left)/r.width*50)),y=Math.max(4,Math.min(96,(e.clientY-r.top)/r.height*100));setPoints(a=>a.map((p,n)=>n===i?{...p,x:Math.round(x*10)/10,y:Math.round(y*10)/10}:p));setNotice('');}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onKeyDown={e=>{const d=e.shiftKey?2:0.5;if(e.key.startsWith('Arrow')){e.preventDefault();setSelected(i);setPoints(a=>a.map((p,n)=>n===i?{...p,x:Math.max(2,Math.min(48,p.x+(e.key==='ArrowRight'?d:e.key==='ArrowLeft'?-d:0))),y:Math.max(4,Math.min(96,p.y+(e.key==='ArrowDown'?d:e.key==='ArrowUp'?-d:0)))}:p));}}}><b>{i+1}</b><small>{p.role}</small></button>)}</div><p className="helper muted">Your team's half · drag a slot or use arrow keys. Roster “Formation slot” determines which player uses each position.</p></div></div>
  {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}<div className="row wrap"><Button onClick={()=>save()}>Save formation</Button><Button variant="secondary" onClick={()=>save('homeFormation')}>Save & apply home</Button><Button variant="secondary" onClick={()=>save('awayFormation')}>Save & apply away</Button>{editing&&<Button variant="outline" onClick={()=>{setEditing('');setName(name+' copy');setNotice('');}}>Make a copy</Button>}</div>
 </DialogContent></Dialog>;
}
