'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Choice,Num} from './controls';
import type {Control,Panel,Project} from '@/lib/studio-model';
import {hardwareTarget,midiInput,midiFeedback,type HardwareInput} from '@/lib/hardware-controls';
export function HardwareControls({panel,project,active,busy,run,onError}:{panel:Panel;project:Project;active:boolean;busy:boolean;run:(c:Control)=>Promise<void>;onError:(e:unknown)=>void}){
 const [armed,setArmed]=useState(false),[status,setStatus]=useState('Disarmed'),[midi,setMidi]=useState<MIDIAccess|null>(null),latest=useRef({panel,project,active,busy,run,onError}),pending=useRef(false);latest.current={panel,project,active,busy,run,onError};
 useEffect(()=>{setArmed(false);},[panel.id,active]);
 useEffect(()=>{if(!armed||!active)return;let frame=0,primed=false,last=new Set<string>(),lastTrigger=0;const reset=()=>{primed=false;last.clear();};
  const fire=(input:HardwareInput)=>{const v=latest.current;if(!v.active||v.busy||pending.current||!document.hasFocus()||document.hidden||(document.activeElement as HTMLElement)?.closest('input,textarea,select,[role=combobox]')||performance.now()-lastTrigger<150)return;
   try{const c=hardwareTarget(v.panel.controls,input,v.project.variables);setStatus(input.kind+' '+input.code+(c?' → '+c.label:' · unmapped'));if(c){lastTrigger=performance.now();pending.current=true;void v.run(c).catch(v.onError).finally(()=>{pending.current=false;});}}catch(e){v.onError(e);}
  };
  const key=(e:KeyboardEvent)=>{if(e.repeat||e.ctrlKey||e.altKey||e.metaKey)return;const match=/^F(\d+)$/.exec(e.key);if(match&&Number(match[1])<=24){const input:HardwareInput={kind:'key',code:111+Number(match[1])};if(latest.current.panel.controls.some(c=>c.hardware?.kind==='key'&&c.hardware.code===input.code)){e.preventDefault();fire(input);}}};
  const attach=()=>midi?.inputs.forEach(port=>{port.onmidimessage=e=>{const input=midiInput(Array.from(e.data||[]));if(input)fire({...input,device:port.name||''});};});attach();if(midi)midi.onstatechange=attach;
  const poll=()=>{if(document.hasFocus()&&!document.hidden){const current=new Set<string>();for(const g of navigator.getGamepads?.()||[]){if(!g)continue;g.buttons.forEach((b,i)=>{if(b.pressed){const key=g.index+':'+i;current.add(key);if(primed&&!last.has(key))fire({kind:'gamepad',code:i,device:g.id});}});}last=current;primed=true;}else reset();frame=requestAnimationFrame(poll);};frame=requestAnimationFrame(poll);window.addEventListener('keydown',key);window.addEventListener('blur',reset);
  return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',key);window.removeEventListener('blur',reset);if(midi){midi.onstatechange=null;midi.inputs.forEach(p=>{p.onmidimessage=null;});midi.outputs.forEach(p=>{for(const c of latest.current.panel.controls)if(c.hardware?.kind==='midi'&&c.hardware.feedback&&(!c.hardware.device||c.hardware.device===p.name))try{p.send([0x90+(c.hardware.channel??0),c.hardware.code,0]);}catch{}});}};
 },[armed,active,panel.id,midi]);
 useEffect(()=>{if(!armed||!active||!midi)return;for(const c of panel.controls)if(c.hardware?.kind==='midi'&&c.hardware.feedback)midi.outputs.forEach(p=>{if(!c.hardware!.device||c.hardware!.device===p.name)try{p.send(midiFeedback(c,project.variables));}catch(e){setStatus('MIDI feedback unavailable');}});},[midi,armed,active,panel.controls,project.variables]);
 return <details className="hardware-box"><summary>Hardware · {armed?'Armed':'Disarmed'}</summary><Button size="sm" variant={armed?'default':'outline'} disabled={!active} onClick={()=>{setArmed(v=>!v);setStatus(armed?'Disarmed':'Listening in this window');}}>{armed?'Disarm hardware':'Arm hardware'}</Button><Button size="sm" variant="outline" disabled={!active} onClick={async()=>{try{if(!navigator.requestMIDIAccess)throw Error('MIDI is unavailable in this runtime.');const access=await navigator.requestMIDIAccess({sysex:false});setMidi(access);setStatus(access.inputs.size+' MIDI input(s), '+access.outputs.size+' output(s)');}catch(e){onError(e);}}}>Connect MIDI</Button><small role="status">{status}</small><p className="helper">Active only in Operate while this window has focus. Stream Deck can send assigned F13–F24 hotkeys. MIDI note-on and gamepad button presses run Click actions once. Mappings are in each control's inspector.</p></details>;
}
export function HardwareSettings({item,patch}:{item:Control;patch:(v:Partial<Control>)=>void}){
 const h=item.hardware;return <details><summary>Hardware mapping</summary><Choice label="Hardware input" value={h?.kind||''} options={[{value:'',label:'No mapping'},{value:'key',label:'Stream Deck / function key'},{value:'midi',label:'MIDI note'},{value:'gamepad',label:'Gamepad button'}]} onChange={kind=>patch({hardware:kind?{kind:kind as 'key'|'midi'|'gamepad',code:kind==='key'?124:0,channel:0}:undefined})}/>{h&&<><label>{h.kind==='key'?'Function key':'Button / note number'}{h.kind==='key'?<Choice label="Hardware function key" value={String(h.code)} options={Array.from({length:24},(_,i)=>({value:String(112+i),label:'F'+(i+1)}))} onChange={code=>patch({hardware:{...h,code:Number(code)}})}/>:<Num label="Hardware code" value={h.code} min={0} max={h.kind==='midi'?127:63} onChange={code=>patch({hardware:{...h,code:Math.round(code)}})}/>}</label>{h.kind==='midi'&&<><label>Channel (1–16)<Num value={(h.channel??0)+1} min={1} max={16} onChange={channel=>patch({hardware:{...h,channel:Math.round(channel)-1}})}/></label><label><input type="checkbox" checked={!!h.feedback} onChange={e=>patch({hardware:{...h,feedback:e.target.checked}})}/>Send note LED feedback (0 disabled / 32 ready / 127 live)</label></>}{h.kind!=='key'&&<label>Exact device name (blank = any)<Input value={h.device||''} onChange={e=>patch({hardware:{...h,device:e.target.value}})}/></label>}</>}</details>;
}
