'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Project,action,uid} from '@/lib/studio-model';
import {planActions} from '@/lib/action-logic';
import {ActionSequenceEditor} from './action-sequence-editor';
export function MacroLibrary({project,change,run,onError,canEdit,busy}:{project:Project;change:(fn:(p:Project)=>Project)=>void;run:(id:string)=>Promise<void>;onError:(e:unknown)=>void;canEdit:boolean;busy:boolean}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState('');const macro=project.macros?.find(m=>m.id===selected)||project.macros?.[0];let validation='';try{if(macro)planActions(project,macro.actions);}catch(e){validation=(e as Error).message;}
 const patch=(v:Partial<NonNullable<Project['macros']>[number]>)=>change(p=>({...p,macros:p.macros?.map(m=>m.id===macro?.id?{...m,...v}:m)}));
 return <><Button variant="secondary" disabled={busy} onClick={()=>setOpen(true)}>Macros</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="macro-dialog"><DialogHeader><DialogTitle>Production macros</DialogTitle><DialogDescription>Create reusable action sequences, then run them here or assign Run macro to a button. Completed actions remain applied after cancellation.</DialogDescription></DialogHeader><div className="macro-layout"><aside><Button disabled={!canEdit||busy||(project.macros?.length||0)>=100} onClick={()=>{const id=uid();change(p=>({...p,macros:[...(p.macros||[]),{id,name:'New macro',actions:[action('delay','','500')]}]}));setSelected(id);}}>New macro</Button>{project.macros?.map(m=><button className={macro?.id===m.id?'selected':''} key={m.id} onClick={()=>setSelected(m.id)}>{m.name}<small>{m.actions.length} actions</small></button>)}</aside><div className="macro-editor">{macro?<><fieldset disabled={!canEdit||busy}><label>Name<Input aria-label="Macro name" value={macro.name} maxLength={100} onChange={e=>{if(e.target.value.trim())patch({name:e.target.value});}}/></label><ActionSequenceEditor project={project} actions={macro.actions} onChange={actions=>patch({actions:actions.length?actions:[action('delay','','0')]})}/></fieldset>{validation&&<p role="alert" className="macro-error">{validation}</p>}<div className="row"><Button disabled={busy||!!validation} onClick={()=>{setOpen(false);run(macro.id).catch(onError);}}>Run {macro.name}</Button><Button variant="ghost" disabled={!canEdit||busy} onClick={()=>change(p=>({...p,macros:p.macros?.filter(m=>m.id!==macro.id)}))}>Delete macro</Button></div></>:<p>Create a macro to build a reusable sequence.</p>}</div></div></DialogContent></Dialog></>;
}
