'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/client-api';
export type MediaAsset={id:string;name:string;mime:string;url:string;size:number;folder?:string;tags?:string[]};
type MediaPage={assets:MediaAsset[];total:number;folders:string[]};
export default function MediaLibrary({insert,upload,close,onError}:{insert:(asset:MediaAsset)=>void;upload:(file:File)=>Promise<string>;close:()=>void;onError:(error:unknown)=>void}){
 const [data,setData]=useState<MediaPage>({assets:[],total:0,folders:[]}),[search,setSearch]=useState(''),[folder,setFolder]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState<MediaAsset|null>(null),[busy,setBusy]=useState(false),file=useRef<HTMLInputElement>(null),request=useRef(0);
 async function load(){const id=++request.current;try{const next=await api<MediaPage>(`/api/media?search=${encodeURIComponent(search)}&folder=${encodeURIComponent(folder)}&offset=${offset}`);if(id===request.current)setData(next);}catch(e){if(id===request.current)onError(e);}}
 useEffect(()=>{const timer=setTimeout(load,150);return()=>clearTimeout(timer);},[search,folder,offset]);useEffect(()=>()=>{request.current++;},[]);
 return <aside className="editing-drawer media-library" aria-label="Media library"><header><strong>Media library</strong><button onClick={close} aria-label="Close media library">×</button></header><div className="row"><input aria-label="Search media" placeholder="Search names, folders, tags" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/><button disabled={busy} onClick={()=>file.current?.click()}>Import</button><input hidden ref={file} type="file" multiple accept="image/png,image/jpeg,image/webp,video/mp4,video/webm" onChange={async e=>{setBusy(true);try{for(const f of Array.from(e.target.files||[]))await upload(f);await load();}catch(err){onError(err);}finally{setBusy(false);e.target.value='';}}}/></div><select aria-label="Media folder" value={folder} onChange={e=>{setFolder(e.target.value);setOffset(0);}}><option value="">All folders</option>{data.folders.map(f=><option key={f}>{f}</option>)}</select><p>Drag media onto the canvas, or double-click to insert.</p><div className="media-grid">{data.assets.map(a=><button draggable key={a.id} className={a.id===selected?.id?'selected':''} onClick={()=>setSelected(a)} onDoubleClick={()=>insert(a)} onDragStart={e=>{e.dataTransfer.setData('application/x-broadcastcg-asset',JSON.stringify(a));e.dataTransfer.effectAllowed='copy';}}>{a.mime.startsWith('video/')?<video src={a.url} muted preload="metadata"/>:<img src={a.url} alt="" loading="lazy"/>}<span>{a.name}</span><small>{a.mime.startsWith('video/')?'Video':'Image'} · {Math.round(a.size/1024)} KB</small></button>)}</div>{!data.assets.length&&<p>No matching media. Import an image or video to begin.</p>}<footer><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous</button><span>{data.total} assets</span><button disabled={offset+100>=data.total} onClick={()=>setOffset(offset+100)}>Next</button></footer>{selected&&<form key={selected.id} onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{await api('/api/media/'+selected.id,{method:'POST',body:JSON.stringify({name:form.get('name'),folder:form.get('folder'),tags:String(form.get('tags')).split(',').map(v=>v.trim()).filter(Boolean)})});await load();}catch(error){onError(error);}}}><label>Name<input name="name" defaultValue={selected.name} maxLength={200} required/></label><label>Folder<input name="folder" defaultValue={selected.folder||''} maxLength={100}/></label><label>Tags, comma separated<input name="tags" defaultValue={selected.tags?.join(', ')||''}/></label><div className="row"><button type="submit">Save organization</button><button type="button" onClick={()=>insert(selected)}>Insert media</button></div></form>}</aside>;
}
