'use client';
import {renderedMediaReady} from '@/lib/media-ready';
import {useEffect,useState} from 'react';import {Program} from '@/lib/studio-model';import {api} from '@/lib/client-api';import {Graphic} from './canvas';
import {cueTime} from '@/lib/creative-tools';
import {desktopBridge} from '@/lib/desktop';
export function ProgramGraphic({program,id='program'}:{program:Program|null;id?:string}){const [now,setNow]=useState(Date.now());useEffect(()=>{let frame:number;let last=0;function tick(n:number){if(n-last>16){setNow(Date.now());last=n;}frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[]);if(!program?.scene)return null;const elapsed=Math.max(0,(now-program.startedAt)/1000);if(program.mode==='hide'&&elapsed>=.5)return null;const frameTime=cueTime(program.scene,elapsed,program.cue);if(frameTime===null)return null;return <div style={{width:'100%',height:'100%',opacity:program.mode==='hide'?Math.max(0,1-elapsed/.5):1}}><Graphic elapsed={elapsed} scene={program.scene} time={program.mode==='hide'?program.scene.duration:frameTime} variables={program.variables} id={id}/></div>;}
export default function OutputView(){const[program,setProgram]=useState<Program|null>(null),[error,setError]=useState('');useEffect(()=>{document.documentElement.classList.add('output-page');let stopped=false,last='',generation=0;const unsubscribe=desktopBridge()?.onProgram(p=>{generation++;last=JSON.stringify(p);setProgram(p);setError('');});async function poll(){const requestGeneration=generation;try{const p=await api<Program|null>('/api/program');if(!stopped&&requestGeneration===generation&&JSON.stringify(p)!==last){last=JSON.stringify(p);setProgram(p);}if(!stopped)setError('');}catch(e){if(!stopped)setError(e instanceof Error?e.message:'Output connection lost.');}if(!stopped)setTimeout(poll,400);}poll();return()=>{stopped=true;unsubscribe?.();document.documentElement.classList.remove('output-page');};},[]);
useEffect(()=>{if(!program||!desktopBridge())return;let second=0,cancelled=false;const first=requestAnimationFrame(()=>{void renderedMediaReady().then(()=>{if(!cancelled)second=requestAnimationFrame(()=>desktopBridge()?.acknowledgeProgram(program.revision));}).catch(e=>{if(!cancelled)setError(e.message);});});return()=>{cancelled=true;cancelAnimationFrame(first);cancelAnimationFrame(second);};},[program?.revision]);
return <main className="output-window" data-revision={program?.revision||''}><ProgramGraphic program={program}/>{error&&<div className="output-error" role="alert">{error} {!desktopBridge()&&<a href="/signin-with-chatgpt?return_to=/output" target="_top">Sign in</a>}</div>}</main>;}
