'use client';
import {publishComponentStyles} from '@/lib/linked-components';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Copy,Group,Ungroup,Lock,Unlock,Trash2,Layers,Eye,EyeOff,Grid2X2,Library,CheckCircle2,AlertTriangle} from 'lucide-react';
import type {Panel,Project} from '@/lib/studio-model';
import {alignSelection,deleteSelection,distributeSelection,duplicateSelection,expandSelection,groupSelection,insertComponent,isControlLocked,makeComponent,orderSelection,panelIssues,selectionBounds,ungroupSelection,type Align} from '@/lib/panel-builder';
import {arrangePanel} from '@/lib/panel-layout';
type Props={project:Project;panel:Panel;selected:string[];select:(ids:string[])=>void;patch:(fn:(p:Panel)=>Panel)=>void;change:(fn:(p:Project)=>Project)=>void;onError:(e:unknown)=>void};
export function PanelBuilderTools({project,panel,selected,select,patch,change,onError}:Props){
 const [library,setLibrary]=useState(false),[validation,setValidation]=useState(false),[name,setName]=useState('My control group'),[prefix,setPrefix]=useState(''),[notice,setNotice]=useState('');
 const locked=panel.controls.some(c=>selected.includes(c.id)&&isControlLocked(panel,c)),issues=panelIssues(project,panel),errors=issues.filter(i=>i.severity==='error'),box=selectionBounds(panel,selected);
 function apply(fn:(p:Panel)=>Panel){try{patch(fn);}catch(e){onError(e);}}
 function duplicate(){try{const result=duplicateSelection(panel,selected);patch(()=>result.panel);select(result.ids);}catch(e){onError(e);}}
 return <><div className="panel-builder-toolbar" role="toolbar" aria-label="Panel layout tools">
  <span className="panel-selection-count">{selected.length?selected.length+' selected':'Select controls'}</span>
  <Button size="sm" variant="outline" disabled={!selected.length} onClick={duplicate} title="Duplicate selection (Ctrl+D)"><Copy/>Duplicate</Button>
  <Button size="sm" variant="outline" disabled={selected.length<2||locked} onClick={()=>apply(p=>groupSelection(p,selected))} title="Group (Ctrl+G)"><Group/>Group</Button>
  <Button size="sm" variant="ghost" disabled={!selected.some(id=>panel.controls.find(c=>c.id===id)?.groupId)||locked} onClick={()=>apply(p=>ungroupSelection(p,selected))} title="Ungroup (Ctrl+Shift+G)"><Ungroup/>Ungroup</Button>
  <label className="panel-tool-select">Align<select aria-label="Align selected controls" disabled={selected.length<2||locked||!panel.freeLayout} value="" onChange={e=>apply(p=>alignSelection(p,selected,e.target.value as Align))}><option value="">Choose…</option>{(['left','center','right','top','middle','bottom'] as const).map(a=><option key={a} value={a}>{a.charAt(0).toUpperCase()+a.slice(1)}</option>)}</select></label>
  <label className="panel-tool-select">Space<select aria-label="Distribute selected controls" disabled={selected.length<3||locked||!panel.freeLayout} value="" onChange={e=>apply(p=>distributeSelection(p,selected,e.target.value as 'x'|'y'))}><option value="">Evenly…</option><option value="x">Horizontally</option><option value="y">Vertically</option></select></label>
  <label className="panel-tool-select">Order<select aria-label="Order selected controls" disabled={!selected.length||locked} value="" onChange={e=>apply(p=>orderSelection(p,selected,e.target.value as 'front'|'back'))}><option value="">Choose…</option><option value="front">Bring to front</option><option value="back">Send to back</option></select></label>
  <Button size="icon" variant="ghost" aria-label="Delete selected controls" disabled={!selected.length||locked} onClick={()=>{apply(p=>deleteSelection(p,selected));select([]);}}><Trash2/></Button>
  <span className="spacer"/>
  <label className="panel-tool-select"><Grid2X2 size={14}/>Snap<select aria-label="Snap grid" value={panel.snapGrid||0} onChange={e=>apply(p=>({...p,layoutVersion:2,snapGrid:Number(e.target.value)}))}>{[0,4,8,16,32].map(n=><option key={n} value={n}>{n?n+' px':'Off'}</option>)}</select></label>
  <Button size="sm" variant="secondary" onClick={()=>{setNotice('');setLibrary(true);}}><Library/>Components</Button>
  <Button size="sm" variant="outline" className={errors.length?'panel-validation-error':''} onClick={()=>setValidation(true)}>{issues.length?<AlertTriangle/>:<CheckCircle2/>}{issues.length?issues.length+' issues':'Validate'}</Button>
 </div><div className="panel-builder-hint"><span>{panel.freeLayout?'Drag to move · Shift-click or drag empty space to select many · Alt selects one group member / bypasses snap':'Choose Free layout to position and resize controls.'}</span>{box&&<span>{box.width} × {box.height} px{locked?' · Selection contains locked controls':''}</span>}</div>
 <Dialog open={library} onOpenChange={setLibrary}><DialogContent className="panel-component-dialog"><DialogHeader><DialogTitle>Reusable components</DialogTitle><DialogDescription>Save a set of controls with its layout, actions and variable defaults. Add linked copies to share their appearance. Publish selected styles updates colors, borders, fonts, icons and state styles; positions, labels, actions and data bindings stay independent. Components travel with project exports.</DialogDescription></DialogHeader>
  <form className="component-save-row" onSubmit={e=>{e.preventDefault();try{if((project.panelComponents?.length||0)>=100)throw Error('A project supports 100 saved components.');const c=makeComponent(project,panel,selected,name);change(p=>({...p,panelComponents:[...(p.panelComponents||[]),c]}));setNotice('Saved '+c.name+'.');}catch(e){onError(e);}}}><Input aria-label="Component name" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/><Button disabled={!selected.length||selected.length>100}>Save {selected.length} selected</Button></form>
  <label className="component-prefix">Variable prefix when adding<Input aria-label="Component variable prefix" value={prefix} onChange={e=>setPrefix(e.target.value)} placeholder="e.g. match2_" maxLength={50}/><small>Leave empty to share existing variables. A prefix creates independent fields; existing values are never reset.</small></label>
  <div className="component-list">{project.panelComponents?.length?project.panelComponents.map(c=><article key={c.id}><div><strong>{c.name}</strong><p>{c.controls.length} controls · {c.width} × {c.height} · v{c.version}</p><small>{Object.keys(c.variables).join(', ')||'No stored variables'}</small></div><Button onClick={()=>{try{const result=insertComponent(project,panel.id,c,prefix);change(()=>result.project);select(result.ids);setLibrary(false);}catch(e){onError(e);}}}>Add {c.name}</Button><Button variant="outline" onClick={()=>{try{const result=insertComponent(project,panel.id,c,prefix,true);change(()=>result.project);select(result.ids);setLibrary(false);}catch(e){onError(e);}}}>Add linked</Button><Button variant="outline" disabled={!panel.controls.some(v=>selected.includes(v.id)&&v.componentLink?.componentId===c.id)} onClick={()=>{try{change(p=>publishComponentStyles(p,c.id,selected));setNotice('Published styles to every linked copy of '+c.name+'.');}catch(e){onError(e);}}}>Publish selected styles</Button><Button variant="ghost" size="icon" aria-label={'Delete component '+c.name} onClick={()=>change(p=>({...p,panelComponents:p.panelComponents?.filter(v=>v.id!==c.id),panels:p.panels.map(panel=>({...panel,controls:panel.controls.map(control=>control.componentLink?.componentId===c.id?{...control,componentLink:undefined}:control)}))}))}><Trash2/></Button></article>):<p className="muted">Select controls on your canvas, name the component, and save it here.</p>}</div>{notice&&<p role="status" className="success">{notice}</p>}
 </DialogContent></Dialog>
 <Dialog open={validation} onOpenChange={setValidation}><DialogContent className="panel-component-dialog"><DialogHeader><DialogTitle>Panel validation</DialogTitle><DialogDescription>{errors.length?errors.length+' errors prevent the affected controls from operating.':'No blocking control errors.'} Warnings help you check layout and touch sizing.</DialogDescription></DialogHeader><div className="panel-issues">{issues.length?issues.map((i,n)=><button key={n} onClick={()=>{select([i.controlId]);setValidation(false);}}><span className={i.severity==='error'?'panel-error-tag':'panel-warning-tag'}>{i.severity}</span><div><strong>{panel.controls.find(c=>c.id===i.controlId)?.label||'Control'}</strong><p>{i.message}</p></div></button>):<p className="success">Variables, actions and shortcuts passed validation.</p>}</div><p className="helper muted">Validation checks saved references and types. Test your data feeds and output connection separately before production.</p></DialogContent></Dialog>
 </>;
}
export function PanelLayers({panel,selected,select,patch}:{panel:Panel;selected:string[];select:(ids:string[])=>void;patch:(fn:(p:Panel)=>Panel)=>void}){
 const [expanded,setExpanded]=useState(true);
 return <section className="panel-layers"><button className="panel-heading panel-layer-heading" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><Layers size={14}/>CONTROLS & GROUPS <span>{panel.controls.length}</span></button>{expanded&&<>
  {panel.groups?.map(g=><div className="panel-group-row" key={g.id}><Group size={12}/><input aria-label="Group name" value={g.name} maxLength={100} onChange={e=>{const value=e.target.value;if(value.trim())patch(p=>({...p,groups:p.groups?.map(x=>x.id===g.id?{...x,name:value}:x)}));}}/><button aria-label={(g.locked?'Unlock':'Lock')+' group '+g.name} onClick={()=>patch(p=>({...p,groups:p.groups?.map(x=>x.id===g.id?{...x,locked:!x.locked}:x)}))}>{g.locked?<Lock size={13}/>:<Unlock size={13}/>}</button></div>)}
  <div className="panel-layer-list">{[...panel.controls].reverse().map(c=><div key={c.id} className={'panel-layer-row '+(selected.includes(c.id)?'selected':'')}><button className="panel-layer-select" aria-pressed={selected.includes(c.id)} aria-label={'Select '+c.label} onClick={e=>{const ids=expandSelection(panel,[c.id],e.altKey);select(e.shiftKey?selected.some(id=>ids.includes(id))?selected.filter(id=>!ids.includes(id)):[...new Set([...selected,...ids])]:ids);}}><span>{c.groupId?'↳ ':''}{c.label||c.kind}</span><small>{c.kind}</small></button><button aria-label={(c.hidden?'Show ':'Hide ')+c.label} onClick={()=>patch(p=>({...p,layoutVersion:2,controls:p.controls.map(x=>x.id===c.id?{...x,hidden:!x.hidden}:x)}))}>{c.hidden?<EyeOff size={13}/>:<Eye size={13}/>}</button><button disabled={!!panel.groups?.find(g=>g.id===c.groupId)?.locked} aria-label={(c.locked?'Unlock ':'Lock ')+c.label} onClick={()=>patch(p=>({...p,layoutVersion:2,controls:p.controls.map(x=>x.id===c.id?{...x,locked:!x.locked}:x)}))}>{isControlLocked(panel,c)?<Lock size={13}/>:<Unlock size={13}/>}</button></div>)}</div>
  {!panel.controls.length&&<p className="helper muted">Add a control below.</p>}
 </>}</section>;
}
