'use client';
import {useEffect,useRef,useState} from 'react';
import {atTime,type Layer,type Scene} from '@/lib/studio-model';
import {animationDescriptors,readAnimatedProperty,setPropertyKey,writeAnimatedProperty,type PropertyDescriptor} from '@/lib/property-animation';
import type {MotionKey} from '@/lib/motion-schema';
import TimelineNumber from './timeline-number';
export default function PropertyTracks({layer:l,scene,time,preview,commit,seek,error}:{layer:Layer;scene:Scene;time:number;preview:(s:Scene|null)=>void;commit:(s:Scene)=>void;seek:(n:number)=>void;error:(e:unknown)=>void}){
 const [open,setOpen]=useState(!!l.propertyTracks?.length),[selected,setSelected]=useState<{property:string;time:number}|null>(null),[offset,setOffset]=useState(0);const gesture=useRef<{base:Scene;property:string;time:number;x:number;width:number;delta:number}|null>(null),latest=useRef({scene,preview});latest.current={scene,preview};
 const descriptors=animationDescriptors(l),available=descriptors.filter(d=>!l.propertyTracks?.some(t=>t.property===d.id));
 const update=(next:Layer)=>commit({...scene,layers:scene.layers.map(v=>v.id===l.id?next:v)}),safe=(fn:()=>void)=>{try{fn();}catch(e){error(e);}},cancel=()=>{gesture.current=null;setOffset(0);latest.current.preview(null);};
 useEffect(()=>{if(gesture.current&&gesture.current.base!==scene)cancel();},[scene]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel();};window.addEventListener('keydown',key);window.addEventListener('blur',cancel);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('blur',cancel);if(gesture.current)latest.current.preview(null);};},[]);
 function changeKey(property:string,t:number,patch:Partial<MotionKey>){const track=l.propertyTracks!.find(p=>p.property===property)!;const next={...l,propertyTracks:l.propertyTracks!.map(p=>p===track?{...p,keys:p.keys.filter(k=>k.time!==patch.time||k.time===t).map(k=>k.time===t?{...k,...patch}:k).sort((a,b)=>a.time-b.time)}:p)};update(next);}
 const entry=selected&&l.propertyTracks?.find(t=>t.property===selected.property),key=entry?.keys.find(k=>Math.abs(k.time-(selected?.time||0))<1e-6),chosen=entry&&descriptors.find(d=>d.id===entry.property);
 function valueField(d:PropertyDescriptor,value:number|string,change:(v:number|string)=>void,live?:(n:number|null)=>void){return d.kind==='color'?<input type="color" aria-label={l.name+' '+d.label+' value'} disabled={l.locked} value={/^#[\da-f]{6}$/i.test(String(value))?String(value):'#ffffff'} onChange={e=>safe(()=>change(e.target.value))}/>:<TimelineNumber label={l.name+' '+d.label+' value'} value={Number(value)} min={d.min} max={d.max} disabled={l.locked} context={scene} scrubStep={d.max===1?.01:1} onPreview={live} onCommit={v=>safe(()=>change(v))}/>;}
 return <><div className="tl-row tl-extra-heading"><div className="tl-label"><button onClick={()=>setOpen(!open)} aria-expanded={open}> {open?'▾':'▸'} Appearance / masks</button><select aria-label={`${l.name} add animated property`} value="" disabled={l.locked} onChange={e=>safe(()=>{const d=descriptors.find(d=>d.id===e.target.value)!;update(setPropertyKey(l,d.id,time,readAnimatedProperty(atTime(l,time),d)));setOpen(true);})}><option value="">+ Property</option>{available.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></div><div className="tl-lane"/></div>
 {open&&l.propertyTracks?.map(track=>{const d=descriptors.find(d=>d.id===track.property);if(!d)return null;const value=readAnimatedProperty(atTime(l,time),d),at=track.keys.find(k=>Math.abs(k.time-time)<1e-6);return <div className="tl-row tl-property-row" key={track.property} data-appearance-property={track.property}><div className="tl-label"><button title="Remove track; retain playhead value" disabled={l.locked} onClick={()=>safe(()=>{const result=writeAnimatedProperty(l,d,value);update({...result,propertyTracks:l.propertyTracks?.filter(t=>t!==track)});})}>◷</button><span className="tl-property-name" title={d.label}>{d.label}</span>{valueField(d,value,v=>update(setPropertyKey(l,d.id,time,v)),n=>safe(()=>preview(n===null?null:{...scene,layers:scene.layers.map(v=>v.id===l.id?setPropertyKey(l,d.id,time,n):v)})))}<button aria-label={`Add ${l.name} ${d.label} key`} disabled={l.locked} aria-pressed={!!at} onClick={()=>safe(()=>update(at?{...l,propertyTracks:l.propertyTracks?.map(t=>t===track?{...t,keys:t.keys.filter(k=>k!==at)}:t)}:setPropertyKey(l,d.id,time,value)))}>◇</button></div><div className="tl-lane" onDoubleClick={e=>{if(l.locked||(e.target as HTMLElement).closest('button'))return;const b=e.currentTarget.getBoundingClientRect(),t=Math.round((e.clientX-b.left)/b.width*scene.duration*(scene.frameRate||60))/(scene.frameRate||60);safe(()=>update(setPropertyKey(l,d.id,t,readAnimatedProperty(atTime(l,t),d))));seek(t);}}>{track.keys.filter(k=>k.time<=scene.duration).map((k,i)=><button className="tl-key" key={i} aria-label={`${l.name} ${d.label} key ${i+1}`} aria-pressed={selected?.property===d.id&&selected.time===k.time} style={{left:`${(k.time+(gesture.current?.property===d.id&&gesture.current.time===k.time?offset:0))/scene.duration*100}%`}} onPointerDown={e=>{e.stopPropagation();e.preventDefault();setSelected({property:d.id,time:k.time});seek(k.time);if(l.locked)return;e.currentTarget.setPointerCapture(e.pointerId);gesture.current={base:scene,property:d.id,time:k.time,x:e.clientX,width:e.currentTarget.parentElement!.getBoundingClientRect().width,delta:0};}} onPointerMove={e=>{const g=gesture.current;if(!g)return;const fps=scene.frameRate||60,next=Math.max(0,Math.min(scene.duration,Math.round((g.time+(e.clientX-g.x)/g.width*scene.duration)*fps)/fps));g.delta=Math.round((next-g.time)*1e6)/1e6;setOffset(g.delta);}} onPointerUp={e=>{const g=gesture.current;if(!g)return;gesture.current=null;setOffset(0);e.currentTarget.releasePointerCapture(e.pointerId);if(latest.current.scene===g.base&&Math.abs(e.clientX-g.x)>2){const t=Math.round((g.time+g.delta)*1e6)/1e6;changeKey(g.property,g.time,{time:t});setSelected({property:g.property,time:t});}}} onPointerCancel={cancel} onLostPointerCapture={()=>{if(gesture.current)cancel();}}/>)}<div className="tl-playhead" style={{left:`${time/scene.duration*100}%`}}/></div></div>;})}
 {open&&key&&chosen&&selected&&<div className="tl-row tl-extra-selected"><div className="tl-label"><span>Key</span><TimelineNumber label="Appearance key time" value={key.time} min={0} max={600} onCommit={time=>{changeKey(chosen.id,key.time,{time});setSelected({property:chosen.id,time});}} disabled={l.locked}/>{valueField(chosen,key.value,value=>changeKey(chosen.id,key.time,{value}))}<select aria-label="Appearance key easing" disabled={l.locked} value={key.ease} onChange={e=>changeKey(chosen.id,key.time,{ease:e.target.value as MotionKey['ease']})}>{['linear','smooth','step','bezier'].map(s=><option key={s}>{s}</option>)}</select><button disabled={l.locked} onClick={()=>{update({...l,propertyTracks:l.propertyTracks?.map(t=>t===entry?{...t,keys:t.keys.filter(k=>k!==key)}:t)});setSelected(null);}}>×</button></div><span className="tl-lane"/></div>}</>;
}
