'use client';

import {useEffect,useState,type ReactNode} from 'react';
import {Move,Paintbrush,Clapperboard,Scan,Database,Search,X,Lock,Unlock,Eye,EyeOff,Copy,Trash2,ChevronUp,ChevronDown,Diamond,Settings2} from 'lucide-react';
import {atTime,propertyValue,validateProject,type Layer,type Scene,type Project,type Property} from '@/lib/studio-model';
import {editValues} from '@/lib/editing-tools';
import {percentProperty,propertyBounds,propertyLabels,setTimelineValue,timelineSourceValue,sameKeyTime} from '@/lib/timeline-tools';
import {sceneDuration,editClip} from '@/lib/timeline-clips';
import {deleteDesignLayers,duplicateDesignLayers} from '@/lib/design-tools';
import type {LayerMask} from '@/lib/design-schema';
import type {DesignTool} from './design-canvas';
import TimelineNumber from './timeline-number';
import {Choice,Num} from './controls';
import MotionInspector,{SavedMotionPresets} from './motion-inspector';
import EditingInspector from './editing-inspector';
import MaskInspector from './mask-inspector';
import {ProductionLibrary,LayoutInspector,GroupDesigner,ExtraDrawing,MediaInspector} from './production-inspector';
import {VisualInspector,CueInspector,MotionPresets} from './creative-inspector';
import KeyEditor from './key-editor';
import './properties-inspector.css';

type Tab='transform'|'style'|'motion'|'masks'|'data';
const tabs=[{id:'transform',label:'Transform',icon:Move},{id:'style',label:'Style',icon:Paintbrush},{id:'motion',label:'Motion',icon:Clapperboard},{id:'masks',label:'Masks',icon:Scan},{id:'data',label:'Data',icon:Database}] as const;
type Props={
 project:Project;scene:Scene;item?:Layer;selection:string[];animate:boolean;time:number;
 patch:(value:Partial<Layer>)=>void;update:(fn:(scene:Scene)=>Scene,checkpoint?:boolean)=>void;
 change:(fn:(project:Project)=>Project,checkpoint?:boolean)=>void;preview:(scene:Scene|null)=>void;
 pause:()=>void;seek:(time:number)=>void;select:(ids:string[])=>void;editText:()=>void;tool:(tool:DesignTool)=>void;
 mask:(mask:LayerMask|undefined)=>void;upload:(file:File)=>Promise<string>;error:(e:unknown)=>void;
 playing:boolean;previewVideo:()=>void;previewCue:(id:string)=>void;activeCue:string;reference:(time:number)=>void;
};
type Section={id:string;tab:Tab;title:string;keywords:string;hint?:string;badge?:ReactNode;open?:boolean;content:ReactNode};

function ColorField({value,change}:{value:string;change:(value:string)=>void}){
 const [draft,setDraft]=useState(value),[invalid,setInvalid]=useState(false);
 useEffect(()=>{setDraft(value);setInvalid(false);},[value]);
 const commit=()=>{if(draft===value)return;if(/^#[a-f\d]{6}$/i.test(draft)){change(draft);setInvalid(false);}else{setInvalid(true);}};
 return <label>Fill color<div className="pi-color"><input type="color" aria-label="Layer color" value={/^#[a-f\d]{6}$/i.test(value)?value:'#ffffff'} onChange={e=>change(e.target.value)}/><input aria-label="Layer color hex" value={draft} aria-invalid={invalid} onChange={e=>{setDraft(e.target.value);setInvalid(false);}} onBlur={commit} onKeyDown={e=>{e.stopPropagation();if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){setDraft(value);setInvalid(false);}}}/></div>{invalid&&<small role="status">Use a six-digit hex color, such as #FF6A00. Bind a variable in Data.</small>}</label>;
}

export default function PropertiesInspector(props:Props){
 const {project,scene,item,selection,animate,time,patch,update,change,preview,pause,seek,select,editText,tool,mask,upload,error}=props;
 const [tab,setTab]=useState<Tab>('transform'),[query,setQuery]=useState(''),[sceneMode,setSceneMode]=useState(false);
 useEffect(()=>{setQuery('');setSceneMode(false);if(item?.type==='video')setTab('style');},[scene.id,item?.id]);
 const playhead=animate?time:scene.duration;
 const safely=(fn:()=>void)=>{try{fn();}catch(e){error(e);}};
 const commitScene=(next:Scene)=>safely(()=>{validateProject({...project,scenes:project.scenes.map(s=>s.id===scene.id?next:s)});preview(null);update(()=>next,true);});
 const commitLayer=(next:Layer)=>commitScene({...scene,layers:scene.layers.map(l=>l.id===next.id?next:l)});
 // Patches from legacy tools retain their shared animation and schema cleanup rules.
 const layerPatch=(value:Partial<Layer>)=>{if(!item?.locked)patch(value);};
 const number=(property:Property,label=propertyLabels[property])=>{
  if(!item)return null;
  const factor=percentProperty(property)?100:1,bounds=propertyBounds(property),shown=propertyValue(atTime(item,playhead),property);
  const keyed=item.keys[property]?.some(k=>sameKeyTime(k.time,playhead)),driven=item.formulas?.some(f=>f.enabled&&f.property===property);
  const next=(value:number)=>({...scene,layers:scene.layers.map(l=>l.id===item.id?editValues(l,{[property]:value/factor},playhead,animate):l)});
  return <label key={property} className="pi-number-label">{label}<span className="pi-value"><TimelineNumber label={'Inspector '+propertyLabels[property]} value={shown*factor} min={bounds.min===undefined?undefined:bounds.min*factor} max={bounds.max===undefined?undefined:bounds.max*factor} step={.01} scrubStep={property.startsWith('scale')?.25:1} disabled={item.locked||driven} context={scene} onScrubStart={pause} onPreview={value=>preview(value===null?null:next(value))} onCommit={value=>commitScene(next(value))}/><span className="pi-unit">{factor===100?'%':property==='rotation'?'°':'px'}</span>{animate&&<button className={'pi-key'+(keyed?' active':'')} aria-label={'Set '+propertyLabels[property]+' keyframe'} title={'Set key at '+time.toFixed(3)+'s'} disabled={item.locked||driven} onClick={()=>safely(()=>commitLayer(setTimelineValue(item,property,playhead,timelineSourceValue(item,property,playhead),true)))}><Diamond size={11}/></button>}</span>{driven&&<button className="pi-driven" onClick={()=>{setQuery('');setTab('data');}}>Controlled by formula →</button>}</label>;
 };
 const editing=(section:'text'|'effects'|'path'|'motion'|'composition')=>item&&<EditingInspector section={section} item={item} project={project} duration={scene.duration} patch={layerPatch} editText={editText} editPath={motion=>tool(motion?'motion':'nodes')}/>;
 const visual=(section:'appearance'|'effects'|'image'|'text')=>item&&<VisualInspector section={section} item={item} patch={layerPatch}/>;
 const keyCount=item?Object.values(item.keys).reduce((n,k)=>n+(k?.length||0),0)+(item.propertyTracks||[]).reduce((n,t)=>n+t.keys.length,0):0;
 const sections:Section[]=item?[
  {id:'geometry',tab:'transform',title:'Position & size',keywords:'x y width height rotation scale transform position size opacity',open:true,content:<><div className="property-grid">{number('x','X position')}{number('y','Y position')}{number('width')}{number('height')}{number('rotation')}{number('opacity')}</div><p className="pi-tip">Drag values left / right. Shift: faster · Alt: finer.</p></>},
  {id:'anchor',tab:'transform',title:'Scale & anchor',keywords:'transform scale anchor origin pivot',open:true,content:<><div className="property-grid">{number('scaleX','Horizontal scale')}{number('scaleY','Vertical scale')}{number('anchorX')}{number('anchorY')}</div><p className="pi-tip">Anchor coordinates are local layer pixels.</p></>},
  {id:'hierarchy',tab:'transform',title:'Group & layout',keywords:'group parent responsive follow clipping fit position layout',content:<><label>Parent group<Choice label="Layer group" value={item.groupId||''} options={[{value:'',label:'No group'},...(scene.groups||[]).map(g=>({value:g.id,label:g.name}))]} onChange={value=>layerPatch({groupId:value||undefined})}/></label><LayoutInspector expanded item={item} scene={scene} patch={layerPatch}/></>},
  ...(item.type==='text'?[{id:'text',tab:'style' as Tab,title:'Text & typography',keywords:'text font family size weight align bold content typography',open:true,content:<><label>Text<textarea aria-label="Layer text" className="layer-text-content" value={item.text} onChange={e=>layerPatch({text:e.target.value})}/></label><label>Font family<input aria-label="Font family" value={item.fontFamily} maxLength={100} onChange={e=>layerPatch({fontFamily:e.target.value})}/></label><div className="property-grid"><label>Size (px)<Num label="Font size" value={item.fontSize} min={1} max={2000} onChange={fontSize=>layerPatch({fontSize})}/></label><label>Weight<Choice label="Font weight" value={String(item.fontWeight)} options={['100','200','300','400','500','600','700','800','900']} onChange={value=>layerPatch({fontWeight:Number(value)})}/></label></div><label>Alignment<Choice label="Text alignment" value={item.align} options={['left','center','right']} onChange={align=>layerPatch({align:align as Layer['align']})}/></label><button onClick={editText}>Edit styled text on canvas</button>{visual('text')}</>}]:[]),
  {id:'fill',tab:'style',title:'Fill & outline',keywords:'appearance fill color stroke outline gradient radius corner',open:true,content:<><ColorField value={item.color} change={color=>layerPatch({color})}/>{visual('appearance')}{item.type==='rect'&&<label>Corner radius (px)<Num label="Corner radius" value={item.radius} min={0} max={1000} onChange={radius=>layerPatch({radius})}/></label>}</>},
  ...(item.type==='image'?[{id:'image',tab:'style' as Tab,title:'Image & crop',keywords:'image source url fit crop zoom photo mask rounded',open:true,content:<><label>Image source<input aria-label="Image source" value={item.src} placeholder="Local asset or {{photoVariable}}" onChange={e=>layerPatch({src:e.target.value})}/></label><label className="pi-file">Replace from computer<input aria-label="Replace layer image" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0],id=item.id;if(file)upload(file).then(src=>update(s=>({...s,layers:s.layers.map(l=>l.id===id&&!l.locked?{...l,src}:l)}),true)).catch(error);e.target.value='';}}/></label>{visual('image')}</>}]:[]),
  {id:'effects',tab:'style',title:'Effects stack',keywords:'effects brightness contrast saturation hue blur shadow outline',badge:item.effects?.length||0,content:editing('effects')},
  {id:'lighting',tab:'style',title:'Shadow & glow',keywords:'shadow glow blur softness light',content:visual('effects')},
  {id:'drawing',tab:'style',title:item.type==='path'?'Vector & blending':'Blending & gradient stops',keywords:'blend drawing gradient stops vector path pen points handles',content:<>{item.type==='path'&&editing('path')}<ExtraDrawing expanded key={item.id} item={item} patch={layerPatch}/></>},
  ...(['video','ticker','countdown'].includes(item.type)?[{id:'media',tab:'style' as Tab,title:'Media content',keywords:'video ticker countdown media speed loop time text',open:true,content:<MediaInspector variables={project.variables} preview={props.previewVideo} playing={props.playing} item={item} patch={layerPatch} upload={upload} onError={error}/>}]:[]),
  {id:'timing',tab:'motion',title:'Layer timing',keywords:'in out duration start end trim timing time',open:true,content:<><div className="pi-timing"><span>VISIBLE FROM</span><strong>{(item.inPoint??0).toFixed(2)} <small>to</small> {(item.outPoint??scene.duration).toFixed(2)}s</strong></div><div className="property-grid"><label>In (seconds)<TimelineNumber label="Layer in point" value={item.inPoint??0} min={0} max={Math.max(0,(item.outPoint??scene.duration)-1/(scene.frameRate||60))} step={.001} onCommit={value=>safely(()=>commitScene(editClip(scene,item.id,'in',value)))}/></label><label>Out (seconds)<TimelineNumber label="Layer out point" value={item.outPoint??scene.duration} min={(item.inPoint??0)+1/(scene.frameRate||60)} max={scene.duration} step={.001} onCommit={value=>safely(()=>commitScene(editClip(scene,item.id,'out',value)))}/></label></div><p className="pi-tip">Trim visibility here, or drag the layer bar in the timeline.</p></>},
  {id:'presets',tab:'motion',title:'Animation presets',keywords:'animation motion presets fade slide pop save',content:<><MotionPresets item={item} duration={scene.duration} patch={layerPatch}/><SavedMotionPresets expanded layer={item} scene={scene} project={project} time={time} change={next=>change(()=>next,true)} error={error}/></>},
  {id:'keys',tab:'motion',title:'Keyframes',keywords:'keyframes animation interpolation ease bezier playhead copy paste',badge:keyCount,open:animate,content:<><p className="pi-tip">Expand a layer in the timeline to animate any supported property. These controls edit transform tracks.</p><KeyEditor key={item.id} item={item} patch={layerPatch} time={time} setTime={seek} duration={scene.duration}/></>},
  {id:'route',tab:'motion',title:'Motion path',keywords:'motion path route progress orient speed loop',content:editing('motion')},
  ...(item.type==='text'?[{id:'text-motion',tab:'motion' as Tab,title:'Text layout & animation',keywords:'text wrap direction rtl ltr paragraph letter word line typewriter reveal stagger text animation',content:editing('text')}]:[]),
  ...(item.composition?[{id:'composition',tab:'motion' as Tab,title:'Composition playback',keywords:'composition instance playback loop offset speed data override',content:editing('composition')}]:[]),
  {id:'brush',tab:'masks',title:'Layer & brush mask',keywords:'layer brush mask hide reveal feather density invert rectangle ellipse',hint:'Paint or draw which parts of the layer are visible.',badge:item.visual?.layerMask?'1':'',open:true,content:<MaskInspector item={item} change={mask} tool={tool}/>},
  {id:'matte',tab:'masks',title:'Shape masks & track matte',keywords:'advanced mask stack add subtract intersect shape polygon alpha luma matte source',hint:'Combine shapes, or use another layer as a mask.',badge:(item.masks?.length||0)+(item.matte?1:0),open:!!(item.masks?.length||item.matte),content:<MotionInspector section="masks" layer={item} scene={scene} project={project} time={time} patch={layerPatch} error={error}/>},
  {id:'bindings',tab:'data',title:'Data bindings',keywords:'data variable color text image photo source api binding',open:true,content:<><p className="pi-tip">Choose from this project’s variables. Manage values and API sources in the Data workspace.</p><label>Fill color variable<Choice label="Layer color variable" value={item.color.match(/^\{\{([^{}]+)\}\}$/)?.[1]||''} options={[{value:'',label:'Fixed color'},...Object.entries(project.variables).filter(([,v])=>typeof v==='string'&&/^#[a-f0-9]{6}$/i.test(v)).map(([key])=>({value:key,label:key}))]} onChange={key=>layerPatch({color:key?'{{'+key+'}}':'#ffffff'})}/></label>{['text','ticker','countdown','image','video'].includes(item.type)&&<label>{['image','video'].includes(item.type)?'Image / video source':'Insert text variable'}<select aria-label="Bind layer data" value="" onChange={e=>{if(!e.target.value)return;const value='{{'+e.target.value+'}}';layerPatch(['image','video'].includes(item.type)?{src:value}:{text:(item.text||'')+value});}}><option value="">Choose a variable…</option>{Object.keys(project.variables).map(key=><option key={key}>{key}</option>)}</select><small>{['image','video'].includes(item.type)?'Replaces this layer’s source.':'Appends the variable to this layer’s text.'}</small></label>}</>},
  {id:'formulas',tab:'data',title:'Property links & formulas',keywords:'formula expression property link driven data numeric variable',badge:item.formulas?.length||0,content:<MotionInspector section="formulas" layer={item} scene={scene} project={project} time={time} patch={layerPatch} error={error}/>},
  ...(item.groupId?[{id:'group-data',tab:'data' as Tab,title:'Group & repeated data',keywords:'group transform repeated rows api table sort layout',content:<GroupDesigner expanded scene={scene} project={project} groupId={item.groupId} update={fn=>update(fn,true)}/>}]:[]),
 ]:[];
 const orderedSections=item?.type==='video'?[...sections.filter(s=>s.id==='media'),...sections.filter(s=>s.id!=='media')]:sections;
 const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean),matches=orderedSections.filter(s=>words.length?words.every(word=>(s.title+' '+s.keywords).toLowerCase().includes(word)):s.tab===tab);
 const showingScene=sceneMode||!item;
 return <div className="properties-inspector" data-inspector-tab={showingScene?'scene':tab}>
  <header className="pi-header"><div className="pi-context"><span>{showingScene?'SCENE':item.type.toUpperCase()+' LAYER'}</span><button className={showingScene?'active':''} aria-label={showingScene&&item?'Return to layer properties':'Scene settings'} title="Scene settings" onClick={()=>{setSceneMode(!showingScene);setQuery('');}}><Settings2 size={13}/>{showingScene&&item?'Layer':'Scene'}</button></div>{showingScene?<strong className="pi-scene-name">{scene.name}</strong>:<><div className="pi-layer-title"><input aria-label="Layer name" value={item.name} disabled={item.locked} onChange={e=>layerPatch({name:e.target.value})}/><button aria-label={item.visible?'Hide selected layer':'Show selected layer'} title={item.visible?'Hide layer':'Show layer'} disabled={item.locked} onClick={()=>layerPatch({visible:!item.visible})}>{item.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button><button aria-label={item.locked?'Unlock selected layer':'Lock selected layer'} title={item.locked?'Unlock layer':'Lock layer'} className={item.locked?'active':''} onClick={()=>patch({locked:!item.locked})}>{item.locked?<Lock size={14}/>:<Unlock size={14}/>}</button></div>{selection.length>1&&<p className="pi-selection">{selection.length} selected · Editing {item.name} only</p>}{item.locked&&<p className="pi-selection">Layer locked. Unlock to make changes.</p>}<div className="pi-search"><Search size={13}/><input aria-label="Find a property" placeholder="Find a property…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear property search" onClick={()=>setQuery('')}><X size={12}/></button>}</div><div className="pi-tabs" role="tablist" aria-label="Layer property categories">{tabs.map(({id,label,icon:Icon})=><button key={id} role="tab" id={'pi-tab-'+id} aria-controls="pi-content" aria-selected={tab===id&&!words.length} aria-label={label+' properties'} tabIndex={tab===id?0:-1} onKeyDown={e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const i=tabs.findIndex(t=>t.id===id),index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[index].id);setQuery('');document.getElementById('pi-tab-'+tabs[index].id)?.focus();}} onClick={()=>{setTab(id);setQuery('');}}><Icon size={15}/><span>{label}</span></button>)}</div></>}</header>
  <div className="pi-scroll" id="pi-content" role={showingScene||words.length?'region':'tabpanel'} aria-label={showingScene?'Scene properties':words.length?'Property search results':tabs.find(t=>t.id===tab)?.label+' properties'}>
   {showingScene?<div className="pi-scene"><h3>Scene settings</h3><label>Name<input aria-label="Scene name" value={scene.name} onChange={e=>update(s=>({...s,name:e.target.value}))}/></label><div className="property-grid"><label>Width (px)<Num label="Scene width" value={scene.width} min={100} max={7680} onChange={width=>update(s=>({...s,width}))}/></label><label>Height (px)<Num label="Scene height" value={scene.height} min={100} max={4320} onChange={height=>update(s=>({...s,height}))}/></label><label>Duration (s)<TimelineNumber label="Scene duration" value={scene.duration} min={.1} max={600} onCommit={value=>safely(()=>commitScene(sceneDuration(scene,value)))}/></label><label>Frame rate<Choice label="Scene frame rate" value={String(scene.frameRate||60)} options={['25','30','50','60']} onChange={value=>update(s=>({...s,frameRate:Number(value) as Scene['frameRate']}),true)}/></label></div><ProductionLibrary project={project} scene={scene} selection={selection} change={change} update={update} onError={error}/><CueInspector scene={scene} update={update} preview={props.previewCue}/>{props.activeCue&&<button onClick={()=>props.previewCue('')}>Stop cue preview</button>}{scene.importReport&&<details className="psd-report"><summary>{scene.importReport.format==='ae'?'AE conversion report':'PSD import report'}</summary>{scene.importReport.format==='ae'&&<Choice label="Saved AE reference time" value={String(time)} options={scene.importReport.references.map(r=>({value:String(r.time),label:r.time.toFixed(3)+' seconds'}))} onChange={value=>props.reference(Number(value))}/>}<p>{scene.importReport.fileName} · {scene.importReport.mode}</p><ul>{scene.importReport.warnings.map((w,i)=><li key={i}><strong>{w.layer}</strong> — {w.message}</li>)}</ul></details>}{!item&&<p className="pi-empty">Select a layer on the canvas or in Layers to edit its properties.</p>}</div>:<>
    {words.length>0&&<p className="pi-results" role="status">{matches.length} matching {matches.length===1?'section':'sections'}</p>}
    {!matches.length&&<div className="pi-empty">No properties match “{query}”.<button onClick={()=>setQuery('')}>Clear search</button></div>}
    {matches.map(section=><details key={item.id+'-'+section.id+'-'+(!!words.length)} data-property-section={section.id} className="pi-section" open={!!words.length||section.open}><summary><span>{section.title}</span>{section.badge!==undefined&&section.badge!==''&&<em>{section.badge}</em>}{words.length>0&&<small>{tabs.find(t=>t.id===section.tab)?.label}</small>}</summary><fieldset disabled={item.locked} className="pi-section-body">{section.hint&&<p className="pi-tip">{section.hint}</p>}{section.content}</fieldset></details>)}
   </>}
  </div>
  {item&&!showingScene&&<footer className="pi-footer"><span title={item.name}>{animate?time.toFixed(2)+'s · '+keyCount+' keys':item.type+' · '+(item.locked?'locked':'editable')}</span><button aria-label="Move layer down" title="Move layer down" disabled={item.locked} onClick={()=>update(s=>{const a=[...s.layers],i=a.findIndex(l=>l.id===item.id),j=a.findLastIndex((l,n)=>n<i&&l.groupId===item.groupId);if(j>=0)[a[i],a[j]]=[a[j],a[i]];return{...s,layers:a};},true)}><ChevronDown size={14}/></button><button aria-label="Move layer up" title="Move layer up" disabled={item.locked} onClick={()=>update(s=>{const a=[...s.layers],i=a.findIndex(l=>l.id===item.id),j=a.findIndex((l,n)=>n>i&&l.groupId===item.groupId);if(j>=0)[a[i],a[j]]=[a[j],a[i]];return{...s,layers:a};},true)}><ChevronUp size={14}/></button><button aria-label="Duplicate layer" title="Duplicate layer" onClick={()=>safely(()=>{const result=duplicateDesignLayers(scene,[item.id]);update(()=>result.scene,true);select(result.selection);})}><Copy size={14}/></button><button aria-label="Delete layer" title="Delete layer" disabled={item.locked} onClick={()=>safely(()=>{update(s=>deleteDesignLayers(s,[item.id]),true);select([]);})}><Trash2 size={14}/></button></footer>}
 </div>;
}
