'use client';
import {useState} from 'react';
import {Eye,EyeOff,ChevronDown,ChevronRight,Lock,Unlock,Copy,FolderPlus,Trash2,Scan} from 'lucide-react';
import type {Scene} from '@/lib/studio-model';
import {sceneTree,type SceneNode} from '@/lib/psd-model';
import {deleteDesignLayers,duplicateDesignLayers,groupDesignLayers,reorderDesignLayer} from '@/lib/design-tools';
import {defaultLayerMask} from '@/lib/design-schema';
export default function SceneLayers({scene,selected,selectedIds,select,update,onError}:{scene:Scene;selected:string;selectedIds?:string[];select:(id:string,additive?:boolean)=>void;update:(fn:(s:Scene)=>Scene,checkpoint?:boolean)=>void;onError?:(e:unknown)=>void}){
 const [collapsed,setCollapsed]=useState<Set<string>>(new Set()),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[renaming,setRenaming]=useState('');
 const ids=selectedIds||[selected],run=(fn:(s:Scene)=>Scene)=>{try{const next=fn(scene);update(()=>next,true);}catch(e){onError?.(e);}},match=(node:SceneNode):boolean=>node.kind==='layer'?node.layer.name.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='masked'&&!!node.layer.visual?.layerMask||node.layer.type===filter):node.children.some(match)||!query&&filter==='all';
 const render=(nodes:SceneNode[],depth=0)=>[...nodes].reverse().filter(match).map(node=>{
  if(node.kind==='layer'){const l=node.layer;return <div key={l.id} data-design-layer={l.id} style={{paddingLeft:depth*8}} className={'layer-row '+(ids.includes(l.id)?'selected':'')} draggable={!l.locked&&!renaming} onDragStart={e=>{e.dataTransfer.setData('application/x-broadcastcg-layer',l.id);e.dataTransfer.effectAllowed='move';}} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-broadcastcg-layer'))e.preventDefault();}} onDrop={e=>{const id=e.dataTransfer.getData('application/x-broadcastcg-layer');if(id){e.preventDefault();e.stopPropagation();run(s=>reorderDesignLayer(s,id,l.id));}}}>
   {renaming===l.id?<input autoFocus aria-label="Rename layer" defaultValue={l.name} maxLength={200} onBlur={e=>{if(e.target.value.trim())run(s=>({...s,layers:s.layers.map(x=>x.id===l.id?{...x,name:e.target.value.trim()}:x)}));setRenaming('');}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){e.currentTarget.value=l.name;e.currentTarget.blur();}}}/>:<button className="layer-select" title={l.name+' · Double-click to rename'} onDoubleClick={()=>!l.locked&&setRenaming(l.id)} onClick={e=>select(l.id,e.shiftKey||e.ctrlKey||e.metaKey)}><span>{l.type==='text'?'T':l.type==='image'?'▧':'◇'}</span>{l.name}</button>}
   <button disabled={l.locked} className={l.visual?.layerMask?'has-mask':''} aria-label={(l.visual?.layerMask?'Select mask for ':'Add mask to ')+l.name} onClick={()=>{select(l.id);if(!l.visual?.layerMask)run(s=>({...s,layers:s.layers.map(x=>x.id===l.id?{...x,visual:{...x.visual,layerMask:defaultLayerMask()}}:x)}));}}><Scan size={13}/></button>
   <button aria-label={(l.visible?'Hide ':'Show ')+l.name} onClick={()=>run(s=>({...s,layers:s.layers.map(x=>x.id===l.id?{...x,visible:!x.visible}:x)}))}>{l.visible?<Eye size={13}/>:<EyeOff size={13}/>}</button>
   <button aria-label={(l.locked?'Unlock ':'Lock ')+l.name} onClick={()=>run(s=>({...s,layers:s.layers.map(x=>x.id===l.id?{...x,locked:!x.locked}:x)}))}>{l.locked?<Lock size={12}/>:<Unlock size={12}/>}</button>
  </div>;}
  const g=node.group;return <div key={g.id} className="scene-layer-group" style={{marginLeft:depth?6:0}}><div className="layer-row"><button aria-label={(collapsed.has(g.id)?'Expand ':'Collapse ')+g.name} onClick={()=>setCollapsed(v=>{const next=new Set(v);next.has(g.id)?next.delete(g.id):next.add(g.id);return next;})}>{collapsed.has(g.id)?<ChevronRight size={14}/>:<ChevronDown size={14}/>}</button><input aria-label={'Group name '+g.name} value={g.name} maxLength={200} onChange={e=>update(s=>({...s,groups:s.groups?.map(v=>v.id===g.id?{...v,name:e.target.value}:v)}))}/><button aria-label={(g.visible?'Hide group ':'Show group ')+g.name} onClick={()=>run(s=>({...s,groups:s.groups?.map(v=>v.id===g.id?{...v,visible:!v.visible}:v)}))}>{g.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button></div>{(!collapsed.has(g.id)||!!query)&&<><label className="scene-group-opacity">Group opacity<input aria-label={'Group opacity '+g.name} type="range" min="0" max="1" step=".01" value={g.opacity} onChange={e=>update(s=>({...s,groups:s.groups?.map(v=>v.id===g.id?{...v,opacity:Number(e.target.value)}:v)}))}/></label>{render(node.children,depth+1)}</>}</div>;
 });
 return <><div className="design-layer-search"><input aria-label="Search layers" placeholder="Find a layer…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter layers" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','text','image','rect','ellipse','path','video','masked'].map(v=><option key={v} value={v}>{v==='all'?'All kinds':v}</option>)}</select></div><div className="design-layer-actions"><button title="Duplicate selected layers" aria-label="Duplicate selected layers" disabled={!ids.length} onClick={()=>{try{const next=duplicateDesignLayers(scene,ids);update(()=>next.scene,true);if(next.selection[0])select(next.selection[0]);}catch(e){onError?.(e);}}}><Copy size={14}/></button><button title="Group selected layers" aria-label="Group selected layers" disabled={!ids.length} onClick={()=>run(s=>groupDesignLayers(s,ids))}><FolderPlus size={14}/></button><button title="Delete selected layers" aria-label="Delete selected layers" disabled={!ids.length} onClick={()=>run(s=>deleteDesignLayers(s,ids))}><Trash2 size={14}/></button><span>{scene.layers.length} layers · drag to reorder</span></div>{render(sceneTree(scene))}</>;
}
