'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Choice,Num} from './controls';
import {type Project,safeImage} from '@/lib/studio-model';
import {sportKinds,sportLabels} from '@/lib/sports-model';
import type {SportOperation} from '@/lib/sports-logic';
import {formationOptions} from '@/lib/formations';
import {RosterEditor} from './panel-widgets';
import type {PanelClocks} from './use-panel-clocks';
import './sports-workspace.css';

export function SportsWorkspace({project,change,execute,clocks,busy,canConfigure,canOperate,onError,onUpdate}:{project:Project;change:(fn:(p:Project)=>Project)=>void;execute:(op:SportOperation)=>Promise<void>;clocks:PanelClocks;busy:boolean;canConfigure:boolean;canOperate:boolean;onError:(e:unknown)=>void;onUpdate:()=>void}){
 const s=project.sports,v=project.variables;
 const [clockDrafts,setClockDrafts]=useState<Record<string,number>>({});
 const [kind,setKind]=useState<typeof sportKinds[number]>(s?.kind||'football'),[bestOf,setBestOf]=useState(s?.bestOf||3),[minutes,setMinutes]=useState(s?.periodSeconds?Math.round(s.periodSeconds/60):45),[pool,setPool]=useState(s?.mapPool.join('\n')||'Map 1\nMap 2\nMap 3\nMap 4\nMap 5'),[resetting,setResetting]=useState(false),[selected,setSelected]=useState(project.players[0]?.id||''),[sub,setSub]=useState(''),[draftTeam,setDraftTeam]=useState<'home'|'away'>('home'),[team,setTeam]=useState<'home'|'away'>('home'),[rosterText,setRosterText]=useState(''),[sourceId,setSourceId]=useState(project.sources[0]?.id||''),[rowsPath,setRowsPath]=useState('players'),[mapping,setMapping]=useState<Record<string,string>>({id:'id',name:'name',number:'number',photo:'photo',position:'position',bench:'bench',slot:'slot',stats:'stats'}),[importing,setImporting]=useState(false);
 const player=project.players.find(p=>p.id===selected),disabled=busy||!canOperate;
 const run=(op:SportOperation)=>execute(op).catch(onError);
 const set=(key:string,value:string|number)=>change(p=>({...p,variables:{...p.variables,[key]:value}}));
 function setup(){void run({op:'configure',kind,bestOf:bestOf as 1|3|5|7,periodSeconds:Math.round(minutes*60),mapPool:pool.split(/[\n,]/).map(x=>x.trim()).filter(Boolean)}).then(()=>setResetting(false));}
 function counter(key:string,label:string){return <div className="sport-counter" key={key}><span>{label}</span><Button size="sm" variant="secondary" aria-label={'Decrease '+label} disabled={disabled} onClick={()=>clocks.counter(key,-1)}>−</Button><strong>{String(v[key]??0)}</strong><Button size="sm" variant="secondary" aria-label={'Increase '+label} disabled={disabled} onClick={()=>clocks.counter(key,1)}>+</Button></div>;}
 function clock(key:string,label:string,direction:'up'|'down',reset:number){const state=clocks.remote[key];return <section className="sport-card clock-card" key={key}><div className="sport-eyebrow">{label}<span>{state?.running?'RUNNING':'PAUSED'}</span></div><output data-clock={key}>{String(v[key]??'00:00')}</output>{state?.interrupted&&<p role="status">Interrupted at the last saved time. Check the official clock before starting.</p>}<div className="row wrap"><Button disabled={disabled||clocks.connectionLost} onClick={()=>clocks.toggleClock(key,direction)}>{state?.running?'Pause':'Start'} {label}</Button><Button variant="secondary" disabled={disabled} onClick={()=>clocks.setClock(key,reset,direction)}>Reset {label}</Button><Button variant="ghost" disabled={disabled} onClick={()=>clocks.adjustClock(key,-1)}>−1s</Button><Button variant="ghost" disabled={disabled} onClick={()=>clocks.adjustClock(key,1)}>+1s</Button></div><label>Set seconds<Num label={'Set '+label+' seconds'} value={clockDrafts[key]??state?.seconds??0} min={0} max={86400} onChange={n=>setClockDrafts(d=>({...d,[key]:n}))}/></label><Button variant="outline" disabled={disabled||clockDrafts[key]===undefined} onClick={async()=>{const ok=await clocks.setClock(key,clockDrafts[key],direction);if(ok)setClockDrafts(d=>{const next={...d};delete next[key];return next;});}}>Set {label} time</Button>{key==='shotClock'&&<Button variant="outline" disabled={disabled} onClick={()=>clocks.setClock(key,14,'down')}>Reset to 14 seconds</Button>}</section>;}
 return <main className="sports-workspace"><header className="sports-heading"><div><div className="sport-eyebrow">MATCH CONTROL</div><h1>{s?sportLabels[s.kind]:'Sports & esports'}</h1><p>{s?'Operate the match, then update your live graphic when ready.':'Choose a match profile to connect scores, clocks, rosters and graphics.'}</p></div><div className="row"><Button variant="secondary" disabled={disabled} onClick={onUpdate}>Update live graphic</Button>{s&&<Button variant="outline" disabled={!canConfigure||busy} onClick={()=>setResetting(!resetting)}>New match setup</Button>}</div></header>
 {(!s||resetting)&&<section className="sport-card match-setup"><h2>{s?'Start a new match':'Set up a match'}</h2><p>Starting resets match scores, clocks, player statistics, cards, draft and results. Team names, rosters, panels and graphics are retained.</p><div className="sports-config"><label>Sport<Choice label="Match sport" value={kind} options={sportKinds.map(value=>({value,label:sportLabels[value]}))} onChange={value=>{setKind(value as typeof kind);setMinutes(value==='basketball'?10:value==='football'?45:2);}}/></label><label>Period length (minutes)<Num label="Period minutes" value={minutes} min={1} max={120} onChange={setMinutes}/></label>{kind==='esports'&&<label>Best of<Choice label="Match best of" value={String(bestOf)} options={['1','3','5','7']} onChange={v=>setBestOf(Number(v) as typeof bestOf)}/></label>}</div>{kind==='esports'&&<label>Map pool — one per line<textarea aria-label="Map pool" value={pool} onChange={e=>setPool(e.target.value)}/></label>}<Button disabled={!canConfigure||busy} onClick={setup}>{s?'Reset and start new match':'Create match'}</Button>{s&&<Button variant="ghost" onClick={()=>setResetting(false)}>Cancel</Button>}<p className="helper muted">Football: configurable 45-minute halves. Basketball: configurable 10-minute quarters. Volleyball: best of five, 25-point sets and a 15-point deciding set, win by two. Esports: configure your series and map pool.</p></section>}
 {s&&<><section className="sports-scoreboard">{(['home','away'] as const).map(side=><div key={side} className={'sport-team '+side} style={{borderColor:String(v[side+'Color']||(side==='home'?'#5093ff':'#ff647c'))}}><label>{side.toUpperCase()} TEAM<Input aria-label={side+' match team'} disabled={disabled} value={String(v[side+'Team']||side)} onChange={e=>set(side+'Team',e.target.value)}/></label><div className="sports-points"><Button aria-label={'Subtract '+side+' point'} disabled={disabled||Number(v[side+'Score'])<=0} variant="secondary" onClick={()=>run({op:'score',team:side,delta:-1})}>−</Button><output data-score={side}>{String(v[side+'Score']||0)}</output><Button aria-label={'Add '+side+' point'} disabled={disabled} onClick={()=>run({op:'score',team:side,delta:1})}>+</Button></div>{s.kind==='basketball'&&<div className="row"><Button disabled={disabled} variant="secondary" onClick={()=>run({op:'score',team:side,delta:2})}>+2 {side}</Button><Button disabled={disabled} variant="secondary" onClick={()=>run({op:'score',team:side,delta:3})}>+3 {side}</Button></div>}{['volleyball','esports'].includes(s.kind)&&<p>{s.kind==='volleyball'?'SETS':'MAPS'} WON <strong>{String(v[side+'Series']||0)}</strong></p>}{s.kind==='football'&&<Choice disabled={disabled} label={side+' match formation'} value={String(v[side+'Formation']||'4-3-3')} options={formationOptions(project)} onChange={value=>set(side+'Formation',value)}/>}<label>Team color<input type="color" aria-label={side+' match color'} disabled={disabled} value={String(v[side+'Color']||(side==='home'?'#5093ff':'#ff647c'))} onChange={e=>set(side+'Color',e.target.value)}/></label></div>)}<div className="sports-match-state"><span className="sport-eyebrow">MATCH STATE</span><Choice disabled={disabled} label="Match phase" value={String(v.matchPhase)} options={['Pregame','Live','Break','Overtime','Final']} onChange={value=>run({op:'phase',value:value as 'Live'})}/><label>{s.kind==='basketball'?'Quarter':s.kind==='football'?'Half':'Game'}<Choice disabled={disabled} label="Match period" value={String(v.period)} options={s.kind==='football'?['1H','2H','ET1','ET2','Penalties']:s.kind==='basketball'?['Q1','Q2','Q3','Q4','OT1','OT2','OT3']:['1','2','3','4','5','6','7']} onChange={value=>run({op:'period',value})}/></label>{v.matchWinner&&<strong>Winner: {String(v.matchWinner)}</strong>}<p>Period changes keep the clock value. Reset or set time for the next period. Break and Final pause all clocks.</p></div></section>
 {clocks.connectionLost&&<p className="sports-alert" role="alert">Clock service is unavailable. Displayed times may be stale.</p>}<div className="sports-clock-grid">{clock('matchClock','Match clock',s.kind==='basketball'?'down':'up',s.kind==='basketball'?s.periodSeconds:0)}{s.kind==='basketball'&&clock('shotClock','Shot clock','down',24)}{clock('timeoutClock','Timeout','down',60)}</div><section className="sport-card"><div className="sports-config">{s.kind==='football'&&counter('stoppage','Added minutes')}{s.kind==='basketball'&&<>{counter('homeFouls','Home fouls')}{counter('awayFouls','Away fouls')}{counter('homeTimeouts','Home timeouts used')}{counter('awayTimeouts','Away timeouts used')}</>}<label>Possession / serve<Choice disabled={disabled} label="Possession or serve" value={String(v.possession||'Home')} options={['Home','Away']} onChange={value=>set('possession',value)}/></label></div></section>
 {s.kind==='esports'&&<section className="sport-card"><div className="sport-section-title"><h2>Map draft & sides</h2><span>BO{s.bestOf}</span></div><div className="row wrap"><Choice label="Draft team" value={draftTeam} options={['home','away']} onChange={v=>setDraftTeam(v as typeof draftTeam)}/><Button variant="secondary" disabled={disabled||!s.draft.length} onClick={()=>run({op:'undo-draft'})}>Undo last draft</Button><Button variant="secondary" disabled={disabled} onClick={()=>run({op:'swap-sides'})}>Swap sides</Button><span>Home: {String(v.homeSide)} · Away: {String(v.awaySide)}</span></div><div className="sports-map-grid">{s.mapPool.map(map=>{const entry=s.draft.find(d=>d.map===map);return <article key={map} data-draft={entry?.choice||'available'}><strong>{map}</strong><small>{entry?entry.team+' '+entry.choice:'Available'}</small><div className="row"><Button size="sm" disabled={disabled||!!entry} onClick={()=>run({op:'draft',team:draftTeam,map,choice:'pick'})}>Pick {map}</Button><Button size="sm" variant="secondary" disabled={disabled||!!entry} onClick={()=>run({op:'draft',team:draftTeam,map,choice:'ban'})}>Ban</Button></div></article>;})}</div><label>Current map<Choice disabled={disabled} label="Current match map" value={String(v.currentMap||'')} options={s.mapPool.filter(map=>!s.draft.some(d=>d.map===map&&d.choice==='ban')&&!s.results.some(r=>r.name===map))} onChange={map=>run({op:'map',map})}/></label></section>}
 {['volleyball','esports'].includes(s.kind)&&<section className="sport-card"><h2>{s.kind==='volleyball'?'Set':'Map'} results</h2><div className="row wrap"><Button disabled={disabled} onClick={()=>run({op:'finish-game'})}>Complete current {s.kind==='volleyball'?'set':'map'}</Button><Button variant="outline" disabled={disabled||!s.results.length} onClick={()=>run({op:'undo-game'})}>Reopen last result</Button></div><p>Complete only after checking the official result. The next game starts at 0–0; a series winner changes the phase to Final.</p><table><thead><tr><th>Game</th><th>Home</th><th>Away</th><th>Winner</th></tr></thead><tbody>{s.results.map((r,i)=><tr key={i}><td>{r.name}</td><td>{r.home}</td><td>{r.away}</td><td>{String(v[r.winner+'Team'])}</td></tr>)}</tbody></table></section>}
 <div className="sports-detail-grid"><section className="sport-card"><h2>Roster & player statistics</h2><Choice label="Match player" value={selected} options={project.players.map(p=>({value:p.id,label:p.team+' · #'+p.number+' '+p.name}))} onChange={id=>{setSelected(id);if(canOperate)void run({op:'select-player',playerId:id});}}/>{player&&<><div className="sports-player">{safeImage(player.photo)&&<img src={player.photo} alt={player.name}/>}<div><strong>{player.name}</strong><p>#{player.number} · {player.position} · {player.bench?'Bench':'Active'}</p></div></div><div className="sports-stat-grid">{(s.kind==='esports'?['kills','deaths','assists']:s.kind==='basketball'?['points','rebounds','assists','fouls']:['goals','assists']).map(stat=><div className="sport-counter" key={stat}><span>{stat}</span><Button aria-label={'Decrease player '+stat} variant="secondary" size="sm" disabled={disabled} onClick={()=>run({op:'stat',playerId:player.id,stat:stat as 'goals',delta:-1})}>−</Button><strong>{player.stats?.[stat as 'goals']||0}</strong><Button aria-label={'Increase player '+stat} variant="secondary" size="sm" disabled={disabled} onClick={()=>run({op:'stat',playerId:player.id,stat:stat as 'goals',delta:1})}>+</Button></div>)}</div><p className="helper muted">Selecting a player fills playerName, playerPhoto, playerNumber and player statistics in Data. Individual statistics do not change the team score.</p>{s.kind==='football'&&<label>Discipline<Choice disabled={disabled} label="Player card" value={player.card||'none'} options={['none','yellow','red']} onChange={card=>run({op:'card',playerId:player.id,card:card==='none'?'':card as 'red'})}/></label>}{!player.bench&&<div className="row wrap"><Choice disabled={disabled} label="Incoming substitute" value={sub} options={project.players.filter(p=>p.bench&&p.team===player.team&&p.card!=='red').map(p=>({value:p.id,label:'#'+p.number+' '+p.name}))} onChange={setSub}/><Button disabled={disabled||!sub} variant="secondary" onClick={()=>run({op:'substitute',out:player.id,incoming:sub})}>Apply substitution</Button></div>}<p className="helper muted">Apply substitution updates the active roster immediately. Use the football panel’s staged substitution when it must be applied after TAKE.</p></>}<fieldset disabled={disabled}><RosterEditor project={project} change={change} selected={selected} onSelect={setSelected}/></fieldset></section>
 <section className="sport-card"><h2>Roster data mapping</h2><p>Map a JSON array from a local file or a saved HTTPS source. Replacing a team roster is atomic; invalid rows leave it unchanged. Bench defaults to true when unmapped.</p><Choice label="Roster team" value={team} options={['home','away']} onChange={v=>setTeam(v as typeof team)}/><div className="sports-mappings">{['id','name','number','position','photo','bench','slot','stats'].map(key=><label key={key}>{key}<Input aria-label={'Roster '+key+' path'} value={mapping[key]||''} onChange={e=>setMapping(m=>({...m,[key]:e.target.value}))}/></label>)}</div><details><summary>Local JSON roster</summary><input aria-label="Open roster JSON" type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(file){if(file.size>200000){onError(Error('Roster JSON must be under 200 KB.'));return;}setRosterText(await file.text());}}}/><textarea aria-label="Roster JSON" value={rosterText} placeholder='[{"id":"9","name":"Player","number":9,"bench":true,"slot":9,"photo":"","position":"ST","stats":{}}]' onChange={e=>setRosterText(e.target.value)}/><Button disabled={disabled||importing} onClick={async()=>{try{setImporting(true);const rows=JSON.parse(rosterText);await execute({op:'roster',team,rows,mapping});}catch(e){onError(e);}finally{setImporting(false);}}}>Replace {team} roster from JSON</Button></details><details><summary>API roster</summary><label>Saved source<Choice label="Roster API source" value={sourceId} options={project.sources.map(s=>({value:s.id,label:s.name}))} onChange={setSourceId}/></label><label>Array path<Input aria-label="Roster array path" value={rowsPath} onChange={e=>setRowsPath(e.target.value)}/></label><Button disabled={disabled||!sourceId} onClick={()=>run({op:'fetch-roster',team,sourceId,rowsPath,mapping})}>Fetch and replace {team} roster</Button><p className="helper muted">Configure source URL and credentials in Data. Use blank paths for optional unmapped fields. Stats maps to an object of numeric player statistics.</p></details></section></div>
 <section className="sport-card"><h2>Match events</h2>{!s.events.length&&<p>No events yet.</p>}<ol className="sports-events">{s.events.slice(0,20).map((e,i)=><li key={e.id+'-'+i}><time>{new Date(e.time).toLocaleTimeString()}</time><span>{e.label}</span></li>)}</ol></section></>}
 </main>;
}
