'use client';
import {Choice,Num} from './controls';
import {VariableSelect} from './variable-select';
import type {Action,Project} from '@/lib/studio-model';
export function SportsActionFields({a,project,patch}:{a:Action;project:Project;patch:(v:Partial<Action>)=>void}){
 let options:Record<string,any>;try{const parsed=JSON.parse(a.value);options=parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{};}catch{options={};}
 const update=(next:Record<string,unknown>)=>{const value={...options,...next};patch({value:JSON.stringify(value),...(a.type==='sport'?{target:String(value.op)}:{})});};
 if(a.type==='clock')return <><label>Clock variable<VariableSelect label="Action clock variable" value={a.target} variables={project.variables} onChange={target=>patch({target})}/></label><label>Clock operation<Choice label="Clock operation" value={options.op||'start'} options={['start','pause','reset','adjust']} onChange={op=>update({op,seconds:options.seconds??0})}/></label>{options.op!=='pause'&&<label>Direction<Choice label="Clock direction" value={options.direction||'up'} options={['up','down']} onChange={direction=>update({direction})}/></label>}{['reset','adjust'].includes(options.op)&&<label>Seconds<Num label="Clock action seconds" value={options.seconds||0} min={options.op==='reset'?0:-86400} max={86400} onChange={seconds=>update({seconds})}/></label>}</>;
 if(a.type==='counter')return <><VariableSelect label="Counter variable" variables={project.variables} value={a.target} numericOnly onChange={target=>patch({target})}/><label>Change by<Num label="Counter delta" value={options.delta??1} onChange={delta=>update({delta})}/></label></>;
 const operations=['score','phase','period','select-player','stat','card','substitute','draft','undo-draft','map','finish-game','undo-game','swap-sides'];
 const playerChoice=(field:string,label:string)=><label>{label}<Choice label={label} value={options[field]||''} options={project.players.map(p=>({value:p.id,label:p.team+' #'+p.number+' '+p.name}))} onChange={value=>update({[field]:value})}/></label>;
 return <><label>Match operation<Choice label="Sports operation" value={options.op||'score'} options={operations} onChange={op=>{patch({target:op,value:JSON.stringify({op,team:'home',delta:1,value:op==='phase'?'Live':'1',playerId:project.players[0]?.id||'',stat:'goals',card:'yellow',choice:'pick',map:project.sports?.mapPool[0]||'',out:project.players.find(p=>!p.bench)?.id||'',incoming:project.players.find(p=>p.bench)?.id||''})});}}/></label>{['score','draft'].includes(options.op)&&<label>Team<Choice label="Action team" value={options.team||'home'} options={['home','away']} onChange={team=>update({team})}/></label>}{['score','stat'].includes(options.op)&&<label>Change by<Num label="Sports delta" value={options.delta??1} min={-3} max={3} onChange={delta=>update({delta:Math.round(delta)})}/></label>}{options.op==='phase'&&<Choice label="Action match phase" value={options.value||'Live'} options={['Pregame','Live','Break','Overtime','Final']} onChange={value=>update({value})}/>} {options.op==='period'&&<Choice label="Action period" value={options.value||'1'} options={project.sports?.kind==='football'?['1H','2H','ET1','ET2','Penalties']:project.sports?.kind==='basketball'?['Q1','Q2','Q3','Q4','OT1','OT2']:['1','2','3','4','5','6','7']} onChange={value=>update({value})}/>}{['stat','card','select-player'].includes(options.op)&&playerChoice('playerId','Action player')}{options.op==='stat'&&<Choice label="Player statistic" value={options.stat||'goals'} options={['goals','assists','kills','deaths','points','rebounds','fouls']} onChange={stat=>update({stat})}/>} {options.op==='card'&&<Choice label="Action card" value={options.card||'none'} options={['none','yellow','red']} onChange={card=>update({card:card==='none'?'':card})}/>} {options.op==='substitute'&&<>{playerChoice('out','Outgoing player')}{playerChoice('incoming','Incoming player')}</>}{['draft','map'].includes(options.op)&&<Choice label="Action map" value={options.map||''} options={project.sports?.mapPool||[]} onChange={map=>update({map})}/>} {options.op==='draft'&&<Choice label="Draft choice" value={options.choice||'pick'} options={['pick','ban']} onChange={choice=>update({choice})}/>}<small className="helper muted">Set up the match in Sports first. These actions use the same service and history as the match console.</small></>;
}
