'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {clipRange,editClip,sceneDuration,retimeSelectedKeys} from '@/lib/timeline-clips';
import {uid,type Layer,type Scene} from '@/lib/studio-model';
import type {TimelineKey} from '@/lib/timeline-tools';
import TimelineNumber from './timeline-number';
type Shared={scene:Scene;commit:(s:Scene)=>void;preview:(s:Scene|null)=>void;error:(e:unknown)=>void};
export function LayerTimeBar({scene,layer,selected,select,snap,commit,preview,error}:Shared&{layer:Layer;selected:string;select:(id:string)=>void;snap:boolean}){
 const gesture=useRef<{base:Scene;startX:number;width:number;mode:'in'|'out'|'move'|'stretch'|'slip';start:number;end:number;next:Scene;pointer:number;node:HTMLElement}|null>(null),latest=useRef({scene,selected,preview});latest.current={scene,selected,preview};const [draft,setDraft]=useState<Layer|null>(null);const r=clipRange(draft||layer,scene.duration);
 function cancel(){const g=gesture.current;gesture.current=null;setDraft(null);latest.current.preview(null);if(g?.node.hasPointerCapture(g.pointer))g.node.releasePointerCapture(g.pointer);}
 useEffect(()=>{if(gesture.current&&(scene!==gesture.current.base||selected!==layer.id||layer.locked))cancel();},[scene,selected,layer.locked]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&gesture.current){e.preventDefault();e.stopPropagation();cancel();}};window.addEventListener('keydown',key,true);window.addEventListener('blur',cancel);return()=>{window.removeEventListener('keydown',key,true);window.removeEventListener('blur',cancel);if(gesture.current)latest.current.preview(null);};},[]);
 function begin(e:PointerEvent<HTMLDivElement>){if(e.button!==0||layer.locked)return;e.preventDefault();e.stopPropagation();select(layer.id);const edge=(e.target as HTMLElement).dataset.edge,mode=edge==='in'?'in':edge==='out'?(e.shiftKey?'stretch':'out'):e.altKey?'slip':'move',range=clipRange(layer,scene.duration);gesture.current={base:scene,startX:e.clientX,width:e.currentTarget.parentElement!.getBoundingClientRect().width,mode,start:range.start,end:range.end,next:scene,pointer:e.pointerId,node:e.currentTarget};e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e:PointerEvent<HTMLDivElement>){const g=gesture.current;if(!g)return;let delta=(e.clientX-g.startX)/g.width*g.base.duration;const anchor=g.mode==='in'?g.start:g.mode==='out'||g.mode==='stretch'?g.end:g.start;if(snap&&!e.ctrlKey)delta=Math.round((anchor+delta)*(scene.frameRate||60))/(scene.frameRate||60)-anchor;try{g.next=editClip(g.base,layer.id,g.mode,['in','out','stretch'].includes(g.mode)?anchor+delta:delta);setDraft(g.next.layers.find(l=>l.id===layer.id)!);preview(g.next);}catch(e){error(e);}}
 return <div role="group" aria-label={`${layer.name} timing bar`} className="tl-duration-bar tl-editable-clip" data-locked={layer.locked} style={{left:`${r.start/scene.duration*100}%`,width:`${Math.max(0,r.end-r.start)/scene.duration*100}%`}} title={`${r.start.toFixed(3)}–${r.end.toFixed(3)} s · Drag: move · Edges: trim · Shift-right-edge: stretch · Alt-drag: slip keys`} onPointerDown={begin} onPointerMove={move} onPointerCancel={cancel} onLostPointerCapture={()=>{if(gesture.current)cancel();}} onPointerUp={e=>{const g=gesture.current;if(!g)return;move(e);gesture.current=null;setDraft(null);preview(null);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(latest.current.scene===g.base&&Math.abs(e.clientX-g.startX)>=2&&g.next!==g.base)commit(g.next);}}><span data-edge="in" className="tl-clip-handle" role="separator" aria-label={`${layer.name} In handle`}/><span className="tl-clip-caption">{r.start.toFixed(2)} — {r.end.toFixed(2)}</span><span data-edge="out" className="tl-clip-handle tl-clip-out" role="separator" aria-label={`${layer.name} Out handle`}/></div>;
}
export function TimingTools({scene,selected,time,seek,commit,preview,error,keys}:{scene:Scene;selected:string;time:number;seek:(n:number)=>void;keys:TimelineKey[]}&Shared){
 const l=scene.layers.find(l=>l.id===selected),r=l&&clipRange(l,scene.duration),fps=scene.frameRate||60,area=scene.workArea||{start:0,end:scene.duration,loop:false};const [stretch,setStretch]=useState(100),[marker,setMarker]=useState('Marker');
 const safe=(fn:()=>void)=>{try{fn();}catch(e){error(e);}};
 const timing=(mode:'in'|'out',value:number)=>editClip(scene,l!.id,mode,value);
 return <div className="tl-timing-tools"><strong>Layer timing</strong>{l&&r?<><span className="tl-timing-name">{l.name}</span>{(['in','out'] as const).map(mode=><label key={mode}>{mode==='in'?'In':'Out'}<TimelineNumber label={`Layer ${mode==='in'?'In':'Out'} time`} value={mode==='in'?r.start:r.end} min={mode==='in'?0:r.start+1/fps} max={mode==='in'?r.end-1/fps:600} step={1/fps} scrubStep={1/fps} disabled={l.locked} context={scene} onPreview={n=>safe(()=>preview(n===null?null:timing(mode,n)))} onCommit={n=>safe(()=>commit(timing(mode,n)))}/></label>)}<span>{(r.end-r.start).toFixed(2)}s</span><button disabled={l.locked||time>=r.end} onClick={()=>safe(()=>commit(timing('in',time)))}>In at playhead</button><button disabled={l.locked||time<=r.start} onClick={()=>safe(()=>commit(timing('out',time)))}>Out at playhead</button></>:<span>Select a layer</span>}
 <details><summary>Graphic range & markers</summary><div className="tl-popup"><p>Trim the graphic without deleting keys outside its end.</p><label>Overall duration<TimelineNumber label="Overall graphic duration" value={scene.duration} min={.1} max={600} onCommit={n=>safe(()=>{commit(sceneDuration(scene,n));seek(Math.min(time,n));})}/></label><label>Preview from<TimelineNumber label="Work area start" value={area.start} min={0} max={area.end-1/fps} onCommit={start=>commit({...scene,workArea:{...area,start}})}/></label><label>Preview to<TimelineNumber label="Work area end" value={area.end} min={area.start+1/fps} max={scene.duration} onCommit={end=>commit({...scene,workArea:{...area,end}})}/></label><label><input type="checkbox" checked={area.loop} onChange={e=>commit({...scene,workArea:{...area,loop:e.target.checked}})}/>Loop preview range</label><button onClick={()=>commit({...scene,workArea:undefined})}>Reset preview range</button><label>Marker name<input aria-label="New marker name" value={marker} maxLength={100} onChange={e=>setMarker(e.target.value)}/></label><button disabled={!marker.trim()||(scene.markers?.length||0)>=100} onClick={()=>commit({...scene,markers:[...(scene.markers||[]),{id:uid(),name:marker.trim(),time}]})}>Add marker at playhead</button>{scene.markers?.map(m=><div className="row" key={m.id}><button onClick={()=>seek(Math.min(m.time,scene.duration))}>{m.name} · {m.time.toFixed(2)}s</button><button aria-label={'Remove marker '+m.name} onClick={()=>commit({...scene,markers:scene.markers?.filter(v=>v.id!==m.id)})}>×</button></div>)}</div></details>
 <details><summary>Retime selected keys</summary><div className="tl-popup"><p>Selected transform keys: {keys.length}</p><button disabled={keys.length<2} onClick={()=>safe(()=>commit(retimeSelectedKeys(scene,keys,'reverse')))}>Reverse selected keys</button><label>Time stretch %<TimelineNumber label="Key time stretch percent" value={stretch} min={1} max={10000} onCommit={setStretch}/></label><button disabled={keys.length<2} onClick={()=>safe(()=>commit(retimeSelectedKeys(scene,keys,'stretch',stretch/100)))}>Stretch selected keys</button></div></details></div>;
}
