'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Project,Control} from '@/lib/studio-model';
import {toolRecipes,panelPacks,type ToolRecipe} from '@/lib/tool-library';
export function ToolLibrary({project,open,onOpenChange,onAdd,onPreset,onRemovePreset}:{project:Project;open:boolean;onOpenChange:(value:boolean)=>void;onAdd:(recipes:ToolRecipe[])=>void;onPreset:(control:Control)=>void;onRemovePreset:(id:string)=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[notice,setNotice]=useState('');
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="tool-library-dialog"><DialogHeader><DialogTitle>Broadcast tool library</DialogTitle><DialogDescription>Add ready-wired tools, then change their variables, colors, options, sizes and actions in the inspector. Existing variable values are kept.</DialogDescription></DialogHeader><Input aria-label="Search tools" placeholder="Search scores, maps, clocks, colors…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="row wrap">{['All','Sports','Esports','Common','Saved'].map(v=><Button key={v} size="sm" variant={category===v?'secondary':'ghost'} onClick={()=>setCategory(v)}>{v}</Button>)}</div>
 {category==='All'&&!query&&<div className="tool-packs">{panelPacks.map(pack=><article key={pack.id}><strong>{pack.label}</strong><p>{pack.description}</p><Button size="sm" onClick={()=>{onAdd(pack.recipes.map(id=>toolRecipes.find(r=>r.id===id)!));setNotice(pack.label+' added to the current panel.');}}>Add {pack.label.toLowerCase()}</Button></article>)}</div>}
 <div className="tool-recipe-grid">{category==='Saved'?(project.toolPresets||[]).filter(c=>c.label.toLowerCase().includes(query.toLowerCase())).map(c=><article key={c.id}><strong>{c.label}</strong><p>{c.kind} · {c.variable||c.actions.length+' actions'}</p><div className="row"><Button size="sm" onClick={()=>{onPreset(c);setNotice(c.label+' added.');}}>Add tool</Button><Button variant="ghost" size="sm" onClick={()=>onRemovePreset(c.id)}>Remove saved tool</Button></div></article>):toolRecipes.filter(r=>(category==='All'||r.category===category)&&(r.label+' '+r.description).toLowerCase().includes(query.toLowerCase())).map(r=><article key={r.id}><small>{r.category}</small><strong>{r.label}</strong><p>{r.description}</p><Button size="sm" variant="secondary" onClick={()=>{onAdd([r]);setNotice(r.label+' added to the current panel.');}}>Add {r.label.toLowerCase()}</Button></article>)}</div>{category==='Saved'&&!project.toolPresets?.length&&<p className="helper muted">Select any control and use “Save to tool library” in its inspector.</p>}{notice&&<p className="success" role="status">{notice}</p>}</DialogContent></Dialog>;
}
