const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:5173';
const delay = ms => new Promise(r => setTimeout(r, ms));
(async () => {
 const browser=await chromium.launch({headless:true,channel:process.env.TEST_BROWSER || 'msedge'});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text());});
 const request=async(path,body)=>page.evaluate(async({path,body})=>{const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return{status:r.status,data:await r.json()};},{path,body});
 try {
 await page.goto(base+'/signin-with-chatgpt?return_to=/',{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('button',{name:'New project',exact:true}).click();
 if(process.env.TEST_PART!=='data'){
 await page.getByLabel('Project name',{exact:true}).fill('QA studio');
 await page.getByRole('textbox',{name:'Text',exact:true}).fill('PERSISTED PRESENTER');
 const x=page.locator('.inspector').getByRole('spinbutton',{name:'x',exact:true});
 await x.fill('250');
 assert.match(await page.locator('#editor-shadow').locator('..').locator('..').locator('[data-layer-id="presenter-name"]').getAttribute('transform'),/translate\(250 /);
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.statusbar').textContent.startsWith('Saved'));
 let list=(await request('/api/projects')).data;
 let saved=(await request('/api/projects/'+list[0].id)).data;
 assert.equal(saved.project.scenes[0].layers.find(l=>l.id==='presenter-name').text,'PERSISTED PRESENTER');
 assert.equal((await request('/api/projects',{project:saved.project,revision:saved.revision-1})).status,409);
 assert.equal((await request('/api/projects',{project:{},revision:0})).status,400);
 console.log('PASS: edit, save, optimistic conflict, invalid project');
 await page.reload({waitUntil:'networkidle'});
 await page.waitForFunction(()=>document.querySelector('.project-name')?.value==='QA studio');
 assert.equal(await page.getByRole('textbox',{name:'Text',exact:true}).inputValue(),'PERSISTED PRESENTER');
 const png=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'PNG',exact:true}).click()]);
 assert.match(png[0].suggestedFilename(),/\.png$/);
 await page.getByRole('tab',{name:'Animate',exact:true}).click();
 await page.getByRole('button',{name:/Set key at/}).click();
 assert.ok(await page.locator('.key-row').count()>=3);
 await page.getByRole('button',{name:'Play',exact:true}).click();
 await delay(400);assert.notEqual(await page.locator('.timecode').innerText(),'0.00 s');
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 console.log('PASS: reload persistence, PNG export, keyframes, playback');
 await page.getByRole('tab',{name:'Panels',exact:true}).click();
 await page.getByRole('button',{name:'Button',exact:true}).click();
 await page.locator('.control-inspector').getByRole('textbox',{name:'Label',exact:true}).fill('Custom stage');
 await page.getByRole('tab',{name:'Operate',exact:true}).click();
 await page.getByRole('button',{name:'Custom stage 1 actions',exact:true}).click();
 assert.match(await page.locator('.transport').innerText(),/Presenter lower third/);
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/program')&&r.request().method()==='POST'),page.getByRole('button',{name:'TAKE',exact:true}).click()]);
 let live=(await request('/api/program')).data;
 assert.equal(live.scene.id,'presenter');
 const output=await context.newPage();await output.goto(base+'/output',{waitUntil:'domcontentloaded'});
 await output.locator('.graphic').waitFor();await delay(800);
 assert.match(await output.locator('body').innerText(),/PERSISTED PRESENTER/);
 assert.equal(await output.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgba(0, 0, 0, 0)');
 console.log('PASS: custom button, TAKE, independent transparent output');
 await page.getByRole('button',{name:'Home player 12 substitute 12',exact:true}).click();
 await page.getByRole('button',{name:'Home player 9 number 9',exact:true}).click();
 assert.match(await page.locator('.transport').innerText(),/Substitution pending/);
 assert.equal((await request('/api/program')).data.scene.id,'presenter');
 await page.getByRole('button',{name:'TAKE',exact:true}).click();await delay(500);
 assert.equal(await page.locator('[data-player="home-12"]').count(),1);
 assert.equal(await page.locator('[data-sub="home-9"]').count(),1);
 assert.doesNotMatch(await page.locator('.transport').innerText(),/Substitution pending/);
 await page.getByRole('button',{name:'Hide',exact:true}).click();await delay(1000);
 assert.equal(await output.locator('.graphic').count(),0);
 console.log('PASS: staged substitution commits on TAKE, hide reaches output');
 }
 await page.getByRole('tab',{name:'Data',exact:true}).click();
 await page.getByRole('button',{name:'Add API',exact:true}).click();
 await page.getByRole('textbox',{name:'GET endpoint',exact:true}).fill('https://dummyjson.com/users/1');
 await page.getByRole('button',{name:'Binding',exact:true}).click();
 await page.getByRole('textbox',{name:'JSON path',exact:true}).fill('firstName');
 await page.getByRole('button',{name:'Fetch data',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.response-view')?.textContent.includes('Emily'),{timeout:20000});
 await page.getByRole('tab',{name:'Design',exact:true}).click();
 assert.equal(await page.getByRole('textbox',{name:'Text',exact:true}).inputValue(),'Emily');
 console.log('PASS: real HTTPS API fetch and text binding');
 await page.locator('.canvas-toolbar input[type=file]').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2dWkAAAAASUVORK5CYII=','base64')});
 await page.getByRole('textbox',{name:'Image URL',exact:true}).waitFor();
 const asset=await page.getByRole('textbox',{name:'Image URL',exact:true}).inputValue();
 assert.ok(asset.startsWith('/api/assets/'));
 assert.equal((await context.request.get(base+asset)).status(),200);
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.statusbar').textContent.startsWith('Saved'));
 console.log('PASS: durable image upload and final project save');
 for(const width of [1024,768,390]){await page.setViewportSize({width,height:900});for(const tab of ['Design','Data','Panels','On air']){await page.getByRole('tab',{name:tab,exact:true}).click();await delay(80);const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert.ok(dimensions.scroll<=dimensions.width+1,`${tab} overflow at ${width}: ${JSON.stringify(dimensions)}`);}await page.screenshot({path:`outputs/mobile-${width}.png`,fullPage:true});}
 console.log('PASS: responsive layouts at 1024, 768, and 390 px');
 console.log('WebMCP available:',await page.evaluate(()=>!!document.modelContext?.registerTool));
 assert.deepEqual(errors,[]);
 const anonymous=await browser.newContext();assert.equal((await anonymous.request.get(base+'/api/projects')).status(),401);await anonymous.close();
 console.log('PASS: authenticated storage, no application console errors');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
