import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import net from 'node:net';
import http from 'node:http';
import {randomBytes} from 'node:crypto';
import {WebSocket,WebSocketServer} from 'ws';
import {createBrowserOutput} from '../desktop/browser-output-server.mjs';
import {outputConfig} from '../desktop/output-config.mjs';
import {frameMeter} from '../desktop/frame-meter.mjs';
import {connectObs,obsAuthentication} from '../desktop/obs-client.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
async function fixture(t,options={}){const root=mkdtempSync(join(tmpdir(),'bc-output-'));writeFileSync(join(root,'output.html'),'<html>Program</html>');writeFileSync(join(root,'private.txt'),'NEVER SERVE');const p=await port(),secret=randomBytes(32).toString('hex'),host=await createBrowserOutput({root,secret,config:{port:p},...options});const clients=[];t.after(async()=>{for(const c of clients)c.terminate();await host.close();assert.ok(resolve(root).startsWith(resolve(tmpdir())+sep+'bc-output-'));rmSync(root,{recursive:true,force:true});});return{host,p,async receiver(){const ws=new WebSocket(host.url.replace('http:','ws:')+'events',{origin:'http://127.0.0.1:'+p});clients.push(ws);const messages=[];ws.on('message',b=>messages.push(JSON.parse(b)));await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});await until(()=>messages.length);return{ws,messages,send:m=>ws.send(JSON.stringify({epoch:messages[0].epoch,width:1920,height:1080,...m}))};}};}
async function until(fn){for(let i=0;i<80;i++){if(await fn())return;await sleep(10);}throw Error('Test timed out');}
const program=revision=>({revision,scene:null,mode:'show',startedAt:Date.now(),variables:{score:0}});

test('output formats are bounded and do not accept arbitrary settings',()=>{assert.deepEqual(outputConfig({unused:'x'}),{width:1920,height:1080,fps:50,port:17810,background:'transparent'});for(const value of [{port:80},{fps:120},{width:100},{background:'url(file://x)'}])assert.throws(()=>outputConfig(value));});
test('browser output serves only capability protected files and refuses command/API requests',async t=>{const {host,p}=await fixture(t);assert.equal((await fetch(host.url)).status,200);assert.equal((await fetch('http://127.0.0.1:'+p+'/api/projects')).status,404);assert.equal((await fetch(host.url+'private.txt')).status,404);assert.equal((await fetch(host.url,{method:'POST',body:'TAKE'})).status,405);assert.equal((await fetch(host.url,{headers:{origin:'https://evil.example'}})).status,403);assert.equal((await new Promise((resolve,reject)=>http.get(host.url,{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject))),403);assert.equal((await fetch(host.url+'%2e%2e/main.cjs')).status,404);assert.equal((await fetch(host.url+'media/secret')).status,404);assert.equal(host.status().ready,false);await assert.rejects(host.publish(program('r1')),/offline/);});
test('only the connected receiver and exact revision acknowledge a TAKE; output media are bounded',async t=>{const f=await fixture(t),r=await f.receiver();r.send({type:'ready'});await until(()=>f.host.status().ready);const p=f.host.publish(program('one'),[{id:'picture',type:'image/png',bytes:Buffer.from('image')}]);await until(()=>r.messages.some(m=>m.program?.revision==='one'));r.send({type:'rendered',revision:'old'});await sleep(20);assert.equal(f.host.status().revision,null);r.send({type:'rendered',revision:'one'});assert.equal((await p).revision,'one');assert.equal(await (await fetch(f.host.url+'media/picture')).text(),'image');assert.ok(f.host.status().ackMs>=0);await assert.rejects(f.host.publish(program('two'),[{id:'../oops',type:'text/html',bytes:Buffer.from('no')}]),/Invalid output image/);});
test('duplicate receivers cannot steal output acknowledgement',async t=>{const f=await fixture(t),r=await f.receiver();r.send({type:'ready'});await until(()=>f.host.status().ready);const second=new WebSocket(f.host.url.replace('http:','ws:')+'events',{origin:'http://127.0.0.1:'+f.p});const code=await new Promise((resolve,reject)=>{second.on('close',resolve);second.on('error',reject);});assert.equal(code,4009);assert.equal(f.host.status().peers,1);});
test('a receiver with the wrong viewport cannot become ready or acknowledge a command',async t=>{const f=await fixture(t),r=await f.receiver();r.send({type:'ready',width:800,height:600});await until(()=>f.host.status().error);assert.equal(f.host.status().ready,false);await assert.rejects(f.host.publish(program('wrong-size')),/offline/);r.send({type:'ready'});await until(()=>f.host.status().ready);assert.equal(f.host.status().error,null);});
test('timeout and receiver failure are unconfirmed and never resend commands',async t=>{const f=await fixture(t,{ackTimeout:60}),r=await f.receiver();r.send({type:'ready'});await until(()=>f.host.status().ready);await assert.rejects(f.host.publish(program('slow')),/timed out/);const p=f.host.publish(program('bad'));await until(()=>r.messages.some(m=>m.program?.revision==='bad'));r.send({type:'failed',revision:'bad'});await assert.rejects(p,/images\/fonts/);await sleep(80);assert.equal(r.messages.filter(m=>m.program?.revision==='slow').length,1);assert.equal(r.messages.filter(m=>m.program?.revision==='bad').length,1);});
test('disconnect rejects pending TAKE; reconnection is a snapshot with the original animation start',async t=>{const f=await fixture(t),r=await f.receiver();r.send({type:'ready'});await until(()=>f.host.status().ready);const value=program('lost'),p=f.host.publish(value);await until(()=>r.messages.some(m=>m.program));r.ws.close();await assert.rejects(p,/disconnected/);const next=await f.receiver();assert.equal(next.messages[0].program.startedAt,value.startedAt);assert.equal(next.messages[0].program.revision,'lost');next.send({type:'rendered',revision:'lost'});await sleep(20);assert.equal(f.host.status().revision,null);});
test('live variable snapshots keep the TAKE revision and ignore unrelated program revisions',async t=>{const f=await fixture(t),r=await f.receiver();r.send({type:'ready'});await until(()=>f.host.status().ready);const p=f.host.publish(program('a'));await until(()=>r.messages.some(m=>m.program));r.send({type:'rendered',revision:'a'});await p;f.host.update({...program('a'),variables:{score:2}});f.host.update(program('b'));await until(()=>r.messages.some(m=>m.program?.variables.score===2));assert.equal(r.messages.at(-1).program.revision,'a');});
test('telemetry rejects invalid counters and frame meter measures callback gaps separately from updates',async t=>{const f=await fixture(t),r=await f.receiver();r.send({type:'ready'});await until(()=>f.host.status().ready);r.send({type:'telemetry',value:{callbacks:-1}});await sleep(10);assert.equal(f.host.status().telemetry,null);const meter=frameMeter(50,0);for(const n of [0,20,40,100])meter.tick(n);const value=meter.snapshot(100);assert.equal(value.lateIntervals,2);assert.equal(value.maxIntervalMs,60);assert.equal(value.renderUpdates,4);r.send({type:'telemetry',value});await until(()=>f.host.status().telemetry);assert.equal(f.host.status().telemetry.lateIntervals,2);});
test('a new host starts empty and with a different epoch',async t=>{const a=await fixture(t),b=await fixture(t),r=await b.receiver();assert.notEqual(a.host.status().epoch,b.host.status().epoch);assert.equal(r.messages[0].program,null);});
test('OBS authentication, source settings, rejection and no automatic retry',async t=>{
 const p=await port(),server=new WebSocketServer({port:p,host:'127.0.0.1'}),requests=[];t.after(()=>server.close());
 server.on('connection',ws=>{ws.send(JSON.stringify({op:0,d:{rpcVersion:1,authentication:{salt:'salt',challenge:'challenge'}}}));ws.on('message',bytes=>{const m=JSON.parse(bytes);if(m.op===1){assert.equal(m.d.authentication,obsAuthentication('secret','salt','challenge'));ws.send(JSON.stringify({op:2,d:{negotiatedRpcVersion:1}}));}else if(m.op===6){requests.push(m.d);ws.send(JSON.stringify({op:7,d:{requestId:m.d.requestId,requestStatus:{result:m.d.requestType!=='Fail',comment:'Denied'},responseData:m.d.requestType==='GetInputKindList'?{inputKinds:['browser_source']}:m.d.requestType==='CreateInput'?{sceneItemId:8}:{}}}));}});});
 const c=await connectObs({port:p,password:'secret'});t.after(()=>c.close());assert.equal((await c.addSource({sceneName:'QA',inputName:'CG',url:'http://127.0.0.1:17810/live/'+'a'.repeat(64)+'/',config:outputConfig()})).sceneItemId,8);const request=requests.find(r=>r.requestType==='CreateInput');assert.equal(request.requestData.sceneItemEnabled,false);assert.equal(request.requestData.inputSettings.fps_custom,true);assert.equal(request.requestData.inputSettings.shutdown,false);assert.equal(request.requestData.inputSettings.restart_when_active,false);await assert.rejects(c.request('Fail'),/Denied/);assert.equal(requests.filter(r=>r.requestType==='Fail').length,1);assert.ok(!requests.some(r=>/StartStream|StartRecord|SetCurrent/.test(r.requestType)));c.close();
});
