import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,readdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {loadOutputKey} from '../desktop/output-key.cjs';
function fixture(t){const directory=mkdtempSync(join(tmpdir(),'bc-output-key-'));t.after(()=>rmSync(directory,{recursive:true,force:true}));return{directory,protect:s=>Buffer.from('test-protected:'+s),unprotect:b=>{const s=b.toString();if(!s.startsWith('test-protected:'))throw Error('Unreadable ciphertext');return s.slice(15);}};}
test('output key is protected, stable across starts and never rewritten when readable',t=>{const f=fixture(t),a=loadOutputKey(f),file=join(f.directory,'browser-output-key.bin'),bytes=readFileSync(file);assert.match(a.secret,/^[a-f0-9]{64}$/);assert.equal(a.recovered,false);assert.notDeepEqual(bytes,Buffer.from(a.secret));assert.deepEqual(loadOutputKey({...f,protect:()=>{throw Error('Must not rewrite');}}),a);assert.deepEqual(readFileSync(file),bytes);});
test('unreadable output key is preserved and replaced without touching other secrets',t=>{const f=fixture(t),file=join(f.directory,'browser-output-key.bin'),damaged=Buffer.from('old Windows profile ciphertext');writeFileSync(file,damaged);writeFileSync(join(f.directory,'remembered-login.bin'),'keep account');const a=loadOutputKey(f);assert.equal(a.recovered,true);assert.match(a.secret,/^[a-f0-9]{64}$/);assert.equal(f.unprotect(readFileSync(file)),a.secret);const preserved=readdirSync(f.directory).filter(n=>n.includes('.unreadable-'));assert.equal(preserved.length,1);assert.deepEqual(readFileSync(join(f.directory,preserved[0])),damaged);assert.equal(readFileSync(join(f.directory,'remembered-login.bin'),'utf8'),'keep account');assert.equal(loadOutputKey(f).secret,a.secret);assert.equal(readdirSync(f.directory).some(n=>n.endsWith('.partial')),false);});
test('invalid decrypted values are never accepted as output capabilities',t=>{const f=fixture(t);writeFileSync(join(f.directory,'browser-output-key.bin'),f.protect(''));assert.equal(loadOutputKey(f).recovered,true);});
test('unavailable encryption or failed protection verification leaves old ciphertext intact',t=>{const f=fixture(t),file=join(f.directory,'browser-output-key.bin'),bytes=Buffer.from('unreadable');writeFileSync(file,bytes);for(const options of [{protect:()=>{throw Error('Windows unavailable');}},{unprotect:()=>{throw Error('Windows cannot decrypt');}}]){assert.throws(()=>loadOutputKey({...f,...options}),/existing key was kept/);assert.deepEqual(readFileSync(file),bytes);assert.deepEqual(readdirSync(f.directory),['browser-output-key.bin']);}});
test('first start fails closed if Windows protection is unavailable',t=>{const f=fixture(t);assert.throws(()=>loadOutputKey({...f,protect:()=>{throw Error('unavailable');}}),/Output was not started/);assert.deepEqual(readdirSync(f.directory),[]);});
