import {remapLayerLinks,removeLayerLinks} from './layer-links.ts';
import {layer,moveLayer,uid,sceneSchema,type Layer,type Scene} from './studio-model.ts';
export type Point={x:number;y:number};
export type CanvasView={scale:number;pan:Point};
export function zoomCanvasAt(view:CanvasView,point:Point,scale:number):CanvasView{
 scale=Math.max(.02,Math.min(16,scale));const ratio=scale/view.scale;
 return {scale,pan:{x:point.x-(point.x-view.pan.x)*ratio,y:point.y-(point.y-view.pan.y)*ratio}};
}
export function drawingBounds(a:Point,b:Point,square=false){let x=b.x-a.x,y=b.y-a.y;if(square){const n=Math.max(Math.abs(x),Math.abs(y));x=(x<0?-1:1)*n;y=(y<0?-1:1)*n;}return{x:Math.min(a.x,a.x+x),y:Math.min(a.y,a.y+y),width:Math.max(1,Math.abs(x)),height:Math.max(1,Math.abs(y))};}
export function drawnLayer(type:Layer['type'],a:Point,b:Point,square=false,color='#ff872e'):Layer{const bounds=drawingBounds(a,b,square);return layer(type,{...bounds,color,...(type==='text'?{text:'New text',fontSize:Math.max(12,Math.min(200,bounds.height*.8)),width:Math.max(200,bounds.width),height:Math.max(60,bounds.height)}:{}),...(type==='line'?{visual:{stroke:color,strokeWidth:6},rotation:Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI,x:a.x,y:a.y-3,width:Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),height:6,anchorX:0,anchorY:3}: {})});}
export function polygonLayer(points:Point[],color='#ff872e'):Layer{if(points.length<3)throw Error('Place at least three points to finish a polygon.');const x=Math.min(...points.map(p=>p.x)),y=Math.min(...points.map(p=>p.y)),width=Math.max(1,Math.max(...points.map(p=>p.x))-x),height=Math.max(1,Math.max(...points.map(p=>p.y))-y);return layer('path',{name:'Polygon',x,y,width,height,color,visual:{closed:true,points:points.map(p=>({x:(p.x-x)/width,y:(p.y-y)/height}))}});}
export function duplicateDesignLayers(scene:Scene,ids:string[]){
 const selected=scene.layers.filter(l=>ids.includes(l.id)&&!l.locked);if(scene.layers.length+selected.length>250)throw Error('A scene supports up to 250 layers.');const map=new Map(selected.map(l=>[l.id,uid()]));
 const copies=selected.map(l=>({...remapLayerLinks(moveLayer(structuredClone(l),l.x+20,l.y+20),map),id:map.get(l.id)!,name:(l.name+' copy').slice(0,200),graphicLink:undefined,layout:l.layout?{...l.layout,target:map.get(l.layout.target||'')||l.layout.target}:undefined,visual:l.visual?{...structuredClone(l.visual),clipLayer:map.get(l.visual.clipLayer||'')||l.visual.clipLayer}:undefined}));
 return {scene:{...scene,layers:scene.layers.flatMap(l=>[l,...copies.filter(c=>map.get(l.id)===c.id)])},selection:copies.map(l=>l.id)};
}
export function deleteDesignLayers(scene:Scene,ids:string[]){const remove=new Set(scene.layers.filter(l=>ids.includes(l.id)&&!l.locked).map(l=>l.id));return {...scene,layers:scene.layers.filter(l=>!remove.has(l.id)).map(l=>removeLayerLinks(l,remove))};}
export function groupDesignLayers(scene:Scene,ids:string[]){const selected=scene.layers.filter(l=>ids.includes(l.id));if(!selected.length)throw Error('Select layers to group.');if(selected.some(l=>l.locked))throw Error('Unlock the selected layers first.');if(new Set(selected.map(l=>l.groupId)).size!==1)throw Error('Group layers that share the same parent.');if((scene.groups?.length||0)>=250)throw Error('A scene supports up to 250 groups.');const set=new Set(ids);for(const l of scene.layers)for(const target of [l.layout?.target,l.visual?.clipLayer,l.matte?.layerId])if(target&&set.has(l.id)!==set.has(target))throw Error('Select linked layout, clipping and matte layers together before grouping.');const id=uid();return sceneSchema.parse({...scene,groups:[...(scene.groups||[]),{id,name:'New group',parentId:selected[0].groupId,opacity:1,visible:true}],layers:scene.layers.map(l=>set.has(l.id)?{...l,groupId:id}:l)});}
export function reorderDesignLayer(scene:Scene,id:string,targetId:string){const source=scene.layers.find(l=>l.id===id),target=scene.layers.find(l=>l.id===targetId);if(!source||!target||id===targetId)return scene;if(source.locked)throw Error('Unlock this layer before reordering.');if(source.groupId!==target.groupId)throw Error('Drag within the same group. Use the Group field to change membership.');const layers=scene.layers.filter(l=>l.id!==id),index=layers.findIndex(l=>l.id===targetId);layers.splice(index+1,0,source);return {...scene,layers};}
