import type {Layer,Scene,Project} from './studio-model.ts';
import {animationDescriptors,readAnimatedProperty,writeAnimatedProperty,type PropertyDescriptor} from './property-animation.ts';
type Expr={kind:'number';value:number}|{kind:'string';value:string}|{kind:'name';value:string}|{kind:'unary';op:string;a:Expr}|{kind:'binary';op:string;a:Expr;b:Expr}|{kind:'call';name:string;args:Expr[]};
const cache=new Map<string,Expr>();
const operators:Record<string,number>={'||':1,'&&':2,'==':3,'!=':3,'>':4,'<':4,'>=':4,'<=':4,'+':5,'-':5,'*':6,'/':6,'%':6};
export function parseFormula(source:string):Expr{if(cache.has(source))return cache.get(source)!;if(source.length>1000)throw Error('Formula is too long.');const tokens:string[]=[];let cursor=0;while(cursor<source.length){const text=source.slice(cursor),space=text.match(/^\s+/);if(space){cursor+=space[0].length;continue;}const match=text.match(/^(?:\d*\.\d+|\d+\.?\d*)(?:[eE][+-]?\d+)?|^"(?:[^"\\]|\\["\\])*"|^[a-zA-Z_][a-zA-Z_0-9]*|^(?:>=|<=|==|!=|&&|\|\||[+\-*/%(),!<>])/);if(!match)throw Error('Unsupported formula syntax at '+(cursor+1)+'.');tokens.push(match[0]);cursor+=match[0].length;if(tokens.length>250)throw Error('Formula is too complex.');}
 let i=0,depth=0;const take=()=>tokens[i++],expect=(s:string)=>{if(take()!==s)throw Error('Expected '+s+'.');};
 function parse(min=0):Expr{if(++depth>24)throw Error('Formula nesting exceeds 24 levels.');let token=take(),a:Expr;if(!token)throw Error('Formula is incomplete.');if(['-','+','!'].includes(token))a={kind:'unary',op:token,a:parse(7)};else if(token==='('){a=parse();expect(')');}else if(/^\d|^\./.test(token))a={kind:'number',value:Number(token)};else if(token.startsWith('"'))a={kind:'string',value:JSON.parse(token)};else if(/^[a-zA-Z_]/.test(token)){if(tokens[i]==='('){take();const args:Expr[]=[];if(tokens[i]!==')'){do{args.push(parse());if(tokens[i]!==',')break;take();}while(true);}expect(')');a={kind:'call',name:token,args};}else a={kind:'name',value:token};}else throw Error('Unexpected '+token+'.');while(operators[tokens[i]]!==undefined&&operators[tokens[i]]>=min){const op=take();a={kind:'binary',op,a,b:parse(operators[op]+1)};}depth--;return a;}
 const ast=parse();if(i!==tokens.length)throw Error('Unexpected formula input.');if(cache.size>512)cache.clear();cache.set(source,ast);return ast;
}
const callArgs:Record<string,number[]>={min:[2],max:[2],clamp:[3],lerp:[3],abs:[1],round:[1],floor:[1],ceil:[1],sin:[1],cos:[1],sqrt:[1],if:[3],var:[1],layer:[2]};
export function formulaReferences(source:string){const refs:{layerId:string;property:string}[]=[],variables:string[]=[];function visit(e:Expr){if(e.kind==='name'&&!['time','value','pi'].includes(e.value))throw Error('Unknown name '+e.value+'. Use var("name") for project data.');if(e.kind==='call'){if(!callArgs[e.name]?.includes(e.args.length))throw Error('Unknown function or wrong number of arguments: '+e.name);if(e.name==='var'||e.name==='layer'){if(e.args.some(a=>a.kind!=='string'))throw Error(e.name+' requires quoted names.');if(e.name==='var')variables.push((e.args[0] as {value:string}).value);else refs.push({layerId:(e.args[0] as {value:string}).value,property:(e.args[1] as {value:string}).value});}else e.args.forEach(visit);}else if(e.kind==='binary'){visit(e.a);visit(e.b);}else if(e.kind==='unary')visit(e.a);else if(e.kind==='string')throw Error('Quoted names belong inside var() or layer().');}visit(parseFormula(source));return{refs,variables};}
export function evaluateFormula(source:string,context:{time:number;value:number;variable:(name:string)=>unknown;layer:(id:string,property:string)=>number}):number{let steps=0;const numeric=(v:unknown)=>{if(typeof v==='boolean')return Number(v);if(typeof v!=='number'||!Number.isFinite(v))throw Error('Formula needs a finite numeric value.');return v;};function run(e:Expr):number{if(++steps>500)throw Error('Formula operation limit exceeded.');if(e.kind==='number')return e.value;if(e.kind==='name')return e.value==='time'?context.time:e.value==='value'?context.value:e.value==='pi'?Math.PI:numeric(undefined);if(e.kind==='unary'){const a=run(e.a);return e.op==='-'?-a:e.op==='!'?Number(!a):a;}if(e.kind==='binary'){const a=run(e.a);if(e.op==='&&'&&!a)return 0;if(e.op==='||'&&a)return 1;const b=run(e.b);switch(e.op){case'+':return a+b;case'-':return a-b;case'*':return a*b;case'/':if(b===0)throw Error('Division by zero.');return a/b;case'%':if(b===0)throw Error('Division by zero.');return a%b;case'>':return Number(a>b);case'<':return Number(a<b);case'>=':return Number(a>=b);case'<=':return Number(a<=b);case'==':return Number(a===b);case'!=':return Number(a!==b);case'&&':return Number(!!b);case'||':return Number(!!b);}}if(e.kind==='call'){if(e.name==='var')return numeric(context.variable((e.args[0] as {value:string}).value));if(e.name==='layer')return context.layer((e.args[0] as {value:string}).value,(e.args[1] as {value:string}).value);if(e.name==='if')return run(e.args[0])?run(e.args[1]):run(e.args[2]);const a=e.args.map(run);switch(e.name){case'min':return Math.min(...a);case'max':return Math.max(...a);case'clamp':return Math.min(a[2],Math.max(a[1],a[0]));case'lerp':return a[0]+(a[1]-a[0])*a[2];case'abs':return Math.abs(a[0]);case'round':return Math.round(a[0]);case'floor':return Math.floor(a[0]);case'ceil':return Math.ceil(a[0]);case'sin':return Math.sin(a[0]);case'cos':return Math.cos(a[0]);case'sqrt':return Math.sqrt(a[0]);}}throw Error('Unsupported formula.');}formulaReferences(source);return numeric(run(parseFormula(source)));}
export function formulaDescriptors(l:Layer):PropertyDescriptor[]{return [...(['x','y','width','height','rotation','opacity','scaleX','scaleY','anchorX','anchorY'] as const).map(key=>({id:key,label:key,kind:'number' as const,path:[key],fallback:l[key]??(key.startsWith('scale')?1:key==='anchorX'?l.width/2:key==='anchorY'?l.height/2:0),min:key==='width'||key==='height'?.001:key==='opacity'?0:-20000,max:key==='opacity'?1:20000})),...animationDescriptors(l).filter(d=>d.kind==='number')];}
export function validateFormulas(scene:Scene,variables?:Project['variables']){const links=new Map<string,string[]>();for(const l of scene.layers){const seen=new Set<string>();for(const f of l.formulas||[]){if(seen.has(f.property))throw Error('Only one formula may control a property.');seen.add(f.property);if(!formulaDescriptors(l).some(d=>d.id===f.property))throw Error('Formula target is missing: '+f.property);const {refs,variables:names}=formulaReferences(f.expression);for(const name of names)if(variables&&(!Object.hasOwn(variables,name)||!['number','boolean'].includes(typeof variables[name])))throw Error('Formula variable must be numeric or Boolean: '+name);for(const ref of refs){const target=scene.layers.find(v=>v.id===ref.layerId);if(!target||!formulaDescriptors(target).some(d=>d.id===ref.property))throw Error('Formula links to a missing layer/property.');}if(f.enabled)links.set(l.id+'\0'+f.property,refs.map(r=>r.layerId+'\0'+r.property));}}
 const done=new Set<string>(),visiting=new Set<string>();function check(id:string,depth=0){if(done.has(id))return;if(visiting.has(id))throw Error('Property links form a cycle.');if(depth>32)throw Error('Property links exceed 32 levels.');visiting.add(id);for(const ref of links.get(id)||[])check(ref,depth+1);visiting.delete(id);done.add(id);}for(const id of links.keys())check(id);
}
/** Input layers have already been evaluated at the playhead. Formula failures retain that value. */
export function resolveFormulas(scene:Scene,time:number,variables:Project['variables']):{scene:Scene;errors:string[]}{const layers=new Map(scene.layers.map(l=>[l.id,l])),resolved=new Map<string,number>(),visiting=new Set<string>(),errors:string[]=[];
 function value(id:string,property:string,depth=0):number{const key=id+'\0'+property;if(resolved.has(key))return resolved.get(key)!;const l=layers.get(id),d=l&&formulaDescriptors(l).find(d=>d.id===property);if(!l||!d)throw Error('Linked property is unavailable.');if(depth>32||visiting.has(key))throw Error('Property link cycle.');const base=Number(readAnimatedProperty(l,d)),f=l.formulas?.find(f=>f.enabled&&f.property===property);if(!f)return base;visiting.add(key);let result=base;try{result=evaluateFormula(f.expression,{time,value:base,variable:name=>variables[name],layer:(id,p)=>value(id,p,depth+1)});result=Math.max(d.min??-1e7,Math.min(d.max??1e7,result));}catch(e){errors.push(l.name+' · '+d.label+': '+(e as Error).message);}visiting.delete(key);resolved.set(key,result);return result;}
 return{errors,scene:{...scene,layers:scene.layers.map(l=>{let out=l;for(const f of l.formulas||[])if(f.enabled){const d=formulaDescriptors(l).find(d=>d.id===f.property);if(d)out=writeAnimatedProperty(out,d,value(l.id,f.property));}return out;})}};
}
