import type {Layer} from './studio-model.ts';
import type {MotionKey} from './motion-schema.ts';
import {bezierProgress} from './creative-schema.ts';
export type PropertyDescriptor={id:string;label:string;kind:'number'|'color';path:(string|number)[];fallback:number|string;min?:number;max?:number};
export function animationDescriptors(l:Layer):PropertyDescriptor[]{
 const d:PropertyDescriptor[]=[];
 const add=(id:string,label:string,fallback:number|string,min?:number,max?:number,path:(string|number)[]=id.split('.'))=>d.push({id,label,path,fallback,kind:typeof fallback==='string'?'color':'number',min,max});
 add('color','Fill color','#ffffff');add('radius','Corner radius',0,0,1000);if(['text','ticker','countdown'].includes(l.type)){add('fontSize','Font size',58,1,2000);add('visual.letterSpacing','Letter spacing',0,-20,100);add('visual.lineHeight','Line height',1.18,.5,3);}
 add('visual.gradientColor','Gradient second color','#233b55');add('visual.gradientAngle','Gradient angle',0,-360,360);add('visual.stroke','Stroke color','#ffffff');add('visual.strokeWidth','Stroke width',0,0,100);
 for(const [key,label,fallback,min,max] of [['blur','Blur',0,0,50],['glow','Glow',0,0,100],['shadowX','Shadow X',0,-200,200],['shadowY','Shadow Y',10,-200,200],['shadowBlur','Shadow blur',15,0,100]] as const)add('visual.'+key,label,fallback,min,max);
 add('visual.shadowColor','Shadow color','#000000');add('visual.glowColor','Glow color','#ffffff');
 if(l.type==='image'){add('visual.cropX','Crop X',50,0,100);add('visual.cropY','Crop Y',50,0,100);add('visual.cropZoom','Crop zoom',1,1,10);}
 l.visual?.gradientStops?.forEach((s,i)=>{add(`visual.gradientStops.${i}.color`,`Gradient stop ${i+1} color`,s.color,undefined,undefined,['visual','gradientStops',i,'color']);add(`visual.gradientStops.${i}.offset`,`Gradient stop ${i+1} position`,s.offset,0,1,['visual','gradientStops',i,'offset']);});
 l.effects?.forEach((e,i)=>{for(const k of ['amount','x','y','color'] as const){if(['x','y'].includes(k)&&e.type!=='shadow'||k==='color'&&!['shadow','outline'].includes(e.type))continue;add(`effect.${e.id}.${k}`,`${e.type} ${i+1} · ${k}`,k==='color'?'#000000':k==='amount'?e.amount:8,k==='amount'?(e.type==='hue'?-360:0):-200,k==='amount'?500:200,['effects',i,k]);}});
 const masks=[...(l.visual?.layerMask?[{id:'legacy',mask:l.visual.layerMask,path:['visual','layerMask'] as (string|number)[],label:'Layer mask'}]:[]),...(l.masks||[]).map((m,i)=>({id:m.id,mask:m,path:['masks',i] as (string|number)[],label:m.name||`Mask ${i+1}`}))];
 for(const {id,mask,path,label} of masks){for(const key of ['x','y','width','height','density','feather'] as const)add(`mask.${id}.${key}`,`${label} · ${key}`,mask[key],key==='width'||key==='height'?.0001:0,key==='feather'?100:1,[...path,key]);mask.points?.forEach((p,i)=>{for(const key of ['x','y'] as const)add(`mask.${id}.point.${i}.${key}`,`${label} point ${i+1} ${key}`,p[key],0,1,[...path,'points',i,key]);});}
 return d;
}
export function readAnimatedProperty(l:Layer,d:PropertyDescriptor):number|string{let v:unknown=l;for(const part of d.path)v=(v as Record<string,unknown>|undefined)?.[part];return typeof v==='number'||typeof v==='string'?v:d.fallback;}
export function normalizeAnimatedValue(d:PropertyDescriptor,value:unknown):number|string{if(d.kind==='color'){if(typeof value!=='string'||!/^#[\da-f]{6}$/i.test(value))throw Error('Use a six-digit hexadecimal color.');return value.toLowerCase();}if(typeof value!=='number'||!Number.isFinite(value))throw Error('Enter a finite number.');return Math.max(d.min??-1e7,Math.min(d.max??1e7,value));}
export function writeAnimatedProperty(l:Layer,d:PropertyDescriptor,value:unknown):Layer{const out={...l} as unknown as Record<string,unknown>;let target=out,source=l as unknown as Record<string,unknown>;for(const part of d.path.slice(0,-1)){const old=source?.[part],copy=Array.isArray(old)?[...old]:{...(old as object||{})};target[part]=copy;target=copy as unknown as Record<string,unknown>;source=old as Record<string,unknown>;}target[d.path.at(-1)!]=normalizeAnimatedValue(d,value);return out as unknown as Layer;}
export function interpolateProperty(keys:MotionKey[],time:number,fallback:number|string):number|string{if(!keys.length)return fallback;const sorted=[...keys].sort((a,b)=>a.time-b.time);if(time<=sorted[0].time)return sorted[0].value;for(let i=1;i<sorted.length;i++){const a=sorted[i-1],b=sorted[i];if(time>b.time)continue;if(time===b.time)return b.value;let t=(time-a.time)/Math.max(.000001,b.time-a.time);if(a.ease==='step')t=0;else if(a.ease==='smooth')t=1-(1-t)**3;else if(a.ease==='bezier')t=bezierProgress(t,a.curve||[.25,.1,.25,1]);if(typeof a.value==='number'&&typeof b.value==='number')return a.value+(b.value-a.value)*t;const rgb=(s:string)=>[1,3,5].map(k=>parseInt(s.slice(k,k+2),16));if(typeof a.value==='string'&&typeof b.value==='string')return '#'+rgb(a.value).map((v,k)=>Math.round(Math.max(0,Math.min(255,v+(rgb(b.value as string)[k]-v)*t))).toString(16).padStart(2,'0')).join('');return a.value;}return sorted.at(-1)!.value;}
export function evaluatePropertyTracks(l:Layer,time:number):Layer{if(!l.propertyTracks?.length)return l;let out=l;const descriptors=animationDescriptors(l);for(const track of l.propertyTracks){const d=descriptors.find(v=>v.id===track.property);if(d)out=writeAnimatedProperty(out,d,interpolateProperty(track.keys,time,readAnimatedProperty(l,d)));}return out;}
export function setPropertyKey(l:Layer,property:string,time:number,value:unknown,force=true):Layer{if(l.locked)throw Error('Unlock the layer first.');const d=animationDescriptors(l).find(d=>d.id===property);if(!d)throw Error('This property no longer exists.');const tracks=l.propertyTracks||[],old=tracks.find(t=>t.property===property);value=normalizeAnimatedValue(d,value);if(!force&&!old?.keys.length)return writeAnimatedProperty(l,d,value);const existing=old?.keys.find(k=>Math.abs(k.time-time)<1e-6),key:MotionKey={...existing,time:Math.round(Math.max(0,Math.min(600,time))*1e6)/1e6,value:value as number|string,ease:existing?.ease||'linear'},keys=[...(old?.keys||[]).filter(k=>Math.abs(k.time-time)>=1e-6),key].sort((a,b)=>a.time-b.time);if(keys.length>1000)throw Error('A track supports 1,000 keys.');return {...l,propertyTracks:old?tracks.map(t=>t===old?{...t,keys}:t):[...tracks,{property,keys}]};}
export function validatePropertyTracks(l:Layer){const descriptors=animationDescriptors(l),seen=new Set<string>();for(const track of l.propertyTracks||[]){if(seen.has(track.property))throw Error('Duplicate animated property.');seen.add(track.property);const d=descriptors.find(d=>d.id===track.property);if(!d)throw Error('Animation refers to a missing property: '+track.property);const times=new Set<number>();for(const k of track.keys){if(times.has(k.time))throw Error('Duplicate property key time.');times.add(k.time);if(normalizeAnimatedValue(d,k.value)!==k.value&&d.kind==='number')throw Error('Animated property value is outside its range.');}}}
