import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export function db(){if(!env.DB)throw new Error('Project storage is temporarily unavailable.');return env.DB;}
export function bucket(){if(!env.BUCKET)throw new Error('Image storage is temporarily unavailable.');return env.BUCKET;}
export class HttpError extends Error{constructor(message:string,public status=400){super(message);}}
export async function owner(req?:Request){const user=await getChatGPTUser();if(!user)throw new HttpError('Sign in to save projects and use live output.',401);if(req&&!['GET','HEAD'].includes(req.method)){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new HttpError('Request origin is not allowed.',403);}return user.userId;}
export async function body(req:Request,max=1600000){if(Number(req.headers.get('content-length')||0)>max)throw new HttpError('Request is too large.',413);const reader=req.body?.getReader();if(!reader)throw new HttpError('Request body is missing.');let bytes=0,text='';const decoder=new TextDecoder();while(true){const {value,done}=await reader.read();if(done)break;bytes+=value.length;if(bytes>max){await reader.cancel();throw new HttpError('Request is too large.',413);}text+=decoder.decode(value,{stream:true});}text+=decoder.decode();try{return JSON.parse(text);}catch{throw new HttpError('Invalid JSON.');}}
export function json(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'no-store'}});}
export async function handled(fn:()=>Promise<Response>){try{return await fn();}catch(error){if(error instanceof HttpError)return json({error:error.message},error.status);if(error&&typeof error==='object'&&'issues' in error)return json({error:'Some project fields are invalid. Check the imported project or edited values.'},400);console.error('Studio request failed',error instanceof Error?error.message:'unknown');return json({error:error instanceof Error?error.message:'The request failed. Please retry.'},500);}}
