import {properties,type Layer,type Scene,type Keyframe} from './studio-model.ts';
import {roundKeyTime,type TimelineKey,resolveTimelineKeys,deleteTimelineKeys} from './timeline-tools.ts';
export function clipRange(l:Layer,duration:number){return{start:l.inPoint??0,end:l.outPoint??duration};}
function mapTimes(l:Layer,fn:(t:number)=>number,factor=1):Layer{const keys={...l.keys};for(const p of properties)if(keys[p])keys[p]=keys[p]!.map(k=>({...k,time:fn(k.time)}));return {...l,keys,propertyTracks:l.propertyTracks?.map(t=>({...t,keys:t.keys.map(k=>({...k,time:fn(k.time)}))})),motionPath:l.motionPath?{...l.motionPath,start:fn(l.motionPath.start),end:fn(l.motionPath.end)}:undefined,textAnimation:l.textAnimation?{...l.textAnimation,start:fn(l.textAnimation.start),duration:l.textAnimation.duration*factor,stagger:l.textAnimation.stagger*factor}:undefined,composition:l.composition?{...l.composition,offset:fn(l.composition.offset),speed:l.composition.speed/factor}:undefined};}
function checkTimes(l:Layer){const times=[...Object.values(l.keys).flatMap(k=>k?.map(v=>v.time)||[]),...(l.propertyTracks||[]).flatMap(t=>t.keys.map(k=>k.time)),...(l.motionPath?[l.motionPath.start,l.motionPath.end]:[]),...(l.textAnimation?[l.textAnimation.start]:[])];if(times.some(t=>t<0||t>600))throw Error('This move puts animation outside 0–600 seconds.');if(l.textAnimation&&(l.textAnimation.duration>600||l.textAnimation.stagger>10)||l.composition&&(l.composition.speed<.01||l.composition.speed>20||Math.abs(l.composition.offset)>600))throw Error('The stretched timing exceeds supported limits.');}
export function editClip(scene:Scene,id:string,mode:'move'|'in'|'out'|'stretch'|'slip',amount:number):Scene{const l=scene.layers.find(l=>l.id===id);if(!l||l.locked)throw Error('Choose an unlocked layer.');if(!Number.isFinite(amount))throw Error('Enter a finite time.');const {start,end}=clipRange(l,scene.duration),frame=1/(scene.frameRate||60);let next=l;
 if(mode==='in'){const value=roundKeyTime(Math.max(0,Math.min(end-frame,amount)));next={...l,inPoint:value,outPoint:end};}
 if(mode==='out'){next={...l,inPoint:start,outPoint:roundKeyTime(Math.max(start+frame,Math.min(600,amount)))};}
 if(mode==='move'||mode==='slip'){const delta=mode==='move'?Math.max(-start,Math.min(600-end,amount)):amount;next=mapTimes(l,t=>roundKeyTime(t+delta));if(mode==='move')next={...next,inPoint:roundKeyTime(start+delta),outPoint:roundKeyTime(end+delta)};checkTimes(next);}
 if(mode==='stretch'){const newEnd=Math.max(start+frame,Math.min(600,amount)),factor=(newEnd-start)/Math.max(frame,end-start);next={...mapTimes(l,t=>roundKeyTime(start+(t-start)*factor),factor),inPoint:start,outPoint:roundKeyTime(newEnd)};checkTimes(next);}
 return {...scene,layers:scene.layers.map(v=>v.id===id?next:v)};
}
export function sceneDuration(scene:Scene,duration:number):Scene{if(!Number.isFinite(duration)||duration<.1||duration>600)throw Error('Graphic duration must be 0.1–600 seconds.');const area=scene.workArea;return{...scene,duration,cues:scene.cues?.filter(c=>c.start<duration).map(c=>({...c,end:Math.min(c.end,duration)})),workArea:area?{...area,start:Math.min(area.start,duration-1/(scene.frameRate||60)),end:Math.min(area.end,duration)}:undefined};}
export function retimeSelectedKeys(scene:Scene,refs:TimelineKey[],mode:'reverse'|'stretch',factor=1):Scene{const keys=resolveTimelineKeys(scene,refs);if(keys.length<2)throw Error('Select at least two keys.');if(keys.some(k=>scene.layers.find(l=>l.id===k.layerId)?.locked))throw Error('Unlock selected layers first.');if(!Number.isFinite(factor)||factor<=0)throw Error('Stretch must be greater than zero.');const min=Math.min(...keys.map(k=>k.time)),max=Math.max(...keys.map(k=>k.time));if(mode==='stretch'&&min+(max-min)*factor>600)throw Error('Stretched keys exceed 600 seconds.');let out=deleteTimelineKeys(scene,refs);const groups=new Map<string,typeof keys>();for(const k of keys){const id=k.layerId+'\0'+k.property;groups.set(id,[...groups.get(id)||[],k]);}for(const group of groups.values()){group.sort((a,b)=>a.time-b.time);for(let i=0;i<group.length;i++){const k=group[i],time=roundKeyTime(mode==='reverse'?min+max-k.time:min+(k.time-min)*factor),incoming=group[i-1]?.key;const frame:Keyframe={...k.key,time,...(mode==='reverse'&&incoming?{ease:incoming.ease,curve:incoming.curve?[1-incoming.curve[2],1-incoming.curve[3],1-incoming.curve[0],1-incoming.curve[1]] as Keyframe['curve']:undefined}:{})};out={...out,layers:out.layers.map(l=>l.id===k.layerId?{...l,keys:{...l.keys,[k.property]:[...(l.keys[k.property]||[]).filter(v=>Math.abs(v.time-time)>=1e-6),frame].sort((a,b)=>a.time-b.time)}}:l)};}}return out;}
