import type {Action,Project} from './studio-model.ts';
import {conditionMatches} from './action-logic.ts';
import {textValue,variableActionValue} from './studio-model.ts';
export function connectFlow(actions:Action[],from:string,port:'next'|'yes'|'no',to:string):Action[]{if(from===to)throw Error('A block cannot connect to itself.');const source=actions.find(a=>a.id===from);if(!source?.flow||to&&!actions.some(a=>a.id===to))throw Error('Choose existing blocks.');if(source.type==='decision'?port==='next':port!=='next')throw Error('Use the block’s available output port.');const next=actions.map(a=>a.id===from?{...a,flow:{...a.flow!,[port]:to||undefined}}:a);validateFlow(next,false);return next;}
export function validateFlow(actions:Action[],requireConnected=true){if(!actions.length)return;if(actions.some(a=>!a.flow))throw Error('Every visual block needs flow metadata.');const entry=actions.filter(a=>a.flow?.entry);if(entry.length!==1)throw Error('Choose exactly one Start block.');const byId=new Map(actions.map(a=>[a.id,a]));if(byId.size!==actions.length)throw Error('Duplicate logic blocks.');const done=new Set<string>(),visiting=new Set<string>();function walk(id:string){if(done.has(id))return;if(visiting.has(id))throw Error('Logic connections cannot form a cycle.');const a=byId.get(id);if(!a)throw Error('A logic connection points to a missing block.');visiting.add(id);if(a.type==='decision'&&!a.when)throw Error('Add a condition to the decision block.');const edges=a.type==='decision'?[a.flow!.yes,a.flow!.no]:[a.flow!.next];if(a.type==='decision'&&a.flow!.next||a.type!=='decision'&&(a.flow!.yes||a.flow!.no))throw Error('The block has an incompatible connection.');for(const edge of edges)if(edge)walk(edge);visiting.delete(id);done.add(id);}for(const a of actions)walk(a.id);if(requireConnected){const reached=new Set<string>();function collect(id:string){if(reached.has(id))return;reached.add(id);const a=byId.get(id)!;for(const next of a.type==='decision'?[a.flow!.yes,a.flow!.no]:[a.flow!.next])if(next)collect(next);}collect(entry[0].id);if(reached.size!==actions.length)throw Error('Connect or remove the disconnected blocks before applying this flow.');}}
export function makeVisualFlow(actions:Action[]):Action[]{if(actions.some(a=>a.flow))return structuredClone(actions);return actions.map((a,i)=>({...a,flow:{x:40+(i%3)*230,y:40+Math.floor(i/3)*145,entry:i===0,next:actions[i+1]?.id}}));}
export function removeFlowNode(actions:Action[],id:string){const remaining=actions.filter(a=>a.id!==id).map(a=>({...a,flow:{...a.flow!,next:a.flow?.next===id?undefined:a.flow?.next,yes:a.flow?.yes===id?undefined:a.flow?.yes,no:a.flow?.no===id?undefined:a.flow?.no}}));if(remaining.length&&!remaining.some(a=>a.flow.entry))remaining[0]={...remaining[0],flow:{...remaining[0].flow,entry:true}};return remaining;}
/** Local trace never calls feeds, writes variables or sends output. Stop when an external result is needed. */
export function traceFlow(actions:Action[],project:Project){validateFlow(actions);const variables={...project.variables},steps:string[]=[];let id=actions.find(a=>a.flow?.entry)?.id;for(let n=0;id&&n<200;n++){const a=actions.find(a=>a.id===id)!;if(a.type==='decision'){const yes=conditionMatches(a,variables);steps.push(`${a.id}: IF → ${yes?'true':'false'}`);id=yes?a.flow?.yes:a.flow?.no;continue;}if(conditionMatches(a,variables)){if(a.type==='set'||a.type==='increment')variables[a.target]=variableActionValue(variables,a.target,textValue(a.value,variables),a.type);steps.push(`${a.id}: ${a.type} ${a.target} ${a.value}`);if(['fetch','macro','branch','sport','clock','counter','select-row'].includes(a.type)){steps.push('Trace paused: this block requires a real action result. No action was executed.');break;}}else steps.push(`${a.id}: skipped by condition`);id=a.flow?.next;}return{steps,variables};}
