import {useEffect,useState} from 'react';
import {desktopBridge} from '../lib/desktop';
import {LocalSession,LocalUser,Permission,Role,permissionLabels,rolePermissions} from '../lib/permissions';
const auth=desktopBridge()!.auth;
export function AccountForm({setup=false,session,onSession,onClose}:{setup?:boolean;session?:LocalSession;onSession:(s:LocalSession)=>void;onClose?:()=>void}){
 const [username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[current,setCurrent]=useState(''),[remember,setRemember]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const changing=!!session;
 return <form className="account-card" onSubmit={async e=>{e.preventDefault();setError('');if((setup||changing)&&password!==confirm){setError('The new passwords do not match.');return;}setBusy(true);try{onSession(await auth<LocalSession>(changing?'changePassword':setup?'setup':'login',{username,displayName,password,currentPassword:current,remember}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
  <div className="account-brand"><span className="desktop-dot"/> BROADCAST CG <small>LOCAL WORKSTATION</small></div>
  <h1>{changing?'Change password':setup?'Set up your workstation':'Welcome back'}</h1>
  <p>{changing?(session.user.mustChangePassword?'Your administrator assigned a temporary password. Choose your own before opening a workspace.':'Changing your password signs out all other sessions and clears remembered sign-ins.'):setup?'Create the first local administrator. Your existing projects stay on this computer.':'Sign in to your local account to open your assigned workspaces.'}</p>
  <fieldset disabled={busy}>{!changing&&<label>Username<input autoFocus autoComplete="username" required minLength={3} maxLength={32} value={username} onChange={e=>setUsername(e.target.value)}/></label>}
   {setup&&<label>Display name<input autoComplete="name" maxLength={100} value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label>}
   {changing&&<label>Current or temporary password<input autoFocus type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/></label>}
   <label>{changing?'New password':'Password'}<input type="password" autoComplete={setup||changing?'new-password':'current-password'} required minLength={setup||changing?15:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>
   {(setup||changing)&&<><small>Use a passphrase of 15–128 characters.</small><label>Confirm new password<input type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>}
   {!changing&&<label className="desktop-check"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Remember me on this Windows account for 30 days</label>}
   <button className="desktop-primary" type="submit">{busy?'Please wait…':changing?'Change password':setup?'Create administrator':'Sign in'}</button>{onClose&&<button type="button" onClick={onClose}>{session?.user.mustChangePassword?'Sign out':'Cancel'}</button>}
  </fieldset>{error&&<p className="account-error" role="alert">{error}</p>}<small>{!changing&&!setup?'For a password reset, contact your local administrator. ':''}Accounts and projects are stored locally. No cloud account is required.</small>
 </form>;
}
type Catalog={permissions:Record<Permission,string>;roles:Record<Role,Permission[]>;workspaces:{id:string;name:string}[]};
type UserDraft={id?:string;username:string;displayName:string;role:Role;enabled:boolean;allWorkspaces:boolean;workspaceIds:string[];extraPermissions:Permission[];deniedPermissions:Permission[];password:string};
const freshUser=():UserDraft=>({username:'',displayName:'',role:'OPERATOR',enabled:true,allWorkspaces:false,workspaceIds:[],extraPermissions:[],deniedPermissions:[],password:''});
type SessionRow={id:string;username:string;workstation:string;created_at:number;last_seen:number;expires_at:number;idle_expires_at:number};
type AuditRow={id:number;time:number;action:string;target:string;status:string;username:string|null;workstation:string;project_id:string|null;previous_value:string|null;next_value:string|null};
export function Administration({session,onClose,startAudit=false}:{session:LocalSession;onClose:()=>void;startAudit?:boolean}){
 const canManage=session.user.permissions.includes('users.manage'),canAudit=session.user.permissions.includes('audit.view');
 const [tab,setTab]=useState(startAudit?'audit':'users'),[users,setUsers]=useState<LocalUser[]>([]),[catalog,setCatalog]=useState<Catalog|null>(null),[sessions,setSessions]=useState<SessionRow[]>([]),[audit,setAudit]=useState<AuditRow[]>([]),[draft,setDraft]=useState<UserDraft|null>(null),[reset,setReset]=useState<LocalUser|null>(null),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[filters,setFilters]=useState({username:'',action:'',workstation:'',projectId:'',from:'',to:''});
 async function refresh(){try{if(canManage){const [u,c,s]=await Promise.all([auth<LocalUser[]>('users'),auth<Catalog>('catalog'),auth<SessionRow[]>('sessions')]);setUsers(u);setCatalog(c);setSessions(s);}if(canAudit)setAudit(await auth<AuditRow[]>('audit',filters));}catch(e){setMessage((e as Error).message);}}
 useEffect(()=>{void refresh();},[]);
 async function perform(fn:()=>Promise<unknown>,success:string){setBusy(true);setMessage('');try{await fn();setMessage(success);await refresh();return true;}catch(e){setMessage((e as Error).message);return false;}finally{setBusy(false);}}
 const allowed=(p:Permission)=>!!draft&&(rolePermissions[draft.role].includes(p)||draft.extraPermissions.includes(p))&&!draft.deniedPermissions.includes(p);
 return <div className="desktop-modal-backdrop"><section className="desktop-settings account-admin" role="dialog" aria-modal="true" aria-label="Accounts and access"><header><div><small>LOCAL SECURITY</small><h1>Accounts & access</h1></div><button aria-label="Close accounts" onClick={onClose}>×</button></header>
  <nav className="account-tabs">{canManage&&<><button aria-pressed={tab==='users'} onClick={()=>setTab('users')}>Users</button><button aria-pressed={tab==='sessions'} onClick={()=>{setTab('sessions');void refresh();}}>Sessions</button></>}{canAudit&&<button aria-pressed={tab==='audit'} onClick={()=>{setTab('audit');void refresh();}}>Audit history</button>}</nav>
  {tab==='users'&&<><div className="account-toolbar"><p>Create accounts, choose roles and assign workspaces.</p><button className="desktop-primary" onClick={()=>{setDraft(freshUser());setMessage('');}}>Add user</button></div><table className="account-table"><thead><tr><th>User</th><th>Role</th><th>Workspaces</th><th>Status</th><th>Last sign-in</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.displayName}</strong><small>{u.username}{u.id===session.user.id?' · You':''}</small></td><td>{u.role}</td><td>{u.allWorkspaces?'All':u.workspaceIds.length+' assigned'}</td><td>{!u.enabled?'Disabled':u.mustChangePassword?'Temporary password':'Enabled'}</td><td>{u.lastLogin?new Date(u.lastLogin).toLocaleString():'Never'}</td><td><button onClick={()=>setDraft({...u,password:''})}>Edit access</button>{u.id!==session.user.id&&<button onClick={()=>{setReset(u);setPassword('');setConfirmation('');}}>Reset password</button>}</td></tr>)}</tbody></table>
   {draft&&<form className="account-editor" onSubmit={async e=>{e.preventDefault();if(await perform(()=>auth(draft.id?'updateUser':'createUser',draft),draft.id?'Access saved. Existing sessions for this user were revoked.':'User created. They must change their temporary password at first sign-in.'))setDraft(null);}}><h2>{draft.id?'Edit access':'New local user'}</h2><fieldset disabled={busy}><div className="desktop-settings-grid"><label>Username<input required minLength={3} maxLength={32} value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></label><label>Display name<input maxLength={100} value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></label><label>Role<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value as Role,extraPermissions:[],deniedPermissions:[]})}>{Object.keys(rolePermissions).map(r=><option key={r}>{r}</option>)}</select></label>{!draft.id&&<label>Temporary password<input type="password" autoComplete="new-password" required minLength={15} maxLength={128} value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/><small>15–128 characters. The user must change it.</small></label>}</div>
    <label className="desktop-check"><input type="checkbox" disabled={draft.id===session.user.id} checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Account enabled</label>
    <h3>Workspace access</h3><label className="desktop-check"><input type="checkbox" checked={draft.role==='ADMIN'||draft.allWorkspaces} disabled={draft.role==='ADMIN'} onChange={e=>setDraft({...draft,allWorkspaces:e.target.checked})}/>All current and future workspaces</label>
    {draft.role!=='ADMIN'&&!draft.allWorkspaces&&<div className="account-options">{catalog?.workspaces.map(w=><label className="desktop-check" key={w.id}><input type="checkbox" checked={draft.workspaceIds.includes(w.id)} onChange={e=>setDraft({...draft,workspaceIds:e.target.checked?[...draft.workspaceIds,w.id]:draft.workspaceIds.filter(id=>id!==w.id)})}/>{w.name}</label>)}{!catalog?.workspaces.length&&<p>Save a project in the studio first, then assign it here.</p>}</div>}
    <details><summary>Individual permissions</summary><p>These override the role defaults. User administration grants authority to manage all local accounts.</p><div className="account-options">{Object.entries(permissionLabels).map(([key,label])=>{const p=key as Permission;return <label key={p} className="desktop-check"><input type="checkbox" disabled={draft.role==='ADMIN'||p==='templates.publish'} checked={allowed(p)} onChange={e=>{const base=rolePermissions[draft.role].includes(p);setDraft({...draft,extraPermissions:[...draft.extraPermissions.filter(v=>v!==p),...(!base&&e.target.checked?[p]:[])],deniedPermissions:[...draft.deniedPermissions.filter(v=>v!==p),...(base&&!e.target.checked?[p]:[])]});}}/>{label}</label>;})}</div></details>
    {draft.id&&<p>Saving access changes signs this user out immediately, including remembered sessions.</p>}<button type="submit" className="desktop-primary">{busy?'Saving…':'Save user'}</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></fieldset></form>}
   {reset&&<form className="account-editor" onSubmit={async e=>{e.preventDefault();if(password!==confirmation){setMessage('Passwords do not match.');return;}if(await perform(()=>auth('resetPassword',{id:reset.id,password}),'Password reset and sessions revoked.'))setReset(null);}}><h2>Reset password for {reset.username}</h2><p>This signs the user out and requires a password change at their next sign-in.</p><fieldset disabled={busy}><label>Temporary password<input type="password" autoComplete="new-password" minLength={15} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm password<input type="password" autoComplete="new-password" required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className="desktop-primary">Reset password</button><button type="button" onClick={()=>setReset(null)}>Cancel</button></fieldset></form>}
  </>}
  {tab==='sessions'&&<><p>Sessions expire after 30 minutes of inactivity or 12 hours. Revocation also removes the associated remembered sign-in.</p><button disabled={busy} onClick={()=>void refresh()}>Refresh sessions</button><table className="account-table"><thead><tr><th>User</th><th>Workstation</th><th>Last activity</th><th>Idle expiry</th><th>Action</th></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td>{s.username}{s.id===session.sessionId?' · Current':''}</td><td>{s.workstation}</td><td>{new Date(s.last_seen).toLocaleString()}</td><td>{new Date(s.idle_expires_at).toLocaleString()}</td><td><button disabled={busy} onClick={()=>void perform(()=>auth('revokeSession',s.id),'Session revoked.')}>Revoke session</button></td></tr>)}</tbody></table></>}
  {tab==='audit'&&<><p>Most recent 500 matching events. Times are shown in this computer’s timezone.</p><form className="account-filters" onSubmit={e=>{e.preventDefault();void perform(()=>auth<AuditRow[]>('audit',filters).then(setAudit),'History refreshed.');}}>{Object.entries(filters).map(([key,value])=><label key={key}>{({username:'Username',action:'Action (exact)',workstation:'Workstation',projectId:'Workspace ID',from:'From',to:'Until'} as Record<string,string>)[key]}<input type={key==='from'||key==='to'?'datetime-local':'text'} value={value} onChange={e=>setFilters({...filters,[key]:e.target.value})}/></label>)}<button disabled={busy}>Apply filters</button></form><table className="account-table"><thead><tr><th>When / user</th><th>Action / status</th><th>Workspace / target</th><th>Changes</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{new Date(a.time).toLocaleString()}<small>{a.username||'System'} · {a.workstation}</small></td><td>{a.action}<small>{a.status}</small></td><td>{a.project_id||'—'}<small>{a.target}</small></td><td>{(a.previous_value||a.next_value)&&<details><summary>View changes</summary><pre>Before: {a.previous_value||'—'}{'\n'}After: {a.next_value||'—'}</pre></details>}</td></tr>)}</tbody></table>{!audit.length&&<p>No matching events.</p>}</>}
  {message&&<p className="account-message" role="status">{message}</p>}
 </section></div>;
}
