import {useEffect,useState} from 'react';
import {desktopBridge} from '../lib/desktop';

type Format={source?:string;width:number;height:number;fps:number;port:number;background:string};
type NdiInfo={available:boolean;running:boolean;ready:boolean;error:string|null;source:string;runtime:string;replaced:number;lastAck:{revision:string;ms:number}|null;health:{frames:number;repeated:number;elapsedMs:number;connections:number;maxSendMs:number}|null};
type OutputInfo={keyRecovered?:boolean;ndi:NdiInfo;mode:string;running:boolean;starting:boolean;url:string|null;config:Format|null;obsConnected:boolean;status:{connected:boolean;ready:boolean;error?:string;ackMs:number|null;revision:string|null;uptimeMs:number;receivedAt:number|null;telemetry:null|{callbacks:number;lateIntervals:number;maxIntervalMs:number;meanIntervalMs:number;elapsedMs:number;renderUpdates:number}}};
type ObsInfo={version:string;scenes:{name:string}[];programScene:string;video:{baseWidth:number;baseHeight:number;fpsNumerator:number;fpsDenominator:number};stats:{activeFps:number;renderSkippedFrames:number;renderTotalFrames:number;outputSkippedFrames:number;outputTotalFrames:number;averageFrameRenderTime:number}};
const defaults:Format={width:1920,height:1080,fps:50,port:17810,background:'transparent'};
const bridge=desktopBridge()!;
export function BroadcastOutput({canConfigure,onClose}:{canConfigure:boolean;onClose:()=>void}){
 const [info,setInfo]=useState<OutputInfo|null>(null),[format,setFormat]=useState(defaults),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[obs,setObs]=useState<ObsInfo|null>(null),[port,setPort]=useState(4455),[password,setPassword]=useState(''),[scene,setScene]=useState(''),[source,setSource]=useState('BroadcastCG Program'),[enabled,setEnabled]=useState(false),[ndiName,setNdiName]=useState('BroadcastCG Program'),[engine,setEngine]=useState('browser');
 useEffect(()=>{let alive=true,first=true;const refresh=()=>bridge.broadcastOutput<OutputInfo>('status').then(v=>{if(!alive)return;setInfo(v);if(first){first=false;if(v.mode==='ndi'||v.config?.source)setEngine('ndi');if(v.config){setFormat(v.config);if(v.config.source)setNdiName(v.config.source);}}}).catch(e=>alive&&setMessage(e.message));void refresh();const timer=setInterval(refresh,1000);return()=>{alive=false;clearInterval(timer);};},[]);
 const run=async(action:string,data?:unknown)=>{setBusy(true);setMessage('');try{const result=await bridge.broadcastOutput(action,data);if(['start','ndiStart','stop','desktop'].includes(action))setInfo(result as OutputInfo);if(action==='copyUrl')setMessage('Output URL copied. Keep it private: it gives read access to the current graphic.');if(action==='obsConnect'||action==='obsStatus'){const v=result as ObsInfo;setObs(v);setScene(s=>s||v.scenes[0]?.name||'');setPassword('');}if(action==='obsAddSource')setMessage(enabled?'Source added to the selected OBS scene.':'Source added hidden. Enable its eye icon in OBS when ready.');if(action==='obsDisconnect')setObs(null);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 const t=info?.status.telemetry,rate=t&&t.elapsedMs>0?t.renderUpdates*1000/t.elapsedMs:null;
 return <div className="desktop-modal-backdrop"><section className="desktop-settings broadcast-settings" role="dialog" aria-modal="true" aria-label="Broadcast output"><header><div><small>OUTPUT ENGINE · LOCAL</small><h1>Broadcast output</h1></div><button aria-label="Close broadcast output" onClick={onClose}>×</button></header>
  <p>Send transparent graphics to OBS or directly over NDI on your local network. For a separate output PC, connect its BroadcastCG client to your production server and attach it in Connections.</p>
  <div className="output-summary"><strong data-ready={info?.mode==='ndi'?info.ndi.ready:!!info?.status.ready}>{info?.mode==='ndi'?(info.ndi.ready?'NDI SENDER READY':'NDI OUTPUT STOPPED'):info?.mode==='desktop'?'DESKTOP ENGINE':info?.status.ready?'BROWSER RECEIVER READY':info?.running?'WAITING FOR RECEIVER':'BROWSER OUTPUT STOPPED'}</strong><span>{info?.mode==='ndi'&&info.ndi.running?'Local network - NDI video with alpha':info?.running?'127.0.0.1 · read-only output':'Starts manually · no automatic TAKE replay'}</span></div>
  <label>Output adapter<select aria-label="Output adapter" disabled={!canConfigure||busy||info?.running} value={engine} onChange={e=>{setEngine(e.target.value);if(e.target.value==='ndi'&&format.width>1920)setFormat({...format,width:1920,height:1080});}}><option value="browser">OBS Browser Source</option><option value="ndi">Direct NDI output</option></select></label><div className="broadcast-columns"><section><h2>Output format</h2><fieldset disabled={!canConfigure||busy||info?.running}>{engine==='ndi'&&<label>NDI source name<input aria-label="NDI source name" maxLength={80} value={ndiName} onChange={e=>setNdiName(e.target.value)}/></label>}<div className="desktop-settings-grid"><label>Resolution<select aria-label="Output resolution" value={format.width} onChange={e=>{const width=Number(e.target.value);setFormat({...format,width,height:width*9/16});}}><option value={1280}>1280 × 720</option><option value={1920}>1920 × 1080</option>{engine==='browser'&&<option value={3840}>3840 × 2160</option>}</select></label><label>Target frame rate<select aria-label="Output frame rate" value={format.fps} onChange={e=>setFormat({...format,fps:Number(e.target.value)})}>{[25,30,50,60].map(n=><option key={n} value={n}>{n} fps</option>)}</select></label><label>Local port<input aria-label="Browser output port" type="number" min={1024} max={65535} value={format.port} onChange={e=>setFormat({...format,port:Number(e.target.value)})}/></label><label>Background<select value={format.background==='transparent'?'transparent':'color'} onChange={e=>setFormat({...format,background:e.target.value==='transparent'?'transparent':'#000000'})}><option value="transparent">Transparent (alpha)</option><option value="color">Solid color</option></select></label></div>{format.background!=='transparent'&&<label>Background color<input type="color" value={format.background} onChange={e=>setFormat({...format,background:e.target.value})}/></label>}</fieldset>
  <div className="network-actions"><button className="desktop-primary" disabled={!canConfigure||busy||info?.running||(engine==='ndi'&&!info?.ndi.available)} onClick={()=>void run(engine==='ndi'?'ndiStart':'start',{...format,source:ndiName})}>{engine==='ndi'?'Start NDI output':'Start browser output'}</button><button disabled={!canConfigure||busy||!info?.running} onClick={()=>void run('stop')}>Stop output</button><button disabled={!canConfigure||busy||info?.mode==='desktop'} onClick={()=>void run('desktop')}>Use desktop engine</button></div>
  {engine==='ndi'&&<><p>In your NDI receiver, select the computer/source name shown here, then use TAKE, Update and Hide as usual.</p>  <p className="output-note">{info?.ndi.available?'Installed NDI runtime detected.':'NDI runtime not found. Install the NDI 6 runtime and reopen this window.'} <button onClick={()=>void run('ndiWebsite')}>NDI information and downloads</button></p>
</>}
  {info?.url&&<><label>Browser Source URL<input className="output-url" aria-label="Browser Source URL" readOnly value={info.url}/></label><button onClick={()=>void run('copyUrl')}>Copy output URL</button></>}
  {engine==='browser'&&<>  <ol className="output-steps"><li>Start browser output.</li><li>In OBS, add a Browser Source using this URL, the resolution above and custom FPS. Leave shutdown and refresh on scene activation off.</li><li>Wait for Receiver ready, then use your normal TAKE, Update and Hide controls.</li></ol><p className="output-note">One receiving browser per URL. A second copy cannot confirm commands. The desktop output window can remain open as a monitor.</p>
</>}
  </section><section>{engine==='ndi'&&<><h2>NDI sender health</h2>  {info?.mode==='ndi'&&<><dl className="desktop-health"><dt>Source</dt><dd>{info.ndi.source||'Stopped'}</dd><dt>Connected receivers</dt><dd>{info.ndi.health?.connections??0}</dd><dt>Frames submitted</dt><dd>{info.ndi.health?.frames??0}</dd><dt>Average submission rate</dt><dd>{info.ndi.health?((info.ndi.health.frames*1000)/info.ndi.health.elapsedMs).toFixed(1)+' fps':'—'}</dd><dt>Last TAKE submission</dt><dd>{info.ndi.lastAck?info.ndi.lastAck.ms+' ms':'No submitted TAKE'}</dd><dt>Repeated frames</dt><dd>{info.ndi.health?.repeated??0}</dd><dt>Replaced queued paints</dt><dd>{info.ndi.replaced}</dd></dl>{info.ndi.error&&<p className="account-error" role="alert">{info.ndi.error}</p>}</>}
  <p className="output-note">NDI video only, with straight alpha. Static frames repeat at the selected rate. Submission confirms the local NDI API accepted the frame; it does not confirm a remote display. No audio, SDI, genlock or automatic failover. NDI is a registered trademark of Vizrt NDI AB.</p>
</>}{engine==='browser'&&<><h2>Receiver health</h2><dl className="desktop-health"><dt>Connection</dt><dd>{info?.status.connected?'Connected':'Offline'}</dd><dt>Last TAKE acknowledgement</dt><dd>{info?.status.ackMs!=null?info.status.ackMs+' ms':'No acknowledged TAKE'}</dd><dt>Average renderer updates</dt><dd>{rate!==null?rate.toFixed(1)+' / second':'Waiting for measurements'}</dd><dt>Late callback intervals</dt><dd>{t?.lateIntervals??'—'}</dd><dt>Longest callback interval</dt><dd>{t?t.maxIntervalMs.toFixed(1)+' ms':'—'}</dd><dt>Last telemetry</dt><dd>{info?.status.receivedAt?new Date(info.status.receivedAt).toLocaleTimeString():'—'}</dd></dl>
  {info?.status.error&&<p className="account-error" role="alert">{info.status.error}</p>}<p className="output-note">These measurements cover the receiving browser and command acknowledgement. They do not measure physical scanout or end-to-end video latency. NDI submission measurements are shown separately. No genlock or automatic failover.</p>
  <h2>OBS connection</h2><p>Optional: add the source and inspect OBS performance here. Enable <strong>Tools → WebSocket Server Settings</strong> in OBS first.</p><fieldset disabled={!canConfigure||busy}><div className="desktop-settings-grid"><label>OBS WebSocket port<input type="number" value={port} onChange={e=>setPort(Number(e.target.value))}/></label><label>OBS password<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)}/></label></div><div className="network-actions"><button onClick={()=>void run('obsConnect',{port,password})}>Connect to OBS</button>{obs&&<><button onClick={()=>void run('obsStatus')}>Refresh OBS metrics</button><button onClick={()=>void run('obsDisconnect')}>Disconnect OBS</button></>}</div></fieldset>
  {obs&&<><p>OBS {obs.version} · {obs.video.baseWidth} × {obs.video.baseHeight} · {obs.stats.activeFps.toFixed(1)} fps</p><dl className="desktop-health"><dt>Frames missed by rendering</dt><dd>{obs.stats.renderSkippedFrames} / {obs.stats.renderTotalFrames}</dd><dt>Frames skipped by encoding</dt><dd>{obs.stats.outputSkippedFrames} / {obs.stats.outputTotalFrames}</dd><dt>Average OBS render time</dt><dd>{obs.stats.averageFrameRenderTime.toFixed(2)} ms</dd></dl><fieldset disabled={!canConfigure||busy||!info?.running}><div className="desktop-settings-grid"><label>Destination scene<select value={scene} onChange={e=>setScene(e.target.value)}>{obs.scenes.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>New source name<input value={source} onChange={e=>setSource(e.target.value)}/></label></div><label className="desktop-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable the new source in this scene immediately</label><button onClick={()=>void run('obsAddSource',{sceneName:scene,inputName:source,enabled})}>Add Browser Source</button></fieldset></>}
  </>}</section></div>{info?.keyRecovered&&<p className="output-note" role="status">The saved output key was unreadable and has been replaced securely. If you use OBS Browser Source, copy the new output URL into OBS. NDI reconnects its internal renderer automatically.</p>}{message&&<p className="network-message" role="status">{message}</p>}
 </section></div>;
}
