import assert from 'node:assert/strict';
export async function commandSmoke({studio,js,api,reload,capture,checks,sleep,until,project}){
 const click=async(selector)=>{await js(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(120);};
 const button=async(text,scope='document')=>{await js(`[...${scope}.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)}).click()`);await sleep(120);};
 const input=async(selector,value)=>{await js(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));})()`);await sleep(100);};
 const tab=async text=>{await js(`[...document.querySelectorAll('[role=tab]')].find(b=>b.textContent.trim()===${JSON.stringify(text)}).dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}))`);await sleep(150);};
 async function choose(selector,label){await js(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.focus();el.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));})()`);await until(()=>js("document.querySelector('[role=option]')!==null"));await js(`[...document.querySelectorAll('[role=option]')].find(el=>el.textContent.trim()===${JSON.stringify(label)}||el.querySelector('.variable-option>span')?.textContent===${JSON.stringify(label)}).click()`);await sleep(150);}
 const state=async()=>(await api('/api/commands?projectId='+project.id)).value;
 const data=async()=>(await api('/api/projects/'+project.id)).value.project;
 await tab('Panels');await button('Macros');await button('New macro');await input('[aria-label="Macro name"]','QA score cue');await input('.macro-editor .action-item:nth-of-type(2) [aria-label="Action value"]','1000');
 await click('.macro-editor [aria-label="Add action"]');await choose('.macro-editor .action-item:nth-of-type(3) [aria-label="Action type"]','Change number (+ / −)');await choose('.macro-editor .action-item:nth-of-type(3) [aria-label="Variable"]','homeScore');await input('.macro-editor .action-item:nth-of-type(3) [aria-label="Action value"]','1');await button('Add condition',"document.querySelector('.macro-editor .action-item:nth-of-type(3)')");await choose('[aria-label="Condition variable"]','homeScore');await choose('[aria-label="Condition operator"]','Less than');await input('[aria-label="Condition value"]','10');
 await click('.macro-editor [aria-label="Add action"]');await choose('.macro-editor .action-item:nth-of-type(4) [aria-label="Action type"]','Stage graphic');await choose('.macro-editor .action-item:nth-of-type(4) [aria-label="Action graphic"]','Match score');
 await click('.macro-editor [aria-label="Add action"]');await choose('.macro-editor .action-item:nth-of-type(5) [aria-label="Action type"]','Take to Program');await capture('macros-editor.png');
 await button('Run QA score cue');await until(async()=>!!(await state()).active);assert.equal(await js("document.querySelector('.projectbar').inert"),true);
 await until(async()=>{const s=await state();return s.history[0]?.status==='succeeded';});await until(()=>js("document.querySelector('.command-monitor').textContent.includes('succeeded')"));assert.equal((await data()).variables.homeScore,2);assert.equal((await api('/api/program')).value.scene.id,'score');assert.equal((await api('/api/program')).value.acknowledged,true);
 const stored=(await data()).macros[0];assert.equal(stored.actions[1].when.rules[0].operator,'lt');assert.equal(typeof stored.actions[1].when.rules[0].value,'number');checks.push('native macro authoring, variable dropdown, typed numeric condition and acknowledged TAKE');
 await button('Execution history');await capture('commands-history.png');await click('[role=dialog] [data-slot=dialog-close]');
 await button('Macros');await input('.macro-editor .action-item:nth-of-type(2) [aria-label="Action value"]','4000');await button('Run QA score cue');await until(async()=>!!(await state()).active);const activeId=(await state()).active.id;
 await reload();await until(()=>js("document.querySelector('.command-monitor').textContent.includes('waiting')"));await capture('commands-reconnected.png');assert.equal((await state()).active.id,activeId);
 await until(async()=>(await state()).history[0]?.status==='succeeded');await until(()=>js("document.querySelector('.command-monitor').textContent.includes('succeeded')"));assert.equal((await data()).variables.homeScore,3);assert.equal((await state()).history.filter(j=>j.label==='QA score cue').length,2);checks.push('renderer reload reconnects to existing command without duplicate execution');
 await tab('Panels');await button('Macros');await button('Run QA score cue');await until(async()=>!!(await state()).active);await button('Cancel sequence',"document.querySelector('.command-monitor')");await until(async()=>(await state()).history[0]?.status==='cancelled');await until(()=>js("document.querySelector('.command-monitor').textContent.includes('cancelled')"));assert.equal((await data()).variables.homeScore,3);assert.equal(await js("document.querySelector('.projectbar').inert"),false);checks.push('native cancellation leaves prior values intact and unlocks editing');
}
