import {useEffect,useState} from 'react';
import {desktopBridge,type ConnectionInfo,type ServerProfile} from '../lib/desktop';
const bridge=desktopBridge()!,blank:ServerProfile={name:'Production',url:'https://127.0.0.1:9443',fingerprint:''};
export function Connections({onClose,beforeSwitch}:{onClose:()=>void;beforeSwitch?:()=>Promise<void>}){
 const [info,setInfo]=useState<ConnectionInfo|null>(null),[profile,setProfile]=useState<ServerProfile>(blank),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[lan,setLan]=useState(false),[password,setPassword]=useState('');
 const refresh=()=>bridge.network<ConnectionInfo>('info').then(setInfo);
 useEffect(()=>{refresh().catch(e=>setMessage(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),3000);return()=>clearInterval(timer);},[]);
 async function perform(fn:()=>Promise<unknown>,success=''){setBusy(true);setMessage('');try{await fn();await refresh();setMessage(success);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const switchTo=(id:string|null)=>perform(async()=>{await beforeSwitch?.();await bridge.network('switch',{id});});
 return <div className="desktop-modal-backdrop"><section className="desktop-settings network-settings" role="dialog" aria-modal="true" aria-label="Connections and production server"><header><div><small>SELF-HOSTED PRODUCTION</small><h1>Connections & servers</h1></div><button onClick={onClose} aria-label="Close connections">×</button></header><p>Current: <strong>{info?.status.local?'Local workstation':info?.status.serverName}</strong> · {info?.status.network}. Each server has its own accounts and workspaces.</p>
 <fieldset disabled={busy}>{info?.managed&&<p><strong>Managed installation.</strong> Sign in to your assigned server. Local mode and host settings are controlled by your administrator.</p>}<h2>Saved servers</h2><div className="network-profiles">{!info?.managed&&<button disabled={!info?.activeId} onClick={()=>void switchTo(null)}>Local workstation · switch & sign out</button>}{info?.profiles.map(p=><div className="network-profile" key={p.id}><div><strong>{p.name}{info.activeId===p.id?' · active':''}{info.backupId===p.id?' · backup':''}</strong><small>{p.url}</small></div>{!info.managed&&<button onClick={()=>setProfile(p)}>Edit / recipient setup</button>}<button disabled={info.activeId===p.id} onClick={()=>void switchTo(p.id!)}>Connect & sign out</button></div>)}</div>
 <p>Switching closes the current session. Close the output window first. Commands are never carried to another server.</p>
 {!info?.managed&&<><div className="desktop-settings-grid"><label>Profile name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>HTTPS address and port<input value={profile.url} onChange={e=>setProfile({...profile,url:e.target.value})}/></label></div><label>SHA-256 certificate fingerprint<input className="network-fingerprint" value={profile.fingerprint} onChange={e=>setProfile({...profile,fingerprint:e.target.value})} placeholder="Copy from the server PC below"/></label>
 <div className="network-actions"><button onClick={()=>setProfile(blank)}>New profile</button><button onClick={()=>void perform(async()=>{const r=await bridge.network<{name:string;latencyMs:number;clients:number}>('test',profile);setMessage(`${r.name} responded in ${r.latencyMs} ms · ${r.clients} clients`);})}>Test connection</button><button className="desktop-primary" onClick={()=>void perform(()=>bridge.network('save',profile),'Server profile saved.')}>Save profile</button><button onClick={()=>void perform(async()=>{const folder=await bridge.network<string|false>('exportManaged',profile);if(folder)setMessage('Recipient setup kit saved: '+folder);})}>Export managed client setup</button></div><p>For recipient PCs, enter a reachable LAN or VPN address, then export a setup kit. Applying the kit on that PC requires Windows administrator access. Your account must allow user and system administration.</p>
 <label>Backup server (manual switching)<select value={info?.backupId||''} onChange={e=>void perform(()=>bridge.network('backupProfile',{id:e.target.value}))}><option value="">None</option>{info?.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={!info?.backupId||info.backupId===info.activeId} onClick={()=>void switchTo(info!.backupId)}>Switch to backup & sign out</button><p>Restore an encrypted snapshot on the backup PC first. This is a manual recovery path; there is no live replication or automatic failover.</p></>}
 {!info?.status.local&&<><h2>Output workstation</h2><p>{info?.status.engine?`Attached: ${info.status.engine.workstation} (${info.status.engine.username})`:'No output workstation attached.'} Open desktop output, or start NDI / a ready browser receiver in Broadcast output, then attach this PC here. Engineer permission is required.</p><div className="network-actions"><button onClick={()=>void perform(()=>bridge.openOutput())}>Open output</button><button onClick={()=>void perform(()=>bridge.network('attachOutput'),'Attachment requested. Check connection status.')}>Attach output on this PC</button><button disabled={!info?.status.engineAttached} onClick={()=>void perform(()=>bridge.network('releaseOutput'))}>Release this output</button></div></>}
 {!info?.managed&&<><h2>Host on this PC</h2>{info?.host?<><p>{info.host.name} · {info.host.running?'Running or starting':'Stopped'} · port {info.host.port}</p><p>{info.host.mode}. Hosting continues when the editor closes.</p><p>Listen address: {info.host.host==='0.0.0.0'?'LAN (all IPv4 interfaces)':'This PC only'}. Host settings require the local administrator in Local mode.</p><button disabled={info.host.running||!info.status.local} onClick={()=>void perform(()=>bridge.network('configureHost',{host:info.host!.host==='0.0.0.0'?'127.0.0.1':'0.0.0.0'}),'Host listen address updated.')}>{info.host.host==='0.0.0.0'?'Limit host to this PC':'Enable LAN listening'}</button><label>Certificate fingerprint<input readOnly value={info.host.fingerprint}/></label><p className="desktop-data-path">{info.host.directory}</p><div className="network-actions"><button onClick={()=>void perform(()=>bridge.network('startHost'),'Production server started.')}>Start server</button><button onClick={()=>void perform(()=>bridge.network('stopHost'),'Production server stopped. No commands will resume.')}>Stop server</button><button onClick={()=>void perform(()=>bridge.network('hostStartup',{enabled:true}),'Host will start at Windows sign-in.')}>Start at sign-in</button><button onClick={()=>void perform(()=>bridge.network('hostStartup',{enabled:false}),'Host sign-in startup disabled.')}>Disable host startup</button></div></>:<><p>Create a separate server database and private certificate. Your local projects remain in local mode; transfer them with project export/import.</p><label className="desktop-check"><input type="checkbox" checked={lan} onChange={e=>setLan(e.target.checked)}/>Listen on the LAN (all IPv4 interfaces)</label><p>{lan?'Allow TCP 9443 on the server’s private Windows network only. Other PCs use its LAN address and the fingerprint shown after provisioning.':'Listen on this PC only for setup and testing.'}</p><button onClick={()=>void perform(()=>bridge.network('provision',{name:'BroadcastCG production',host:lan?'0.0.0.0':'127.0.0.1',port:9443}),'Server provisioned. Start it, then connect to its saved profile to create the first administrator.')}>Create production server</button></>}
 <h2>Encrypted server backup</h2><label>Backup password (15–128 characters)<input type="password" autoComplete="new-password" minLength={15} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><p>Includes accounts, projects, images and feed credentials. Restoring revokes saved sessions. Keep this password safely; it cannot be recovered.</p><div className="network-actions"><button disabled={password.length<15||info?.status.local} onClick={()=>void perform(async()=>{const saved=await bridge.network('backup',{password});if(saved)setPassword('');},'Backup operation finished.')}>Save server backup</button><button disabled={password.length<15||!info?.host||info.host.running||!info.status.local} onClick={()=>void perform(async()=>{await bridge.network('restoreHost',{password});setPassword('');},'Restore operation finished.')}>Restore stopped host</button></div></>}</fieldset>
 {(message||busy)&&<p role="status" className="network-message">{busy?'Working…':message}</p>}</section></div>;
}
