import assert from 'node:assert/strict';
import {layer} from '../lib/studio-model.ts';
export async function designSmoke({studio,js,api,reload,capture,checks,sleep,until,project,getOutput,openOutput}){
 const original=(await api('/api/projects/'+project.id)).value.project,p=structuredClone(original);
 p.scenes=[{id:'design-qa',name:'Design tools QA',width:1000,height:700,duration:5,layers:[layer('rect',{id:'design-plate',name:'Mask plate',x:100,y:100,width:600,height:400,color:'#ff4400'})]}];
 const clearQADraft=async()=>{await sleep(250);await js("[...document.querySelectorAll('.desktop-recovery button')].find(b=>b.textContent==='Use saved project')?.click()");await sleep(100);};
 const read=async()=>(await api('/api/projects/'+p.id)).value,put=async value=>{const r=await api('/api/projects',{project:value,revision:(await read()).revision});assert.equal(r.status,200,JSON.stringify(r));};
 const click=async selector=>{await js(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(100);};
 const select=async(label,value)=>{await js(`(()=>{const e=document.querySelector('[aria-label='+${JSON.stringify(JSON.stringify(label))}+']');e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await sleep(120);};
 const save=async()=>{await click('.projectbar button:last-of-type');await until(()=>js("document.querySelector('.statusbar').textContent.includes('Saved')"));};
 const drag=async(a,b,button='left')=>{studio.show();studio.focus();studio.webContents.sendInputEvent({type:'mouseDown',...a,button,clickCount:1});await sleep(30);for(let i=1;i<=5;i++){studio.webContents.sendInputEvent({type:'mouseMove',x:Math.round(a.x+(b.x-a.x)*i/5),y:Math.round(a.y+(b.y-a.y)*i/5),button});await sleep(20);}studio.webContents.sendInputEvent({type:'mouseUp',...b,button,clickCount:1});await sleep(120);};
 const pos=async(x,y)=>js(`(()=>{const p=new DOMPoint(${x},${y}).matrixTransform(document.querySelector('.canvas-stage svg.graphic').getScreenCTM());return {x:Math.round(p.x),y:Math.round(p.y)};})()`);
 // Rasterize the same SVG as PNG export, removing only editor selection/guides.
 const pixels=async(points,code="document.querySelector('.canvas-stage svg.graphic')")=>js(`(async()=>{const s=${code}.cloneNode(true);s.setAttribute('width','1000');s.setAttribute('height','700');s.querySelectorAll('rect[fill="transparent"],rect[stroke-dasharray]').forEach(e=>e.remove());const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(s)],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=1000;c.height=700;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);return ${JSON.stringify(points)}.map(([x,y])=>[...ctx.getImageData(x,y,1,1).data]);}finally{URL.revokeObjectURL(url);}})()`);
 await put(p);await reload();await clearQADraft();await js("[...document.querySelectorAll('[role=tab]')].find(b=>b.textContent.trim()==='Design').dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}))");await sleep(180);await click('.scene-item');await click('[data-design-layer=design-plate] .layer-select');
 const dimensions=await js("(()=>{const a=document.querySelector('.design-viewport').getBoundingClientRect(),s=document.querySelector('.canvas-stage').getBoundingClientRect();return {height:s.height,width:s.width,contained:s.top>=a.top&&s.bottom<=a.bottom&&s.left>=a.left&&s.right<=a.right};})()");assert.ok(dimensions.height>100&&dimensions.contained&&Math.abs(dimensions.width/dimensions.height-1000/700)<.01,JSON.stringify(dimensions));
 const before=await js("Number(document.querySelector('.design-viewport').dataset.zoom)"),point=await pos(400,300);
 studio.show();studio.focus();studio.webContents.sendInputEvent({type:'mouseWheel',...point,deltaY:80,deltaX:0,canScroll:true});await sleep(180);const after=await js("Number(document.querySelector('.design-viewport').dataset.zoom)");assert.notEqual(before,after,'Native wheel zoom');const anchored=await pos(400,300);assert.ok(Math.abs(anchored.x-point.x)<=1&&Math.abs(anchored.y-point.y)<=1,'Zoom anchor');
 await drag(point,{x:point.x+30,y:point.y+20},'middle');assert.ok(Math.abs(await js("Number(document.querySelector('.design-viewport').dataset.panX)"))>1);await click('[aria-label="Fit canvas"]');
 await click('[aria-label="Draw rectangle (U)"]');await drag(await pos(740,100),await pos(920,250));await save();let saved=(await read()).project.scenes[0];assert.equal(saved.layers.length,2);assert.ok(Math.abs(saved.layers[1].width-180)<4);assert.ok(Math.abs(saved.layers[1].x-740)<4);await click('[aria-label="Undo"]');await save();assert.equal((await read()).project.scenes[0].layers.length,1);await click('[aria-label="Redo"]');await save();assert.equal((await read()).project.scenes[0].layers.length,2);
 checks.push('Native pointer-centered wheel zoom, middle-mouse pan, fitted canvas, drawn geometry and Undo/Redo verified');
 await click('[data-design-layer=design-plate] .layer-select');await click('[aria-label="Add mask to Mask plate"]');await select('Mask shape','ellipse');await save();let rgba=await pixels([[110,110],[400,300]]);assert.equal(rgba[0][3],0);assert.equal(rgba[1][3],255);
 await click('[aria-label="Invert layer mask"]');rgba=await pixels([[110,110],[400,300]]);assert.equal(rgba[0][3],255);assert.equal(rgba[1][3],0);await click('[aria-label="Invert layer mask"]');
 await select('Mask shape','full');await click('[aria-label="Mask brush: hide (B)"]');await drag(await pos(330,300),await pos(470,300));await save();assert.equal((await read()).project.scenes[0].layers[0].visual.layerMask.strokes.length,1);rgba=await pixels([[400,300],[400,180]]);assert.equal(rgba[0][3],0);assert.equal(rgba[1][3],255);
 await click('[aria-label="Mask brush: reveal"]');await drag(await pos(370,300),await pos(430,300));await save();rgba=await pixels([[400,300]]);assert.equal(rgba[0][3],255);await click('[aria-label="Select (V)"]');
 checks.push('Layer masks rasterize correctly for ellipse, inversion, hide strokes and reveal strokes; source layer remains editable');
 await select('Mask shape','ellipse');await save();saved=(await read()).project.scenes[0];
 if(openOutput&&getOutput){await openOutput();await until(()=>getOutput()&&!getOutput().webContents.isLoading());assert.equal((await api('/api/program',{projectId:p.id,scene:saved,variables:p.variables,mode:'show'})).status,200);await until(()=>getOutput().webContents.executeJavaScript("!!document.querySelector('mask')"));assert.equal(await getOutput().webContents.executeJavaScript("document.querySelector('mask').getAttribute('maskUnits')"),'userSpaceOnUse');assert.equal((await api('/api/program',{projectId:p.id,scene:null,variables:{},mode:'hide'})).status,200);}
 checks.push('Saved mask schema and shared broadcast renderer retain editable masks across project persistence');
 const header=await js("(()=>{const r=document.querySelector('[data-design-panel=layers] header').getBoundingClientRect();return{x:Math.round(r.left+45),y:Math.round(r.top+15)}})()");const target=await js("(()=>{const r=document.querySelector('.design-workspace').getBoundingClientRect();return{x:Math.round(r.left+r.width/2),y:Math.round(r.top+130)}})()");await drag(header,target);assert.equal(await js("document.querySelector('[data-design-panel=layers]').dataset.dock"),'float');
 const resize=await js("(()=>{const r=document.querySelector('[data-design-panel=layers] .design-float-resize').getBoundingClientRect();return{x:Math.round(r.right-4),y:Math.round(r.bottom-4)}})()"),oldWidth=await js("document.querySelector('[data-design-panel=layers]').getBoundingClientRect().width");await drag(resize,{x:resize.x+40,y:resize.y+20});assert.ok(await js("document.querySelector('[data-design-panel=layers]').getBoundingClientRect().width")>oldWidth+20);await sleep(500);await reload();await clearQADraft();assert.equal(await js("document.querySelector('[data-design-panel=layers]').dataset.dock"),'float');
 await select('Layers panel position','right');await click('[aria-label="Hide Scenes panel"]');assert.equal(await js("document.querySelector('[data-design-panel=scenes]')===null"),true);await js("[...document.querySelectorAll('.design-layout-bar button')].find(b=>b.textContent==='Reset layout').click()");await sleep(500);assert.equal(await js("document.querySelector('[data-design-panel=layers]').dataset.dock"),'left');await click('[data-design-layer=design-plate] .layer-select');await capture('design-workspace.png');
 checks.push('Native header dragging floats panels; corner resize, docking, hide/show, reset and per-user layout persistence verified');
 await put(original);await reload();await clearQADraft();
}
