import assert from 'node:assert/strict';
import {layer} from '../lib/studio-model.ts';
export async function inspectorSmoke({studio,js,api,reload,capture,checks,sleep,until,project}){
 const original=(await api('/api/projects/'+project.id)).value.project,p=structuredClone(original),size=studio.getSize();
 p.scenes=[{id:'inspector-qa',name:'Properties workspace',width:1920,height:1080,duration:5,frameRate:60,layers:[layer('rect',{id:'pi-shape',name:'Score plate',x:100,y:300,width:700,height:250,color:'#183759'}),layer('text',{id:'pi-text',name:'Team name',x:130,y:340,width:600,height:90,fontSize:70,text:'BROADCAST',color:'#ffffff'})]}];p.variables={...p.variables,accent:'#ff6a00',teamLabel:'HOME'};
 const read=async()=>(await api('/api/projects/'+p.id)).value,put=async value=>assert.equal((await api('/api/projects',{project:value,revision:(await read()).revision})).status,200);
 const click=async selector=>{await js(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(120);};
 const button=async label=>{await js(`[...document.querySelectorAll('.properties-inspector button')].find(b=>b.textContent.trim()===${JSON.stringify(label)}).click()`);await sleep(100);};
 const input=async(selector,value)=>{await js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.focus();Object.getOwnPropertyDescriptor(e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);await sleep(100);};
 const blur=async()=>{await js('document.activeElement?.blur()');await sleep(100);};
 const save=async()=>{await blur();await click('.projectbar button:last-of-type');await until(()=>js("document.querySelector('.statusbar').textContent.includes('Saved')"));};
 const category=name=>click('[aria-label="'+name+' properties"][role=tab]');
 const center=selector=>js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.scrollIntoView({block:'nearest'});const r=e.getBoundingClientRect();return{x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()`);
 const down=async point=>{studio.show();studio.focus();studio.webContents.sendInputEvent({type:'mouseMove',...point});studio.webContents.sendInputEvent({type:'mouseDown',...point,button:'left',clickCount:1});await sleep(70);};
 const move=async(point,modifiers=[])=>{studio.webContents.sendInputEvent({type:'mouseMove',...point,modifiers:['leftButtonDown',...modifiers]});await sleep(120);};
 const up=async point=>{studio.webContents.sendInputEvent({type:'mouseUp',...point,button:'left',clickCount:1});await sleep(120);};
 const tab=async name=>{await js(`[...document.querySelectorAll('.topbar [role=tab]')].find(b=>b.textContent.trim()===${JSON.stringify(name)}).dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}))`);await sleep(150);};
 try{
 await put(p);await reload(p.id);await tab('Design');await click('.scene-item');await click('[data-design-layer=pi-shape] .layer-select');
 assert.equal(await js("document.querySelectorAll('.pi-tabs [role=tab]').length"),5);assert.equal(await js("document.querySelector('[aria-label=\"Inspector Scale X\"]').value"),'100');assert.equal(await js("!!document.querySelector('.properties-inspector [aria-label=\"New effect\"]')"),false);
 const start=await center('[aria-label="Inspector Position X"]'),dest={x:start.x+35,y:start.y};await down(start);await move(dest);assert.equal((await read()).project.scenes[0].layers[0].x,100,'Preview never persists');assert.ok((await js("document.querySelector('.canvas-stage [data-layer-id=pi-shape]').getAttribute('transform')")).includes('135'));await up(dest);await save();assert.equal((await read()).project.scenes[0].layers[0].x,135);await click('[aria-label=Undo]');await save();assert.equal((await read()).project.scenes[0].layers[0].x,100);
 await down(start);await move(dest);studio.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});studio.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await up(dest);await save();assert.equal((await read()).project.scenes[0].layers[0].x,100);
 for(const [modifier,expected] of [['shift',200],['alt',101]]){await down(start);await move({x:start.x+10,y:start.y},[modifier]);await up({x:start.x+10,y:start.y});await save();assert.equal((await read()).project.scenes[0].layers[0].x,expected);await click('[aria-label=Undo]');await save();}
 await input('[aria-label="Inspector Scale X"]','125');await blur();await save();assert.equal((await read()).project.scenes[0].layers[0].scaleX,1.25);await click('[aria-label=Undo]');await save();checks.push('Inspector drags preview live, commit with one Undo, cancel on Escape, support Shift/Alt, and display scales as percentages');
 await click('[aria-label="Lock selected layer"]');assert.equal(await js("document.querySelector('[aria-label=\"Inspector Position X\"]').matches(':disabled')"),true);await category('Style');assert.equal(await js("document.querySelector('[aria-label=\"Layer color\"]').matches(':disabled')"),true);await click('[aria-label="Unlock selected layer"]');await input('[aria-label="Layer color hex"]','#246080');await save();assert.equal((await read()).project.scenes[0].layers[0].color,'#246080');await input('[aria-label="Layer color hex"]','invalid');await save();assert.equal(await js("document.querySelector('[aria-label=\"Layer color hex\"]').getAttribute('aria-invalid')"),'true');assert.equal((await read()).project.scenes[0].layers[0].color,'#246080');
 await click('[data-property-section=effects]>summary');await button('Add effect');await save();assert.equal((await read()).project.scenes[0].layers[0].effects[0].type,'blur');await input('[aria-label="Find a property"]','brush');assert.equal(await js("document.querySelectorAll('[data-property-section]').length"),1);await button('Add layer mask');await save();assert.ok((await read()).project.scenes[0].layers[0].visual.layerMask);await click('[aria-label="Clear property search"]');await category('Masks');await click('[data-property-section=matte]>summary');await button('Add mask');await save();assert.equal((await read()).project.scenes[0].layers[0].masks.length,1);checks.push('Contextual styles, hex validation, effect creation, search and both mask systems save; locked layers disable editing');
 await category('Data');await click('[data-property-section=formulas]>summary');await input('[aria-label="Property formula"]','value + var("homeScore") * 10');await button('Apply formula');await save();assert.equal((await read()).project.scenes[0].layers[0].formulas[0].property,'width');await category('Transform');assert.equal(await js("document.querySelector('[aria-label=\"Inspector Width\"]').disabled"),true);
 await category('Motion');await input('[aria-label="Layer in point"]','1');await blur();await input('[aria-label="Layer out point"]','4');await save();const clip=(await read()).project.scenes[0].layers[0];assert.equal(clip.inPoint,1);assert.equal(clip.outPoint,4);
 await tab('Animate');await click('[data-design-layer=pi-shape] .layer-select');await category('Transform');await click('[aria-label="Set Position X keyframe"]');await save();assert.equal((await read()).project.scenes[0].layers[0].keys.x.length,1);
 await click('[data-design-layer=pi-text] .layer-select');await category('Style');await input('[aria-label="Layer text"]','HOME TEAM');await save();await category('Data');await js("(()=>{const e=document.querySelector('[aria-label=\"Bind layer data\"]');e.value='teamLabel';e.dispatchEvent(new Event('change',{bubbles:true}));})()");await save();assert.equal((await read()).project.scenes[0].layers[1].text,'HOME TEAM{{teamLabel}}');await click('[aria-label="Scene settings"]');await input('[aria-label="Scene duration"]','6');await save();assert.equal((await read()).project.scenes[0].duration,6);assert.equal((await read()).project.scenes[0].frameRate,60);await click('[aria-label="Return to layer properties"]');checks.push('Formula links, data dropdowns, exact layer timing, keyframe insertion, scene duration and 60 fps persist');
 await reload(p.id);await tab('Design');await click('.scene-item');await click('[data-design-layer=pi-shape] .layer-select');const stored=(await read()).project.scenes[0].layers[0];assert.equal(stored.effects.length,1);assert.equal(stored.masks.length,1);assert.ok(stored.visual.layerMask);assert.equal(stored.formulas.length,1);assert.equal(stored.keys.x.length,1);
 for(const [width,height] of [[1280,720],[1920,1080]]){studio.setSize(width,height);await sleep(300);await category('Transform');await click('[aria-label="Fit canvas"]');const bounds=await js("(()=>{const v=document.querySelector('.design-viewport').getBoundingClientRect(),f=document.querySelector('.pi-footer').getBoundingClientRect();return{width:v.width,height:v.height,footer:f.bottom<=innerHeight,overflow:document.documentElement.scrollWidth>innerWidth}})()");assert.ok(bounds.width>300&&bounds.height>100&&bounds.footer&&!bounds.overflow,JSON.stringify(bounds));await capture('properties-inspector-'+width+'.png');for(const name of ['Style','Motion','Masks','Data']){await category(name);assert.equal(await js("document.querySelector('.pi-scroll').scrollWidth>document.querySelector('.pi-scroll').clientWidth"),false,name+' overflows');}}
 const panel=await js("document.querySelector('[aria-label=\"Properties panel position\"]').value");await js("(()=>{const e=document.querySelector('[aria-label=\"Properties panel position\"]');e.value='float';e.dispatchEvent(new Event('change',{bubbles:true}));})()");await sleep(150);assert.equal(await js("document.querySelector('[data-design-panel=properties]').dataset.dock"),'float');await js(`(()=>{const e=document.querySelector('[aria-label="Properties panel position"]');e.value=${JSON.stringify(panel)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);assert.equal((await api('/api/program')).value?.scene??null,null);checks.push('Saved edits reopen; all categories fit 1280×720 and 1920×1080; floating panels work and editing does not TAKE output');
 }finally{studio.setSize(...size);await put(original);await reload(project.id);}
}
