const {contextBridge,ipcRenderer}=require('electron');
const call=(name,...args)=>ipcRenderer.invoke('broadcastcg:'+name,...args);
contextBridge.exposeInMainWorld('broadcastCG',Object.freeze({
  editorState:(section,projectId,value)=>call('editorState',section,projectId,value),
  recovery:(action,data)=>call('recovery',action,data),
  network:(action,data)=>call('network',action,data),
  onNetwork:listener=>{const handler=(_event,state)=>listener(state);ipcRenderer.on('broadcastcg:network',handler);return()=>ipcRenderer.removeListener('broadcastcg:network',handler);},
  auth:async(action,data)=>{const result=await call('auth',action,data);if(!result.ok){const error=new Error(result.error);error.status=result.status;throw error;}return result.value;},
  prepareAe:()=>call('prepareAe'),
  commitAe:options=>call('commitAe',options),
  cancelAe:()=>call('cancelAe'),
  aeReference:options=>call('aeReference',options),
  saveAeExporter:()=>call('saveAeExporter'),
  preparePsd:()=>call('preparePsd'),
  commitPsd:options=>call('commitPsd',options),
  cancelPsd:()=>call('cancelPsd'),
  info:()=>call('info'),
  status:()=>call('status'),
  settings:()=>call('settings'),
  saveSettings:value=>call('saveSettings',value),
  openOutput:displayId=>call('openOutput',displayId),
  importProject:()=>call('importProject'),
  exportProject:project=>call('exportProject',project),
  exportDiagnostics:()=>call('exportDiagnostics'),
  acknowledgeProgram:revision=>ipcRenderer.send('broadcastcg:rendered',revision),
  onProgram:listener=>{const handler=(_event,program)=>listener(program);ipcRenderer.on('broadcastcg:program',handler);return()=>ipcRenderer.removeListener('broadcastcg:program',handler);},
}));
