import assert from 'node:assert/strict';
import {layer,control,action} from '../lib/studio-model.ts';
import {dataGraphicPreset} from '../lib/production-tools.ts';
export async function productionSmoke({studio,js,api,reload,capture,checks,sleep,until,project,openOutput,getOutput}){
 const original=(await api('/api/projects/'+project.id)).value.project,p=structuredClone(original),read=async()=>(await api('/api/projects/'+p.id)).value;
 const put=async p=>{const r=await api('/api/projects',{project:p,revision:(await read()).revision});assert.equal(r.status,200,JSON.stringify(r));};
 const tab=async text=>{await js(`[...document.querySelectorAll('[role=tab]')].find(b=>b.textContent.trim()===${JSON.stringify(text)}).dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}))`);await sleep(180);};
 const button=async text=>{await js(`[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)}).click()`);await sleep(180);};
 const idle=async()=>until(()=>js("document.querySelector('.studio').dataset.commandBusy==='false'"));
 // Generate a real, local VP8 WebM in the test renderer; no display capture or external media.
 const video=await js(`(async()=>{const c=document.createElement('canvas');c.width=160;c.height=90;const ctx=c.getContext('2d'),stream=c.captureStream(15),recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'}),parts=[];recorder.ondataavailable=e=>parts.push(e.data);const done=new Promise(r=>recorder.onstop=r);recorder.start();let n=0;const timer=setInterval(()=>{ctx.fillStyle=n++%2?'#225588':'#dd9944';ctx.fillRect(0,0,160,90);ctx.fillStyle='#ffffff';ctx.fillRect(n*5%130,25,25,25);},65);await new Promise(r=>setTimeout(r,1300));recorder.stop();await done;clearInterval(timer);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(parts,{type:'video/webm'}),response=await fetch('/api/assets',{method:'POST',headers:{'Content-Type':'video/webm','X-File-Name':'production-loop.webm'},body:blob});if(!response.ok)throw Error(await response.text());return (await response.json()).url;})()`);
 p.variables={...p.variables,selected:'',tab:'Players',homeScore:0,awayScore:0};
 let scene={...p.scenes[0],duration:8,layers:[layer('rect',{id:'auto-plate',name:'Responsive plate',x:80,y:20,width:200,height:75,color:'#16486a',layout:{mode:'fit',target:'auto-name',padding:20},visual:{fill:'linear',gradientStops:[{offset:0,color:'#135973'},{offset:.5,color:'#2564b3'},{offset:1,color:'#0e233a'}]}}),layer('text',{id:'auto-name',name:'Responsive name',x:140,y:35,height:60,fontSize:44,text:'{{homeTeam}}',layout:{mode:'text',minWidth:100,maxWidth:1000}}),layer('path',{id:'curved',name:'Curved logo',x:1300,y:200,width:400,height:200,visual:{points:[{x:0,y:1,outX:.2,outY:0},{x:1,y:0,inX:.8,inY:1}],closed:false,fill:'none',stroke:'#ff8800',strokeWidth:8}}),layer('video',{id:'movie',name:'Video loop',src:video,x:1320,y:500,width:400,height:225,media:{start:0,speed:1,loop:true}}),layer('ticker',{id:'ticker',x:140,y:930,width:1400,height:65,fontSize:40,text:'LIVE SPORTS • {{homeTeam}} • BroadcastCG',ticker:{speed:90,gap:80}}),layer('countdown',{id:'countdown',x:1450,y:35,width:220,height:80,fontSize:60,text:'60'})],groups:[]};scene=dataGraphicPreset(scene,'standings');p.scenes[0]=scene;
 p.panels=[{id:'football',name:'Production widgets',type:'custom',columns:3,freeLayout:true,canvasWidth:960,canvasHeight:640,controls:[control('Player cards',[action('increment','homeScore','1')],{id:'cards',kind:'widget',rosterTeam:'home',variable:'selected',selectionBindings:{name:'playerName',number:'playerNumber'},widget:{mode:'cards',columns:2,title:'{{row.name}}',subtitle:'#{{row.number}} · {{row.position}}',photo:'{{row.photo}}'},placement:{x:10,y:10,width:460,height:400}}),control('Drop player',[action('increment','awayScore','1')],{id:'drop',kind:'widget',rosterTeam:'home',variable:'selected',selectionBindings:{name:'playerName'},widget:{mode:'dropzone',columns:1,title:'{{row.name}}',subtitle:'Selected player',photo:'{{row.photo}}'},placement:{x:490,y:10,width:400,height:220}}),control('Hardware goal',[action('increment','homeScore','1')],{id:'hardware',hardware:{kind:'key',code:124},placement:{x:490,y:250,width:300,height:130}})]}];
 await put(p);await reload();await tab('Design');await js("document.querySelector('.scene-item').click()");await sleep(300);
 assert.equal(await js("document.querySelectorAll('#editor-auto-plate-fill stop').length"),3);
 assert.equal(await js("document.querySelectorAll('.canvas-stage [data-layer-id]').length"),21);
 assert.ok(await js("document.querySelector('.canvas-stage [data-layer-id=curved] path').getAttribute('d').includes('C ' )"));
 const size=await js("(()=>{const a=document.querySelector('.canvas-stage [data-layer-id=auto-plate] rect');return Number(a.getAttribute('width'));})()");assert.ok(size>140&&size<1000,String(size));
 await until(()=>js("document.querySelector('.canvas-stage video')?.readyState>=2"));await button('Play');await sleep(650);const media=await js("(()=>{const v=document.querySelector('.canvas-stage video');return{time:v.currentTime,error:!!v.error,countdown:document.querySelector('.canvas-stage [data-layer-id=countdown] text').textContent};})()");assert.ok(media.time>0&&!media.error,JSON.stringify(media));assert.equal(media.countdown,'01:00');await sleep(650);assert.equal(await js("document.querySelector('.canvas-stage [data-layer-id=countdown] text').textContent"),'00:59');await button('Pause');await capture('production-designer.png');checks.push('Production designer renders repeated rows, responsive text/plate, three-stop gradients, curved vectors, decoded local WebM, moving ticker and countdown');
 await js("[...document.querySelectorAll('.layer-select')].find(b=>b.textContent.includes('Responsive name')).click();document.querySelector('.production-library').open=true");await button('Save selected graphic');await button('Insert linked');await button('Save');await until(()=>js("document.querySelector('.statusbar').textContent.includes('Saved')"));let saved=await read();assert.equal(saved.project.graphicComponents.length,1);assert.ok(saved.project.scenes[0].layers.some(l=>l.graphicLink));checks.push('Graphic library UI saves a selected layer and inserts a persistent linked instance');
 await tab('Panels');await tab('Operate');await idle();await js("document.querySelector('[data-control-id=cards] .widget-card-grid button').click()");await until(async()=>(await read()).project.variables.homeScore===1);await idle();assert.equal((await read()).project.variables.playerNumber,1);
 await js(`(()=>{const target=document.querySelector('.widget-dropzone'),data=new DataTransfer();data.setData('application/x-broadcastcg-row',JSON.stringify({projectId:${JSON.stringify(p.id)},value:'home-5'}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:data}));})()`);await until(async()=>(await read()).project.variables.awayScore===1);await idle();assert.equal((await read()).project.variables.playerName,'Home player 5');await capture('production-controls.png');checks.push('Custom cards and drop zone fill mapped player data and run their stored action sequences');
 await js("document.querySelector('.hardware-box').open=true");await button('Arm hardware');studio.show();studio.focus();await sleep(100);studio.webContents.sendInputEvent({type:'keyDown',keyCode:'F13'});studio.webContents.sendInputEvent({type:'keyUp',keyCode:'F13'});await until(async()=>(await read()).project.variables.homeScore===2);await idle();await button('Disarm hardware');studio.webContents.sendInputEvent({type:'keyDown',keyCode:'F13'});studio.webContents.sendInputEvent({type:'keyUp',keyCode:'F13'});await sleep(250);assert.equal((await read()).project.variables.homeScore,2);checks.push('Function-key hardware input runs a saved command only while armed in Operate; disarming prevents another trigger');
 const latest=await read();openOutput();await until(()=>getOutput()&&!getOutput().webContents.isLoading());const taken=await api('/api/program',{projectId:p.id,scene:latest.project.scenes[0],variables:latest.project.variables,mode:'show'});assert.equal(taken.status,200,JSON.stringify(taken));assert.equal(taken.value.acknowledged,true);const outputJs=code=>getOutput().webContents.executeJavaScript(code);assert.ok(await outputJs("document.querySelector('video').readyState>=2"));await sleep(500);assert.ok(await outputJs("document.querySelector('video').currentTime>0"));assert.equal(await outputJs("document.querySelectorAll('[data-layer-id]').length"),22);await api('/api/program',{projectId:p.id,scene:null,variables:{},mode:'hide'});await sleep(700);getOutput().close();await until(()=>!getOutput());checks.push('Native output acknowledges decoded local video with responsive repeated graphics, advances playback, and hides cleanly');
 await put(original);await reload();
}
