import {useEffect,useState} from 'react';
import {desktopBridge} from '../lib/desktop';
const bridge=desktopBridge()!;
type Backup={id:string;createdAt:number;label:string;bytes:number;sha256:string|null};
type Catalog={backups:Backup[];local:boolean;automaticUpdates:boolean;version:string};
type Report={schemaVersion:number;projects:number;accounts:number;images:number;sha256:string;verified:boolean};
export function RecoveryCenter({onClose,beforeMaintenance}:{onClose:()=>void;beforeMaintenance:()=>Promise<void>}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[password,setPassword]=useState(''),[label,setLabel]=useState('Manual backup'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[report,setReport]=useState<Report|null>(null);
 const refresh=()=>bridge.recovery<Catalog>('list').then(setCatalog);
 useEffect(()=>{refresh().catch(e=>setMessage(e.message));},[]);
 async function perform(fn:()=>Promise<unknown>,success:string){setBusy(true);setMessage('');setReport(null);try{await fn();await refresh();setMessage(success);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="desktop-modal-backdrop"><section className="desktop-settings network-settings" role="dialog" aria-modal="true" aria-label="Backups and recovery"><header><div><small>DEPLOYMENT & RECOVERY</small><h1>Backups & recovery</h1></div><button disabled={busy} onClick={onClose} aria-label="Close recovery">×</button></header>
 <p>{catalog?.local?'Local workstation':'Connected production server'} · Version {catalog?.version}. Backups contain accounts, workspaces, graphics, panels, images and encrypted feed credentials.</p>
 <fieldset disabled={busy}><label>Backup password (15–128 characters)<input type="password" autoComplete="new-password" minLength={15} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><p>Use the password that created a backup when verifying or restoring it. It cannot be recovered. Export a copy to another disk for protection against disk failure.</p>
 <div className="desktop-settings-grid"><label>New backup label<input maxLength={100} value={label} onChange={e=>setLabel(e.target.value)}/></label><div className="network-actions"><button className="desktop-primary" disabled={password.length<15} onClick={()=>void perform(async()=>{await beforeMaintenance();await bridge.recovery('create',{password,label});},'Encrypted backup created.')}>Create backup</button></div></div>
 <h2>Available backups</h2>{!catalog?.backups.length&&<p>No recovery backups yet. Create one before upgrading or making major changes.</p>}
 <div className="recovery-list">{catalog?.backups.map(b=><article key={b.id}><div><strong>{b.label}</strong><small>{new Date(b.createdAt).toLocaleString()} · {(b.bytes/1048576).toFixed(2)} MB</small><code title={b.sha256||''}>{b.sha256?'SHA-256 '+b.sha256.slice(0,20)+'…':'No recorded checksum'}</code></div><button disabled={password.length<15} onClick={()=>void perform(async()=>setReport(await bridge.recovery<Report>('verify',{id:b.id,password})),'Password, database integrity and credentials verified.')}>Verify</button><button onClick={()=>void perform(async()=>{const saved=await bridge.recovery('export',{id:b.id});if(!saved)throw Error('Export cancelled.');},'Encrypted backup exported.')}>Export</button></article>)}</div>
 <h2>Restore from a file</h2><p>Verify a .bcbackup or .bcserver file first. Restoring replaces accounts and workspaces, revokes sessions, and retains the previous database for rollback. The editor opens at sign-in. Output, running clocks and sequences are not resumed.</p>
 <div className="network-actions"><button disabled={password.length<15} onClick={()=>void perform(async()=>{const r=await bridge.recovery<Report|null>('inspectFile',{password});if(r)setReport(r);else throw Error('Verification cancelled.');},'Backup file verified.')}>Verify backup file</button><button disabled={password.length<15||!catalog?.local} onClick={()=>void perform(async()=>{await beforeMaintenance();await bridge.recovery('restoreFile',{password});},'Restore operation finished.')}>Restore local workstation…</button></div>
 {!catalog?.local&&<p>To restore a production server, open BroadcastCG on its host in Local mode, stop the host under Connections, then choose Restore stopped host. Connected clients cannot replace the server database.</p>}
 <h2>Updates</h2><p>Automatic updates are disabled. Install a release manually after exporting and verifying a backup. Keep the earlier installer and matching database snapshot together for rollback; an older application may not support newer data.</p><p>The current release is unsigned. Publicly signed installers require a publisher signing certificate. No online update service is contacted.</p>
 </fieldset>{report&&<div className="recovery-report"><strong>Verified</strong><p>{report.projects} workspaces · {report.accounts} accounts · {report.images} images · schema {report.schemaVersion}</p><code>{report.sha256}</code></div>}{(message||busy)&&<p role="status" className="network-message">{busy?'Working…':message}</p>}</section></div>;
}
