import {createRoot} from 'react-dom/client';
import {useEffect,useRef,useState} from 'react';
import Studio from '../app/studio/studio';
import OutputView from '../app/studio/output-view';
import {desktopBridge,DesktopSettings,DesktopStatus} from '../lib/desktop';
import {LocalSession,Permission} from '../lib/permissions';
import {api} from '../lib/client-api';
import {BroadcastOutput} from './broadcast-output';
import {RecoveryCenter} from './recovery-center';
import {Connections} from './connections';
import {AccountForm,Administration} from './accounts';
import '../app/globals.css';
import './desktop.css';
const bridge=desktopBridge()!;
function DesktopApp(){
 const [connections,setConnections]=useState(false),[managed,setManaged]=useState(false),[offline,setOffline]=useState(false);
 useEffect(()=>{bridge.network<{managed:boolean;status:{network:string}}> ('info').then(n=>{setManaged(n.managed);setOffline(n.status.network==='disconnected');}).catch(()=>{});return bridge.onNetwork(n=>{if(n.status)setOffline(n.status.network==='disconnected');});},[]);
 const [session,setSession]=useState<LocalSession|null>(null),[setup,setSetup]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{bridge.auth<{setupRequired:boolean;setupBlocked?:boolean}>('bootstrap').then(async b=>{setSetup(b.setupRequired);if(b.setupBlocked)setError('Create the first administrator on the server computer.');try{setSession(await bridge.auth<LocalSession>('me'));}catch{}setLoading(false);}).catch(e=>{setError(e.message);setLoading(false);});},[]);
 useEffect(()=>{if(!session)return;let alive=true,lastTouch=0;const refresh=()=>bridge.auth<LocalSession>('me').then(s=>{if(alive)setSession(s);}).catch(e=>{if(alive&&e.status===401){setSession(null);setError(e.message+' Output keeps its current graphic.');}});const timer=setInterval(refresh,5000);const activity=(event:Event)=>{if(!event.isTrusted||Date.now()-lastTouch<60000)return;lastTouch=Date.now();bridge.auth('touch').catch(()=>{});};window.addEventListener('pointerdown',activity);window.addEventListener('keydown',activity);window.addEventListener('broadcastcg-auth-required',refresh);return()=>{alive=false;clearInterval(timer);window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity);window.removeEventListener('broadcastcg-auth-required',refresh);};},[session?.sessionId]);
 useEffect(()=>bridge.onNetwork(n=>{if(n.sessionEnded){setSession(null);setError(n.error||'Your session ended. Contact the administrator if access expired.');}}),[]);
 useEffect(()=>{if(!session?.user.accessExpiresAt)return;const remaining=session.user.accessExpiresAt-(session.serverTime||Date.now()),started=performance.now();let timer:ReturnType<typeof setTimeout>;const check=()=>{const left=remaining-(performance.now()-started);if(left<=0){setSession(null);setError('Your access period has expired. Contact the administrator to renew it.');}else timer=setTimeout(check,Math.min(left,86400000));};check();return()=>clearTimeout(timer);},[session]);
 const signedIn=(s:LocalSession)=>{setSession(s);setSetup(false);setError('');};
 const logout=async()=>{await bridge.auth('logout');setSession(null);setError('');};
 if(loading)return <div className="account-screen"><p>Opening your local workstation…</p></div>;
 if(!session)return <div className="account-screen"><div><button onClick={()=>setConnections(true)}>Connections & servers</button>{connections&&<Connections onClose={()=>setConnections(false)}/>}{error&&<p className="account-error" role="alert">{error}</p>}<AccountForm setup={setup} onSession={signedIn}/></div></div>;
 if(session.user.mustChangePassword)return <div className="account-screen"><AccountForm session={session} onSession={signedIn} onClose={()=>void logout()}/></div>;
 if(managed&&offline)return <div className="account-screen"><section className="account-card"><h1>Production server unavailable</h1><p>This managed installation requires its assigned server. Reconnecting automatically. No commands are replayed.</p><button onClick={()=>setConnections(true)}>Connections</button><button onClick={()=>void logout()}>Sign out</button>{connections&&<Connections onClose={()=>setConnections(false)}/>}</section></div>;
 return <Workspace key={session.sessionId} session={session} onSession={signedIn} logout={logout}/>;
}
function Workspace({session,onSession,logout}:{session:LocalSession;onSession:(s:LocalSession)=>void;logout:()=>Promise<void>}){
 const [connections,setConnections]=useState(false);
 const [recovering,setRecovering]=useState(false),[broadcast,setBroadcast]=useState(false);
 const [open,setOpen]=useState(false),[admin,setAdmin]=useState(false),[account,setAccount]=useState(false),[preferences,setPreferences]=useState<DesktopSettings|null>(null),[status,setStatus]=useState<DesktopStatus|null>(null),[info,setInfo]=useState<{version:string;dataDirectory:string}|null>(null),[message,setMessage]=useState(''),[workspaceReady,setWorkspaceReady]=useState<boolean|null>(null),[leaving,setLeaving]=useState(false);
 const flush=useRef<null|(()=>Promise<void>)>(null),can=(p:Permission)=>session.user.permissions.includes(p);
 useEffect(()=>{let active=true;const refresh=()=>bridge.status().then(s=>active&&setStatus(s)).catch(()=>active&&setStatus(null));refresh();const timer=setInterval(refresh,2000);bridge.info().then(setInfo).catch(()=>{});bridge.settings().then(setPreferences).catch(()=>{});if(!can('projects.view'))setWorkspaceReady(false);else api<unknown[]>('/api/projects').then(list=>{if(active)setWorkspaceReady(list.length>0||can('projects.create'));}).catch(e=>setMessage(e.message));return()=>{active=false;clearInterval(timer);};},[]);
 async function signOut(){setLeaving(true);try{await flush.current?.();}catch{}try{await logout();}catch(e){setMessage((e as Error).message);setLeaving(false);}}
 return <><div className="desktop-strip"><strong><span className="desktop-dot"/>BROADCAST CG</strong><span>{status?.local?'LOCAL WORKSTATION':`${status?.serverName||'PRODUCTION'} · ${status?.network||'connecting'}`}</span><button onClick={()=>setConnections(true)}>Connections</button><span className="desktop-output-state">{status?.output==='connected'?(status.outputUnconfirmed?'OUTPUT UNCONFIRMED':'OUTPUT CONNECTED'):'OUTPUT OFFLINE'}</span><button onClick={()=>setAccount(true)}>{session.user.displayName} · {session.user.role}</button>{(can('users.manage')||can('audit.view'))&&<button onClick={()=>setAdmin(true)}>Accounts & access</button>}{can('users.manage')&&can('system.configure')&&session.user.accessExpiresAt===null&&<button onClick={()=>setRecovering(true)}>Backups & recovery</button>}{can('outputs.view')&&<button onClick={()=>setBroadcast(true)}>Broadcast output</button>}<button onClick={()=>setOpen(true)}>System</button><button disabled={leaving} onClick={()=>void signOut()}>{leaving?'Signing out…':'Sign out'}</button></div>
 {session.user.accessExpiresAt&&<div className="account-idle">Access expires {new Date(session.user.accessExpiresAt).toLocaleString()}. Contact your administrator to renew.</div>}
 {session.idleExpiresAt-Date.now()<5*60000&&<div className="account-idle">Your session will lock soon. Click or type to keep working. Output will continue.</div>}
 <div className="desktop-workspace">{workspaceReady===null?<div className="account-empty">Loading assigned workspaces…</div>:workspaceReady?<Studio session={session} onFlushReady={fn=>{flush.current=fn;}}/>:<div className="account-empty"><h1>No workspace access</h1><p>Ask a local administrator to assign a saved project and allow workspace viewing.</p></div>}</div>
 {connections&&<Connections onClose={()=>setConnections(false)} beforeSwitch={async()=>{await flush.current?.();}}/>}
 {broadcast&&<BroadcastOutput canConfigure={can('outputs.configure')} onClose={()=>setBroadcast(false)}/>}
 {recovering&&<RecoveryCenter onClose={()=>setRecovering(false)} beforeMaintenance={async()=>{await flush.current?.();}}/>}
 {account&&<div className="desktop-modal-backdrop"><AccountForm session={session} onSession={onSession} onClose={()=>setAccount(false)}/></div>}
 {admin&&<Administration session={session} onClose={()=>setAdmin(false)} startAudit={!can('users.manage')}/>}
 {open&&<div className="desktop-modal-backdrop"><section className="desktop-settings" role="dialog" aria-modal="true" aria-label="System and settings"><header><div><small>WORKSTATION</small><h1>System & settings</h1></div><button aria-label="Close settings" onClick={()=>setOpen(false)}>×</button></header><p>Local accounts & permissions · Version {info?.version}. Signed in as {session.user.username}.</p>{preferences&&<><fieldset disabled={!can('system.configure')}><div className="desktop-settings-grid"><label>Workstation name<input value={preferences.workstation} onChange={e=>setPreferences({...preferences,workstation:e.target.value})}/></label><label>Workstation role<input value={preferences.role} onChange={e=>setPreferences({...preferences,role:e.target.value})}/></label><label>Location<input value={preferences.location} onChange={e=>setPreferences({...preferences,location:e.target.value})}/></label><label>Interface scale<select value={preferences.uiScale} onChange={e=>setPreferences({...preferences,uiScale:Number(e.target.value)})}>{[.75,.9,1,1.1,1.25,1.5].map(v=><option key={v} value={v}>{Math.round(v*100)}%</option>)}</select></label></div><label className="desktop-check"><input type="checkbox" checked={preferences.startup} onChange={e=>setPreferences({...preferences,startup:e.target.checked})}/>Launch at Windows sign-in (installed application)</label><button className="desktop-primary" onClick={()=>bridge.saveSettings(preferences).then(v=>{setPreferences(v);setMessage('Workstation settings saved.');}).catch(e=>setMessage(e.message))}>Save settings</button></fieldset><h2>Output displays</h2><p>Use F11 in the output window for fullscreen.</p><div className="desktop-displays">{preferences.displays.map(d=><button disabled={!can('outputs.configure')} key={d.id} onClick={()=>bridge.openOutput(d.id).catch(e=>setMessage(e.message))}>{d.label}<small>{d.width} × {d.height} · {Math.round(d.scaleFactor*100)}%</small></button>)}</div></>}
 <h2>System status</h2><dl className="desktop-health"><dt>Database</dt><dd>{status?.database||'Unavailable'}</dd><dt>Desktop output</dt><dd>{status?.output||'Unavailable'}</dd><dt>Accounts</dt><dd>Local · role and workspace checks</dd><dt>Session expiry</dt><dd>30 minutes idle / 12 hours total</dd><dt>Production connection</dt><dd>{status?.local?'Local mode':status?.serverName+' · '+status?.network}</dd><dt>SDI / NDI</dt><dd>Not implemented</dd><dt>Automatic updates</dt><dd>Disabled</dd></dl><p className="desktop-data-path">Data folder: {info?.dataDirectory}</p>{can('diagnostics.view')&&<button onClick={()=>bridge.exportDiagnostics().then(saved=>saved&&setMessage('Diagnostic report exported.')).catch(e=>setMessage(e.message))}>Export diagnostic report</button>}{message&&<p role="status">{message}</p>}</section></div>}</>;
}
createRoot(document.getElementById('root')!).render(location.pathname==='/output'?<OutputView/>:<DesktopApp/>);
