import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import {join} from 'node:path';
import {defaultProject} from '../lib/studio-model.ts';
import {creativeSmoke} from './creative-smoke.mjs';
import {panelSmoke} from './panel-smoke.mjs';
import {aeSmoke} from './ae-smoke.mjs';
import {psdSmoke} from './psd-smoke.mjs';
import {sportsSmoke} from './sports-smoke.mjs';
import {commandSmoke} from './command-smoke.mjs';
import {networkSmoke} from './network-smoke.mjs';
import {recoverySmoke} from './recovery-smoke.mjs';
import {outputSmoke} from './output-smoke.mjs';
import {ndiSmoke} from './ndi-smoke.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let n=0;n<100;n++){if(await fn())return;await sleep(100);}throw Error('Renderer readiness timed out.');}
export async function run({app,studio,dialog,openOutput,getOutput,service,directory}){
 const errors=[],checks=[];studio.webContents.on('console-message',(_e,...args)=>{const d=args[0];if((typeof d==='object'&&d.level==='error')||d===3)errors.push(typeof d==='object'?d.message:args[1]);});
 const js=code=>studio.webContents.executeJavaScript(code),auth=(action,data)=>js(`window.broadcastCG.auth(${JSON.stringify(action)},${JSON.stringify(data)})`);
 const capture=async name=>{studio.show();studio.focus();await sleep(600);for(let n=0;n<3;n++){try{writeFileSync(join(directory,name),(await studio.webContents.capturePage()).toPNG());return;}catch(e){if(n===2)throw e;await sleep(400);}}};
 async function reload(){studio.reload();await until(()=>js("document.querySelector('.studio')!==null").catch(()=>false));await sleep(150);}
 async function api(path,body){return js(`fetch(${JSON.stringify(path)},${JSON.stringify(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})}).then(async r=>({status:r.status,value:await r.json()}))`);}
 await until(()=>js("document.body.innerText.includes('Set up your workstation')").catch(()=>false));
 await capture('accounts-setup.png');assert.equal((await api('/api/projects')).status,401);
 assert.equal(await js('typeof window.require'), 'undefined');assert.equal(await js('typeof window.process'), 'undefined');
 const password=randomBytes(24).toString('hex'),credentials={username:'qa_admin',displayName:'QA Administrator',password,remember:true};
 const admin=await auth('setup',credentials);assert.equal(admin.user.role,'ADMIN');assert.equal(admin.token,undefined);assert.equal(admin.rememberToken,undefined);checks.push('first-run gate and private main-process tokens');
 await reload();
 const layout=await js(`(()=>{const c=document.querySelector('.canvas-area .canvas-stage').getBoundingClientRect(),a=document.querySelector('.canvas-area').getBoundingClientRect();return {height:c.height,contained:c.top>=a.top&&c.bottom<=a.bottom+1&&c.left>=a.left&&c.right<=a.right+1};})()`);
 assert.ok(layout.height>200&&layout.contained,JSON.stringify(layout));
 const p=defaultProject();p.name='Stage 2 runtime QA';assert.equal((await api('/api/projects',{project:p,revision:0})).status,200);
 await panelSmoke({studio,js,api,reload,capture,checks,sleep,until,project:p});
 await creativeSmoke({studio,js,api,reload,capture,checks,sleep,until,project:p});
 const command={projectId:p.id,scene:p.scenes[0],variables:p.variables,mode:'show'};
 assert.equal((await api('/api/program',command)).status,503);openOutput();await until(()=>getOutput()&&!getOutput().webContents.isLoading());
 const take=await api('/api/program',command);assert.equal(take.status,200,JSON.stringify(take));
 assert.equal(await getOutput().webContents.executeJavaScript('document.querySelectorAll("svg[data-testid=graphic]").length'),1);checks.push('native TAKE and renderer acknowledgement');
 // Delay one already-fetched snapshot across a newer pushed TAKE.
 await getOutput().webContents.executeJavaScript(`(()=>{const original=window.fetch;let held=false;window.fetch=async(...args)=>{const response=await original(...args);if(!held&&String(args[0]).includes('/api/program')){held=true;window.qaPollWaiting=true;return new Promise(resolve=>{window.qaReleasePoll=()=>{window.fetch=original;resolve(response);};});}return response;};})()`);
 await until(()=>getOutput().webContents.executeJavaScript('!!window.qaPollWaiting'));
 const freshTake=await api('/api/program',command);assert.equal(freshTake.status,200);
 await getOutput().webContents.executeJavaScript('window.qaReleasePoll()');await sleep(150);
 assert.equal(await getOutput().webContents.executeJavaScript('document.querySelector("main").dataset.revision'),freshTake.value.revision);checks.push('A delayed desktop poll cannot replace a newer pushed TAKE');
 await commandSmoke({studio,js,api,reload,capture,checks,sleep,until,project:p});
 await sportsSmoke({studio,js,api,reload,capture,checks,sleep,until,project:p,getOutput});
 await psdSmoke({studio,dialog,js,api,reload,capture,checks,sleep,until,project:p,directory,getOutput});
 await aeSmoke({studio,dialog,js,api,reload,capture,checks,sleep,until,project:p,directory,getOutput});
 await outputSmoke({js,api,capture,checks,sleep,until});
 await ndiSmoke({js,api,capture,checks});
 assert.equal((await api('/api/program',command)).status,200);
 await js("[...document.querySelectorAll('button')].find(b=>b.textContent==='Accounts & access').click()");await until(()=>js("document.querySelector('.account-table tbody tr')!==null"));await capture('accounts-admin.png');
 const viewer=await auth('createUser',{username:'qa_viewer',displayName:'QA Viewer',password,role:'VIEWER',enabled:true,allWorkspaces:false,workspaceIds:[p.id]});
 await auth('logout');assert.equal((await api('/api/projects')).status,401);
 assert.equal(await getOutput().webContents.executeJavaScript('fetch("/api/program").then(r=>r.json()).then(p=>p.mode)'), 'show');
 assert.equal(await getOutput().webContents.executeJavaScript('fetch("/api/projects").then(r=>r.status)'),403);
 assert.equal(await getOutput().webContents.executeJavaScript('fetch("/api/program",{method:"POST",body:"{}"}).then(r=>r.status)'),403);checks.push('logout preserves output; output context cannot edit');
 await auth('login',{username:viewer.username,password});assert.equal((await api('/api/projects')).status,403);
 await auth('changePassword',{currentPassword:password,password:password+'new'});await reload();
 assert.equal(await js("document.querySelector('[role=tab][data-state=active]').textContent"),'On air');
 assert.equal((await api('/api/projects',{project:p,revision:1})).status,403);
 const preferences=await js('window.broadcastCG.settings()');await assert.rejects(()=>js(`window.broadcastCG.saveSettings(${JSON.stringify(preferences)})`),/permission/);
 await assert.rejects(()=>js("window.broadcastCG.broadcastOutput('start',{})"),/permission/);
 await assert.rejects(()=>js("window.broadcastCG.broadcastOutput('ndiStart',{})"),/permission/);
 await assert.rejects(()=>js("window.broadcastCG.broadcastOutput('obsConnect',{})"),/permission/);
 assert.equal((await js("window.broadcastCG.broadcastOutput('status')")).url,null);
 assert.equal((await api('/api/program',command)).status,403);await capture('accounts-viewer.png');checks.push('temporary password required; Viewer API and native settings denied');
 await auth('logout');await auth('login',credentials);await reload();
 await js("[...document.querySelectorAll('button')].find(b=>b.textContent==='Accounts & access').click()");await until(()=>js("document.querySelectorAll('.account-table tbody tr').length===2"));await capture('accounts-admin.png');
 await js("[...document.querySelectorAll('button')].find(b=>b.textContent==='Audit history').click()");await sleep(200);await capture('accounts-audit.png');
 assert.equal((await api('/api/program',{projectId:p.id,scene:null,variables:{},mode:'hide'})).status,200);
 assert.deepEqual(errors,[]);checks.push('administration and audit render; console clean');
 await recoverySmoke({js,api,auth,dialog,reload,capture,checks,sleep,until,getOutput,credentials,directory,project:p});
 await networkSmoke({js,api,reload,capture,checks,sleep,until,getOutput,credentials});
 writeFileSync(join(directory,'smoke-result.json'),JSON.stringify({ok:true,checks,versions:process.versions,storage:(await js('window.broadcastCG.status()')).database},null,2));
 studio.destroy();getOutput()?.destroy();app.quit();
}
