import assert from 'node:assert/strict';
export async function sportsSmoke({studio,js,api,reload,capture,checks,sleep,until,project,getOutput}){
 const data=async()=>(await api('/api/projects/'+project.id)).value.project;
 const idle=()=>until(()=>js("document.querySelector('.studio')?.dataset.commandBusy==='false'"));
 const button=async text=>{await idle();await js(`[...document.querySelectorAll('.sports-workspace button')].find(b=>b.textContent.trim()===${JSON.stringify(text)}).click()`);await sleep(150);await idle();};
 const tab=async()=>{await js("[...document.querySelectorAll('[role=tab]')].find(b=>b.textContent.trim()==='Sports').dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}))");await sleep(150);};
 const click=async selector=>{await idle();await js(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(150);await idle();};
 async function choose(selector,label){await js(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.focus();el.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));})()`);await until(()=>js("document.querySelector('[role=option]')!==null"));await js(`[...document.querySelectorAll('[role=option]')].find(el=>el.textContent.trim()===${JSON.stringify(label)}).click()`);await sleep(150);await idle();}
 await tab();await button('Create match');await until(async()=>(await data()).sports?.kind==='football');
 await click('[aria-label="Add home point"]');assert.equal((await data()).variables.homeScore,1);
 const p=await data();assert.equal((await api('/api/program',{projectId:p.id,scene:p.scenes[2],variables:p.variables,mode:'show'})).status,200);
 await button('Start Match clock');await sleep(1400);
 await reload();await tab();await until(()=>js("[...document.querySelectorAll('.sports-workspace button')].some(b=>b.textContent==='Pause Match clock')"));
 const clock=(await api('/api/clocks?projectId='+p.id)).value.matchClock;assert.equal(clock.running,true);assert.ok(clock.seconds>=1);
 await until(()=>getOutput().webContents.executeJavaScript("document.body.textContent.includes('00:0')"));const currentOutput=await getOutput().webContents.executeJavaScript("fetch('/api/program').then(r=>r.json())");assert.notEqual(currentOutput.variables.matchClock,'00:00');await capture('sports-football.png');await button('Pause Match clock');checks.push('sports UI scoring and authoritative clock continue through editor reload and update native output');
 await button('New match setup');await choose('[aria-label="Match sport"]','Basketball');await button('Reset and start new match');await button('+3 home');assert.equal((await data()).variables.homeScore,3);await button('Reset to 14 seconds');assert.equal((await api('/api/clocks?projectId='+p.id)).value.shotClock.seconds,14);await js("(()=>{const el=document.querySelector('[aria-label=\"Set Shot clock seconds\"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'37');el.dispatchEvent(new Event('input',{bubbles:true}));})()");await sleep(100);assert.equal((await api('/api/clocks?projectId='+p.id)).value.shotClock.seconds,14);await button('Set Shot clock time');assert.equal((await api('/api/clocks?projectId='+p.id)).value.shotClock.seconds,37);await button('Reset to 14 seconds');await capture('sports-basketball.png');checks.push('basketball three-point scoring and 14-second shot clock reset');
 await button('New match setup');await choose('[aria-label="Match sport"]','Esports');await button('Reset and start new match');await button('Pick Map 1');await click('[aria-label="Add home point"]');await button('Complete current map');let result=await data();assert.equal(result.sports.results.length,1);assert.equal(result.variables.homeSeries,1);assert.equal(result.variables.homeScore,0);await capture('sports-esports.png');
 await click('[aria-label="Increase player kills"]');result=await data();assert.equal(result.variables.playerKills,1);
 await js("document.querySelector('.sports-workspace').scrollTop=document.querySelector('.sports-workspace').scrollHeight");await capture('sports-roster.png');checks.push('esports draft, completed map result, series scoring and player statistics fill graphics fields');
 studio.setContentSize(1024,800);await sleep(250);assert.equal(await js('document.documentElement.scrollWidth>document.documentElement.clientWidth+1'),false);await capture('sports-compact.png');studio.setContentSize(1440,950);
}
