import assert from 'node:assert/strict';
import {layer} from '../lib/studio-model.ts';
export async function toolboxSmoke({studio,js,api,reload,capture,checks,sleep,until,project,openOutput,getOutput}){
 const original=(await api('/api/projects/'+project.id)).value.project,p=structuredClone(original),size=studio.getSize();
 p.scenes=[{id:'toolbox-qa',name:'Toolbox QA',width:1000,height:700,duration:5,frameRate:60,layers:[layer('rect',{id:'red',name:'Red plate',x:100,y:100,width:220,height:180,color:'#ff0000'}),layer('rect',{id:'blue',name:'Blue plate',x:400,y:100,width:180,height:180,color:'#0000ff'}),layer('rect',{id:'locked',name:'Locked plate',x:700,y:100,width:160,height:180,color:'#ffffff',locked:true})]}];
 const read=async()=>(await api('/api/projects/'+p.id)).value,put=async value=>assert.equal((await api('/api/projects',{project:value,revision:(await read()).revision})).status,200);
 const click=async selector=>{await js(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(100);};
 const tool=async id=>click('[data-design-tool="'+id+'"]');
 const save=async()=>{await click('.projectbar button:last-of-type');await until(()=>js("document.querySelector('.statusbar').textContent.includes('Saved')"));return (await read()).project.scenes[0];};
 const pos=async(x,y)=>js(`(()=>{const p=new DOMPoint(${x},${y}).matrixTransform(document.querySelector('.canvas-stage svg.graphic').getScreenCTM());return{x:Math.round(p.x),y:Math.round(p.y)}})()`);
 const key=async(keyCode,modifiers=[])=>{studio.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});studio.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await sleep(100);};
 const pointer=async(type,point,modifiers=[])=>{studio.webContents.sendInputEvent({type,...point,button:'left',clickCount:1,modifiers:type==='mouseMove'?['leftButtonDown',...modifiers]:modifiers});await sleep(35);};
 const path=async(points,{cancel=false,modifiers=[],during}={})=>{studio.show();studio.focus();await pointer('mouseDown',await pos(...points[0]),modifiers);for(const point of points.slice(1))await pointer('mouseMove',await pos(...point),modifiers);if(during)await during();if(cancel){await js("window.toolboxKeyTrace=[];window.addEventListener('keydown',e=>window.toolboxKeyTrace.push({key:e.key,code:e.code,defaultPrevented:e.defaultPrevented,target:e.target.outerHTML?.slice(0,200)}),{once:true,capture:true})");await key('Escape');assert.equal(await js("document.querySelector('.design-viewport').dataset.tool"),'select',await js("JSON.stringify({keys:window.toolboxKeyTrace,focus:document.activeElement.outerHTML.slice(0,300)})"));}await pointer('mouseUp',await pos(...points.at(-1)),modifiers);await sleep(150);};
 const drag=(a,b,options)=>path(Array.from({length:7},(_,i)=>[a[0]+(b[0]-a[0])*i/6,a[1]+(b[1]-a[1])*i/6]),options);
 const selected=()=>js("[...document.querySelectorAll('[data-design-layer] .layer-select.selected')].map(e=>e.closest('[data-design-layer]').dataset.designLayer)");
 const selectedCount=()=>js("document.querySelector('.designer-selection-tools').textContent.match(/(\\d+) selected/)[1]");
 const input=async(label,value)=>{await js(`(()=>{const e=document.querySelector('[aria-label='+${JSON.stringify(JSON.stringify(label))}+']');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);await sleep(100);};
 const pixels=points=>js(`(async()=>{const s=document.querySelector('.canvas-stage svg.graphic').cloneNode(true);s.setAttribute('width','1000');s.setAttribute('height','700');s.querySelectorAll('rect[fill="transparent"],rect[stroke-dasharray]').forEach(e=>e.remove());const u=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(s)],{type:'image/svg+xml'}));try{const img=new Image();img.src=u;await img.decode();const c=document.createElement('canvas');c.width=1000;c.height=700;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);return ${JSON.stringify(points)}.map(([x,y])=>[...ctx.getImageData(x,y,1,1).data]);}finally{URL.revokeObjectURL(u);}})()`);
 try{
  await put(p);await reload(p.id);await js("[...document.querySelectorAll('.topbar [role=tab]')].find(b=>b.textContent.trim()==='Design').dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}))");await sleep(200);await click('.scene-item');await tool('marquee');await drag([75,75],[600,310]);assert.equal(await selectedCount(),'2');
  await drag([380,80],[600,300],{modifiers:['alt']});assert.equal(await selectedCount(),'1');await tool('lasso');await path([[380,80],[600,80],[600,300],[380,300],[380,80]],{modifiers:['shift']});assert.equal(await selectedCount(),'2');await tool('ellipse-select');await drag([80,80],[330,300]);assert.equal(await selectedCount(),'1');
  checks.push('Native marquee, ellipse and lasso select layer bounds; Shift adds, Alt subtracts and locked layers are excluded');
  await tool('star');await drag([100,360],[300,550]);let saved=await save();assert.equal(saved.layers.at(-1).name,'Star');assert.equal(saved.layers.at(-1).visual.points.length,10);await click('[aria-label=Undo]');assert.equal((await save()).layers.length,3);await click('[aria-label=Redo]');await save();
  for(const kind of ['rounded-rect','triangle','regular-polygon','arrow']){await tool(kind);await drag([650,360],[800,500]);saved=await save();assert.ok(saved.layers.length>3);await click('[aria-label=Undo]');await save();}
  await tool('brush');await input('Paint brush size','20');await input('Paint opacity','65');await path([[370,380],[395,400],[430,380],[460,440],[500,430]]);saved=await save();assert.equal(saved.layers.at(-1).name,'Brush stroke');assert.equal(saved.layers.at(-1).visual.strokeWidth,20);assert.equal(saved.layers.at(-1).opacity,.65);assert.ok(saved.layers.at(-1).visual.points.length>2);const brushCount=saved.layers.length;
  await path([[650,400],[750,450]],{cancel:true});assert.equal((await save()).layers.length,brushCount);await tool('brush');const a=await pos(650,400),b=await pos(750,450);await pointer('mouseDown',a);await pointer('mouseMove',b);await js("document.querySelector('.design-viewport').dispatchEvent(new PointerEvent('pointercancel',{bubbles:true}))");await pointer('mouseUp',b);assert.equal((await save()).layers.length,brushCount);
  checks.push('Editable shapes and vector brush size/opacity work; each completed stroke is one Undo step and Escape/pointer cancellation adds nothing');
  await click('[data-design-layer=red] .layer-select');await tool('mask-hide');const beforeMask=await save();await drag([150,190],[260,190],{during:async()=>{assert.equal((await pixels([[200,190]]))[0][3],0);assert.deepEqual((await read()).project.scenes[0],beforeMask);}});saved=await save();assert.equal(saved.layers[0].visual.layerMask.strokes.length,1);await click('[aria-label=Undo]');assert.equal((await save()).layers[0].visual?.layerMask,undefined);await click('[aria-label=Redo]');await save();
  await tool('mask-reveal');await drag([180,190],[225,190]);assert.equal((await pixels([[200,190]]))[0][3],255);await save();
  await tool('mask-rectangle');await drag([120,120],[290,255],{cancel:true});assert.equal((await save()).layers[0].visual.layerMask.shape,'full');await tool('mask-rectangle');await drag([120,120],[290,255]);assert.equal((await pixels([[110,110],[200,150]]))[0][3],0);assert.equal((await save()).layers[0].visual.layerMask.shape,'rectangle');
  checks.push('Eraser, restore and crop masks preview live, preserve source content, cancel safely and persist as one Undo step');
  await click('[data-design-layer=blue] .layer-select');await input('Drawing color','#ff0000');await input('Background drawing color','#0000ff');await tool('gradient');await drag([420,130],[560,130]);saved=await save();assert.equal(saved.layers[1].visual.fill,'linear');let rgba=await pixels([[415,160],[565,160]]);assert.ok(rgba[0][0]>rgba[0][2]&&rgba[1][2]>rgba[1][0]);
  await drag([420,130],[420,250],{cancel:true});assert.ok(Math.abs((await save()).layers[1].visual.gradientAngle)<2);
  await tool('eyedropper');await path([[200,150]]);await until(()=>js("document.querySelector('[aria-label=\"Drawing color\"]').value==='#ff0000'"));await input('Drawing color','#12aa77');await tool('fill');await path([[470,200]]);assert.equal((await save()).layers[1].color,'#12aa77');await path([[740,200]]);assert.equal((await save()).layers[2].color,'#ffffff');
  checks.push('Gradient direction previews and cancels; rendered-artwork eyedropper and fill respect locks and save correctly');
  await tool('select');await js('document.activeElement?.blur()');await key('b');assert.equal(await js("document.querySelector('.design-viewport').dataset.tool"),'brush');await key('e');assert.equal(await js("document.querySelector('.design-viewport').dataset.tool"),'mask-hide');await key('e',['shift']);assert.equal(await js("document.querySelector('.design-viewport').dataset.tool"),'mask-reveal');await key('d');assert.equal(await js("document.querySelector('[aria-label=\"Drawing color\"]').value"),'#000000');await key('x');assert.equal(await js("document.querySelector('[aria-label=\"Drawing color\"]').value"),'#ffffff');
  await tool('zoom');const oldZoom=await js("Number(document.querySelector('.design-viewport').dataset.zoom)");await path([[500,350]]);assert.ok(await js("Number(document.querySelector('.design-viewport').dataset.zoom)")>oldZoom);await click('[aria-label="Fit canvas"]');
  saved=await save();await reload(p.id);await click('.scene-item');assert.deepEqual((await read()).project.scenes[0],saved);assert.equal((await api('/api/program')).value?.scene??null,null);
  for(const [width,height] of [[1280,720],[1920,1080]]){studio.setSize(width,height);await sleep(250);await click('[aria-label="Show tool names"]');assert.ok(await js("document.querySelector('.design-viewport').clientWidth>180"));await capture('toolbox-labels-'+width+'.png');await click('[aria-label="Compact toolbox"]');await tool('brush');assert.ok(await js("document.querySelector('.design-viewport').clientHeight>150"));await capture('toolbox-'+width+'.png');}
  checks.push('Tool shortcuts, swatch swap/defaults, click zoom, save/reopen and compact/named toolbox at 1280×720 and 1920×1080 verified; editing never TAKEs');
  if(openOutput&&getOutput){await openOutput();await until(()=>getOutput()&&!getOutput().webContents.isLoading());const result=await api('/api/program',{projectId:p.id,scene:saved,variables:p.variables,mode:'show'});assert.equal(result.status,200);assert.equal(result.value.acknowledged,true);await until(()=>getOutput().webContents.executeJavaScript("!!document.querySelector('mask') && !!document.querySelector('path[stroke-linecap=round]')"));await api('/api/program',{projectId:p.id,scene:null,variables:{},mode:'hide'});await sleep(700);getOutput()?.close();checks.push('Shared desktop output renders vector brush strokes and nondestructive masks and acknowledges explicit show/hide');}
 }finally{studio.setSize(...size);await put(original);await reload(project.id);}
}
