import assert from 'node:assert/strict';
export async function videoSmoke({studio,js,api,reload,capture,checks,sleep,until,project,openOutput,getOutput}){
 const original=(await api('/api/projects/'+project.id)).value.project,p=structuredClone(original),size=studio.getSize();
 p.scenes=[{id:'video-qa',name:'Video import QA',width:1920,height:1080,duration:5,frameRate:60,layers:[]}];
 const read=async()=>(await api('/api/projects/'+p.id)).value,put=async value=>assert.equal((await api('/api/projects',{project:value,revision:(await read()).revision})).status,200);
 const click=async selector=>{await js(`document.querySelector(${JSON.stringify(selector)}).click()`);await sleep(120);};
 const input=async(selector,value)=>{await js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);await sleep(100);};
 const save=async()=>{await click('.projectbar button:last-of-type');await until(()=>js("document.querySelector('.statusbar').textContent.includes('Saved')"));};
 const tab=async name=>{await js(`[...document.querySelectorAll('.topbar [role=tab]')].find(b=>b.textContent.trim()===${JSON.stringify(name)}).dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}))`);await sleep(150);};
 const sendFile=async(selector,expression)=>{await js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)}),data=new DataTransfer();data.items.add(${expression});e.files=data.files;e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await sleep(120);};
 const choose=async()=>{await js("window.videoPickerClicks=0;document.querySelector('[aria-label=\"Choose video file\"]').addEventListener('click',e=>{window.videoPickerClicks++;e.preventDefault();},{once:true})");await click('[aria-label="Import video layer"]');assert.equal(await js('window.videoPickerClicks'),1);};
 let firstSrc;
 try{
  await put(p);await reload(p.id);await tab('Design');await click('.scene-item');await choose();await save();assert.equal((await read()).project.scenes[0].layers.length,0,'Opening/canceling the picker cannot add a blank layer');
  const assets=(await api('/api/media')).value.total;await sendFile('[aria-label="Choose video file"]',"new File(['not a video'],'broken.mp4',{type:'video/mp4'})");await until(()=>js("[...document.querySelectorAll('[data-sonner-toast]')].some(e=>e.textContent.includes('cannot be decoded'))"));await save();assert.equal((await read()).project.scenes[0].layers.length,0);assert.equal((await api('/api/media')).value.total,assets);
  checks.push('Video toolbar opens its picker; cancellation and undecodable files create no empty layers or uploaded assets');
  // Genuine locally generated moving video fixtures, not camera/display capture.
  const formats=await js(`(async()=>{window.videoFixtures={};const formats=[['webm','video/webm;codecs=vp8'],['mp4','video/mp4;codecs=avc1.42001E']];for(const [extension,mime] of formats){if(!MediaRecorder.isTypeSupported(mime))continue;const c=document.createElement('canvas');c.width=320;c.height=180;const ctx=c.getContext('2d'),stream=c.captureStream(24),parts=[],recorder=new MediaRecorder(stream,{mimeType:mime}),done=new Promise(resolve=>recorder.onstop=resolve);recorder.ondataavailable=e=>parts.push(e.data);let n=0;const draw=()=>{ctx.fillStyle=n++%2?'#154f87':'#db7635';ctx.fillRect(0,0,320,180);ctx.fillStyle='white';ctx.fillRect(n*8%270,40,40,80);};draw();recorder.start();const timer=setInterval(draw,42);await new Promise(resolve=>setTimeout(resolve,1400));recorder.stop();await done;clearInterval(timer);stream.getTracks().forEach(t=>t.stop());window.videoFixtures[extension]=new File(parts,'Motion sample.'+extension,{type:mime.split(';')[0]});}return Object.keys(window.videoFixtures);})()`);
  assert.ok(formats.includes('webm'));assert.ok(formats.includes('mp4'),'This qualification requires a real H.264 MP4 fixture');
  for(const extension of formats){const count=(await read()).project.scenes[0].layers.length;await choose();await sendFile('[aria-label="Choose video file"]',`window.videoFixtures.${extension}`);await until(()=>js("!document.querySelector('[aria-label=\"Import video layer\"]').disabled"));await until(()=>js("!!document.querySelector('.canvas-stage video') && document.querySelector('.canvas-stage video').readyState>=2"));await save();const saved=(await read()).project.scenes[0],l=saved.layers.at(-1);assert.equal(saved.layers.length,count+1);assert.equal(l.name,'Motion sample.'+extension);assert.ok(l.src.startsWith('/api/assets/'));assert.ok(Math.abs(l.width/l.height-16/9)<1e-6);assert.equal(l.visual.imageFit,'contain');assert.equal(await js("document.querySelector('.properties-inspector').dataset.inspectorTab"),'style');assert.equal(await js("getComputedStyle(document.querySelector('[aria-label=\"Import video\"]')).display"),'none');
   if(!firstSrc){firstSrc=l.src;await click('[aria-label=Undo]');await save();assert.equal((await read()).project.scenes[0].layers.length,count);await click('[aria-label=Redo]');await save();}
   await until(()=>js("document.querySelector('.video-source-preview')?.readyState>=2"));await click('[aria-label="Preview video on canvas"]');await sleep(650);assert.ok(await js(`document.querySelector('.canvas-stage [data-layer-id="${l.id}"] video').currentTime>.1`));await click('[aria-label="Pause video preview"]');await sleep(250);assert.equal(await js(`document.querySelector('.canvas-stage [data-layer-id="${l.id}"] video').paused`),true);assert.equal(await js("!!document.querySelector('.canvas-stage [data-media-error=true]')"),false);assert.equal((await api('/api/program')).value?.scene??null,null);
  }
  checks.push('Real VP8 WebM and H.264 MP4 import from the toolbar with correct proportions, visible media controls, one-step Undo, preview/play/pause and no automatic TAKE');
  await input('[aria-label="Video start offset"]','999');await sleep(100);assert.ok(await js("!!document.querySelector('.canvas-stage [data-media-error=true]')"));await input('[aria-label="Video start offset"]','0');await sleep(150);assert.equal(await js("!!document.querySelector('.canvas-stage [data-media-error=true]')"),false);
  const before=(await read()).project.scenes[0].layers.length;await js("(()=>{const data=new DataTransfer();data.items.add(window.videoFixtures.webm);document.querySelector('.design-viewport').dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:data}));})()");await until(()=>js("!document.querySelector('[aria-label=\"Import video layer\"]').disabled"));await save();assert.equal((await read()).project.scenes[0].layers.length,before+1);
  await sendFile('[aria-label="Import video"]','window.videoFixtures.mp4');await until(()=>js("!document.querySelector('.video-source-editor button').disabled"));await save();assert.equal((await read()).project.scenes[0].layers.length,before+1,'Replace preserves layer identity/count');
  let current=(await read()).project;current.variables.videoClip=firstSrc;current.scenes[0].layers.at(-1).src='{{videoClip}}';await put(current);await reload(p.id);await tab('Design');await click('.scene-item');const id=current.scenes[0].layers.at(-1).id;await click('[data-design-layer="'+id+'"] .layer-select');await until(()=>js(`document.querySelector('.canvas-stage [data-layer-id="${id}"] video')?.readyState>=2`));assert.equal(await js(`document.querySelector('.canvas-stage [data-layer-id="${id}"] video').getAttribute('src')`),firstSrc);
  checks.push('Video file drop, replace-in-place, invalid-offset recovery, and local video variable bindings work after saving and reopening');
  for(const [width,height] of [[1280,720],[1920,1080]]){studio.setSize(width,height);await sleep(250);assert.ok(await js("document.querySelector('.pi-scroll').scrollWidth<=document.querySelector('.pi-scroll').clientWidth"));await capture('video-import-'+width+'.png');}
  if(openOutput&&getOutput){await openOutput();await until(()=>getOutput()&&!getOutput().webContents.isLoading());current=(await read()).project;const result=await api('/api/program',{projectId:p.id,scene:current.scenes[0],variables:current.variables,mode:'show'});assert.equal(result.status,200);assert.equal(result.value.acknowledged,true);await sleep(600);assert.ok(await getOutput().webContents.executeJavaScript("[...document.querySelectorAll('video')].every(v=>v.readyState>=2&&v.currentTime>0&&!v.error)"));await api('/api/program',{projectId:p.id,scene:null,variables:{},mode:'hide'});await sleep(700);getOutput()?.close();checks.push('Isolated desktop output acknowledges both video formats, advances playback and hides; controls fit 1280×720 and 1920×1080');}
 }finally{studio.setSize(...size);await put(original);await reload(project.id);}
}
